---
permalink: a1k/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a1k,  verify and set HA state, complete the replacement process 
summary: 컨트롤러를 재부팅하고 시스템 상태를 확인한 후, 실패한 부품을 NetApp 으로 반환하여 AFF A1K 섀시 교체 절차의 마지막 단계를 완료합니다. 
---
= 섀시 교체 완료 - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러를 재부팅하고 시스템 상태를 확인한 후, 실패한 부품을 NetApp 으로 반환하여 AFF A1K 섀시 교체 절차의 마지막 단계를 완료합니다.



== 단계 1: 컨트롤러를 부팅하고 컨트롤러를 되돌립니다

컨트롤러가 재부팅되면 ONTAP를 부팅하고 컨트롤러를 반납합니다.

.단계
. 콘솔 출력을 확인합니다.
+
.. 컨트롤러가 Loader 프롬프트로 부팅되면 명령을 사용하여 컨트롤러를 `boot_ontap` 재부팅합니다.
.. 재부팅 후 콘솔이 표시되면 `waiting for giveback` 파트너 컨트롤러에 로그인하여 교체한 컨트롤러가 명령을 사용하여 반환 준비가 되었는지 확인합니다 `storage failover show`.


. 반환 수행:
+
.. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
.. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다. `storage failover giveback -ofnode _impaired_node_name_`
.. 자동 환불이 비활성화된 경우 다시 활성화하세요. `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`






== 2단계: 스토리지 시스템 상태 확인

컨트롤러에서 스토리지를 반환한 후에는 를 통해 전체 상태를 확인해야 합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].

.단계
. 기브백이 완료된 후 Active IQ Config Advisor를 실행하여 스토리지 시스템의 상태를 확인합니다.
. 발생한 모든 문제를 해결합니다.




== 3단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다.  https://mysupport.netapp.com/site/info/rma["부품 반환 및 교체"]자세한 내용은 페이지를 참조하십시오.
