---
permalink: a1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a1k, how to recable the system, how to reassign disks 
summary: AFF A1K 시스템이 정상 작동을 재개할 수 있도록 스토리지 리소스의 제어를 교체 컨트롤러로 되돌립니다. 
---
= 컨트롤러 - AFF A1K를 돌려줍니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A1K 시스템이 정상 작동을 재개할 수 있도록 스토리지 리소스의 제어를 교체 컨트롤러로 되돌립니다. 반환 절차는 시스템에서 사용하는 암호화 유형(암호화 안 함 또는 Onboard Key Manager(OKM) 암호화)에 따라 다릅니다.

[role="tabbed-block"]
====
.암호화 또는 External Key Manager(EKM) 없음
--
손상된 컨트롤러를 다시 보관하여 정상 작동으로 되돌립니다.

.단계
. Loader 프롬프트에서 를 입력합니다 `boot_ontap`.
. 콘솔 메시지가 중지되면 <enter> 키를 누릅니다.
+
** _login_prompt가 표시되면 이 섹션 끝에 있는 다음 단계로 이동합니다.
** _waiting for Giveback_이 표시되면 <enter> 키를 누르고 파트너 노드에 로그인한 후 이 섹션 끝에 있는 다음 단계로 이동합니다.


. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다. `storage failover giveback -ofnode _impaired_node_name_`
. 자동 반환이 비활성화되어 있는 경우, 다시 활성화합니다. `storage failover modify -node local -auto-giveback _true_`
. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.온보드 암호화(OKM)
--
OKM의 온보드 암호화 키를 복원하고 다시 봉인하여 컨트롤러를 정상 작동 상태로 되돌리십시오.

.시작하기 전에
시작하기 전에 https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"]를 검토하거나 NetApp 지원팀에 문의하십시오.

.단계
. Loader 프롬프트에서 ONTAP 메뉴로 부팅하고 `boot_ontap menu` 옵션 10을 선택합니다.
. 정상 작동하는 컨트롤러에서 클러스터 전체 암호를 검색하고 확인합니다.
+
.. 클러스터 전체 암호를 검색하려면 다음 명령을 실행하십시오.
+
`security key-manager onboard show-backup`

.. 다음 명령을 사용하여 클러스터 전체 암호를 확인하십시오.
+
`security key-manager onboard verify-backup`



. OKM 암호를 입력합니다.
+

NOTE: 암호를 묻는 메시지가 두 번 표시됩니다.

. 메시지가 나타나면 백업 키 데이터를 입력합니다.
. 부팅 메뉴에서 일반 부팅에 대한 옵션을 입력합니다 `1`.
. when_waiting for Giveback_이 표시되면 <enter> 키를 누릅니다.
. 콘솔 케이블을 파트너 노드로 이동하고 로 `admin`로그인합니다.
. CFO 애그리게이트(루트 애그리게이트)만 반환합니다. `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** 오류가 발생하면 에 문의하십시오 https://support.netapp.com["NetApp 지원"].


. 반환 보고서가 완료된 후 5분 동안 기다린 다음 페일오버 상태와 반환 상태를 확인합니다 `storage failover show`. 및 `storage failover show-giveback`.
. 동기화 및 키 상태 확인:
+
.. 콘솔 케이블을 다시 교체용 컨트롤러로 이동합니다.
.. 누락된 키 동기화: `security key-manager onboard sync`
+

NOTE: 클러스터에 대한 OKM의 클러스터 전체 암호를 묻는 메시지가 표시됩니다.

.. 키 상태 확인: `security key-manager key query -restored false`
+
올바르게 동기화되면 출력에 결과가 표시되지 않아야 합니다.

+
출력에 결과(시스템의 내부 키 테이블에 없는 키의 키 ID)가 표시되면 에 문의하십시오 https://support.netapp.com["NetApp 지원"].



. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다. `storage failover giveback -ofnode _impaired_node_name_`
. 자동 반환이 비활성화되어 있는 경우, 다시 활성화합니다. `storage failover modify -node local -auto-giveback _true_`
+

NOTE: 키가 누락된 경우 반환에 대한 거부권을 무시하지 마십시오. NetApp 지원팀에 문의하십시오.

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.다음 단계
스토리지 리소스의 소유권을 교체 컨트롤러로 다시 이전한 후에는 절차를 수행해야 link:controller-replace-restore-system-rma.html["컨트롤러 교체를 완료합니다"]합니다.
