---
permalink: a400/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: aff a400, aff, a400, procedure, boot, impair, controller, recovery, image, system, two-node, metrocluster, configuration, boot the recovery image 
summary: 복구 이미지에서 손상된 컨트롤러를 부팅하는 절차는 시스템이 2노드 MetroCluster 구성에 있는지 여부에 따라 다릅니다. 
---
= 복구 이미지 부팅 - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템에 새 부팅 미디어 장치를 설치한 후 USB 드라이브에서 복구 이미지를 부팅하고 파트너 노드에서 구성을 복원할 수 있습니다.

.단계
. LOADER 프롬프트에서 USB 플래시 드라이브에서 복구 이미지를 부팅하십시오: "boot_recovery"
+
이미지는 USB 플래시 드라이브에서 다운로드됩니다.

. 메시지가 표시되면 이미지 이름을 입력하거나 화면의 괄호 안에 표시된 기본 이미지를 그대로 사용합니다.
. var 파일 시스템을 복구합니다.
+
[role="tabbed-block"]
====
.옵션 1: ONTAP 9.16.0 이하
--
.. 손상된 컨트롤러에서 가 표시되면 `Do you want to restore the backup configuration now?` 를 누릅니다 `Y`
.. 손상된 컨트롤러에 메시지가 나타나면 를 `Y` 눌러 _/etc/ssh/ssh_host_ECDSA_key_를 덮어씁니다.
.. 건강한 파트너 컨트롤러에서 손상된 컨트롤러를 고급 권한 수준으로 설정합니다 `set -privilege advanced`.
.. 정상 상태의 파트너 컨트롤러에서 복원 백업 명령을 실행합니다. `system node restore-backup -node local -target-address impaired_node_IP_address`
+
*참고:* 복원에 성공하지 않은 메시지가 표시되면 에 문의하십시오 https://support.netapp.com["NetApp 지원"].

.. 정상적인 파트너 컨트롤러에서 손상된 컨트롤러를 관리자 수준으로 되돌립니다 `set -privilege admin`.
.. 손상된 컨트롤러에서 가 표시되면 `Was the restore backup procedure successful?` 를 `Y` 누릅니다.
.. 손상된 컨트롤러에서 가 표시되면 `...would you like to use this restored copy now?` 를 `Y` 누릅니다.
.. 손상된 컨트롤러에서 손상된 컨트롤러를 재부팅하라는 메시지가 나타나면 키를 `Y` 누르고 부팅 메뉴를 누릅니다 `ctrl-c`.
.. 시스템에서 암호화를 사용하지 않는 경우 _option 1 Normal Boot._를 선택하고, 그렇지 않으면 로 이동합니다link:bootmedia-encryption-restore.html["암호화를 복원합니다"].


--
.옵션 2: ONTAP 9.16.1 이상
--
.. 손상된 컨트롤러에서 백업 구성을 복원하라는 메시지가 나타나면 키를 `Y` 누릅니다.
+
복원 절차가 성공하면 콘솔 - 에 이 메시지가 표시됩니다 `syncflash_partner: Restore from partner complete`.

.. 손상된 컨트롤러에서 복원이 성공했는지 확인하는 메시지가 나타나면 키를 누릅니다 `Y`.
.. 손상된 컨트롤러에서 복원된 구성을 사용하라는 메시지가 나타나면 를 `Y` 누릅니다.
.. 손상된 컨트롤러에서 노드를 재부팅하라는 메시지가 표시되면 키를 누릅니다 `Y`.
.. 손상된 컨트롤러에서 손상된 컨트롤러를 재부팅하라는 메시지가 나타나면 키를 `Y` 누르고 부팅 메뉴를 누릅니다 `ctrl-c`.
.. 시스템에서 암호화를 사용하지 않는 경우 _option 1 Normal Boot._를 선택하고, 그렇지 않으면 로 이동합니다link:bootmedia-encryption-restore.html["암호화를 복원합니다"].


--
====


. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 'storage failover -fromnode local' 명령을 사용하여 컨트롤러를 반환하십시오.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. AutoSupport가 설정된 경우 명령을 사용하여 자동 케이스 생성을 복원/억제 `system node autosupport invoke -node * -type all -message MAINT=END` 해제합니다.
+
*참고:* 프로세스가 실패하면 에 https://support.netapp.com["NetApp 지원"]문의하십시오.


