---
permalink: a400/maintain-overview.html 
sidebar: sidebar 
keywords: aff A400 maintenance, maintenance, repairing A400, repairing aff A400, replace aff A400 components, replace aff A400 components 
summary: ASA A400 하드웨어 유지 관리 
---
= AFF A400 하드웨어 유지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A400 스토리지 시스템의 경우 다음 구성 요소에 대해 유지보수 절차를 수행할 수 있습니다.



== 미디어를 부팅합니다

부팅 매체는 시스템이 부팅될 때 사용하는 1차 및 2차 부팅 이미지 파일 세트를 저장합니다.



== 섀시

섀시는 컨트롤러/CPU 장치, 전원 공급 장치 및 I/O와 같은 모든 컨트롤러 구성 요소를 수용하는 물리적 인클로저입니다



== 컨트롤러

컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 ONTAP 기능을 구현합니다.



== DIMM

메모리 불일치가 있거나 DIMM에 결함이 있는 경우 DIMM(Dual In-line Memory Module)을 교체해야 합니다.



== 팬

팬이 컨트롤러를 냉각시킵니다.



== NVDIMM 배터리

NVDIMM 전지는 NVDIMM 모듈의 전원 관리를 담당합니다.



== NVDIMM

 The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown.


== PCIe 또는 메자닌 카드

PCIe(Peripheral Component Interconnect Express) 카드는 마더보드의 PCIe 슬롯에 꽂는 확장 카드입니다.

메자닌 카드는 마더보드의 특수 슬롯에 삽입되도록 설계된 확장 카드입니다.



== 전원 공급 장치

전원 공급 장치는 컨트롤러 쉘프에 이중 전원을 제공합니다.



== 실시간 시계 배터리

실시간 시계 배터리는 전원이 꺼져 있을 경우 시스템 날짜 및 시간 정보를 보존합니다.
