---
permalink: a70-90/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a70, aff a90, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: 컨트롤러의 HA 구성이 활성 상태이고 AFF A70 또는 AFF A90 스토리지 시스템에서 올바르게 작동하는지 확인하고 시스템 어댑터에 디스크의 모든 경로가 나열되어 있는지 확인합니다. 
---
= 시스템 구성(AFF A70 및 AFF A90)을 복원하고 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러의 HA 구성이 활성 상태이고 AFF A70 또는 AFF A90 스토리지 시스템에서 올바르게 작동하는지 확인하고 시스템 어댑터에 디스크의 모든 경로가 나열되어 있는지 확인합니다.



== 1단계: HA 구성 설정 확인

컨트롤러 모듈의 HA 상태를 확인하고 필요한 경우 시스템 구성과 일치하도록 상태를 업데이트해야 합니다.

.단계
. 유지보수 모드로 부팅: `boot_ontap maint`
+
.. _부팅 계속?_이 표시되면 를 입력합니다 `y`.
+
시스템 ID mismatch_warning 메시지가 표시되면 를 입력합니다 `y`.



.  `sysconfig -v`표시 내용을 입력하고 캡처합니다.
+

NOTE: _Personality mismatch_가 표시되면 고객 지원에 문의하십시오.

.  `sysconfig -v`출력에서 어댑터 카드 정보를 교체용 컨트롤러의 카드 및 위치와 비교합니다.
. 모든 구성요소가 동일한 상태를 `ha-config show` 표시하는지 확인합니다. `HA`
+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 컨트롤러 모듈의 표시된 시스템 상태가 시스템 구성과 일치하지 않는 경우 컨트롤러 모듈의 상태를 설정합니다 `HA`. `ha-config modify controller ha`
+
HA 상태 값은 다음 중 하나가 될 수 있습니다.

+
** 하
** `mcc` (지원되지 않음)
** `mccip` (ASA 시스템에서는 지원되지 않음)
** `non-ha` (지원되지 않음)


. 설정이 변경되었는지 확인합니다. ha-config show




== 2단계: 디스크 목록을 확인합니다

모든 시스템 디스크의 어댑터 목록과 경로를 확인해야 합니다.

.단계
. 어댑터가 를 사용하여 모든 디스크에 대한 경로를 나열하는지 `storage show disk -p` 확인합니다.
+
문제가 있는 경우 케이블을 확인하고 케이블을 다시 장착합니다.

. 유지 관리 모드를 `halt` 종료합니다.


.다음 단계
AFF A70 또는 AFF A90 시스템에 대한 시스템 구성을 복원하고 확인한 후에는 다음을 수행해야 link:controller-replace-recable-reassign-disks.html["컨트롤러를 반납합니다"]합니다.
