---
permalink: a70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, prerequisite, replace the controller module 
summary: AFF A70 또는 AFF A90 시스템의 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다. 
---
= 컨트롤러 교체 요구사항 - AFF A70 및 AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70 또는 AFF A90 시스템의 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다.

컨트롤러 모듈 교체 요구 사항을 검토하십시오.

* 모든 드라이브 쉘프가 올바로 작동하고 있어야 합니다.
* 건강한 컨트롤러는 교체되는 컨트롤러(이 절차에서는 손상된 컨트롤러라고 함)를 대신 수행할 수 있어야 합니다.
* 컨트롤러 업그레이드에는 이 절차를 사용하지 마세요.  참조하다 https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["컨트롤러 하드웨어 업그레이드 절차를 선택합니다"] 지침을 위해.
* 시스템이 MetroCluster 구성인 경우 다음을 검토하세요. https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["올바른 복구 절차 선택"] 이 절차를 사용할지 여부를 결정합니다.
* 오류가 발생한 구성 요소를 NetApp 에서 받은 현장 교체 가능 장치(FRU)로 교체합니다.
* 컨트롤러 모듈을 동일한 모델 유형의 컨트롤러 모듈로 교체합니다.  컨트롤러 모듈을 교체하여 시스템을 업그레이드할 수 없습니다.
* 이 절차에서는 드라이브나 드라이브 선반을 변경할 수 없습니다.
* 부팅 장치는 시스템 뒷면에 설치된 시스템 관리 모듈에 있습니다.  컨트롤러 모듈을 교체할 때 부트 장치를 옮길 필요는 없습니다.
* 이 절차에서 사용되는 컨트롤러 용어를 이해하세요.
+
** _손상된_ 컨트롤러는 교체되는 컨트롤러입니다.
** _교체_ 컨트롤러는 손상된 컨트롤러를 대체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 캡처합니다.
+
이는 교체 과정에서 발생하는 문제를 해결하기 위한 절차에 대한 기록을 제공합니다.



.다음 단계
AFF A70 또는 AFF A90 컨트롤러 교체 요구 사항을 검토한 후에는 다음 단계를 수행해야 합니다.link:controller-replace-shutdown.html["손상된 컨트롤러를 종료합니다"] .
