---
permalink: a70-90/install-prepare.html 
sidebar: sidebar 
keywords: aff a70-90k, prepare installation 
summary: AFF A70, AFF A90 플랫폼 설치를 준비합니다. 
---
= 설치 준비 - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 설치를 준비합니다.

.시작하기 전에
* 를 사용하여 https://docs.netapp.com/us-en/ontap/software_setup/index.html["클러스터 설정 워크시트"] 필요한 값을 link:complete-install.html#step-3-configure-your-cluster["클러스터를 구성합니다"]기록합니다. 기본값이 제공되는 경우 해당 값을 사용하거나 직접 입력할 수 있습니다.
* 하드웨어 설치를 완료하는 데 필요한 모든 추가 장비와 도구가 있는지 확인합니다.
+
** Phillips #2 드라이버
** 플래시
** ESD 스트랩
** NS224 선반 ID 설정을 위한 종이 클립 또는 끝이 뾰족한 볼펜
** USB/직렬 연결이 있는 랩톱 또는 콘솔
** 웹 브라우저에 액세스하여 스토리지 시스템을 구성합니다


* 플랫폼 무게와 관련된 안전 문제를 숙지해야 합니다.
+
완전히 장착된 A70-90 플랫폼은 무게가 최대 68.8kg(151.68파운드)이며, 유압 리프트를 들어 올리거나 사용하려면 4명이 필요합니다.

+
image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90 를 참조하십시오]

* 선반의 무게와 관련된 안전 문제를 알고 있어야 합니다.
+
완전히 장착된 선반은 무게가 최대 30.29kg(66.78lbs)이며 유압 리프트를 사용하거나 들어 올리려면 2명이 필요합니다. 선반 무게가 불균형하게 되므로 선반 무게를 줄이기 위해 선반 구성 요소(선반 전면 또는 후면의)를 제거하지 마십시오.

+
image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 인양 주의]

* 스토리지 시스템을 통과하는 공기 흐름은 베젤 또는 엔드 캡이 설치된 전면에서 들어오고 포트가 있는 후면에서 배출됩니다.




== 1단계: 사이트를 준비합니다

사용할 사이트 및 캐비닛 또는 랙이 스토리지 시스템의 사양을 충족하는지 확인하십시오.

.단계
. 에 표시된 대로 작업장이 플랫폼의 환경 및 전기 요구 사항을 충족하는지 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]확인합니다.
. 충분한 랙 공간이 있는지 확인합니다.
+
** 플랫폼 섀시용 4U
** NS224 쉘프당 2U


. 플랫폼 근처에 필요한 네트워크 스위치를 설치합니다.
+
설치 지침 및 호환성 정보는 를 https://docs.netapp.com/us-en/ontap-systems-switches/index.html["스위치 설명서"^] link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 참조하십시오.





== 2단계: 상자의 포장을 풉니다

모든 상자의 포장을 풀고 내용물을 포장 명세서에 있는 항목과 비교합니다.

. 모든 상자를 조심스럽게 열고 정리된 방식으로 내용물을 배치합니다.
. 포장을 푼 내용물과 포장 명세서의 목록을 비교합니다.
+

NOTE: 배송 상자 측면의 QR 코드를 스캔하여 포장 목록을 얻을 수 있습니다.

+
다음 항목은 상자에 표시될 수 있는 내용 중 일부입니다.

+
상자에 들어 있는 모든 항목이 포장 명세서의 목록과 일치하는지 확인합니다. 불일치 사항이 있는 경우 추가 조치를 위해 메모하십시오.

+
[cols="12,9,4"]
|===


| * 하드웨어 * | * 케이블 * |  


 a| 
** 온보드 드라이브가 설치된 플랫폼
** 쉘프(옵션)
** 지침이 포함된 레일 키트(옵션)
** 케이블 관리 장치 2개
** 베젤

 a| 
** 전원 코드
** 네트워크 케이블
** 관리 이더넷 케이블(RJ-45 케이블)
** USB-C 직렬 포트 케이블
** 스토리지 케이블(추가 스토리지를 주문한 경우)

|  
|===




== 3단계: 하드웨어를 등록합니다

지원 혜택을 받으려면 플랫폼을 등록하십시오.

.단계
. 사용 중인 플랫폼에 해당하는 시스템 일련 번호를 찾습니다.
+
포장 명세서, 확인 이메일 또는 포장을 푼 후 컨트롤러에서 번호를 찾을 수 있습니다.

+
image::../media/drw_ssn_label.svg[번호 위치를 보여 주는 시스템 일련 번호의 예입니다]

. NetApp 지원 사이트 로 이동합니다 http://mysupport.netapp.com/["mysupport.netapp.com"^].
. 하드웨어 등록:
+
[role="tabbed-block"]
====
.옵션 1: 기존 NetApp 고객
--
.단계
.. 사용자 이름과 암호를 사용하여 로그인합니다.
.. 시스템 * > * 내 시스템 * 을 선택합니다.
.. 새 시스템의 일련 번호가 나열되어 있는지 확인합니다.



NOTE: 새 시스템 일련 번호가 목록에 없으면 새 NetApp 고객을 위한 지침을 따릅니다.

--
.옵션 2: 신규 NetApp 고객
--
.. 지금 등록 * 을 클릭하고 계정을 만듭니다.
.. 시스템 * > * 시스템 등록 * 을 선택합니다.
.. 제품 시스템 일련 번호 및 요청된 세부 정보를 입력합니다.


등록이 승인되면 필요한 소프트웨어를 다운로드할 수 있습니다. 승인 프로세스는 최대 24시간이 걸릴 수 있습니다.

--
====

