---
permalink: a70-90/install-cable.html 
sidebar: sidebar 
keywords: aff a70, a90, prepare installation 
summary: 컨트롤러의 관리 네트워크 포트는 스위치에 연결됩니다. HA 인터커넥트 및 클러스터 인터커넥트 포트는 두 컨트롤러 모두에 케이블로 연결됩니다. 컨트롤러 모듈은 주문한 경우 외부 스토리지에 연결됩니다. 
---
= 하드웨어 케이블 연결 - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 스토리지 시스템 구성에 따라 컨트롤러와 쉘프에 케이블을 연결합니다.

.시작하기 전에
케이블 커넥터의 당김 탭 방향이 올바른지 케이블 다이어그램의 그림 화살표를 확인합니다.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[케이블 당김 탭 방향의 예]

* 커넥터를 삽입할 때 딸깍 소리가 들려야 합니다. 딸깍 소리가 느껴지지 않으면 커넥터를 분리하고 케이블 헤드를 뒤집은 다음 다시 시도하십시오.
* 광 스위치에 연결하는 경우 포트에 케이블을 연결하기 전에 컨트롤러 포트에 SFP를 삽입합니다.




== 1단계: 컨트롤러를 네트워크에 케이블로 연결합니다

컨트롤러를 스위치가 없는 2노드 클러스터 또는 스위치 있는 클러스터로 네트워크에 케이블로 연결합니다.

.시작하기 전에
스토리지 시스템을 스위치에 연결하는 방법에 대한 자세한 내용은 네트워크 관리자에게 문의하십시오.

.이 작업에 대해
다음 절차는 일반적인 구성을 보여 줍니다. 특정 케이블 연결은 스토리지 시스템에 대해 주문된 구성 요소에 따라 다릅니다. 포괄적인 구성 및 슬롯 우선 순위에 대한 자세한 내용은 을 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.

[role="tabbed-block"]
====
.옵션 1: 스위치가 없는 클러스터 케이블 연결
--
스위치 없는 클러스터 연결을 케이블로 연결합니다.

.단계
. 클러스터/HA 인터커넥트 포트 E1A와 e1A를 클러스터/HA 인터커넥트 케이블로 e7a에 연결합니다.
+

NOTE: 클러스터 인터커넥트 트래픽과 HA 트래픽은 동일한 물리적 포트를 공유합니다.

+
.. 컨트롤러 A의 케이블 포트 E1A를 컨트롤러 B의 포트 E1A에 연결합니다
.. 컨트롤러 A의 케이블 포트 e7a를 컨트롤러 B의 포트 e1A로 연결합니다
+
* 클러스터/HA 인터커넥트 케이블 *





image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[클러스터 HA 케이블]

+ image::../media/drw_70-90_tnsc_cluster_cluster_cabling_ieops-1653.svg [스위치가 없는 2노드 클러스터 케이블 연결 다이어그램, 너비=500px]

+. 이더넷 모듈 포트를 호스트 네트워크에 케이블로 연결합니다.

+ 다음은 일반적인 호스트 네트워크 케이블 연결 예입니다. 특정 시스템 구성은 를 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 참조하십시오.

. 그림과 같이 이더넷 데이터 네트워크 스위치에 e9a 및 e9b를 케이블로 연결합니다.
+

NOTE: 클러스터 및 HA 트래픽에서 시스템 성능을 최대화하려면 호스트 네트워크 연결에 포트 e1b 및 e7b 포트를 사용하지 않는 것이 좋습니다. 성능을 최대화하려면 별도의 호스트 카드를 사용하십시오.

+
* 100 GbE 케이블 *

+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gb 이더넷 케이블]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[100Gb 이더넷 네트워크에 케이블 연결]

. 10/25 GbE 호스트 네트워크 스위치에 케이블을 연결합니다.
+
* 4포트, 10/25 GbE 호스트 *

+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25Gb 케이블]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[100Gb 이더넷 네트워크에 케이블 연결]

+
.. 1000BASE-T RJ-45 케이블을 사용하여 컨트롤러 관리(렌치) 포트를 관리 네트워크 스위치에 연결합니다.
+
image::../media/oie_cable_rj45.svg[RJ45 케이블]

+
* 1000BASE-T RJ-45 케이블 *

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[관리 네트워크에 연결합니다]






IMPORTANT: 아직 전원 코드를 연결하지 마십시오.

--
.옵션 2: 케이블 스위치 클러스터
--
스위치된 클러스터 연결을 케이블로 연결합니다.

.단계
. 다음과 같은 케이블 연결을 설정합니다.
+

NOTE: 클러스터 인터커넥트 트래픽과 HA 트래픽은 동일한 물리적 포트를 공유합니다.

+
.. 컨트롤러 A의 케이블 포트 E1A와 컨트롤러 B의 포트 E1A를 클러스터 네트워크 스위치 A에 연결합니다
.. 컨트롤러 A의 케이블 포트 e7a와 컨트롤러 B의 포트 e7a를 클러스터 네트워크 스위치 B에 연결합니다
+
* 100 GbE 케이블 *

+
image::../media/oie_cable100_gbe_qsfp28.svg[100Gb 케이블]

+
image::../media/drw_70-90_switched_cluster_cabling_ieops-1657.svg[클러스터 연결을 클러스터 네트워크에 케이블 연결합니다]



. 이더넷 모듈 포트를 호스트 네트워크에 케이블로 연결합니다.
+
다음은 몇 가지 일반적인 호스트 네트워크 케이블 연결의 예입니다. 특정 시스템 구성은 를 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 참조하십시오.

+
.. 그림과 같이 이더넷 데이터 네트워크 스위치에 e9a 및 e9b를 케이블로 연결합니다.
+

NOTE: 클러스터 및 HA 트래픽에서 시스템 성능을 최대화하려면 호스트 네트워크 연결에 포트 e1b 및 e7b 포트를 사용하지 않는 것이 좋습니다. 성능을 최대화하려면 별도의 호스트 카드를 사용하십시오.

+
* 100 GbE 케이블 *

+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gb 이더넷 케이블]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[100Gb 이더넷 네트워크에 케이블 연결]

.. 10/25 GbE 호스트 네트워크 스위치에 케이블을 연결합니다.
+
* 4포트, 10/25 GbE 호스트 *

+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25GB 이더넷 케이블]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[10/25GB 이더넷 네트워크에 케이블 연결]



. 1000BASE-T RJ-45 케이블을 사용하여 컨트롤러 관리(렌치) 포트를 관리 네트워크 스위치에 연결합니다.
+
image::../media/oie_cable_rj45.svg[RJ-45 케이블]

+
* 1000BASE-T RJ-45 케이블 *

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[관리 네트워크에 연결합니다]




IMPORTANT: 아직 전원 코드를 연결하지 마십시오.

--
====


== 2단계: 컨트롤러를 쉘프에 케이블 연결합니다

컨트롤러를 쉘프 또는 쉘프에 케이블을 연결합니다.

다음 절차는 컨트롤러를 1개 쉘프 및 2개 쉘프에 연결하는 방법을 보여줍니다. 컨트롤러를 최대 4개의 쉘프에 연결할 수 있습니다.

[role="tabbed-block"]
====
.옵션 1: NS224 쉘프 1개에 케이블 연결
--
각 컨트롤러를 NS224 쉘프의 NSM 모듈에 연결합니다. 그래픽은 각 컨트롤러의 케이블 연결을 보여줍니다. 컨트롤러 A 케이블은 파란색으로, 컨트롤러 B 케이블은 노란색으로 연결합니다.

.단계
. 컨트롤러 A 포트 e11a를 NSM A 포트 e0a에 연결합니다.
. 컨트롤러 A 포트 e11b를 포트 NSM B 포트 e0b에 연결합니다.
+
image:../media/drw_a70-90_1shelf_cabling_a_ieops-1731.svg["컨트롤러 A e11a 및 e11b - 단일 NS224 쉘프"]

. 컨트롤러 B 포트 e11a를 NSM B 포트 e0a에 연결합니다.
. 컨트롤러 B 포트 e11b를 NSM A 포트 e0b에 연결합니다.
+
image:../media/drw_a70-90_1shelf_cabling_b_ieops-1732.svg["컨트롤러 B e11a 및 e11b - 단일 NS224 쉘프"]



--
.옵션 2: NS224 쉘프 2개에 케이블 연결
--
각 컨트롤러를 두 NS224 쉘프의 NSM 모듈에 케이블로 연결합니다. 그래픽은 각 컨트롤러의 케이블 연결을 보여줍니다. 컨트롤러 A 케이블은 파란색으로, 컨트롤러 B 케이블은 노란색으로 연결합니다.

.단계
. 컨트롤러 A에서 다음 케이블을 연결합니다.
+
.. 포트 e11a를 쉘프 1, NSM A 포트 e0a에 연결합니다.
.. 포트 e11b를 쉘프 2,NSM B 포트 e0b에 연결합니다.
.. 포트 e8a를 쉘프 2, NSM A 포트 e0a에 연결합니다.
.. 포트 e8b를 쉘프 1,NSM B 포트 e0b에 연결합니다.
+
image:../media/drw_a70-90_2shelf_cabling_a_ieops-1733.svg["컨트롤러 A의 컨트롤러-쉘프 연결"]



. 컨트롤러 B에서 다음 케이블을 연결합니다.
+
.. 포트 e11a를 쉘프 1, NSM B 포트 e0a에 연결합니다.
.. 포트 e11b를 쉘프 2,NSM A 포트 e0b에 연결합니다.
.. 포트 e8a를 쉘프 2, NSM B 포트 e0a에 연결합니다.
.. 포트 e8b를 쉘프 1,NSM A 포트 e0b에 연결합니다.
+
image:../media/drw_a70-90_2shelf_cabling_b_ieops-1734.svg["컨트롤러 B의 컨트롤러-쉘프 연결"]





--
====