---
permalink: a70-90/maintain-overview.html 
sidebar: sidebar 
keywords: aff a70 aff a90 maintenance, maintenance, repairing aff a70 aff a90, repairing a70 aff a90, replace a70 aff a90 components 
summary: AFF A70, AFF A90 하드웨어를 유지 관리합니다 
---
= AFF A70, AFF A90 하드웨어 유지 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70, AFF A90 스토리지 시스템의 경우 다음 구성 요소에 대한 유지보수 절차를 수행할 수 있습니다.



== 미디어를 부팅합니다

부팅 매체는 시스템이 부팅될 때 사용하는 1차 및 2차 부팅 이미지 파일 세트를 저장합니다.



== 섀시

섀시는 컨트롤러/CPU 장치, 전원 공급 장치 및 I/O와 같은 모든 컨트롤러 구성 요소를 수용하는 물리적 인클로저입니다



== 컨트롤러

컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 ONTAP 기능을 구현합니다.



== DIMM

메모리 불일치가 있거나 DIMM에 결함이 있는 경우 DIMM(Dual In-line Memory Module)을 교체해야 합니다.



== 드라이브

드라이브는 물리적 데이터 저장 미디어를 제공하는 장치입니다.



== 팬

팬이 컨트롤러를 냉각시킵니다.



== NVRAM

NVRAM(Non-Volatile Random Access Memory)은 시스템 전원이 꺼질 경우 컨트롤러가 전송 중인 데이터를 보호하고 저장할 수 있도록 하는 모듈입니다. 시스템 ID는 NVRAM 모듈에 상주합니다. 교체된 경우 컨트롤러는 교체용 NVRAM 모듈의 새 시스템 ID로 가정합니다.



== NV 배터리

NVRAM 배터리는 정전 후 전송 중인 데이터에 플래시 메모리로 디스테이징되는 동안 NVRAM 모듈에 전원을 공급하는 역할을 합니다.



== 입출력 모듈

I/O 모듈(입/출력 모듈)은 컨트롤러와 데이터를 교환해야 하는 여러 장치 또는 시스템 간의 중간 역할을 하는 하드웨어 구성 요소입니다.



== 전원 공급 장치

전원 공급 장치는 컨트롤러에 중복 전원을 제공합니다.



== 실시간 시계 배터리

실시간 시계 배터리는 전원이 꺼져 있을 경우 시스템 날짜 및 시간 정보를 보존합니다.



== 시스템 관리 모듈

시스템 관리 모듈은 컨트롤러 또는 시스템 유지 관리를 위해 컨트롤러와 콘솔 또는 랩톱 간에 인터페이스를 제공합니다. 시스템 관리 모듈에는 부팅 매체가 포함되어 있으며 시스템 일련 번호(SSN)가 저장됩니다.
