---
permalink: a900/bootmedia_encryption_restore.html 
sidebar: sidebar 
keywords:  
summary: '환경 변수를 선택한 후에는 Onboard Key Manager\(OKM\), NetApp Storage Encryption\(NSE\), NetApp Volume Encryption\(NVE\)가 활성화된 시스템 관련 단계를 완료해야 합니다.' 
---
= OKM, NSE 및 NVE-AFF A900에 대한 부팅 후 미디어 교체 단계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


환경 변수를 선택한 후에는 온보드 키 관리자(OKM), NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE)를 복원하는 특정 단계를 완료해야 합니다.

. OKM, NSE 또는 NVE 구성을 복원하는 데 사용할 섹션 결정: NSE 또는 NVE가 온보드 키 관리자와 함께 활성화된 경우 이 절차를 시작할 때 캡처한 설정을 복원해야 합니다.
+
** NSE 또는 NVE가 활성화되고 온보드 키 관리자가 활성화된 경우 로 이동합니다  NVE or NSE when Onboard Key Manager is enabled.
** NSE 또는 NVE가 ONTAP 9.6에 대해 활성화된 경우 로 이동합니다  NSE/NVE on systems running ONTAP 9.6 and later.






== Onboard Key Manager가 활성화된 경우 NVE 또는 NSE를 복원합니다

. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 boot_ONTAP 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,2"]
|===
| 콘솔에 다음이 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
부팅 메뉴에서 boot_ontap menu로 컨트롤러를 부팅합니다



 a| 
반환 대기 중
 a| 
.. 프롬프트에 Ctrl-C를 입력합니다
.. 메시지: Do you wish to halt this node than wait [y/n]? y를 입력합니다
.. LOADER 프롬프트에서 'boot_ontap menu' 명령을 입력한다.


|===
. 부팅 메뉴에서 숨겨진 명령 recover_onboard_keymanager를 입력하고 프롬프트에 y를 입력합니다.
. 이 절차를 시작할 때 고객으로부터 받은 온보드 키 관리자의 암호를 입력합니다.
. 백업 데이터를 입력하라는 메시지가 나타나면 이 섹션의 시작 부분에 캡처한 백업 데이터를 붙여 넣습니다. Security key-manager backup show 또는 security key-manager 온보드 show-backup 명령의 출력을 붙여 넣는다.
+

NOTE: 이 데이터는 보안 키 관리자 백업 쇼 또는 보안 키 관리자 온보드 show-backup 명령을 통해 출력됩니다.

+
백업 데이터의 예:

+
백업 데이터 입력:

+
====
------------------------------ 백업 시작 ------------------------------------------------------- AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOVAAABAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVHAVH0AAVAAVAAVHAAVHAAAHABOH0AAH0AAHAAAH0AAH0AAHAAAHAAAHAAAH0AAH0AAAAAAAAHAAAH0AAAAHAAAHAAAHAAAHAAAHAAAH0AAHAAAHAAAH0AAAAAAAAAAAAAAAAH0AAAAAAAAAAAAHAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAAA . . . H4nPQM0nrDRYRA9SCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

------------------------------------------------- 엔드 백업 ------------------------

====
. 부팅 메뉴에서 Normal Boot 옵션을 선택합니다.
+
시스템이 반환 대기 중... 프롬프트로 부팅됩니다.

. 콘솔 케이블을 파트너 컨트롤러로 이동하고 admin으로 로그인합니다.
. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.
. 'storage failover back-fromode local-only-CFO-aggregate true' 명령을 사용하여 CFO 애그리게이트만 반환하십시오.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 고객에게 CIFS 세션을 닫는 방법을 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태이기 때문에 명령이 실패하면 NVRAM이 동기화될 때까지 5분 정도 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 콘텐츠를 참조하십시오.


. 반환이 완료되면 'storage failover show' 및 'storage failover show-반환' 명령을 사용하여 페일오버 및 반환 상태를 확인하십시오.
+
CFO 애그리게이트(루트 애그리게이트 및 CFO 스타일 데이터 애그리게이트)만 표시됩니다.

. ONTAP 9.6 이상을 실행 중인 경우 보안 키 관리자 온보드 동기화를 실행합니다.
+
.. Security key-manager 온보드 sync 명령을 실행한 다음 메시지가 나타나면 암호를 입력합니다.
.. 'Security key-manager key-query' 명령어를 입력하여 Onboard Key Manager에 저장된 모든 키의 상세 보기를 확인하고 모든 인증 키의 복원된 칼럼 = yes/true를 확인한다.
+

NOTE: 'restored(복원됨)' 열이 Yes/true(예/참) 이외의 경우 고객 지원 센터에 문의하십시오.

.. 키가 클러스터 전체에서 동기화될 때까지 10분 정도 기다립니다.


. 콘솔 케이블을 파트너 컨트롤러로 이동합니다.
. 'storage failover -fromnode local' 명령을 사용하여 타겟 컨트롤러를 다시 제공합니다.
. 'storage failover show' 명령을 사용하여 완료 후 3분 후에 반환 상태를 확인하십시오.
+
20분 후 기브백이 완료되지 않으면 고객 지원 팀에 문의하십시오.

. 클러스터 셸 프롬프트에서 net int show -is -home false 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
"false"로 표시된 인터페이스가 있으면 net int revert 명령을 사용하여 해당 인터페이스를 홈 포트로 되돌립니다.

. 콘솔 케이블을 대상 컨트롤러로 옮기고 rsion -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.




== ONTAP 9.6 이상을 실행하는 시스템에서 NSE/NVE를 복원합니다

. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 boot_ONTAP 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,2"]
|===
| 콘솔에 다음이 표시되는 경우... | 그러면... 


 a| 
로그인 프롬프트
 a| 
7단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
.. 파트너 컨트롤러에 로그인합니다.
.. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.


|===
. 콘솔 케이블을 파트너 컨트롤러로 이동하여 스토리지 페일오버 반환 -fromnode local -only-CFO -aggregate 실제 로컬 명령을 사용하여 타겟 컨트롤러 스토리지를 다시 제공합니다.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 고객에게 CIFS 세션을 닫는 방법을 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태로 인해 명령이 실패하면, NVMEM이 동기화될 때까지 5분 동안 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 콘텐츠를 참조하십시오.


. 3분 동안 기다린 다음 storage failover show 명령을 사용하여 페일오버 상태를 확인합니다.
. 클러스터 셸 프롬프트에서 "net int show -is -home false" 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
만약 어떤 인터페이스가 false로 나열된다면, net int revert 명령을 사용하여 그 인터페이스를 홈 포트로 되돌리십시오.

. 콘솔 케이블을 대상 컨트롤러로 옮기고 rsion -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. 클러스터 셸 프롬프트에서 '스토리지 암호화 디스크 표시'를 사용하여 출력을 검토합니다.
. Security key-manager key-query 명령을 사용하여 키 관리 서버에 저장된 암호화 및 인증 키를 표시합니다.
+
** 'restored' 칼럼이 'yes/true'인 경우, 사용자는 모두 완료되어 교체 프로세스를 완료할 수 있습니다.
** Key Manager type="external" 및 "restored" column = yes/true" 이외의 경우, security key-manager external restore 명령을 사용하여 인증 키의 키 ID를 복구한다.
+

NOTE: 명령이 실패하면 고객 지원 센터에 문의하십시오.

** Key Manager type="Onboard" 및 "restored" column = yes/true" 이외의 경우 보안 키 관리자 온보드 동기화 명령을 사용하여 Key Manager 유형을 다시 동기화하십시오.
+
Security key-manager key-query 명령을 사용하여 모든 인증 키에 대해 restored column = yes/true인지 확인한다.



. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 스토리지 페일오버 반환 -fromnode local 명령을 사용하여 컨트롤러를 다시 제공합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.

