---
permalink: a900/bootmedia_encryption_preshutdown_checks.html 
sidebar: sidebar 
keywords:  
summary: 손상된 컨트롤러를 종료하고 온보드 암호화 키의 상태를 확인하기 전에 손상된 컨트롤러의 상태를 확인하고, 자동 반환을 비활성화하고, 시스템이 실행 중인 ONTAP의 버전을 확인해야 합니다. 
---
= 온보드 암호화 키 사전 종료 검사 - AFF A900
:allow-uri-read: 


[role="lead"]
손상된 컨트롤러를 종료하고 온보드 암호화 키의 상태를 확인하기 전에 손상된 컨트롤러의 상태를 확인하고, 자동 반환을 비활성화하고, 시스템에서 실행 중인 ONTAP의 버전을 확인해야 합니다.

노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다. 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].

.단계
. 손상된 컨트롤러의 상태를 점검합니다.
+
** 손상된 컨트롤러가 로그인 프롬프트에 있으면 admin으로 로그인합니다.
** 손상된 컨트롤러가 로더 프롬프트에 있고 HA 구성의 일부인 경우 정상 컨트롤러에 admin으로 로그인합니다.
** 장애가 있는 컨트롤러가 독립 실행형 구성이고 로더 프롬프트에서 에 문의하십시오 link:http://mysupport.netapp.com/["mysupport.netapp.com"^].


. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 손상된 컨트롤러가 작동 중일 경우 손상된 컨트롤러에서 실행 중인 ONTAP 버전을 확인하거나, 손상된 컨트롤러가 다운된 경우 rsion -v 명령을 사용하여 파트너 컨트롤러에서 실행 중인 버전을 확인합니다.
+
** 명령 출력에 <lno-DARE> 또는 <1Ono-DARE>가 표시되면 시스템이 NVE를 지원하지 않는 것입니다. 컨트롤러를 계속 종료합니다.






== ONTAP 9.6 이상

손상된 컨트롤러를 종료하기 전에 시스템에 NetApp Volume Encryption(NVE) 또는 NetApp Storage Encryption(NSE)이 활성화되어 있는지 확인해야 합니다. 그렇다면 구성을 확인해야 합니다.

. 클러스터의 모든 볼륨에 NVE가 사용되고 있는지 확인합니다. 'volume show-is-encrypted true'
+
출력에 표시되는 볼륨이 하나라도 있으면 NVE가 구성되어 NVE 구성을 확인해야 합니다. 나열된 볼륨이 없으면 NSE가 구성되어 있고 사용 중인지 확인합니다.

. NSE 설정 및 사용 여부 확인:'Storage encryption disk show
+
** 명령 출력에 모드 및 키 ID 정보가 포함된 드라이브 세부 정보가 표시되는 경우 NSE가 구성되어 있으며 NSE 구성을 확인하고 사용 중인 것입니다.
** 디스크가 표시되지 않으면 NSE가 구성되지 않은 것입니다.
** NVE와 NSE가 구성되지 않은 경우 NSE 키로 보호되는 드라이브가 없으므로 손상된 컨트롤러를 종료하는 것이 안전합니다.






== NVE 구성을 검증합니다

. 키 관리 서버에 저장된 인증 키의 키 ID를 표시합니다. `security key-manager key query`
+

NOTE: ONTAP 9.6 릴리스 후에는 추가 키 관리자 유형이 있을 수 있습니다. KMIP, AKV, GCP 등이 있다. 이러한 유형의 확인 과정은 외부 또는 온보드 키 관리자 유형을 확인하는 과정과 같습니다.

+
** 키 관리자 유형이 외형이고 복원된 칼럼에 예라고 표시되면 손상된 컨트롤러를 차단하는 것이 안전합니다.
** 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(Yes)가 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형이 '내장'으로 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 추가 단계를 완료해야 합니다.


. 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(yes)가 표시되면 OKM 정보를 수동으로 백업합니다.
+
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 키 관리 정보(보안 키 관리자 온보드 show-backup)를 표시하려면 명령을 입력합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 손상된 컨트롤러를 종료합니다.


. 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. 외부 키 관리 인증 키를 클러스터의 모든 노드에 복원: '보안 키 관리자 외부 복원
+
명령이 실패하면 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 를 확인합니다 `Restored` 열이 동일합니다 `yes` 모든 인증 키의 경우: `security key-manager key query`
.. 손상된 컨트롤러를 종료합니다.


. 키 관리자 유형에 '온보드'가 표시되고 '복원된' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. Onboard security key-manager sync command:'security key-manager 온보딩 sync'를 입력한다
+

NOTE: 프롬프트에서 고객의 32자 영숫자 온보드 키 관리 암호를 입력합니다. 암호를 제공할 수 없는 경우 NetApp Support에 문의하십시오. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 를 확인합니다 `Restored` 열이 표시됩니다 `yes` 모든 인증 키의 경우: `security key-manager key query`
.. 키 관리자 유형에 온보드(Onboard)이 표시되는지 확인한 다음 OKM 정보를 수동으로 백업합니다.
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 명령을 입력하여 키 관리 백업 정보 '보안 키 관리자 온보드 show-backup'을 표시합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.






== NSE 구성을 확인합니다

. 키 관리 서버에 저장된 인증 키의 키 ID를 표시합니다. `security key-manager key query -key-type NSE-AK`
+

NOTE: ONTAP 9.6 릴리스 후에는 추가 키 관리자 유형이 있을 수 있습니다. KMIP, AKV, GCP 등이 있다. 이러한 유형의 확인 과정은 외부 또는 온보드 키 관리자 유형을 확인하는 과정과 같습니다.

+
** 키 관리자 유형이 외형이고 복원된 칼럼에 예라고 표시되면 손상된 컨트롤러를 차단하는 것이 안전합니다.
** 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(Yes)가 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.


. 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(yes)가 표시되면 OKM 정보를 수동으로 백업합니다.
+
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 키 관리 정보(보안 키 관리자 온보드 show-backup)를 표시하려면 명령을 입력합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.


. 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. 외부 키 관리 인증 키를 클러스터의 모든 노드에 복원: '보안 키 관리자 외부 복원
+
명령이 실패하면 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 를 확인합니다 `Restored` 열이 동일합니다 `yes` 모든 인증 키의 경우: `security key-manager key query`
.. 컨트롤러를 안전하게 종료할 수 있습니다.


. 키 관리자 유형에 '온보드'가 표시되고 '복원된' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. Onboard security key-manager sync command:'security key-manager 온보딩 sync'를 입력한다
+
프롬프트에서 고객의 32자 영숫자 온보드 키 관리 암호를 입력합니다. 암호를 제공할 수 없는 경우 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 를 확인합니다 `Restored` 열이 표시됩니다 `yes` 모든 인증 키의 경우: `security key-manager key query`
.. 키 관리자 유형에 온보드(Onboard)이 표시되는지 확인한 다음 OKM 정보를 수동으로 백업합니다.
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 명령을 입력하여 키 관리 백업 정보 '보안 키 관리자 온보드 show-backup'을 표시합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.



