---
permalink: a900/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: aff a900, shutdown the controllers 
summary: 섀시를 교체하려면 컨트롤러를 종료해야 합니다. 
---
= 컨트롤러 종료 - AFF A900
:allow-uri-read: 




== 컨트롤러 종료 - AFF A900

[role="lead"]
섀시에 대한 유지 관리를 수행할 수 있도록 컨트롤러를 종료합니다.

이 절차는 2개 노드 구성이 있는 시스템을 위한 것입니다. 시스템에 노드가 3개 이상인 경우 를 참조하십시오. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["4노드 클러스터에서 한 HA 쌍의 정상적인 종료와 전원을 켜는 방법"^]

.시작하기 전에
* 모든 클라이언트/호스트에서 NetApp 시스템의 데이터에 액세스하지 못하도록 합니다.
* 외부 백업 작업을 일시 중지합니다.
* 필요한 사용 권한과 자격 증명이 있는지 확인합니다.
+
** ONTAP에 대한 로컬 관리자 자격 증명입니다.
** 스토리지 암호화 또는 NVE/NAE를 사용하는 경우 NetApp 온보드 키 관리(OKM) 클러스터 전체 암호에 사용할 수 있습니다.
** 각 컨트롤러에 대한 BMC 접근성


* 교체에 필요한 도구와 장비가 있는지 확인합니다.
* 시스템을 종료하기 전에 다음을 수행해야 합니다.
+
** 추가 를 수행합니다 https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["시스템 상태 점검"].
** ONTAP를 시스템의 권장 릴리스로 업그레이드합니다.
** 모두 해결 https://activeiq.netapp.com/["Active IQ Wellness 알림 및 위험"]. 시스템 구성 요소의 LED와 같은 현재 시스템에 있는 모든 결함을 기록해 둡니다.




.단계
. SSH를 통해 클러스터에 로그인하거나 로컬 콘솔 케이블과 랩톱/콘솔을 사용하여 클러스터의 노드에서 로그인합니다.
. AutoSupport를 끄고 시스템이 오프라인이 될 것으로 예상되는 기간을 표시합니다.
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. 모든 노드의 SP/BMC 주소 확인:
+
`system service-processor show -node * -fields address`

. 클러스터 쉘을 종료합니다. `exit`
. 이전 단계의 출력에 나열된 노드의 IP 주소를 사용하여 SSH를 통해 SP/BMC에 로그인합니다.
+
콘솔/랩톱을 사용하는 경우 동일한 클러스터 관리자 자격 증명을 사용하여 컨트롤러에 로그인합니다.

+

NOTE: 진행 상황을 모니터링할 수 있도록 모든 SP/BMC 연결에 대한 SSH 세션을 엽니다.

. 손상된 섀시에 있는 2개의 노드를 중지합니다.
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: StrictSync 모드에서 운영되는 SnapMirror 동기식 클러스터를 사용하는 클러스터의 경우: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 가 표시되면 클러스터의 각 컨트롤러에 대해 * y * 를 입력합니다 `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. 각 컨트롤러가 멈출 때까지 기다린 후 LOADER 프롬프트가 표시됩니다.

