---
permalink: asa800/maintain-overview.html 
sidebar: sidebar 
keywords: asa A800 maintenance, maintenance, repairing ASA A800, repairing asa A800, replace asa A800 components, replace asa A800 components 
summary: ASA A800 하드웨어 유지 관리 
---
= ASA A800 하드웨어 유지 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장기적인 안정성과 최적의 성능을 보장하려면 ASA A800 스토리지 시스템의 하드웨어를 유지 관리하세요. 고장난 부품 교체와 같은 정기적인 유지 관리 작업을 수행하면 가동 중지 및 데이터 손실을 방지하는 데 도움이 됩니다.

유지 관리 절차에서는 ASA A800 스토리지 시스템이 이미 ONTAP 환경에서 스토리지 노드로 배포되었다고 가정합니다.



== 시스템 구성 요소

ASA A800 스토리지 시스템의 경우 다음 구성 요소에 대한 유지보수 절차를 수행할 수 있습니다.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["부팅 미디어 - 자동 복구"]
 a| 
부팅 미디어는 스토리지 시스템이 부팅하는 데 사용하는 기본 및 보조 ONTAP 이미지 파일 세트를 저장합니다.  자동 복구 중에 시스템은 파트너 노드에서 부트 이미지를 검색하고 적절한 부트 메뉴 옵션을 자동으로 실행하여 교체 부트 미디어에 이미지를 설치합니다. 자동 부팅 미디어 복구 프로세스는 ONTAP 9.17.1 이상에서만 지원됩니다. 스토리지 시스템에서 이전 버전의 ONTAP 실행 중인 경우 link:bootmedia-replace-workflow.html["수동 부팅 복구 절차"] .



 a| 
link:bootmedia-replace-workflow.html["부팅 미디어 - 수동 복구"]
 a| 
부팅 미디어는 스토리지 시스템이 부팅하는 데 사용하는 기본 및 보조 ONTAP 이미지 파일 세트를 저장합니다. 수동 복구 중에는 USB 드라이브에서 스토리지 시스템을 부팅하고 파일 시스템 이미지와 구성을 수동으로 복원합니다.  스토리지 시스템에서 ONTAP 9.17.1 이상을 실행 중인 경우 다음을 사용하십시오.link:bootmedia-replace-workflow-bmr.html["자동 부팅 복구 절차"] .



 a| 
link:chassis-replace-workflow.html["섀시"]
 a| 
섀시는 컨트롤러/CPU 장치, 전원 공급 장치 및 I/O와 같은 모든 컨트롤러 구성 요소를 수용하는 물리적 인클로저입니다



 a| 
link:controller-replace-overview.html["컨트롤러"]
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 ONTAP 기능을 구현합니다.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
메모리 불일치가 있거나 DIMM에 결함이 있는 경우 DIMM(Dual In-line Memory Module)을 교체해야 합니다.



 a| 
link:drive-replace.html["드라이브"]
 a| 
드라이브는 물리적 데이터 저장 미디어를 제공하는 장치입니다.



 a| 
link:fan-replace.html["팬"]
 a| 
팬이 컨트롤러를 냉각시킵니다.



 a| 
link:nvdimm-replace.html["NVDIMM"]
 a| 
NVDIMM(비휘발성 듀얼 인라인 메모리 모듈)은 휘발성 메모리에서 비휘발성 저장소로 데이터를 전송하고 전원 손실 또는 시스템 종료 시 데이터 무결성을 유지합니다.



 a| 
link:nvdimm-battery-replace.html["NVDIMM 배터리"]
 a| 
NVDIMM 전지는 NVDIMM 모듈의 전원 관리를 담당합니다.



 a| 
link:pci-cards-and-risers-replace.html["PCIe 카드 및 라이저"]
 a| 
PCIe(Peripheral Component Interconnect Express) 카드는 마더보드의 PCIe 슬롯이나 마더보드에 연결된 라이저에 꽂는 확장 카드입니다.



 a| 
link:power-supply-replace.html["전원 공급 장치"]
 a| 
전원 공급 장치는 컨트롤러 쉘프에 이중 전원을 제공합니다.



 a| 
link:rtc-battery-replace.html["실시간 시계 배터리"]
 a| 
실시간 시계 배터리는 전원이 꺼져 있을 경우 시스템 날짜 및 시간 정보를 보존합니다.

|===