---
permalink: a200/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a200, how to recable the system, how to reassign disks 
summary: 스토리지를 다시 설정하고 디스크 재할당을 확인해야 합니다. 
---
= 시스템을 재할당하고 디스크를 재할당할 수 있습니다. - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지를 다시 케이블로 연결하고 디스크 재할당을 확인하여 교체 절차를 계속합니다.



== 1단계: 시스템 케이블을 다시 연결합니다

컨트롤러 모듈의 스토리지 및 네트워크 연결을 확인합니다.

.단계
. 을 사용하여 케이블이 올바른지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Config Advisor를 다운로드하고 설치합니다.
.. 대상 시스템에 대한 정보를 입력한 다음 데이터 수집 을 클릭합니다.
.. 케이블 연결 탭을 클릭한 다음 출력을 확인합니다. 모든 디스크 쉘프가 표시되고 모든 디스크가 출력에 표시되는지 확인하여 찾은 케이블 연결 문제를 해결합니다.
.. 해당 탭을 클릭하여 다른 케이블을 확인한 다음 Config Advisor의 출력을 확인합니다.






== 2단계: 디스크를 재할당합니다

스토리지 시스템이 HA 쌍 내에 있는 경우, 절차 종료 시 기브백이 발생하면 새 컨트롤러 모듈의 시스템 ID가 자동으로 디스크에 할당됩니다. 독립 실행형 시스템에서는 ID를 디스크에 수동으로 재할당해야 합니다. 구성에 맞는 절차를 사용해야 합니다.



=== 옵션 1: HA 시스템의 시스템 ID 변경을 확인합니다

_replacement_controller를 부팅할 때 시스템 ID 변경을 확인한 다음 변경이 구현되었는지 확인해야 합니다.

.이 작업에 대해
이 절차는 HA 쌍에서 ONTAP를 실행하는 시스템에만 적용됩니다.

.단계
. replacement_controller가 유지보수 모드("*>" 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. refacement_controller의 LOADER 프롬프트에서 시스템 ID 불일치로 인해 시스템 ID를 재정의하라는 메시지가 표시되면 y를 입력하여 컨트롤러를 부팅합니다
. replacement_controller 콘솔에 'Waiting for 반환...' 메시지가 표시될 때까지 기다린 후 정상적인 컨트롤러에서 새 파트너 시스템 ID가 자동으로 지정되었는지 확인합니다. 'storage failover show
+
명령 출력에는 손상된 컨트롤러에서 시스템 ID가 변경되었다는 메시지와 함께 올바른 이전 및 새 ID가 표시되어야 합니다. 다음 예제에서 node2는 교체를 거쳤으며 새 시스템 ID가 151759706입니다.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 정상적인 컨트롤러에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 모든 코어 덤프를 저장합니다. 'system node run-node_local-node-name_partner savecore'
.. 반환 명령을 실행하기 전에 'avecore' 명령이 완료될 때까지 기다리십시오.
+
다음 명령을 입력하여 savecore 명령의 진행 상태를 모니터링할 수 있습니다. 'system node run-node_local-node-name_partner savecore -s'

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. 스토리지 시스템에 스토리지 또는 볼륨 암호화가 구성된 경우 온보드 키 관리를 사용하는지 또는 외부 키 관리를 사용하는지 여부에 따라 다음 절차 중 하나를 사용하여 스토리지 또는 볼륨 암호화 기능을 복원해야 합니다.
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["온보드 키 관리 암호화 키를 복원합니다"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["외부 키 관리 암호화 키를 복원합니다"^]


. 컨트롤러를 다시 제공합니다.
+
.. 정상적인 컨트롤러에서 교체된 컨트롤러의 스토리지를 다시 제공합니다. 'storage failover 반환 - ofnode_replacement_node_name_'
+
replacement_controller가 스토리지를 다시 가져와 부팅을 완료합니다.

+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 y를 입력해야 합니다.

+

NOTE: 기브백이 거부되면 거부권을 재정의할 수 있습니다.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["사용 중인 ONTAP 9 버전에 맞는 고가용성 구성 콘텐츠를 찾아보십시오"]

.. 기브백이 완료된 후 HA 쌍이 정상 작동 중인지, 그리고 테이크오버가 가능한지, 즉 '스토리지 페일오버 표시'인지 확인합니다
+
'storage failover show' 명령의 출력에는 파트너 메시지에서 변경된 시스템 ID가 포함되지 않아야 합니다.



. 디스크가 제대로 할당되었는지 확인합니다. '스토리지 디스크 표시-소유권'
+
_replacement_controller에 속하는 디스크는 새 시스템 ID를 표시해야 합니다. 다음 예에서는 노드 1이 소유한 디스크에 새 시스템 ID 1873775277이 표시됩니다.

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. 각 컨트롤러에 대해 예상되는 볼륨이 'vol show-node-name'인지 확인합니다
. 재부팅 시 자동 테이크오버 기능을 비활성화한 경우 정상 컨트롤러 'storage failover modify -node_replacement -node -name_-onreboot true'에서 활성화하십시오




=== 옵션 2: ONTAP의 독립 실행형 시스템에 시스템 ID를 수동으로 재할당합니다

독립 실행형 시스템에서는 시스템을 정상 운영 상태로 되돌리기 전에 디스크를 새 컨트롤러의 시스템 ID로 수동으로 재할당해야 합니다.

.이 작업에 대해

NOTE: 이 절차는 독립 실행형 구성에 있는 시스템에만 적용됩니다.

.단계
. 아직 재부팅하지 않은 경우_replacement_node를 재부팅하고 Ctrl-C를 눌러 부팅 프로세스를 중단한 다음, 표시된 메뉴에서 유지보수 모드로 부팅하는 옵션을 선택하십시오.
. 시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 Y를 입력해야 합니다.
. 시스템 ID를 봅니다
. 디스크 소유자 열의 일부로 표시되는 이전 시스템 ID를 기록해야 합니다.
+
다음 예는 11807329의 이전 시스템 ID를 보여줍니다.

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118073209)  Pool0  J8XJE9LC       system-1  (118073209)
disk_name    system-1  (118073209)  Pool0  J8Y478RC       system-1  (118073209)
.
.
.

----
. disk show 명령어에서 얻은 시스템 ID 정보인 '디스크 재할당-s 기존 시스템 ID 디스크 재할당-s 118073209'를 사용하여 디스크 소유권을 재할당합니다
. 디스크가 올바르게 할당되었는지 확인합니다
+
교체 노드에 속한 디스크에 새 시스템 ID가 표시되어야 합니다. 다음 예에서는 시스템 1이 소유한 디스크를 새 시스템 ID 118065481로 표시합니다.

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
.
.
.

----
. 스토리지 시스템에 스토리지 또는 볼륨 암호화가 구성된 경우 온보드 키 관리를 사용하는지 또는 외부 키 관리를 사용하는지 여부에 따라 다음 절차 중 하나를 사용하여 스토리지 또는 볼륨 암호화 기능을 복원해야 합니다.
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["온보드 키 관리 암호화 키를 복원합니다"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["외부 키 관리 암호화 키를 복원합니다"^]


. boot:'boot_ontap' 노드를 부팅한다

