---
permalink: a200/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a200, restore and verify the system configuration, verify and set the ha state of the controller module, run system-level diagnostics 
summary: 하드웨어 교체를 완료하고 유지 관리 모드로 부팅한 후에는 교체 컨트롤러의 하위 수준 시스템 구성을 확인하고 필요에 따라 시스템 설정을 재구성합니다. 
---
= 시스템 구성 복원 및 확인 - AFF A200
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어 교체를 완료하고 유지 관리 모드로 부팅한 후에는 교체 컨트롤러의 하위 수준 시스템 구성을 확인하고 필요에 따라 시스템 설정을 재구성합니다.



== 1단계: 컨트롤러를 교체한 후 시스템 시간을 설정하고 확인합니다

교체 컨트롤러 모듈의 시간과 날짜를 HA 쌍의 정상 컨트롤러 모듈 또는 독립형 구성의 안정적인 시간 서버와 확인해야 합니다. 시간과 날짜가 일치하지 않으면 시간 차이로 인해 클라이언트가 중단되는 것을 방지하기 위해 교체 컨트롤러 모듈에서 해당 날짜와 시간을 재설정해야 합니다.

올바른 시스템에 다음 단계에 있는 명령을 적용하는 것이 중요합니다.

* replacement_node는 이 절차의 일부로 손상된 노드를 교체한 새 노드입니다.
* healthy_node는 _replacement_node의 HA 파트너입니다.


.단계
. refacement_node가 LOADER 프롬프트에 있지 않으면 시스템을 LOADER 프롬프트로 중단합니다.
. healthy_node에서 시스템 시간, 즉 '날짜 표시'를 확인한다
+
날짜 및 시간은 GMT로 제공됩니다.

. LOADER 프롬프트에서, _replacement_node:sHow date의 날짜와 시간을 확인하십시오
+
날짜 및 시간은 GMT로 제공됩니다.

. 필요한 경우 교체 노드의 날짜(GMT)를 'SET DATE_MM/dd/yyyy_'로 설정합니다
. 필요한 경우 교체 노드의 시간을 GMT 단위로 'SET TIME_hh:mm:ss_'로 설정합니다
. LOADER 프롬프트에서 _replacement_node:sHow date의 날짜와 시간을 확인합니다
+
날짜 및 시간은 GMT로 제공됩니다.





== 2단계: 컨트롤러 모듈의 HA 상태를 확인하고 설정합니다

컨트롤러 모듈의 HA 상태를 확인하고 필요한 경우 시스템 구성과 일치하도록 상태를 업데이트해야 합니다.

.단계
. 새 컨트롤러 모듈의 유지보수 모드에서 모든 구성요소가 동일한 HA 상태 ha-config show를 표시하는지 확인합니다
+
HA 상태의 값은 다음 중 하나일 수 있습니다.

+
** HA
** 비 하


. 컨트롤러 모듈의 표시된 시스템 상태가 시스템 구성과 일치하지 않으면 컨트롤러 모듈의 HA 상태를 "ha-config modify controller ha-state"로 설정합니다
. 설정이 변경되었는지 확인합니다. ha-config show




== 3단계: 시스템 수준 진단 프로그램을 실행합니다

컨트롤러를 교체할 때마다 특정 구성 요소와 하위 시스템에 대해 종합적이거나 집중적인 진단 테스트를 실행해야 합니다.

진단 절차의 모든 명령은 구성 요소를 교체하는 컨트롤러에서 실행됩니다.

.단계
. 수리할 컨트롤러가 LOADER 프롬프트에서 없으면 컨트롤러를 "HALT"로 재부팅합니다
+
명령을 실행한 후 시스템이 로더 프롬프트에서 중지될 때까지 기다려야 합니다.

. LOADER 프롬프트에서 시스템 수준 진단이 제대로 작동하도록 특별히 설계된 특수 드라이버('BOOT_DIAGS')에 액세스합니다
+
부팅 프로세스 중에 유지보수 모드 프롬프트(*>)가 나타날 때까지 프롬프트에 "y"로 안전하게 응답할 수 있습니다.

. 컨트롤러 모듈에서 사용할 수 있는 'ldiag device show-dev MB'를 표시하고 기록합니다
+
표시되는 컨트롤러 모듈 장치 및 포트는 다음 중 하나 이상이 될 수 있습니다.

+
** bootmedia는 시스템 부팅 장치입니다.
** CNA는 네트워크 또는 스토리지 장치에 연결되지 않은 통합 네트워크 어댑터 또는 인터페이스입니다.
** FCAL은 Fibre Channel 네트워크에 연결되지 않은 Fibre Channel 중재 루프 디바이스입니다.
** env는 마더보드 환경이다.
** MEM은 시스템 메모리입니다.
** NIC는 네트워크 인터페이스 카드입니다.
** NVRAM은 비휘발성 RAM입니다.
** nvmem은 NVRAM과 시스템 메모리의 혼합입니다.
** 'AS'는 디스크 쉘프에 연결되지 않은 직렬 연결 SCSI 장치입니다.


. 원하는 대로 진단 유틸리티를 실행합니다.
+
[cols="1,2"]
|===
| 에 대한 진단 테스트를 실행하려면... | 그러면... 


 a| 
개별 부품
 a| 
.. 상태 로그 'ldiag device clearstatus'를 지웁니다
.. 선택한 장치에 대해 사용 가능한 테스트 'sldiag device show-dev_dev_name_'을 표시합니다
+
_dev_name_은 이전 단계에서 식별된 포트 및 장치 중 하나일 수 있습니다.

.. 출력을 검사하고 해당되는 경우 'sldiag device modify -dev_dev_name_-selection only'(실행할 테스트만 선택)를 선택합니다
+
-selection은 장치에 대해 실행하지 않을 다른 모든 검사만 비활성화합니다.

.. 'sldiag device run-dev_dev_name_' 테스트를 실행합니다
+
테스트가 완료되면 다음 메시지가 표시됩니다.

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. 'sldiag device status-dev_dev_name_-long-state failed'라는 테스트가 실패하지 않았는지 확인합니다
+
시스템 수준 진단은 테스트 실패가 없을 경우 프롬프트로 돌아가거나 구성 요소 테스트로 인한 전체 실패 상태를 표시합니다.





 a| 
동시에 여러 개의 부품을 사용할 수 있습니다
 a| 
.. 위 절차의 출력에서 활성화 및 비활성화된 장치를 검토하고 동시에 실행할 장치를 결정합니다.
.. 'sldiag device show -dev_dev_name_' 장치에 대한 개별 테스트를 나열합니다
.. 출력을 검사하고 해당되는 경우 'sldiag device modify -dev_dev_name_-selection only'(실행할 테스트만 선택)를 선택합니다
+
-selection은 장치에 대해 실행하지 않을 다른 모든 검사만 비활성화합니다.

.. 'ldiag device show'라는 테스트가 수정되었는지 확인합니다
.. 동시에 실행할 각 장치에 대해 이러한 하위 단계를 반복합니다.
.. 모든 장치에 대해 'ldiag 장치 실행'을 진단 유틸리티를 실행합니다
+

NOTE: 진단 프로그램을 실행한 후에는 항목을 추가하거나 수정하지 마십시오.

+
테스트가 완료되면 다음 메시지가 표시됩니다.

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. 컨트롤러에 하드웨어 문제가 없는지 확인합니다. 'ldiag 장치 상태 - long-state failed'
+
시스템 수준 진단은 테스트 실패가 없을 경우 프롬프트로 돌아가거나 구성 요소 테스트로 인한 전체 실패 상태를 표시합니다.



|===
. 이전 단계의 결과에 따라 계속 진행합니다.
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
실패없이 완료되었습니다
 a| 
.. 상태 로그 'ldiag device clearstatus'를 지웁니다
.. 'ldiag device status'라는 로그가 지워졌는지 확인한다
+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 유지보수 모드를 종료합니다
+
LOADER 프롬프트가 표시됩니다.

+
시스템 수준 진단을 완료했습니다.





 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 유지보수 모드를 종료합니다
.. 완전 종료를 수행한 다음 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결한 다음 스토리지 시스템의 전원을 켭니다.
.. 시스템 수준 진단 테스트를 다시 실행하십시오.


|===

