---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP 하드웨어 시스템 설명서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: ONTAP 하드웨어 시스템의 새로운 기능
      url: "/whats-new.html"
    - title: ONTAP 하드웨어 및 소프트웨어 호환성
      url: "/supported-platforms.html"
    - title: 지원 종료
      url: "/eoa-hardware.html"
  - title: 빠른 시작
    url: "/get-up-and-run.html"
  - title: AFF 시스템
    url: "/aff-landing/index.html"
    entries:
    - title: A-Series 시스템
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: C-Series 시스템
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
      - section: c800
  - title: AFX 시스템
    url: "/afx/index.html"
    entries:
    - title: 설치 및 설정
      url: "/afx/afx-install-setup.html"
    - title: 유지 관리
      pdf-filename: AFX 유지
      url: "/afx-landing-maintain/index.html"
      entries:
      - title: 유지 보수 개요
        url: "/afx-1k/maintain-overview.html"
      - title: 미디어를 부팅합니다
        pdf-filename: AFX 1K 부트 미디어
        entries:
        - title: 부팅 미디어 교체 워크플로우
          url: "/afx-1k/bootmedia-replace-workflow.html"
        - title: 요구사항 검토
          url: "/afx-1k/bootmedia-replace-requirements.html"
        - title: 컨트롤러를 종료합니다
          url: "/afx-1k/bootmedia-shutdown.html"
        - title: 부팅 미디어를 교체합니다
          url: "/afx-1k/bootmedia-replace.html"
        - title: 부팅 미디어 복원
          url: "/afx-1k/bootmedia-recovery-image-boot.html"
        - title: 오류가 발생한 부품을 NetApp으로 반환합니다
          url: "/afx-1k/bootmedia-complete-rma.html"
      - title: 섀시
        pdf-filename: AFX A1K 섀시
        entries:
        - title: 섀시 교체 워크플로우
          url: "/afx-1k/chassis-replace-workflow.html"
        - title: 요구사항 검토
          url: "/afx-1k/chassis-replace-requirements.html"
        - title: 교체를 준비합니다
          url: "/afx-1k/chassis-replace-prepare.html"
        - title: 컨트롤러를 종료합니다
          url: "/afx-1k/chassis-replace-shutdown.html"
        - title: 섀시를 교체합니다
          url: "/afx-1k/chassis-replace-move-hardware.html"
        - title: 섀시 교체를 완료합니다
          url: "/afx-1k/chassis-replace-complete-system-restore-rma.html"
      - title: 컨트롤러
        pdf-filename: AFX 1K 컨트롤러
        entries:
        - title: 컨트롤러 교체 워크플로우
          url: "/afx-1k/controller-replace-workflow.html"
        - title: 요구사항 검토
          url: "/afx-1k/controller-replace-requirements.html"
        - title: 손상된 컨트롤러를 종료합니다
          url: "/afx-1k/controller-replace-shutdown.html"
        - title: 컨트롤러를 교체합니다
          url: "/afx-1k/controller-replace-move-hardware.html"
        - title: 시스템 구성을 복원합니다
          url: "/afx-1k/controller-replace-system-config-restore-and-verify.html"
        - title: 컨트롤러를 반납합니다
          url: "/afx-1k/controller-replace-recable-reassign-disks.html"
        - title: 전체 컨트롤러 교체
          url: "/afx-1k/controller-replace-restore-system-rma.html"
      - title: DIMM
        url: "/afx-1k/dimm-replace.html"
      - title: 팬
        url: "/afx-1k/fan-replace.html"
      - title: NVRAM
        url: "/afx-1k/nvram-replace.html"
      - title: NV 배터리
        url: "/afx-1k/nvdimm-battery-replace.html"
      - title: 입출력 모듈
        pdf-filename: AFX 1K IO 모듈
        entries:
        - title: I/O 모듈 개요
          url: "/afx-1k/io-module-overview.html"
        - title: 입출력 모듈을 추가합니다
          url: "/afx-1k/io-module-add.html"
        - title: 입출력 모듈을 교체합니다
          url: "/afx-1k/io-module-replace.html"
      - title: 전원 공급 장치
        url: "/afx-1k/power-supply-replace.html"
      - title: 실시간 시계 배터리
        url: "/afx-1k/rtc-battery-replace.html"
      - title: 시스템 관리 모듈
        url: "/afx-1k/system-management-replace.html"
  - title: ASA 시스템
    url: "/allsan-landing/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: ASA r2 시스템
    url: "/asa-r2/index.html"
    entries:
    - title: 설치 및 설정
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: 유지 관리
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: FAS 시스템
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: 이용 종료 시스템
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: asa-c250
    - section: asa-c400
    - section: asa-c800
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: 기타 모델
      url: "/other/other-models.html"
  - title: 드라이브 쉘프
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: nx224
    - section: sas3
  - title: 캐비닛 및 레일 키트
    entries:
    - title: SuperRail 키트
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700/FAS9000 2포스트 레일 키트
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42U 1280 mm 시스템 캐비닛
      entries:
      - title: 캐비닛 설치를 준비합니다
        entries:
        - title: 캐비닛 기능
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: 필요한 공구/장비
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: 공간 요구 사항 및 캐비닛 치수
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: 지원되는 PDU 유형 및 사양
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: 시스템 캐비닛의 포장을 풉니다
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: 캐비닛을 설치합니다
        entries:
        - title: 개요
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: 캐비닛 상호 연결 키트를 설치합니다
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: 볼트 다운 키트를 장착하십시오
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: 지지 레일을 설치합니다
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: 장비를 설치합니다
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: 캐비닛 전원을 켭니다
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: PDU를 교체합니다
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: 캐비닛 전면 덮개를 반대로 합니다
        entries:
        - title: 필요한 것
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: 조명이 들어오는 배지를 제거하십시오
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: 캐비닛 도어를 제거합니다
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: 배지 전원 공급 장치 및 케이블을 이동합니다
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: 도어 힌지 및 잠금 캐치를 반대로 합니다
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: 도어 및 조명 배지를 다시 장착하십시오
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: 구성품별 교체 절차
    url: "/fru-reference/index.html"
    entries:
    - title: 미디어를 부팅합니다
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: 캐싱 모듈
      url: "/fru-reference/caching-module-fru-links.html"
    - title: 섀시
      url: "/fru-reference/chassis-fru-links.html"
    - title: 컨트롤러
      url: "/fru-reference/controller-fru-links.html"
    - title: DCPM 전원 모듈
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: 드라이브
      url: "/fru-reference/drive-fru-links.html"
    - title: 팬
      url: "/fru-reference/fan-fru-links.html"
    - title: 입출력 모듈
      url: "/fru-reference/io-module-fru-links.html"
    - title: LED 모듈
      url: "/fru-reference/led-module-fru-links.html"
    - title: 중 이층
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: NVMEM/ NVRAM 배터리
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: NVRAM 모듈
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: NSM
      url: "/fru-reference/nsm-fru-links.html"
    - title: PCI 카드 및 라이저
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: 전원 공급 장치
      url: "/fru-reference/power-supply-fru-links.html"
    - title: RTC 배터리
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: 시스템 관리 모듈
      url: "/fru-reference/system-management-fru-links.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
