---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, afx, asa r2, aff, asa, fas 
summary: ONTAP 하드웨어 시스템을 위한 새로운 플랫폼에 대해 알아보십시오. 
---
= ONTAP 하드웨어 시스템의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAP 하드웨어 시스템의 새로운 기능에 대해 알아보십시오. 추가 지원 정보는 다음을 참조하세요. link:supported-platforms.html["ONTAP 하드웨어 및 소프트웨어 호환성"] 그리고 link:eoa-hardware.html["더 이상 지원되지 않는 하드웨어"] .



== 2025년 10월



=== AFX 스토리지 시스템

새로운 NetApp AFX 스토리지 시스템은 AI/ML 애플리케이션을 포함한 고성능 NAS 및 S3 워크로드의 엄격한 요구 사항을 충족하도록 설계된 분산 솔루션을 제공합니다. AFX 시스템은 확장 가능하고 처리량이 높은 파일 및 개체 스토리지를 필요로 하는 고객을 위해 특수 기능을 제공합니다.

link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["AFX 시스템에 대해 자세히 알아보세요"] .



=== AFX용 새로운 드라이브 선반

AFX용 새로운 NXS224 스토리지 선반은 NVMe-oF(Non-Volatile Memory Express over Fabrics)를 사용하여 고밀도 SSD를 연결합니다. 디스크는 RoCE(RDMA over Converged Ethernet)를 사용하여 초저지연 패브릭을 통해 통신합니다. I/O 모듈, NIC, 팬, 전원 공급 장치를 포함한 스토리지 선반은 단일 장애 지점 없이 완벽하게 중복됩니다. 자체 관리 기술은 RAID 구성과 디스크 레이아웃의 모든 측면을 관리하고 제어하는 데 사용됩니다.



=== AFX용 새로운 스위치

Cisco 9364D-GX2A 스위치와 Cisco 9332D-GX2B 스위치는 AFX 컨트롤러 노드를 스토리지 선반에 연결합니다.  이러한 새로운 스위치를 사용하면 두 개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다. 성능을 최적화하기 위해 고급 프로토콜이 사용됩니다. 이 설계는 여러 네트워크 경로를 갖춘 VLAN 태깅과 기술 업데이트 구성을 기반으로 하여 지속적인 운영과 쉬운 업그레이드를 보장합니다.



== 2025년 9월



=== 플랫폼 사양

ONTAP 하드웨어 시스템 설명서에는 이제 다음에서도 찾을 수 있는 사양이 포함됩니다.link:https://hwu.netapp.com["Hardware Universe"] . 예를 들어,link:https://docs.netapp.com/us-en/ontap-systems/a1k/overview.html["AFF A1K 의 주요 사양"] .



=== 플랫폼 제품군별 교체 참조

ONTAP 하드웨어 시스템 설명서에서는 이제 플랫폼 제품군별로 구성된 NetApp 스토리지 시스템에 대한 교체 절차를 제공합니다.

link:fru-reference/index.html["대체 절차 찾기"]스토리지 시스템의 현장 교체 장치(FRU)용입니다.



== 2025년 5월



=== ASA C30

새로운 ASA C30 시스템은 더 많은 고객과 작업 부하에 고성능, 지능적이고 포괄적인 데이터 관리 기능을 제공합니다.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"^] .



== 2025년 4월



=== FAS50를 참조하십시오

FAS50 시스템은 보조 스토리지와 보안 사이버 볼트에 대해 기가바이트당 가장 낮은 비용을 제공하며, 더 빠른 백업, 더 높은 IOPS, 5~10ms의 낮은 지연 시간으로 보조 워크로드에 대한 성능을 향상시킵니다.

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 시스템에 대해 자세히 알아보십시오"^] .



== 2025년 2월



=== ASA A20, ASA A30 및 ASA A50

엔트리 레벨 ASA A20 및 미드레인지 ASA A30 및 A50 시스템은 데이터베이스 및 가상 머신과 같은 미션 크리티컬 애플리케이션을 위해 모든 규모의 기업에서 블록 스토리지를 사용할 수 있도록 지원합니다.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"^] .



== 2024년 출시

.2024년 12월
[%collapsible]
====
.AFF A20, AFF A30 및 AFF A50의 약어입니다
새로운 AFF A20, A30, A50 하드웨어 시스템은 더 많은 고객과 워크로드에서 고성능의 지능적이고 포괄적인 데이터 관리 기능을 확장합니다.

이 시스템은 블록, 파일 및 오브젝트 스토리지를 지원하는 AI, VMware, 데이터베이스 및 분석을 포함한 미션 크리티컬 워크로드를 위한 실시간 ML 기반 랜섬웨어 감지, 원활한 클라우드 통합, 탁월한 성능을 제공합니다.

link:https://www.netapp.com/data-storage/aff-a-series/["AFF A-Series 시스템에 대해 자세히 알아보십시오"^] .

.AFF C30, AFF C60 및 AFF C80의 약어입니다
새로운 AFF C30, AFF C60, AFF C80 하드웨어 시스템은 2랙 구축에서 업계 최고 수준의 1.5PB의 스토리지 용량을 제공하여 기업이 플래시의 성능 및 효율성 이점을 더욱 활용할 수 있도록 지원합니다.

이 솔루션은 60TB 드라이브로 탁월한 집적도와 향상된 성능, 개선된 I/O 유연성을 제공합니다.

link:https://www.netapp.com/data-storage/aff-c-series/["AFF C-Series 시스템에 대해 자세히 알아보십시오"^] .

.NSM100B 쉘프 모듈이 포함된 NS224 드라이브 쉘프
NS224와 새로운 NSM100B NVMe 스토리지 확장 모듈을 통해 데이터 센터의 기능을 향상하십시오. NSM100 모듈을 직접 대체하도록 설계된 새로운 NSM100B 셸프 모듈은 기존 설정에 원활하게 통합됩니다. NS224 쉘프의 직접 연결 및 스위치 연결 구성을 모두 지원하므로 뛰어난 유연성을 제공하여 스토리지 시스템의 효율성과 확장성을 최적화할 수 있습니다.

====
.2024년 9월
[%collapsible]
====
.ASA r2 시스템
새로운 ASA R2 하드웨어 시스템(ASA A1K, ASA A70 및 ASA A90)은 SAN 전용 고객의 요구 사항에 맞는 간소화된 환경을 제공하는 통합 하드웨어 및 소프트웨어 솔루션을 제공합니다.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"^] .

.FAS70 및 FAS90
새로운 FAS70 및 FAS90 하드웨어 시스템은 경제적이고 성능이 우수한 백업 스토리지를 제공하여 랜섬웨어 공격으로부터 복구할 수 있는 안전한 사이버 보관소를 제공합니다.

link:https://www.netapp.com/data-storage/fas/["FAS 시스템에 대해 자세히 알아보십시오"^] .

====