---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features,aff, asa,  fas, legacy, end-of-support 
summary: AFF, ASA 및 FAS 시스템의 새로운 기능과 더 이상 지원되지 않는 기존 하드웨어에 대해 알아보십시오. 
---
= AFF, ASA 및 FAS 시스템의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
AFF, ASA 및 FAS 시스템의 새로운 기능에 대해 알아보십시오.

ONTAP 9 릴리스의 알려진 문제, 제한 사항 및 업그레이드 주의 사항에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"]. 릴리스 정보에 액세스하려면 NetApp 계정으로 로그인하거나 계정을 만들어야 합니다.



== 새로운 플랫폼 지원

[cols="2*"]
|===
| 플랫폼(데이터 시트에 대한 링크 포함) | 처음부터 사용할 수 있습니다 


 a| 
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A1K 를 참조하십시오"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A70 를 참조하십시오"]
* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A90 를 참조하십시오"]

 a| 
ONTAP 9.15.1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250 을 참조하십시오"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400 을 참조하십시오"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800을 참조하십시오"]
 a| 
ONTAP 9.13.P11



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1 을 참조하십시오



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA 이상 ONTAP 릴리즈

[NOTE]
====
이러한 플랫폼은 ONTAP 9.13.1 RC1에서는 지원되지 않습니다.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
지원되지 않는 버전의 ONTAP로 AFF A150 스토리지 시스템을 설치하거나 부팅하지 마십시오. 지원되지 않는 버전의 ONTAP를 사용하여 시스템을 설치하거나 부팅하려고 하면 ONTAP에서 이를 허용합니다(ONTAP는 시도를 차단하지 않습니다). 결과적으로 AFF A150 스토리지 시스템이 FAS2750 스토리지 시스템으로 등장할 것입니다.

==== a| 
ONTAP 9.13.1 이상 ONTAP 릴리스

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3입니다



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["500f로 설정합니다"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7623-ds-3989.pdf["AFF C190"^]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===


== 새로운 스위치 지원

[cols="20,65,15"]
|===
| 스위치 | 설명 | 처음부터 사용할 수 있습니다 


 a| 
https://hwu.netapp.com/Switch/Index["NVIDIA IP SN2100 스위치"]
 a| 
NVIDIA IP SN2100 스토리지 스위치는 A900/FAS9500 플랫폼을 사용하는 MetroCluster IP 구성에서 지원됩니다.
 a| 
ONTAP 9.12.1



 a| 
https://hwu.netapp.com/Switch/Index["NVIDIA IP SN2100 스위치(X190006)"]
 a| 
NVIDIA IP SN2100 스토리지 스위치는 다음 플랫폼을 사용하는 MetroCluster IP 구성에서 지원됩니다.

* FAS500f/AFF A250
* FAS8300/AFF A400
* FAS8700
* FAS9000/AFF A700
* AFF A800

 a| 
ONTAP 9.10.1P3입니다



 a| 
https://hwu.netapp.com/Switch/Index["36포트 100GbE Cisco 스위치(X190200)"]
 a| 
MetroCluster IP 구성을 포함하여 동일한 Cisco Nexus 9336C-FX2 스위치 쌍에서 공유 인프라(클러스터, HA 및 스위치 연결 스토리지)를 지원합니다.
 a| 
ONTAP 9.9.1



 a| 
https://hwu.netapp.com/Switch/Index["36포트 100GbE Cisco 스위치(X190200 및 X190210)"]
 a| 
Cisco Nexus 9336C-FX2 클러스터 인터커넥트 스위치 및 스토리지 스위치 지원으로 AFF/FAS 컨트롤러 및 프런트 엔드 데이터 연결 지원
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BES-53248 스위치(X190005 및 X190005R)"]
 a| 
40/100GbE 포트가 있는 AFF/FAS 컨트롤러에 대한 Broadcom BES-53248 클러스터 인터커넥트 스위치 지원
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["36포트 100GbE Cisco 스위치(X190200)"] https://hwu.netapp.com/Switch/Index["32포트 100GbE Cisco 스위치(X190100 및 X190100R)"]
 a| 
Cisco Nexus 100 GbE 스위치는 NS224 NVMe 드라이브 쉘프를 다음 플랫폼에 연결하는 전용 스토리지 스위치로 사용할 수 있습니다.

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Broadcom BES-53248 스위치(X190005 및 X190005R)"]
 a| 
Broadcom BES-53248 클러스터 인터커넥트 스위치는 10/25GbE 포트가 있는 AFF/FAS 컨트롤러를 지원합니다.
 a| 
ONTAP 9.5P8

|===


== 새로운 어댑터 지원

[cols="4*"]
|===
| 어댑터 부품 번호 | 설명 | 범주 | 처음부터 사용할 수 있습니다 


 a| 
https://hwu.netapp.com/adapter/index["X91148A"]
 a| 
2포트 100GbE RoCE QSFP28
 a| 
* 스토리지
* 네트워킹
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
2-포트 25GbE RoCE QSFP28
 a| 
* 네트워킹
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
NVMe SSD 모듈(1TB)
 a| 
코어 덤프 장치
 a| 
ONTAP 9.8

|===


== 새로운 쉘프 지원

[cols="2*"]
|===
| 쉘프 | 처음부터 사용할 수 있습니다 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== 새 하드웨어 업데이트

[cols="25h,~,~"]
|===
| 기능 | 설명 및 자세한 내용 | 처음부터 사용할 수 있습니다 


 a| 
멀티 클러스터 인터커넥트 스위치
 a| 
다중 클러스터 구성을 사용하면 여러 클러스터가 4x4 및 2x8 노드 구성을 위한 2개의 새로운 참조 구성 파일을 통해 제공되는 동일한 클러스터 스위치를 공유할 수 있습니다.
 a| 
ONTAP 9.14.1



 a| 
NS224 드라이브 쉘프를 위한 플랫폼 지원 확장
 a| 
다음 플랫폼은 NS224 드라이브 쉘프를 지원합니다.

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A250/AFF ASA A250
* 500f로 설정합니다

 a| 
ONTAP 9.8



 a| 
6Gb SAS 스토리지 스택에 12Gb SAS 쉘프를 핫 추가합니다
 a| 
이제 SAS 스토리지 스택에서 6Gb에서 12Gb로 단일 속도 전환이 지원됩니다. 따라서 12Gb 쉘프를 사용하여 기존 6Gb 스택의 스토리지를 확장할 수 있습니다.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["IOM6 모듈을 사용해 쉘프 스택에 IOM12 모듈을 장착한 상태로 쉘프 추가"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===