---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: AFF C80 저장 시스템의 주요 사양 
---
= AFF C80의 주요 사양
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음은 AFF C80의 일부 사양입니다.  방문하다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] AFF C80 사양의 전체 목록은 (HWU)에서 확인하세요.  이 페이지는 단일 고가용성 쌍을 반영합니다.



=== AFF C80의 주요 사양

플랫폼 구성: AFF C80 단일 섀시 HA 쌍

최대 원시 용량: 14.7360 PB

메모리: 512.0000GB

폼 팩터: 2개의 HA 컨트롤러와 48개의 드라이브 슬롯이 있는 4U 섀시

ONTAP 버전: b_startONTAP: 9.16.1P2b_end

PCIe 확장 슬롯: 18개

최소 ONTAP 버전: ONTAP 9.16.1RC1



=== 스케일아웃 최대값

|===


| 유형 | HA 쌍 | 원시 용량 | 최대 메모리 


| NAS | 12 | 176.8PB / 157.0PiB | 6144GB 


| SAN | 6 | 88.4페타바이트 / 78.5파이바이트 | 3072GB 


| HA 쌍 |  | 14.7PB / 13.1PiB | 512.0000 
|===


=== 아이오



==== 온보드 IO

온보드 IO 데이터가 없습니다.



==== 총 IO

|===


| 규약 | 포트 


| 이더넷 200Gbps | 24 


| 이더넷 100Gbps | 36 


| 이더넷 25Gbps | 56 


| 이더넷 10Gbps | 56 


| FC 64Gbps | 56 


| NVMe/FC 64Gbps | 56 


|  | 0 
|===


==== 관리 포트

|===


| 규약 | 포트 


| 이더넷 1Gbps | 2 


| RS-232 115Kbps | 4 


| USB 600Mbps | 2 
|===


=== 스토리지 네트워킹 지원

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; NAS가 있는 S3; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== 시스템 환경 사양

환경 데이터가 없습니다.



=== 규정 준수

* 인증 EMC/EMI: AMCA, FCC, ICES, KC, 모로코, VCCI
* 인증 안전: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* 인증 안전/EMC/EMI: EAC, UKRSEPRO
* 인증 안전/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* 표준 EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Part 15 Class A, ICES-003, KS C 9832, KS C 9835
* 표준 안전: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252(파트 1)




=== 고가용성

이더넷 기반 베이스보드 관리 컨트롤러(BMC) 및 ONTAP 관리 인터페이스; 중복 핫스왑 가능 컨트롤러; 중복 핫스왑 가능 전원 공급 장치; [//] 2025-10-15 ontap-systems-internal/issues/1357
