---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: '시스템 캐비닛은 측면 패널, 전면 및 후면 도어, 볼트 다운 키트(옵션), 인터커넥트 키트(옵션), 장비용 PDU 및 통합 케이블 관리 시스템으로 구성되어 있습니다.' 
---
= 시스템 캐비닛 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 캐비닛은 측면 패널, 전면 및 후면 도어, 볼트 다운 키트(옵션), 인터커넥트 키트(옵션), 장비용 PDU 및 통합 케이블 관리 시스템으로 구성되어 있습니다.

[cols="1,2"]
|===
| 피처 | 설명 


 a| 
측면 패널
 a| 
시스템 캐비닛에는 잠금식, 탈착식, 교체 가능한 측면 패널이 있습니다.



 a| 
천공 처리된 전방 및 후방 도어
 a| 
시스템 캐비닛에는 신속 분리 장치가 있는 탈착식 전면 및 후면 도어가 있습니다. 전면 도어는 가역식으로 되어 있으며 후면 도어는 분리되어 있습니다. 두 도어 모두 냉각을 위해 천공식 처리되어 있습니다.



 a| 
공통 키
 a| 
이 키는 프론트 도어, 리어 도어 및 측면 패널의 잠금을 해제합니다.



 a| 
예비 부품 키트
 a| 
이 키트는 캐비닛 도어에 부착된 시스템 캐비닛 안에 있습니다. 여기에는 다음과 같은 구성 요소가 포함되어 있습니다.

* 10-32인치 x 0.75인치 Phillips 파일럿 나사 4개
* 10-32 케이지 너트 4개
* 케이지 너트 삽입 도구 1개
* 마스터 키 복사본 2개




 a| 
케이블 액세스
 a| 
케이블 패스스루는 캐비닛의 상단 및 하단, 후면 도어의 하단 및 프레임 사이에 내장되어 있습니다.



 a| 
케이블 관리
 a| 
케이블 관리 후크와 루프 스트래핑은 동일한 간격으로 시스템 캐비닛의 프레임에 부착됩니다.



 a| 
지지 레일
 a| 
받는 지지 레일 수는 구성에 따라 다릅니다. 빈 시스템 캐비닛은 지지 레일이 설치되지 않은 상태로 배송됩니다.

* 구성된 시스템 캐비닛의 경우 80xx, FAS8200, DS4486 후면 고정 브래킷을 지원하는 고정 레일 키트 1개가 시스템 캐비닛과 함께 제공됩니다.
* 빠른 배송 시스템 캐비닛에는 추가 고정 레일 키트가 포함되어 있지 않습니다.




 a| 
블랭킹 패널
 a| 
받은 블랭킹 패널의 수와 크기는 구성에 따라 다릅니다. 빈 시스템 캐비닛은 블랭킹 패널이 설치되지 않은 상태로 제공됩니다.



 a| 
볼트 다운 키트
 a| 
이 옵션 키트를 사용하면 시스템 캐비닛을 데이터 센터 플로어에 고정할 수 있습니다. 이 키트는 내진 안정성을 위한 것이 아닙니다.

* 볼트 다운 브래킷 4개
* 스페이서 브래킷 4개
* M8x20mm 육각 헤드 볼트 및 와셔 6개




 a| 
상호 연결 키트
 a| 
이 옵션 키트를 사용하면 여러 시스템 캐비닛을 서로 연결할 수 있습니다.

* 상호 연결 브래킷
+
** 시스템 캐비닛과 측면 패널을 연결하기 위한 4개의 상호 연결 브래킷 세트 1개
** 시스템 캐비닛과 측면 패널을 연결하기 위한 4개의 상호 연결 브래킷 세트 1개


* 측면 패널이 장착된 시스템 캐비닛에 사용되는 M12x20 Torx-30 나사 4개.
* 측면 패널이 꺼진 시스템 캐비닛에 사용되는 M6x10 카운터싱크 Torx-30 나사 8개.




 a| 
서포트 레일 키트
 a| 
시스템 캐비닛과 함께 추가 지원 레일을 주문한 경우 각 키트에는 왼쪽 및 오른쪽 지지 레일 1개가 들어 있습니다.


NOTE: 지지 레일과 키트는 NetApp 42U 1280 mm 시스템 캐비닛에만 적합하도록 설계되었습니다. 다른 시스템 캐비닛의 레일 또는 레일 키트는 42U 1280 mm 시스템 캐비닛에서 사용하도록 설계되지 않았으므로 사용하지 마십시오.

* 좌측 및 우측 지지 레일
* 시스템 캐비닛 프레임에 레일을 고정하기 위한 레일당 나사 2개




 a| 
크레센트 렌치
 a| 
크레센트 렌치는 포장 팔레트에서 홀드 다운 브래킷을 제거하고, 시스템 캐비닛 수평 조정 받침대를 조정하고, 필요한 경우 볼트 다운 키트 브래킷을 설치하는 데 사용됩니다.

|===