---
permalink: platform-supplemental/42u-1280mm-replace-pdus.html 
sidebar: sidebar 
keywords: replace, fail, PDU, system, cabinet, replace, exist, replace pdu 
summary: 시스템 캐비닛에서 장애가 발생한 PDU를 교체하거나 기존 PDU를 다른 유형의 PDU로 교체할 수 있습니다. 
---
= PDU를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 캐비닛에서 장애가 발생한 PDU를 교체하거나 기존 PDU를 다른 유형의 PDU로 교체할 수 있습니다.

교체 PDU는 시스템 캐비닛에서 지원해야 하며 설치된 장비에 충분한 전원을 공급해야 합니다.

https://hwu.netapp.com/["hwu.netapp.com"]

. 대상 PDU의 회로 차단기를 끄고 AC 전원에서 기존 PDU를 분리합니다.
. 시스템 캐비닛에 접지한 다음 각 시스템 구성 요소 및 PDU에서 전원 코드를 뽑습니다.
. 먼저 PDU 프레임에서 아래쪽 나사를 제거합니다.
+

NOTE: PDU 상단에서 마지막 나사를 분리하는 동안 한 손으로 PDU를 지지해야 합니다. 이렇게 하면 나사를 제거한 후 PDU가 사용자 쪽으로 떨어지거나 떨어지지 않습니다.

. 시스템 캐비닛에서 기존 PDU를 분리합니다.
+
교체용 PDU를 설치할 때 다시 사용할 수 있도록 장착 나사를 추적해야 합니다.

. 기존 PDU에서 브래킷을 제거한 다음 교체 PDU 뒷면에 설치합니다.
. 교체용 PDU를 지원하는 동안 PDU의 장착 브래킷의 슬롯을 시스템 캐비닛 내부의 프레임 상단 구멍에 맞춘 다음 이전 PDU의 장착 나사를 사용하여 PDU를 시스템 캐비닛 프레임에 고정합니다.
. PDU 하단을 시스템 캐비닛 프레임에 고정한 다음 모든 장착 나사를 조입니다.
. 모든 전원 스위치 또는 회로 차단기가 꺼짐 위치에 있는지 확인합니다.
+
회로 차단기가 Off(꺼짐) 위치에 있지 않으면 소형 스크루드라이버 또는 곧게 편 종이 클립을 Off(꺼짐) 라벨 오른쪽의 슬롯에 밀어 넣어 회로 차단기를 정지시키고 회로를 끕니다.

. 각 구성 요소를 PDU 콘센트에 직접 연결하여 시스템 전원 코드를 PDU에 연결합니다.
+

TIP: 가장 좋은 방법은 PDU 분기 전체에 총 부하를 분산하여 각 분기 부하를 가능한 한 동일하게 만드는 것입니다.

. 케이블 리테이너 클립의 굽은 가장자리를 플러그 숄더 위로 밀어 각 구성요소 전원 케이블 플러그를 케이블 리테이너 클립 위에 고정합니다.
. PDU 전원 코드를 AC 전원에 연결합니다.
. PDU 전원 스위치 또는 PDU 회로 차단기를 켭니다.
+
PDU 회로 차단기의 경우 PDU 프레임과 플러싱할 때 버튼이 켜져 있습니다.


