---
permalink: platform-supplemental/sldiag-device-failure-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, help, access, device, intermittent, device, unavailable, storage, system, failure, run device failure diagnostic 
summary: 진단 프로그램을 실행하면 특정 장치에 대한 액세스가 간헐적으로 발생하는 이유 또는 스토리지 시스템에서 장치를 사용할 수 없는 이유를 확인할 수 있습니다. 
---
= 장치 오류 진단을 실행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
진단 프로그램을 실행하면 특정 장치에 대한 액세스가 간헐적으로 발생하는 이유 또는 스토리지 시스템에서 장치를 사용할 수 없는 이유를 확인할 수 있습니다.

. 스토리지 시스템 프롬프트에서 LOADER 프롬프트로 'HALT'를 전환합니다
. LOADER 프롬프트에서 'boot_diags' 명령을 입력합니다
+

NOTE: Loader 프롬프트에서 이 명령을 실행하여 시스템 수준 진단이 제대로 기능하도록 해야 합니다. boot_diags 명령은 시스템 수준 진단을 위해 특별히 설계된 특수 드라이버를 시작합니다.

. 'sldiag device run[-dev devtype | MB | slotslotnum][-name device]' 명령을 입력하여 문제가 발생한 장치에 대한 진단 유틸리티를 실행합니다
+
** -dev_devtype_은 테스트할 장치의 유형을 지정합니다.
+
*** ATA는 첨단 기술 어태치먼트 장치입니다.
*** bootmedia는 시스템 부팅 장치입니다.
*** CNA는 네트워크 또는 스토리지 장치에 연결되지 않은 통합 네트워크 어댑터입니다.
*** env는 마더보드 환경이다.
*** FCache는 성능 가속화 모듈 2라고도 하는 Flash Cache 어댑터입니다.
*** FCAL은 스토리지 디바이스 또는 Fibre Channel 네트워크에 연결되지 않은 Fibre Channel 중재 루프 장치입니다.
*** fcvi는 Fibre Channel 네트워크에 연결되지 않은 Fibre Channel 가상 인터페이스입니다.
*** 상호 연결(interconnect)이나 NVRAM-IB는 고가용성 인터페이스입니다.
*** 시스템 메모리입니다.
*** NIC는 네트워크에 연결되지 않은 네트워크 인터페이스 카드입니다.
*** NVRAM은 비휘발성 RAM입니다.
*** nvmem은 NVRAM과 시스템 메모리의 혼합입니다.
*** 'AS'는 디스크 쉘프에 연결되지 않은 직렬 연결 SCSI 장치입니다.
*** 서비스 프로세서는 세르시프입니다.
*** '스토리지'는 디스크 쉘프가 연결된 ATA, FC-AL 또는 SAS 인터페이스입니다.
*** TOE는 일종의 NIC인 TCP Offload Engine입니다.


** mb는 모든 마더보드 장치를 테스트하도록 지정합니다.
** 'lot'_slotnum_은 특정 슬롯 번호의 장치를 테스트하도록 지정합니다.
** '-name_device_'는 지정된 디바이스 클래스와 유형을 지정합니다.


. 'ldiag device status' 명령어를 입력하여 테스트 상태를 확인할 수 있다
+
테스트가 실행되는 동안 스토리지 시스템에서 다음 출력을 제공합니다.

+
[listing]
----
There are still test(s) being processed.
----
+
모든 테스트가 완료되면 기본적으로 다음 응답이 나타납니다.

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 'sldiag device status[-dev devtype|MB|slottnum][-name_device_] - long-state failed' 명령을 입력하여 하드웨어 문제를 식별합니다
+
다음 예에서는 FC-AL 어댑터 테스트로 인한 전체 실패 상태가 표시되는 방식을 보여 줍니다.

+
[listing]
----

*> **sldiag device status fcal -long -state failed**

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. 완전 종료를 수행하고 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결하고 스토리지 시스템의 전원을 켭니다.
.. 실행 중인 장치 오류 진단 _ 의 1-5단계를 반복합니다.




 a| 
동일한 테스트 실패가 발생했습니다
 a| 
기술 지원 부서에서는 일부 테스트의 기본 설정을 수정하여 문제를 파악하는 것이 좋습니다.

.. 다음 명령을 입력하여 스토리지 시스템에 있는 특정 디바이스 또는 디바이스 유형의 선택 상태를 수정합니다. 'sldiag 장치 수정[-dev_devtype_|MB|slot_slotnum_] [-name device] [-selection_enable|disable|default|only_] '+-'selection_enable|disable|default|only_'를 사용하면 지정된 장치 유형이나 명명된 장치의 기본 선택을 활성화, 비활성화, 수락하거나, 다른 모든 장치에서 지정된 장치 또는 명명된 장치를 먼저 비활성화할 수 있습니다.
.. 'ldiag option show' 명령을 입력하여 테스트가 수정되었는지 확인합니다
.. 실행 중인 장치 오류 진단 _ 의 3-5단계를 반복합니다.
.. 문제를 식별하고 해결한 후 1단계와 2단계를 반복하여 테스트를 해당 '기본' 상태로 재설정합니다.
.. 실행 중인 장치 오류 진단 _ 의 1-5단계를 반복합니다.




 a| 
실패없이 완료되었습니다
 a| 
하드웨어 문제가 없으며 스토리지 시스템이 프롬프트로 돌아갑니다.

.. 'sldiag device clearstatus[-dev_devtype_|MB|slot_slotnum_]' 명령을 입력하여 상태 로그를 지웁니다
.. 'sldiag device status[-dev_devtype_|MB|slot_slotnum_]' 명령을 입력하여 로그가 지워졌는지 확인합니다
+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. LOADER 프롬프트에서 다음 명령을 입력하여 스토리지 시스템을 부팅합니다. "boot_ONTAP" 시스템 레벨 진단이 완료되었습니다.


|===


단계를 반복해도 오류가 계속되면 하드웨어를 교체해야 합니다.
