---
permalink: platform-supplemental/sldiag-system-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, initial, system, installation, identify, version, system-level, diagnostic, support, device, storage, system, successful, hardware, function, properly, run system installation diagnostic 
summary: 초기 시스템 설치 후 진단 프로그램을 실행하여 스토리지 시스템에서 시스템 수준 진단 프로그램의 버전과 지원되는 장치를 식별하고, 설치가 성공적이며 모든 하드웨어가 제대로 작동하는지 확인합니다. 
---
= 시스템 설치 진단 프로그램을 실행합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
초기 시스템 설치 후 진단 프로그램을 실행하여 스토리지 시스템에서 시스템 수준 진단 프로그램의 버전과 지원되는 장치를 식별하고, 설치가 성공적이며 모든 하드웨어가 제대로 작동하는지 확인합니다.

스토리지 시스템에서 Data ONTAP를 이미 실행 중이어야 합니다.

. 스토리지 시스템 프롬프트에서 LOADER 프롬프트로 'HALT'를 전환합니다
. LOADER 프롬프트에서 'boot_diags' 명령을 입력합니다
+

NOTE: Loader 프롬프트에서 이 명령을 실행하여 시스템 수준 진단이 제대로 기능하도록 해야 합니다. boot_diags 명령은 시스템 수준 진단을 위해 특별히 설계된 특수 드라이버를 시작합니다.

. 'ldiag version show' 명령을 입력하여 스토리지 시스템에 있는 시스템 수준 진단 버전을 확인합니다
+
버전은 시스템 레벨 진단 프로그램X.nn.nn 형식으로 표시됩니다. X는 알파벳 참조 및 nn.nn은 각각 주 및 부 숫자 참조입니다.

. 'ldiag device types' 명령을 입력하여 확인할 구성 요소를 알 수 있도록 새 시스템 설치에서 장치 유형을 식별합니다
+
스토리지 시스템에 다음 디바이스 일부 또는 전체가 표시됩니다.

+
** ATA는 첨단 기술 어태치먼트 장치입니다.
** bootmedia는 시스템 부팅 장치입니다.
** CNA는 네트워크 또는 스토리지 장치에 연결되지 않은 통합 네트워크 어댑터입니다.
** env는 마더보드 환경이다.
** FCache는 성능 가속화 모듈 2라고도 하는 Flash Cache 어댑터입니다.
** FCAL은 스토리지 디바이스 또는 Fibre Channel 네트워크에 연결되지 않은 Fibre Channel 중재 루프 장치입니다.
** fcvi는 Fibre Channel 네트워크에 연결되지 않은 Fibre Channel 가상 인터페이스입니다.
** 상호 연결(interconnect)이나 NVRAM-IB는 고가용성 인터페이스입니다.
** MEM은 시스템 메모리입니다.
** NIC는 네트워크에 연결되지 않은 네트워크 인터페이스 카드입니다.
** NVRAM은 비휘발성 RAM입니다.
** nvmem은 NVRAM과 시스템 메모리의 혼합입니다.
** 'AS'는 디스크 쉘프에 연결되지 않은 직렬 연결 SCSI 장치입니다.
** 서비스 프로세서는 세르시프입니다.
** '스토리지'는 디스크 쉘프가 연결된 ATA, FC-AL 또는 SAS 인터페이스입니다.
** TOE는 일종의 NIC인 TCP Offload Engine입니다.


. 'ldiag device run' 명령을 입력하여 스토리지 시스템에서 선택한 모든 기본 진단 테스트를 실행합니다
. 'ldiag device status' 명령어를 입력하여 테스트 상태를 확인할 수 있다
+
테스트가 실행되는 동안 스토리지 시스템에서 다음 출력을 제공합니다.

+
[listing]
----
There are still test(s) being processed.
----
+
모든 테스트가 완료되면 기본적으로 다음 응답이 나타납니다.

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 'ldiag device status - long-state failed' 명령을 입력하여 새 스토리지 시스템에 하드웨어 문제가 없는지 확인합니다
+
다음 예는 적절한 하드웨어 없이 테스트 실행에서 오류의 전체 상태가 표시되는 방식을 보여줍니다.

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
실패없이 완료되었습니다
 a| 
하드웨어 문제가 없으며 스토리지 시스템이 프롬프트로 돌아갑니다.

.. 'ldiag device clearstatus' 명령을 입력하여 상태 로그를 지웁니다
.. 'ldiag device status' 명령을 입력하여 로그가 지워졌는지 확인한다
+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. LOADER 프롬프트에서 다음 명령을 입력하여 스토리지 시스템을 부팅합니다. "boot_ONTAP" 시스템 레벨 진단이 완료되었습니다.




 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. 완전 종료를 수행하고 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결하고 스토리지 시스템의 전원을 켭니다.
.. 시스템 설치 진단 실행 중 _ 의 1-7단계를 반복합니다.


|===

