---
permalink: platform-supplemental/sldiag-system-panic-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, storage, system, suffer, panic, identify, cause, run system panic diagnostic 
summary: 스토리지 시스템에서 시스템 패닉이 발생한 후 진단 유틸리티를 실행하면 패닉 상태를 파악하는 데 도움이 됩니다. 
---
= 시스템 패닉 진단을 실행합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템에서 시스템 패닉이 발생한 후 진단 유틸리티를 실행하면 패닉 상태를 파악하는 데 도움이 됩니다.

. 스토리지 시스템 프롬프트에서 LOADER 프롬프트로 'HALT'를 전환합니다
. LOADER 프롬프트에서 'boot_diags' 명령을 입력합니다
+

NOTE: Loader 프롬프트에서 이 명령을 실행하여 시스템 수준 진단이 제대로 기능하도록 해야 합니다. boot_diags 명령은 시스템 수준 진단을 위해 특별히 설계된 특수 드라이버를 시작합니다.

. 'ldiag device run' 명령을 입력하여 모든 장치에 대해 진단 유틸리티를 실행합니다
. 'ldiag device status' 명령어를 입력하여 테스트 상태를 확인할 수 있다
+
테스트가 실행되는 동안 스토리지 시스템에서 다음 출력을 제공합니다.

+
[listing]
----
There are still test(s) being processed.
----
+
모든 테스트가 완료되면 다음과 같은 기본 응답이 제공됩니다.

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 'ldiag device status - long-state failed' 명령을 입력하여 시스템 패닉의 원인을 파악합니다
+
다음 예는 적절한 하드웨어 없이 테스트 실행에서 오류의 전체 상태가 표시되는 방식을 보여줍니다.

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
실패없이 완료되었습니다
 a| 
하드웨어 문제가 없으며 스토리지 시스템이 프롬프트로 돌아갑니다.

.. 'ldiag device clearstatus' 명령을 입력하여 상태 로그를 지웁니다
.. 'ldiag device status' 명령을 입력하여 로그가 지워졌는지 확인한다
+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. LOADER 프롬프트에서 다음 명령을 입력하여 스토리지 시스템을 부팅합니다. "boot_ONTAP" 시스템 레벨 진단이 완료되었습니다.




 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 'halt' 명령어를 입력하여 Maintenance Mode를 종료한다
.. 완전 종료를 수행하고 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결하고 스토리지 시스템의 전원을 켭니다.
.. 시스템 패닉 진단 _ 실행 중 1단계부터 5단계까지 반복합니다.


|===


단계를 반복해도 오류가 계속되면 하드웨어를 교체해야 합니다.
