---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: 시스템 수준 진단은 지원되는 스토리지 시스템에서 하드웨어 문제를 검색하고 확인하는 테스트를 위한 명령줄 인터페이스를 제공합니다. 시스템 수준 진단을 사용하여 특정 구성 요소가 제대로 작동하는지 확인하거나 결함이 있는 구성 요소를 식별할 수 있습니다. 
---
= 시스템 수준 진단 소개
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 수준 진단은 지원되는 스토리지 시스템에서 하드웨어 문제를 검색하고 확인하는 테스트를 위한 명령줄 인터페이스를 제공합니다. 시스템 수준 진단을 사용하여 특정 구성 요소가 제대로 작동하는지 확인하거나 결함이 있는 구성 요소를 식별할 수 있습니다.

지원되는 스토리지 시스템에서만 시스템 수준 진단을 사용할 수 있습니다. 지원되지 않는 스토리지 시스템의 명령줄 인터페이스에서 시스템 수준 진단을 입력하면 오류 메시지가 생성됩니다.

다음과 같은 일반적인 문제 해결 상황 중 하나를 수행한 후 시스템 수준 진단을 실행합니다.

* 초기 시스템 설치
* 하드웨어 구성 요소의 추가 또는 교체
* 알 수 없는 하드웨어 오류로 인한 시스템 패닉
* 특정 장치에 대한 액세스가 간헐적으로 발생하거나 장치를 사용할 수 없게 됩니다
* 시스템 응답 시간이 느려짐


시스템 수준 진단을 실행하려면 Data ONTAP에서 * 유지 관리 모드 부팅 * 옵션에 도달해야 하므로 Data ONTAP를 이미 실행하고 있어야 합니다. 이 옵션을 선택하는 방법은 여러 가지가 있지만 이 가이드에 설명된 절차에 따라 권장되는 접근 방법입니다. 시스템의 일부 하드웨어 구성 요소에는 특정 접근 방식이 필요할 수 있으며, 이는 해당 현장 교체 장치(FRU) 전단지에 문서화되어 있습니다. 이 가이드에서는 특정 명령, 하위 명령, 테스트 또는 조건에 대한 자세한 정의는 제공하지 않습니다.

명령을 입력하면 백그라운드에서 테스트가 실행되고 테스트 통과 또는 실패 결과가 고정된 크기의 내부 메모리 기반 로그에 기록됩니다. 일부 테스트는 유틸리티이며 통과 또는 실패보다는 완료된 것으로 표시됩니다. 적절한 테스트를 실행한 후 이 가이드에 설명된 절차를 통해 상태 보고서를 생성할 수 있습니다. 테스트 결과에 시스템 수준 진단이 성공적으로 완료된 것으로 표시되면 로그를 지우는 것이 좋습니다.

테스트 실패 시 상태 보고서는 기술 지원 부서에서 적절한 권장 사항을 제공하는 데 도움이 됩니다. FRU를 재설치하거나, 케이블이 연결되어 있는지 확인하거나, 기술 지원 부서에서 권장하는 특정 테스트를 활성화한 다음 테스트를 다시 실행하여 장애를 해결할 수 있습니다. 장애를 해결할 수 없는 경우 하드웨어 장애가 있으므로 영향을 받는 하드웨어를 교체해야 합니다.

추가 정의 또는 설명이 필요한 오류 메시지가 없습니다.
