---
permalink: platform-supplemental/sldiag-requirements.html 
sidebar: sidebar 
keywords: system-level, diagnostic, test, run, time, system, requirement, system, memory, general, nic, sas, fc-al, cna, interconnect, requirement for running system-level diagnostic 
summary: 실행 중인 시스템 수준 진단 테스트에 따라 시간 및 시스템 하드웨어 요구 사항을 알아야 합니다. 
---
= 시스템 수준 진단 프로그램 실행을 위한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실행 중인 시스템 수준 진단 테스트에 따라 시간 및 시스템 하드웨어 요구 사항을 알아야 합니다.

문서화된 각 과제에는 약간의 차이가 있습니다. 작업에 대해 권장되는 절차를 사용하십시오.

시스템 수준 진단을 실행할 때는 다음 요구 사항을 충족해야 합니다. 그렇지 않으면 테스트 중 일부가 실패하고 오류 메시지가 상태 보고서에 표시됩니다.



== 일반 요구 사항

* 테스트할 각 시스템은 별도의 네트워크에 있어야 합니다.
+
네트워크 인터페이스 테스트에서는 스토리지 시스템에서 사용 가능한 모든 네트워크 인터페이스에 172.25.150.23부터 고유한 정적 IP 주소를 할당합니다. 따라서 서로 다른 스토리지 컨트롤러의 네트워크 인터페이스 포트에 동일한 IP 주소가 할당됩니다. 테스트 중인 모든 시스템이 동일한 네트워크에 있는 경우 연결된 콘솔에 중복 IP 주소 경고 메시지가 나타납니다. 이러한 경고 메시지는 테스트 결과에 영향을 주지 않습니다.





== 시스템 메모리 요구 사항

* 메모리 테스트를 실행할 때는 시간을 낭비해야 합니다. 스토리지 시스템의 메모리 용량이 클수록 더 오래 걸립니다.




== NIC 요구 사항

* 표준 이더넷 케이블을 사용하여 최상의 성능을 얻으려면 시스템의 모든 인접 네트워크 인터페이스 포트를 연결해야 합니다.
+
인접 포트의 예로는 e0a 및 e0b 또는 E2C 및 e2D가 있습니다.

+

NOTE: 내부 스위치 연결로 인해 e0M과 e0P 포트를 함께 연결할 수 없습니다. e0M 및 e0P 포트가 있는 시스템에서 가장 효율적인 페어링은 e0a 및 e0b가 포함된 e0M입니다.

* 시스템에 여러 개의 네트워크 인터페이스 포트가 있는 경우 NIC 시스템 수준 진단 테스트를 여러 번 실행해야 할 수 있으며, 각 실행은 매번 두 쌍 이상으로 제한됩니다.




== SAS 요구 사항

* SAS 시스템 레벨 진단 테스트를 실행할 경우 최상의 성능을 위해 인접한 SAS 포트를 연결해야 합니다. 스토리지 쉘프의 케이블을 포트에서 분리해야 합니다.
+

NOTE: Data ONTAP 8.2를 실행하는 시스템에서는 인접한 SAS 포트 간의 연결이 더 이상 필요하지 않지만, 연결되지 않은 SAS 포트가 있는 시스템에서는 내부 루프백 테스트만 실행됩니다.





== FC-AL 요구 사항

* FC-AL 시스템 수준 진단 테스트를 실행할 때는 최상의 성능을 위해 마더보드나 확장 어댑터의 FC-AL 인터페이스에 루프백 후드를 설치해야 합니다. 스토리지 또는 파이버 채널 네트워크의 다른 모든 케이블은 포트에서 분리해야 합니다.
+

NOTE: FC-AL 인터페이스에서 루프백 후드를 사용하는 것은 더 이상 Data ONTAP 8.2를 실행하는 시스템에 대한 요구 사항이 아니지만 인터페이스의 테스트 범위도 줄어듭니다.





== CNA 요구 사항

* 루프백 후드를 사용하는 것은 CNA 시스템 수준 진단 테스트를 실행하는 데 필요하지 않습니다.




== 상호 연결 요구 사항

* 이중 컨트롤러 시스템의 두 플랫폼 컨트롤러 모듈은 상호 연결 시스템 수준 진단 테스트를 실행하려면 유지보수 모드에 있어야 합니다.
+

NOTE: 다른 시스템 수준 진단 테스트를 사용하여 상호 연결 시스템 수준 진단 테스트를 실행하려고 하면 경고 메시지가 표시됩니다.


