---
permalink: sas3/install-change-shelf-id.html 
sidebar: sidebar 
keywords: change, shelf, id, system, ontap, run, hot-add, ontap, controller, module, available, serve, data, unown, spare, offline, aggregate 
summary: 'ONTAP가 아직 실행되지 않거나 시스템에 케이블로 연결되기 전에 쉘프를 핫 추가할 때 시스템의 쉘프 ID를 변경할 수 있습니다. ONTAP가 실행 중일 때(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음) 쉘프 ID를 변경할 수도 있고, 쉘프의 모든 드라이브가 소유되지 않은 상태, 스페어 또는 오프라인 애그리게이트의 일부일 때도 변경할 수 있습니다.' 
---
= IOM12 모듈을 사용하여 쉘프 ID-쉘프 변경
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP가 아직 실행되지 않거나 시스템에 케이블로 연결되기 전에 쉘프를 핫 추가할 때 시스템의 쉘프 ID를 변경할 수 있습니다. 또한 ONTAP가 가동 중이고 실행 중일 때(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음) 쉘프 ID를 변경할 수 있으며 쉘프의 모든 드라이브가 소유 안 됨, 스페어 또는 오프라인 애그리게이트의 일부임

.시작하기 전에
* ONTAP가 실행 중인 경우(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음), 쉘프의 모든 드라이브가 소유되지 않은 애그리게이트, 스페어 또는 오프라인 애그리게이트의 일부인지 확인해야 합니다.
+
'storage disk show -shelf_shelf_number_' 명령을 사용하여 드라이브의 상태를 확인할 수 있습니다. Container Type(컨테이너 유형) 열의 출력은 장애가 발생한 드라이브인 경우 spare(스페어) 또는 Broken(중단됨)으로 표시되어야 합니다. 또한 컨테이너 이름 및 소유자 열에는 대시가 있어야 합니다.

* Active IQ Config Advisor를 실행하거나 'storage shelf show-fields shelf-id' 명령을 사용하여 시스템에서 이미 사용 중인 쉘프 ID를 확인할 수 있습니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"]



.이 작업에 대해
* 유효한 쉘프 ID는 00부터 99까지입니다.
* 쉘프 ID는 HA 쌍 또는 단일 컨트롤러 구성 내에서 고유해야 합니다.
+
내부 스토리지가 있는 플랫폼을 사용하는 경우 쉘프 ID는 내부 디스크 쉘프와 외부 연결 디스크 쉘프 전체에서 고유해야 합니다.

* 쉘프 ID를 적용하려면 쉘프의 전원을 껐다가 켜야 합니다.
+
전원을 다시 켜기 전에 대기하는 시간은 이 절차의 뒷부분에 설명된 대로 ONTAP 상태에 따라 달라집니다.



.단계
. 아직 켜져 있지 않은 경우 디스크 쉘프의 전원을 켭니다.
. 왼쪽 엔드 캡을 제거하여 쉘프 LED 근처에 있는 단추를 찾습니다.
. 디지털 디스플레이에서 첫 번째 숫자가 깜박일 때까지 주황색 버튼을 길게 눌러 쉘프 ID의 첫 번째 번호를 변경합니다. 이 작업은 최대 3초가 걸릴 수 있습니다.
+
[NOTE]
====
ID가 깜빡이는 데 3초 이상 걸리는 경우 버튼을 다시 눌러 완전히 누르십시오.

그러면 디스크 쉘프 ID 프로그래밍 모드가 활성화됩니다.

====
. 버튼을 눌러 0에서 9 사이의 원하는 숫자에 도달할 때까지 번호를 계속 진행합니다.
+
첫 번째 숫자가 계속 깜박입니다.

. 디지털 디스플레이에서 두 번째 숫자가 깜박일 때까지 버튼을 길게 눌러 쉘프 ID의 두 번째 번호를 변경합니다. 이 작업은 최대 3초가 걸릴 수 있습니다.
+
디지털 디스플레이의 첫 번째 숫자가 깜박임을 멈춥니다.

. 버튼을 눌러 원하는 숫자가 1에서 9 사이의 숫자가 될 때까지 번호를 계속 진행합니다.
+
두 번째 숫자가 계속 깜박입니다.

. 원하는 숫자를 잠그고 두 번째 숫자의 깜박임이 멈출 때까지 버튼을 길게 눌러 프로그래밍 모드를 종료합니다. 이 때 최대 3초가 걸릴 수 있습니다.
+
디지털 디스플레이의 두 숫자가 깜박이기 시작하고 작동 디스플레이 패널의 황색 LED가 약 5초 후에 켜지면서 보류 중인 디스크 쉘프 ID가 아직 적용되지 않았음을 알려줍니다.

. 디스크 쉘프의 전원을 껐다가 켜서 쉘프 ID가 적용되도록 합니다.
+
두 전원 스위치를 모두 끄고 적절한 시간을 기다린 다음 전원을 다시 켜서 전원을 껐다가 켜야 합니다.

+
** ONTAP가 아직 실행되지 않았거나 shelf(시스템에 아직 케이블로 연결되지 않은)를 핫 추가할 경우, 10초 이상 기다리십시오.
** ONTAP가 실행 중이고(컨트롤러를 사용하여 데이터를 제공할 수 있는 경우) 쉘프의 모든 디스크 드라이브가 소유되지 않은 경우, 스페어 또는 오프라인 애그리게이트의 일부일 경우 70초 이상 기다려야 합니다.
+
이 시간 동안 ONTAP는 이전 쉘프 주소를 적절히 삭제하고 새 쉘프 주소의 복사본을 업데이트할 수 있습니다.



. 왼쪽 엔드 캡을 다시 장착합니다.
. 각 추가 디스크 쉘프에 대해 1단계부터 9단계까지 반복합니다.
. 시스템에 중복 쉘프 ID가 없는지 확인합니다.
+
두 개 이상의 디스크 쉘프가 동일한 ID를 갖는 경우, 시스템은 중복 디스크 쉘프의 소프트 ID 번호를 100보다 크거나 같게 할당합니다. 소프트 ID(중복) 번호를 변경해야 합니다.

+
.. Active IQ Config Advisor를 실행하여 중복 쉘프 ID 알림을 확인하거나 'storage shelf show-fields shelf-id' 명령을 실행하여 중복 ID를 포함하여 이미 사용 중인 쉘프 ID 목록을 확인하십시오.
.. 시스템에 중복 쉘프 ID가 있는 경우 이 절차를 반복하여 중복 쉘프 ID를 변경하십시오.



