---
permalink: a320/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process 
summary: 섀시를 교체하려면 컨트롤러를 종료해야 합니다. 
---
= 컨트롤러 종료 - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차는 2개 노드 구성이 있는 시스템을 위한 것입니다. 클러스터를 서비스할 때 정상 종료에 대한 자세한 내용은 을 참조하십시오 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["스토리지 시스템을 정상적으로 종료하고 전원을 켭니다. 해결 가이드 - NetApp 기술 자료"].

.시작하기 전에
* 필요한 사용 권한과 자격 증명이 있는지 확인합니다.
+
** ONTAP에 대한 로컬 관리자 자격 증명입니다.
** 각 컨트롤러에 대한 BMC 접근성.


* 교체에 필요한 도구와 장비가 있는지 확인합니다.


.단계
. SSH를 통해 클러스터에 로그인하거나 로컬 콘솔 케이블과 랩톱/콘솔을 사용하여 클러스터의 노드에서 로그인합니다.
. 모든 클라이언트/호스트에서 NetApp 시스템의 데이터에 액세스하지 못하도록 합니다.
. 외부 백업 작업을 일시 중지합니다.
. AutoSupport가 활성화된 경우 케이스 생성을 억제하고 시스템이 오프라인이 될 것으로 예상되는 기간을 표시합니다.
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 모든 클러스터 노드의 SP/BMC 주소 식별:
+
`system service-processor show -node * -fields address`

. 클러스터 쉘을 종료합니다.
+
`exit`

. 이전 단계에서 확인한 IP 주소를 사용하여 각 컨트롤러의 SP/BMC에 로그인하십시오.
+
** SSH를 통해 BMC에서 로그인하는 경우 SP/BMC 주소(예:  `ssh admin@<SP/BMC_address>`)를 사용하여 연결한 다음  `system console` 명령을 입력하고 인증하십시오.
** 컨트롤러에 직접 연결된 로컬 콘솔이나 랩톱을 사용하는 경우 동일한 클러스터 관리자 자격 증명을 사용하여 로그인하십시오.


. 손상된 섀시에 있는 2개의 노드를 중지합니다.
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: StrictSync 모드에서 운영되는 SnapMirror 동기식 클러스터를 사용하는 클러스터의 경우: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 다음이 표시되면 클러스터의 각 컨트롤러에 대해 * y * 를 입력합니다.
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 각 컨트롤러가 멈출 때까지 기다린 후 LOADER 프롬프트가 표시됩니다.

