---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: 손상된 섀시에서 팬, 하드 드라이브 및 컨트롤러 모듈 또는 모듈을 새 섀시로 이동하고 손상된 섀시를 손상된 섀시와 동일한 모델의 새 섀시로 장비 랙 또는 시스템 캐비닛에서 교체하십시오. 
---
= 하드웨어 교체 - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
손상된 섀시에서 팬, 하드 드라이브 및 컨트롤러 모듈 또는 모듈을 새 섀시로 이동하고 손상된 섀시를 손상된 섀시와 동일한 모델의 새 섀시로 장비 랙 또는 시스템 캐비닛에서 교체하십시오.



== 1단계: 컨트롤러 모듈을 분리합니다

섀시를 교체하려면 이전 섀시에서 컨트롤러 모듈을 분리해야 합니다.

. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 전원 케이블 고정 장치를 분리한 다음 전원 공급 장치에서 케이블을 분리합니다.
. 케이블을 케이블 관리 장치에 연결하는 후크 및 루프 스트랩을 푼 다음, 케이블이 연결된 위치를 추적하면서 컨트롤러 모듈에서 시스템 케이블과 SFP(필요한 경우)를 분리합니다.
+
케이블 관리 장치에 케이블을 남겨 두면 케이블 관리 장치를 다시 설치할 때 케이블이 정리됩니다.

. 컨트롤러 모듈의 왼쪽과 오른쪽에서 케이블 관리 장치를 분리하여 한쪽에 둡니다.
. 섀시에서 컨트롤러 모듈을 분리합니다.
+
.. 검지를 컨트롤러 모듈 양쪽에 있는 래치 장치에 삽입합니다.
.. 래칭 메커니즘의 상단에 있는 주황색 탭을 눌러 섀시의 래치 핀을 지웁니다.
+
래치 메커니즘 후크는 거의 수직이어야 하며 섀시 핀이 없어야 합니다.

.. 컨트롤러 모듈 측면을 잡을 수 있도록 컨트롤러 모듈을 사용자 쪽으로 몇 인치 정도 가볍게 당깁니다.
.. 양손으로 컨트롤러 모듈을 섀시에서 조심스럽게 당겨 평평하고 안정적인 표면에 놓습니다.


. 섀시의 다른 컨트롤러 모듈에 대해 이 단계를 반복합니다.




== 2단계: 팬을 이동합니다

섀시를 교체할 때 팬 모듈을 교체 섀시로 이동하려면 특정 작업 순서를 수행해야 합니다.

. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 베젤의 양 측면에 있는 입구를 잡은 다음 섀시 프레임의 볼 스터드에서 베젤이 분리될 때까지 양손으로 베젤을 분리합니다(필요한 경우).
. 팬 모듈 캠 핸들의 분리 래치를 아래로 누른 다음 캠 핸들을 아래쪽으로 돌립니다.
+
팬 모듈은 섀시에서 약간 떨어진 곳으로 이동합니다.

. 팬 모듈을 섀시에서 똑바로 당겨 빼내고, 다른 손으로 팬 모듈을 지지하여 섀시에서 흔들리지 않도록 하십시오.
+

CAUTION: 팬 모듈이 단락되었습니다. 팬 모듈이 갑자기 섀시에서 떨어져 다치지 않도록 항상 다른 손으로 팬 모듈의 하단을 지지하십시오.

. 팬 모듈을 따로 보관해 둡니다.
. 나머지 팬 모듈에 대해 위의 단계를 반복합니다.
. 팬 모듈을 입구에 맞춘 다음 섀시에 밀어 넣어 교체 섀시에 넣습니다.
. 팬 모듈 캠 손잡이를 단단히 눌러 섀시에 완전히 장착합니다.
+
팬 모듈이 완전히 장착되면 캠 핸들이 약간 올라갑니다.

. 캠 핸들을 닫힘 위치까지 돌려 캠 핸들 해제 래치가 딸깍 소리를 내며 잠금 위치에 있는지 확인합니다.
+
팬이 장착되고 작동 속도로 회전된 후에는 팬 LED가 녹색이어야 합니다.

. 나머지 팬 모듈에 대해 이 단계를 반복합니다.




== 3단계: 장비 랙 또는 시스템 캐비닛 내에서 섀시를 교체합니다

교체 섀시를 설치하려면 먼저 장비 랙 또는 시스템 캐비닛에서 기존 섀시를 분리해야 합니다.

. 섀시 장착 지점에서 나사를 분리합니다.
. 두 사람이 있는 상태에서 이전 섀시를 시스템 캐비닛 또는 장비 랙의 랙 레일에서 밀어 낸 다음 한쪽에 둡니다.
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 시스템 캐비닛 또는 장비 랙의 랙 레일에 섀시를 부착하여 두 사람이 교체용 섀시를 장비 랙 또는 시스템 캐비닛에 설치합니다.
. 섀시를 장비 랙 또는 시스템 캐비닛에 완전히 밀어 넣습니다.
. 이전 섀시에서 분리한 나사를 사용하여 섀시의 전면을 장비 랙 또는 시스템 캐비닛에 고정합니다.
. 아직 설치하지 않은 경우 베젤을 설치합니다.




== 4단계: 컨트롤러 모듈을 설치합니다

새 섀시에 컨트롤러 모듈을 설치한 후 진단 테스트를 실행할 수 있는 상태로 부팅해야 합니다.

동일한 섀시에 2개의 컨트롤러 모듈이 있는 HA 쌍의 경우, 컨트롤러 모듈을 설치하는 순서는 섀시에 완전히 장착되자마자 재부팅을 시도하기 때문에 특히 중요합니다.

. 컨트롤러 모듈의 끝을 섀시의 입구에 맞춘 다음 컨트롤러 모듈을 반쯤 조심스럽게 시스템에 밀어 넣습니다.
+

NOTE: 지시가 있을 때까지 컨트롤러 모듈을 섀시에 완전히 삽입하지 마십시오.

. 콘솔을 컨트롤러 모듈에 다시 연결하고 관리 포트를 다시 연결합니다.
. 전원 케이블을 전원 공급 장치에 연결하고 전원 케이블 고정 장치를 다시 설치합니다.
. 컨트롤러 모듈 재설치를 완료합니다.
+
.. 래치 암이 확장된 위치에 잠겨 있는지 확인합니다.
.. 래치 암을 사용하여 컨트롤러 모듈이 멈출 때까지 섀시 베이에 밀어 넣습니다.
.. 래칭 메커니즘 상단의 주황색 탭을 누르고 있습니다.
.. 컨트롤러 모듈이 섀시 모서리와 수평이 될 때까지 섀시 베이에 부드럽게 밀어 넣습니다.
+

NOTE: 래칭 메커니즘 암이 섀시에 밀어 넣습니다.

+
컨트롤러 모듈이 섀시에 완전히 장착되면 바로 부팅이 시작됩니다.

.. 래치를 해제하여 컨트롤러 모듈을 제자리에 고정합니다.
.. 전원 공급 장치를 다시 연결합니다.
.. 아직 설치하지 않은 경우 케이블 관리 장치를 다시 설치하십시오.
.. Ctrl-C를 눌러 정상적인 부팅 프로세스를 중단합니다.


. 이전 단계를 반복하여 새 섀시에 두 번째 컨트롤러를 설치합니다.

