---
permalink: fas500f/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: fas500f, replace the boot media 
summary: FAS500f 시스템의 부팅 미디어를 교체하기 전에 성공적인 교체를 위한 필수 조건을 충족하는지 확인하십시오. 여기에는 적절한 용량의 USB 플래시 드라이브가 있는지, 그리고 올바른 교체용 부팅 장치인지 확인하는 것이 포함됩니다. 
---
= 수동 부팅 미디어 복구 요구 사항 - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS500f 시스템의 부팅 미디어를 교체하기 전에 성공적인 교체를 위한 필수 조건을 충족하는지 확인하십시오. 여기에는 적절한 용량의 USB 플래시 드라이브가 있는지, 그리고 올바른 교체용 부팅 장치인지 확인하는 것이 포함됩니다.

스토리지 시스템이 ONTAP 9.18.1 이상을 실행 중인 경우 link:bootmedia-replace-workflow-bmr.html["자동 부팅 복구 절차"]을(를) 사용하십시오. 시스템이 이전 버전의 ONTAP를 실행 중인 경우 수동 부팅 복구 절차를 사용해야 합니다.

.USB 플래시 드라이브
* USB 플래시 드라이브가 FAT32로 포맷되었는지 확인하세요.
* USB에는 다음을 저장할 수 있는 충분한 저장 용량이 있어야 합니다.  `image_xxx.tgz` 파일.


.파일 준비
복사하다  `image_xxx.tgz` 파일을 USB 플래시 드라이브에 복사합니다. 이 파일은 USB 플래시 드라이브를 사용하여 ONTAP 이미지를 전송할 때 사용됩니다.

.구성 요소 교체
실패한 구성 요소를 NetApp 에서 제공한 교체 구성 요소로 교체합니다.

.컨트롤러 식별
손상된 부트 미디어를 교체할 때는 올바른 컨트롤러에 명령을 적용하는 것이 중요합니다.

* _손상된 컨트롤러_는 유지 관리를 수행하고 있는 컨트롤러입니다.
* 건강한 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.


.다음 단계
부팅 미디어를 교체하는 데 필요한 요구 사항을 검토한 후 를 link:bootmedia-encryption-preshutdown-checks.html["부팅 미디어에서 암호화 키 지원 및 상태를 확인합니다"]수행해야 합니다.
