---
permalink: fas500f/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas500f, shutdown the controllers 
summary: 섀시를 교체하려면 컨트롤러를 종료해야 합니다. 
---
= 컨트롤러 종료 - FAS500f
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차는 2-노드, 비-MetroCluster 구성에 한해서만 적용됩니다. 두 개 이상의 노드가 있는 시스템의 경우 를 참조하십시오 https://["4노드 클러스터에서 1개의 HA 쌍을 정상 종료하여 전원을 켜는 방법"^].

.시작하기 전에
필요한 사항:

* ONTAP에 대한 로컬 관리자 자격 증명입니다.
* 스토리지 암호화를 사용하는 경우 NetApp 온보드 키 관리(OKM) 클러스터 전체 암호 구문
* 각 컨트롤러에 대한 SP/BMC 액세스 가능성
* 모든 클라이언트/호스트에서 NetApp 시스템의 데이터에 액세스하지 못하도록 합니다.
* 외부 백업 작업을 일시 중지합니다.
* 교체에 필요한 공구 및 장비



NOTE: 시스템이 FabricPool 클라우드 계층으로 사용되는 NetApp StorageGRID 또는 ONTAP S3인 경우 를 참조하십시오 https://["스토리지 시스템을 정상적으로 종료하고 전원을 켭니다 해결 설명서"] 이 절차를 수행한 후


NOTE: FlexArray 스토리지 LUN을 사용하는 경우 이 절차를 수행한 후 해당 시스템에 대해 수행할 종료 절차는 해당 공급업체의 스토리지 시스템 설명서를 참조하십시오.


NOTE: SSD를 사용하는 경우 을 참조하십시오 https://["SU490: (영향: 위험) SSD 모범 사례: 2개월 이상 전원을 끈 경우 드라이브 고장 및 데이터 손실 위험을 피하십시오"]

시스템을 종료하기 전에 다음을 수행해야 합니다.

* 추가 를 수행합니다 https://["시스템 상태 점검"].
* ONTAP를 시스템의 권장 릴리스로 업그레이드합니다.
* 모두 해결 https://["Active IQ Wellness 알림 및 위험"]. 시스템 구성 요소의 LED와 같은 현재 시스템에 있는 모든 결함을 기록해 둡니다.


.단계
. SSH를 통해 클러스터에 로그인하거나 로컬 콘솔 케이블과 랩톱/콘솔을 사용하여 클러스터의 노드에서 로그인합니다.
. AutoSupport를 끄고 시스템이 오프라인 상태로 될 것으로 예상되는 시간을 표시합니다.
+
`system node autosupport invoke -node * -type all -messages "MAINT=8h Power Maintenance"`

. 모든 노드의 SP/BMC 주소 확인:
+
`system service-processor show -node * -fields address`

. 클러스터 쉘을 종료합니다. `exit`
. 이전 단계의 출력에 나열된 노드의 IP 주소를 사용하여 SSH를 통해 SP/BMC에 로그인합니다.
+
콘솔/노트북을 사용하는 경우 동일한 클러스터 관리자 자격 증명을 사용하여 컨트롤러에 로그인합니다.

+

NOTE: 진행 상황을 모니터링할 수 있도록 모든 SP/BMC 연결에 대한 SSH 세션을 엽니다.

. 클러스터의 모든 노드 중지:
+
`system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`.

+

NOTE: StrictSync 모드에서 작동하는 SnapMirror Synchronous를 사용하는 클러스터의 경우: `system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 클러스터의 각 컨트롤러에 대해 * y * 를 입력합니다 `_Warning: Are you sure you want to halt node "cluster name-controller number"?
{y|n}:_`
. 각 컨트롤러가 멈출 때까지 기다린 후 LOADER 프롬프트가 표시됩니다.
. PSU 켜기/끄기 스위치가 없는 경우 각 PSU를 끄거나 전원 코드를 뽑습니다.
. 각 PSU에서 전원 코드를 뽑습니다.
. 손상된 섀시의 모든 컨트롤러의 전원이 꺼져 있는지 확인합니다.

