---
permalink: fas500f/overview.html 
sidebar: sidebar 
keywords: FAS500f specifications, FAS500f specs, NetApp FAS500f, FAS500f hardware 
summary: FAS500f 스토리지 시스템의 주요 사양 
---
= FAS500f의 주요 사양
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음은 FAS500f에 대한 선택 사양입니다.  https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] (HWU)를 방문하여 FAS500f 사양의 전체 목록을 확인하십시오. 이 페이지는 단일 고가용성 쌍을 반영합니다.



=== FAS500f의 주요 사양

플랫폼 구성: FAS500f 단일 섀시 HA 쌍

최대 원시 용량: 1.1016 PB

메모리: 128.0000GB

폼 팩터: 2개의 HA 컨트롤러와 24개의 드라이브 슬롯이 있는 2U 섀시

ONTAP 버전: 9.16.1P2

PCIe 확장 슬롯: 4개

최소 ONTAP 버전: ONTAP 9.8RC1



=== 스케일아웃 최대값

|===


| 유형 | HA 쌍 | 원시 용량 | 최대 메모리 


| NAS | 12 | 13.2PB / 11.7PiB | 1536GB 


| SAN | 6 | 6.6페타바이트 / 5.9파이바이트 | 768GB 


| HA 쌍 |  | 1.1PB / 1.0PiB | 128.0000 
|===


=== 아이오



==== 온보드 IO

|===


| 규약 | 포트 


| 이더넷 25Gbps | 4 


| 이더넷 10Gbps | 4 
|===


==== 총 IO

|===


| 규약 | 포트 


| 이더넷 100Gbps | 4 


| 이더넷 25Gbps | 20 


| 이더넷 10Gbps | 4 


| FC 32Gbps | 16 


| NVMe/FC 32Gbps | 16 


|  | 0 


| SAS 12Gbps | 8 
|===


==== 관리 포트

|===


| 규약 | 포트 


| 이더넷 1Gbps | 2 


| RS-232 115Kbps | 4 


| USB 12Mbps | 4 
|===


=== 스토리지 네트워킹 지원

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; NAS가 있는 S3; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== 시스템 환경 사양

* 일반적인 전력: 2642 BTU/hr
* 최악의 경우 전력: 3476 BTU/hr
* 무게: 54.3파운드 24.6kg
* 높이: 2U
* 너비: 19인치 IEC 랙 규격 준수 (17.6인치, 44.7cm)
* 깊이: 21.38"(54.3cm)
* 작동 온도/고도/습도: 최대 3048m(10000피트) 고도에서 10°C ~ 35°C(50°F ~ 95°F), 상대 습도 8% ~ 80%(비응축)
* 비작동 시 온도/습도: -40°C ~ 70°C (-40°F ~ 158°F), 최대 12,192m (40,000ft), 상대 습도 10% ~ 95% (비응축), 원래 용기 기준
* 음향 소음: 공칭 음향 출력(LwAd): 7.2; 음압(LpAm)(주변 관찰자 위치): 69.1 dB




=== 규정 준수

* 인증 EMC/EMI: AMCA, FCC, ICES, KC, 모로코, VCCI
* 인증 안전: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* 인증 안전/EMC/EMI: EAC, UKRSEPRO
* 인증 안전/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* 표준 EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Part 15 Class A, ICES-003, KS C 9832, KS C 9835
* 표준 안전: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252(파트 1)




=== 고가용성

이더넷 기반 베이스보드 관리 컨트롤러(BMC) 및 ONTAP 관리 인터페이스; 중복 핫스왑 가능 컨트롤러; 중복 핫스왑 가능 전원 공급 장치; 외부 선반을 위한 SAS 연결을 통한 SAS 인밴드 관리;
