---
permalink: a800/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: a800, replace the boot media 
summary: AFF A800 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요건을 충족하는지 확인하십시오. 여기에는 적절한 용량의 저장 공간이 있는 USB 플래시 드라이브가 있는지, 그리고 올바른 교체 부팅 장치가 있는지 확인하는 것이 포함됩니다. 
---
= 수동 부팅 미디어 복구 요구 사항 - AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A800 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요건을 충족하는지 확인하십시오. 여기에는 적절한 용량의 저장 공간이 있는 USB 플래시 드라이브가 있는지, 그리고 올바른 교체 부팅 장치가 있는지 확인하는 것이 포함됩니다.

스토리지 시스템에서 ONTAP 9.17.1 이상을 실행 중인 경우 다음을 사용하십시오.link:bootmedia-replace-workflow-bmr.html["자동 부팅 복구 절차"] .  시스템에서 이전 버전의 ONTAP 실행 중인 경우 수동 부팅 복구 절차를 사용해야 합니다.

[NOTE]
====
NetApp에서는 작업 중인 장치에서 콘솔 로깅을 활성화하고 이 절차를 수행할 때 다음 조치를 취할 것을 강력히 권장합니다.

* 유지 관리 중에도 AutoSupport 기능을 활성화 상태로 유지하십시오. 이렇게 하면 문제가 발생할 경우 NetApp 지원팀에서 진단 정보를 받을 수 있습니다.
* CLI 세션에 대한 세션 로깅을 활성화하십시오. 이렇게 하면 유지보수 윈도우 중에 수행된 모든 명령과 시스템 출력에 대한 완전한 기록이 생성됩니다. 세션 로깅 활성화 방법에 대한 자세한 내용은 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 최적의 연결을 위해 PuTTY를 구성하는 방법"^]을 참조하십시오.


====
.USB 플래시 드라이브
* USB 플래시 드라이브가 FAT32로 포맷되었는지 확인하세요.
* USB에는 다음을 저장할 수 있는 충분한 저장 용량이 있어야 합니다.  `image_xxx.tgz` 파일.


.파일 준비
복사하다  `image_xxx.tgz` 파일을 USB 플래시 드라이브에 복사합니다. 이 파일은 USB 플래시 드라이브를 사용하여 ONTAP 이미지를 전송할 때 사용됩니다.

추출한 ONTAP 이미지에서  `EFI` 폴더를 USB 플래시 드라이브의 루트 디렉터리에 복사합니다.

.구성 요소 교체
실패한 구성 요소를 NetApp 에서 제공한 교체 구성 요소로 교체합니다.

.컨트롤러 식별
손상된 부트 미디어를 교체할 때는 올바른 컨트롤러에 명령을 적용하는 것이 중요합니다.

* _손상된 컨트롤러_는 유지 관리를 수행하고 있는 컨트롤러입니다.
* 건강한 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.


.다음 단계
부팅 미디어를 교체하는 데 필요한 요구 사항을 검토한 후 를 link:bootmedia-encryption-preshutdown-checks.html["부팅 미디어에서 암호화 키 지원 및 상태를 확인합니다"]수행해야 합니다.
