---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 'ASA C30 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요구 사항과 고려 사항을 충족하는지 확인하십시오. 여기에는 올바른 교체 부트 미디어를 가지고 있는지, 손상된 컨트롤러의 e0S(e0M 렌치) 포트가 제대로 작동하는지, 그리고 Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.' 
---
= 부팅 미디어 교체 요구 사항 - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C30 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요구 사항과 고려 사항을 충족하는지 확인하십시오. 여기에는 올바른 교체 부트 미디어를 가지고 있는지, 손상된 컨트롤러의 e0S(e0M 렌치) 포트가 제대로 작동하는지, 그리고 Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.



== 요구 사항

* 장애가 발생한 구성 요소를 NetApp에서 제공한 것과 동일한 용량의 교체 FRU 구성 요소로 교체해야 합니다.
* 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 결함이 있을 수 없습니다.
+
e0S 포트는 자동 부팅 복구에 사용됩니다.

* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.






== 고려 사항

* 다음 단계의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 유지 관리를 수행하는 컨트롤러입니다.
** healy_controller는 손상된 컨트롤러의 HA 파트너입니다.


* 필요한 경우 플랫폼 섀시 위치(파란색) LED를 켜서 영향을 받는 플랫폼을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
플랫폼 섀시에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.



.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["컨트롤러를 종료합니다"]
