---
permalink: a250/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a250, prerequisite, replace the controller module 
summary: 교체 절차를 위한 필수 구성 요소를 검토하고 사용 중인 ONTAP 운영 체제 버전에 맞는 올바른 구성 요소를 선택해야 합니다. 
---
= 컨트롤러 교체 요구 사항 - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 스토리지 시스템에서 컨트롤러를 교체하기 전에 성공적인 교체를 위한 필수 요건을 충족했는지 확인하십시오. 여기에는 시스템의 다른 모든 구성 요소가 제대로 작동하는지 확인하고, 올바른 교체용 컨트롤러를 사용하고 있는지 확인하고, 컨트롤러 콘솔 출력을 텍스트 로그 파일에 저장하는 것이 포함됩니다.

교체 절차를 위한 필수 구성 요소를 검토하고 사용 중인 ONTAP 운영 체제 버전에 맞는 올바른 구성 요소를 선택해야 합니다.

* 모든 드라이브 쉘프가 올바로 작동하고 있어야 합니다.
* 시스템이 MetroCluster 구성인 경우 해당 섹션을 검토해야 합니다 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["올바른 복구 절차 선택"] 이 절차를 사용해야 하는지 여부를 확인합니다.
* 오류가 발생한 구성 요소를 공급업체로부터 받은 교체 FRU 구성 요소로 교체해야 합니다.
* 컨트롤러 모듈을 동일한 모델 유형의 컨트롤러 모듈로 교체해야 합니다. 컨트롤러 모듈만 교체하면 시스템을 업그레이드할 수 없습니다.
* 이 절차의 일부로 드라이브 또는 드라이브 쉘프를 변경할 수 없습니다.
* 이 절차에서는 _ replacement_controller가 이전 컨트롤러 모듈과 동일한 버전의 ONTAP에서 부팅되도록 부팅 장치를 손상된 컨트롤러에서 _replacement_controller로 이동합니다.
* 올바른 시스템에 다음 단계에 있는 명령을 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 컨트롤러의 콘솔 출력을 항상 텍스트 파일로 캡처해야 합니다.
+
교체 프로세스 중에 발생할 수 있는 문제를 해결할 수 있도록 절차에 대한 기록을 제공합니다.



.다음 단계
손상된 컨트롤러를 교체하기 위한 요구 사항을 검토한 후 link:controller-replace-shutdown.html["손상된 컨트롤러를 종료합니다"]해야 합니다.
