---
permalink: fas8200/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas8200, post boot media replacement steps for okm, nse, and nve 
summary: '환경 변수를 선택한 후에는 Onboard Key Manager\(OKM\), NetApp Storage Encryption\(NSE\), NetApp Volume Encryption\(NVE\)가 활성화된 시스템 관련 단계를 완료해야 합니다.' 
---
= 필요에 따라 OKM, NSE 및 NVE를 복원합니다 - FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
환경 변수를 선택한 후에는 온보드 키 관리자(OKM), NetApp 스토리지 암호화(NSE), NetApp 볼륨 암호화(NVE)가 활성화된 시스템과 관련된 단계를 완료해야 합니다.

OKM, NSE 또는 NVE 구성을 복원하는 데 사용할 섹션을 결정합니다.

NSE 또는 NVE를 온보드 키 관리자와 함께 사용할 경우 이 절차를 시작할 때 캡처한 설정을 복원해야 합니다.

* NSE 또는 NVE가 활성화되고 온보드 키 관리자가 활성화된 경우 로 이동합니다  1: Restore NVE or NSE when Onboard Key Manager is enabled.
* NSE 또는 NVE가 ONATP 9.5에 대해 활성화된 경우 로 이동합니다  2: Restore NSE/NVE on systems running ONTAP 9.5 and earlier.
* NSE 또는 NVE가 ONTAP 9.6에 대해 활성화된 경우 로 이동합니다  3: Restore NSE/NVE on systems running ONTAP 9.6 and later.




== 옵션 1: Onboard Key Manager가 활성화된 경우 NVE 또는 NSE를 복원합니다

.단계
. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 "boot_ontap" 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,3"]
|===
| * 콘솔이 표시되는 경우... * | 그 다음에... * 


 a| 
LOADER 메시지가 표시됩니다
 a| 
부팅 메뉴에서 boot_ontap menu로 컨트롤러를 부팅합니다



 a| 
반환 대기 중...
 a| 
.. 프롬프트에 Ctrl-C를 입력합니다
.. 메시지: [y/n]을(를) 기다리지 않고 이 컨트롤러를 중지하시겠습니까? y를 입력합니다
.. LOADER 프롬프트에서 'boot_ontap menu' 명령을 입력한다.


|===
. 부팅 메뉴에서 숨겨진 명령 recover_onboard_keymanager를 입력하고 프롬프트에 y를 입력합니다.
. 이 절차를 시작할 때 고객으로부터 받은 온보드 키 관리자의 암호를 입력합니다.
. 백업 데이터를 입력하라는 메시지가 나타나면 이 절차의 시작 부분에서 캡처한 백업 데이터를 붙여 넣습니다. Security key-manager backup show 또는 security key-manager 온보드 show-backup 명령의 출력을 붙여 넣는다.
+

NOTE: 이 데이터는 보안 키 관리자 백업 쇼 또는 보안 키 관리자 온보드 show-backup 명령을 통해 출력됩니다.

+
백업 데이터의 예:

+
====
------------------------------ 백업 시작 ------------------------------------------------------- AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOVAAABAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVAAVHAVH0AAVAAVAAVHAAVHAAAHABOH0AAH0AAHAAAH0AAH0AAHAAAHAAAHAAAH0AAH0AAAAAAAAHAAAH0AAAAHAAAHAAAHAAAHAAAHAAAH0AAHAAAHAAAH0AAAAAAAAAAAAAAAAH0AAAAAAAAAAAAHAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAAA . . . H4nPQM0nrDRYRA9SCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

------------------------------------------------- 엔드 백업 ------------------------

====
. 부팅 메뉴에서 Normal Boot 옵션을 선택합니다.
+
시스템이 '기브백을 기다리는 중...' 프롬프트로 부팅됩니다.

. 콘솔 케이블을 파트너 컨트롤러로 이동하고 admin으로 로그인합니다.
. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.
. fromnode local-only-CFO-aggregate true" 명령을 사용하여 스토리지 페일오버 기브백을 가진 CFO 애그리게이트만 돌려주십시오.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 CIFS 세션을 닫는 방법에 대해 고객에게 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태로 인해 명령이 실패하면, NVMEM이 동기화될 때까지 5분 동안 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 문서 센터를 참조하십시오.


. 반환이 완료되면 'storage failover show' 및 'storage failover show'-반환 명령으로 페일오버와 반환 상태를 확인하십시오.
+
CFO 애그리게이트(루트 애그리게이트 및 CFO 스타일 데이터 애그리게이트)만 표시됩니다.

. 콘솔 케이블을 대상 컨트롤러로 이동합니다.
. ONTAP 9.5 이전 버전을 실행 중인 경우 키 관리자 설정 마법사를 실행합니다.
+
.. 'Security key-manager setup-notenodename' 명령을 사용하여 마법사를 시작한 다음 메시지가 나타나면 온보드 키 관리를 위한 암호를 입력합니다.
.. key-manager key show-detail 명령을 입력하여 Onboard Key Manager에 저장된 모든 키의 상세 보기를 확인하고 모든 인증 키의 restored column="yes" 여부를 확인한다.
+

NOTE: '복원된' 열이 '예'가 아닌 경우 고객 지원 센터에 문의하십시오.

.. 키가 클러스터 전체에서 동기화될 때까지 10분 정도 기다립니다.


. ONTAP 9.6 이상을 실행 중인 경우:
+
.. Security key-manager 온보드 sync 명령을 실행한 다음 메시지가 나타나면 암호를 입력합니다.
.. 'Security key-manager key query' 명령어를 입력하여 Onboard Key Manager에 저장된 모든 키의 상세 보기를 확인하고 모든 인증 키의 'restored' column = yes/true인지 확인한다.
+

NOTE: 'restored(복원됨)' 열이 Yes/true(예/참) 이외의 경우 고객 지원 센터에 문의하십시오.

.. 키가 클러스터 전체에서 동기화될 때까지 10분 정도 기다립니다.


. 콘솔 케이블을 파트너 컨트롤러로 이동합니다.
. 'storage failover -fromnode local' 명령을 사용하여 타겟 컨트롤러를 다시 제공합니다.
. 'storage failover show' 명령을 사용하여 완료 후 3분 동안 반환 상태를 확인하십시오.
+
20분 후 기브백이 완료되지 않으면 고객 지원 팀에 문의하십시오.

. 클러스터 셸 프롬프트에서 "net int show -is -home false" 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
만약 어떤 인터페이스가 false로 나열된다면, net int revert 명령을 사용하여 그 인터페이스를 홈 포트로 되돌리십시오.

. 콘솔 케이블을 대상 컨트롤러로 옮기고 rsion -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.




== 옵션 2: ONTAP 9.5 이전 버전을 실행 중인 시스템에서 NSE/NVE를 복원합니다

.단계
. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 "boot_ontap" 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,3"]
|===
| * 콘솔이 표시되는 경우... * | 그 다음에... * 


 a| 
로그인 프롬프트
 a| 
7단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
.. 파트너 컨트롤러에 로그인합니다.
.. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.


|===
. 콘솔 케이블을 파트너 컨트롤러로 이동하여 'storage failover back - fromnode local -only -CFO -aggregate true local' 명령을 사용하여 타겟 컨트롤러 스토리지를 반환하십시오.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 고객에게 CIFS 세션을 닫는 방법을 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태로 인해 명령이 실패하면, NVMEM이 동기화될 때까지 5분 동안 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 문서 센터를 참조하십시오.


. 3분 정도 기다린 후 'storage failover show' 명령으로 페일오버 상태를 확인한다.
. 클러스터 셸 프롬프트에서 "net int show -is -home false" 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
만약 어떤 인터페이스가 false로 나열된다면, net int revert 명령을 사용하여 그 인터페이스를 홈 포트로 되돌리십시오.

. 콘솔 케이블을 대상 컨트롤러로 이동하고 버전 '-v 명령'을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. 클러스터 셸 프롬프트에서 '스토리지 암호화 디스크 표시'를 사용하여 출력을 검토합니다.
+

NOTE: NVE(NetApp Volume Encryption)가 구성된 경우 이 명령이 작동하지 않습니다

. 보안 키 관리자 쿼리를 사용하여 키 관리 서버에 저장된 인증 키의 키 ID를 표시합니다.
+
** 'restored' 열 = 'yes'이고 모든 주요 관리자가 사용 가능한 상태로 보고하는 경우, _ 로 이동하여 교체 프로세스를 완료합니다.
** 'restored' column = yes가 아닌 다른 column 및/또는 하나 이상의 key manager를 사용할 수 없는 경우, 'security key-manager restore-address' 명령을 사용하여 모든 가용 Key Management 서버의 모든 nodes와 연관된 모든 Authentication key(ACK)와 key ID를 검색하고 복구한다.
+
보안 키 관리자 쿼리의 결과를 다시 확인하여 "복원된" 열 = "예"와 모든 키 관리자가 사용 가능한 상태로 보고하는지 확인합니다



. Onboard Key Management(온보드 키 관리)가 활성화된 경우:
+
.. 온보드 키 관리자에 저장된 모든 키의 상세 보기를 보려면 '보안 키 관리자 키 표시-세부정보'를 사용하십시오.
.. Security key-manager key show-detail 명령을 사용하여 모든 인증 키에 대해 restored column= yes인지 확인한다.
+
'restored' column = yes가 아닌 경우, 'Security key-manager setup-node_repaired_(target)_node_' 명령어를 이용하여 Onboard Key Management 설정을 복구한다. Security key-manager key show-detail 명령을 다시 실행하여 모든 인증 키에 대해 Restored column=yes를 확인한다.



. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 'storage failover -fromnode local' 명령을 사용하여 컨트롤러를 반환하십시오.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.




== 옵션 3: ONTAP 9.6 이상을 실행하는 시스템에서 NSE/NVE를 복원합니다

.단계
. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 "boot_ontap" 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,3"]
|===
| 콘솔에 다음이 표시되는 경우... | 그러면... 


 a| 
로그인 프롬프트
 a| 
7단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
.. 파트너 컨트롤러에 로그인합니다.
.. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.


|===
. 콘솔 케이블을 파트너 컨트롤러로 이동하여 'storage failover back - fromnode local -only -CFO -aggregate true local' 명령을 사용하여 타겟 컨트롤러 스토리지를 반환하십시오.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 CIFS 세션을 닫는 방법에 대해 고객에게 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태로 인해 명령이 실패하면, NVMEM이 동기화될 때까지 5분 동안 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 문서 센터를 참조하십시오.


. 3분 정도 기다린 후 'storage failover show' 명령으로 페일오버 상태를 확인한다.
. 클러스터 셸 프롬프트에서 "net int show -is -home false" 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
만약 어떤 인터페이스가 false로 나열된다면, net int revert 명령을 사용하여 그 인터페이스를 홈 포트로 되돌리십시오.

. 콘솔 케이블을 대상 컨트롤러로 옮기고 rsion -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. 클러스터 셸 프롬프트에서 '스토리지 암호화 디스크 표시'를 사용하여 출력을 검토합니다.
. 보안 키-관리자 키 쿼리 명령을 사용하여 키 관리 서버에 저장된 인증 키의 키 ID를 표시합니다.
+
** 'restored' 칼럼이 'yes/true'인 경우, 사용자는 모두 완료되어 교체 프로세스를 완료할 수 있습니다.
** Key Manager type="external" 및 "restored" column=yes/true 이외의 경우 보안 key-manager external restore 명령을 사용하여 인증 키의 키 ID를 복구한다.
+

NOTE: 명령이 실패하면 고객 지원 센터에 문의하십시오.

** Key Manager type="Onboard" 및 "restored" column = yes/true 이외의 경우, 보안 key-manager 온보드 sync 명령을 사용하여 Key Manager 유형을 다시 동기화한다.
+
보안 키 관리자 키 쿼리를 사용하여 모든 인증 키에 대해 "restored" 열 = "yes/true"인지 확인합니다.



. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 'storage failover -fromnode local' 명령을 사용하여 컨트롤러를 반환하십시오.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.

