---
permalink: afx-1k/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: afx 1k, boot the recovery image 
summary: AFX 1K 스토리지 시스템에 새 부트 미디어 장치를 설치한 후 자동 부트 미디어 복구 프로세스를 시작하여 파트너 노드에서 구성을 복원할 수 있습니다. 
---
= 복구 이미지 부팅 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K 스토리지 시스템에 새 부트 미디어 장치를 설치한 후 자동 부트 미디어 복구 프로세스를 시작하여 파트너 노드에서 구성을 복원할 수 있습니다.

.이 작업에 대해
복구 프로세스 동안 시스템은 암호화가 활성화되어 있는지 확인하고 사용되는 키 암호화 유형을 식별합니다. 키 암호화가 활성화되어 있는 경우, 시스템은 복원을 위한 적절한 단계를 안내합니다.

.시작하기 전에
* OKM의 경우 클러스터 전체 암호와 백업 데이터가 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.




.단계
. Loader 프롬프트에서 다음 명령을 입력합니다.
+
`boot_recovery -partner`

+
화면에 다음 메시지가 표시됩니다.

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. 부팅 미디어 설치 복구 프로세스를 모니터링합니다.
+
프로세스가 완료되고 `Installation complete` 메시지가 표시됩니다.

. 시스템에서 암호화 및 암호화 유형을 확인하고 두 메시지 중 하나를 표시합니다. 표시되는 메시지에 따라 다음 작업 중 하나를 수행합니다.
+

IMPORTANT: 경우에 따라 프로세스에서 키 관리자가 시스템에 구성되어 있는지 여부를 확인하지 못할 수 있습니다. 오류 메시지가 표시되고 시스템에 키 관리자가 구성되어 있는지 확인한 다음 구성된 키 관리자 유형을 묻습니다. 문제를 해결한 후 프로세스가 재개됩니다.

+
.프롬프트를 찾는 구성 오류 예를 표시합니다
[%collapsible]
====
....
Error when fetching key manager config from partner ${partner_ip}: ${status}

Has key manager been configured on this system

Is the key manager onboard

....
====
+
[cols="1,2"]
|===
| 이 메시지가 표시되는 경우... | 수행할 작업... 


 a| 
`key manager is not configured. Exiting.`
 a| 
시스템에 암호화가 구성되어 있지 않습니다. 다음 단계를 완료하세요.

.. 콘솔 메시지가 중지되면 <enter> 키를 누릅니다.
+
*** 로그인 메시지가 나타나면 4단계로 이동하세요.
*** 로그인 프롬프트가 나타나지 않으면 파트너 노드에 로그인하고 4단계로 진행하세요.


.. 자동 환불이 비활성화되어 있는 경우 6단계로 이동하여 자동 환불을 활성화하세요.




 a| 
`key manager is configured.`
 a| 
5단계로 이동하여 적절한 키 관리자를 복원하세요.

노드는 부팅 메뉴에 액세스하여 다음을 실행합니다.

** Onboard Key Manager(OKM)가 있는 시스템의 경우 옵션 10
** EKM(External Key Manager)이 있는 시스템의 경우 옵션 11.


|===
. 시스템에 암호화가 설치되어 있지 않고 로그인 프롬프트가 표시되지 않는 경우. 다음 단계를 완료하세요.
+
.. override-destination-checks 옵션을 사용하여 루트만 반환:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 이 명령은 진단 모드에서만 사용할 수 있습니다. 자세한 내용은 다음을 참조하십시오. link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["ONTAP CLI 명령에 대한 권한 수준"^] .

+
오류가 발생하면 에 문의하십시오 https://support.netapp.com["NetApp 지원"].

.. 반환 보고서가 완료된 후 5분 동안 기다린 다음 페일오버 상태와 반환 상태를 확인합니다.
+
`storage failover show`그리고 `storage failover show-giveback`

+

NOTE: 다음 명령은 진단 모드 권한 수준에서만 사용할 수 있습니다.

.. ONTAP 9.17.1을 실행 중이고 HA 내부 연결 링크가 끊어진 경우 다시 연결하세요.
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

+

NOTE: 9.18.1 이상을 실행 중이라면 위 단계를 건너뛰고 다음 단계로 넘어가세요.

.. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다.
+
'Storage failover 반환 - ofnode_impaired_node_name_'



. 키 관리자가 구성된 시스템의 경우 적절한 키 관리자 복원 프로세스를 선택합니다.
+
[role="tabbed-block"]
====
.온보드 키 관리자(OKM)
--
OKM이 감지되면 시스템은 다음 메시지를 표시하고 BootMenu 옵션 10을 실행하기 시작합니다.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. OKM 복구 프로세스 시작을 확인하는 프롬프트에 를 `Y` 입력합니다.
.. 메시지가 나타나면 다음을 입력하세요.
+
... 암호문구
... 확인을 요청하면 암호를 다시 입력하세요.
... 온보드 키 관리자를 위한 백업 데이터
+
.암호문구 및 백업 데이터 프롬프트의 예를 보여주세요
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END ACKUP-----
....
=====


.. 파트너 노드에서 적절한 파일을 복원하므로 복구 프로세스를 계속 모니터링합니다.
+
복구 프로세스가 완료되면 노드가 재부팅됩니다. 다음 메시지는 복구에 성공했음을 나타냅니다.

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. 노드를 재부팅할 때 시스템이 다시 온라인 상태이고 작동 중인지 확인하여 부팅 미디어 복구가 성공적인지 확인합니다.
.. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다.
+
'Storage failover 반환 - ofnode_impaired_node_name_'

+
... HA 상호 연결 링크가 끊어진 경우 자동으로 다시 연결되도록 다시 연결하세요.
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



.. 파트너 노드가 완전히 가동되어 데이터를 제공하는 후 클러스터 전체에서 OKM 키를 동기화합니다.
+
`security key-manager onboard sync`



--
.외부 키 관리자(EKM)
--
EKM이 감지되면 시스템은 다음 메시지를 표시하고 BootMenu 옵션 11을 실행하기 시작합니다.

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. 키가 성공적으로 복원되었는지 여부에 따라 다음 작업 중 하나를 수행합니다.
+
*** 당신이 보면 `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` 출력에서 EKM 구성이 성공적으로 복원되었습니다.
+
이 프로세스는 파트너 노드에서 적절한 파일을 복원하고 노드를 재부팅합니다.  d 단계로 이동합니다.

*** 키가 성공적으로 복구되지 않으면 시스템이 중단되고 키를 복구할 수 없다는 메시지가 표시됩니다.  오류 및 경고 메시지가 표시됩니다.  복구 프로세스를 다시 실행해야 합니다.
+
`boot_recovery -partner`

+
.키 복구 오류 및 경고 메시지의 예를 표시합니다
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. 노드가 재부팅될 때 시스템이 다시 온라인 상태이고 작동 중인지 확인하여 부팅 미디어 복구가 성공했는지 확인합니다.
.. 스토리지를 되돌려 컨트롤러를 정상 작업으로 되돌립니다.
+
'Storage failover 반환 - ofnode_impaired_node_name_'

+
... HA 상호 연결 링크가 끊어진 경우 자동으로 다시 연결되도록 다시 연결하세요.
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`





--
====


. 자동 반환이 비활성화된 경우 다시 활성화하십시오.
+
`storage failover modify -node local auto-giveback-of true`

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음 단계
ONTAP 이미지를 복원하고 노드가 작동하여 데이터를 제공하면 다음을 수행해야 합니다.link:bootmedia-complete-rma.html["결함이 있는 부품을 NetApp로 반환합니다"] .
