---
permalink: afx-1k/controller-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shut down the impaired controller 
summary: AFX 1K 저장 시스템의 컨트롤러가 손상되면 끄세요.  유지관리나 구성 요소 교체를 수행하기 전에 데이터 손실을 방지하고 시스템 안정성을 확보하기 위해 컨트롤러를 안전하게 종료하는 것이 중요합니다. 
---
= 손상된 컨트롤러 종료 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러를 교체할 때 데이터 손실을 방지하고 시스템 안정성을 확보하려면 AFX 1K 저장 시스템에서 손상된 컨트롤러를 종료하세요.

다음 옵션 중 하나를 사용하여 컨트롤러 모듈을 종료합니다.

손상된 컨트롤러를 종료하려면 컨트롤러의 상태를 확인하고 필요한 경우 컨트롤러의 스토리지 장애 조치 인수를 수행하여 정상 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 해야 합니다.

.이 작업에 대해
* 4개 이상의 노드가 있는 클러스터가 있는 경우 쿼럼에 있어야 합니다.  노드에 대한 클러스터 정보를 보려면 다음을 사용하세요. `cluster show` 명령.  자세한 내용은 `cluster show` 명령, 참조link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["ONTAP 클러스터에서 노드 수준 세부 정보 보기"^] .
* 클러스터가 쿼럼에 포함되지 않았거나 손상된 컨트롤러를 제외한 모든 컨트롤러의 상태 또는 적격성이 거짓으로 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다. 보다 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^] .


.단계
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다.

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 손상된 컨트롤러의 콘솔에서 자동 반환을 비활성화합니다.
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: _자동 환불을 비활성화하시겠습니까?_라는 메시지가 표시되면 다음을 입력하세요. `y` .

+
.. ONTAP 버전 9.17.1을 실행 중이고 손상된 컨트롤러를 가동할 수 없거나 이미 인수된 경우 손상된 컨트롤러를 부팅하기 전에 정상 컨트롤러에서 HA 상호 연결 링크를 끊어야 합니다.  이렇게 하면 손상된 컨트롤러가 자동으로 반환하는 것을 방지할 수 있습니다.
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`



. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트
 a| 
건강한 컨트롤러로부터 손상된 컨트롤러를 인수하거나 중단합니다.
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

_-halt true_ 매개변수는 손상된 노드를 LOADER 프롬프트로 가져옵니다.

|===


.다음 단계
컨트롤러를 종료한 후,link:controller-replace-move-hardware.html["컨트롤러를 교체합니다"] .
