---
permalink: afx-1k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: afx 1k, prerequisite, replace the controller module 
summary: AFX 1K 스토리지 시스템의 컨트롤러를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요.  여기에는 올바른 교체 컨트롤러, 시스템 구성 백업, 필요한 도구 및 펌웨어에 대한 액세스가 포함됩니다. 
---
= 컨트롤러 교체 요구 사항 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K 스토리지 시스템의 컨트롤러를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요. 여기에는 시스템의 다른 모든 구성 요소가 제대로 작동하는지 확인하고, 올바른 교체 컨트롤러를 가지고 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 것이 포함됩니다.

컨트롤러 교체 요구 사항을 검토하십시오.

* 올바른 시스템에 다음 단계에 있는 명령을 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 모든 드라이브 쉘프가 올바로 작동하고 있어야 합니다.
* 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러"라고 함).
* 장애가 발생한 구성요소를 NetApp에서 제공한 현장 교체 장치(FRU)로 교체해야 합니다.
* 컨트롤러 모듈을 동일한 모델 유형의 컨트롤러 모듈로 교체해야 합니다. 컨트롤러 모듈만 교체하면 시스템을 업그레이드할 수 없습니다.
* 이 절차의 일부로 드라이브 또는 드라이브 쉘프를 변경할 수 없습니다.
* 항상 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 캡처해야 합니다.
+
교체 프로세스 중에 발생할 수 있는 문제를 해결할 수 있도록 절차에 대한 기록을 제공합니다.



.다음 단계
AFX 1K 컨트롤러를 교체하기 위한 요구 사항을 검토한 후,link:controller-replace-shutdown.html["컨트롤러를 끄세요"] .
