---
permalink: fas50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, replace the boot media 
summary: FAS50 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 적절한 용량의 USB 플래시 드라이브가 있는지 확인하고 올바른 교체용 부팅 장치가 있는지 확인하는 작업이 포함됩니다. 
---
= 부팅 미디어 교체 요구 사항 - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 적절한 용량의 USB 플래시 드라이브가 있는지 확인하고 올바른 교체용 부팅 장치가 있는지 확인하는 작업이 포함됩니다.

부팅 미디어를 교체하기 전에 다음 요구 사항 및 고려 사항을 검토하십시오.



== 요구 사항

* "image_xxx.tgz"를 저장할 적절한 저장 공간을 가진 FAT32로 포맷된 USB 플래시 드라이브가 있어야 합니다.
* 이 절차에서 나중에 사용할 수 있도록 파일을 USB 플래시 드라이브에 복사해야 `image_xxx.tgz` 합니다.
* 장애가 발생한 구성 요소는 공급자로부터 받은 용량과 동일한 용량의 교체용 FRU 구성 요소로 교체해야 합니다.




== 고려 사항

* 다음 단계의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 유지 관리를 수행하는 컨트롤러입니다.
** healy_controller는 손상된 컨트롤러의 HA 파트너입니다.


* 필요한 경우 플랫폼 섀시 위치(파란색) LED를 켜서 영향을 받는 플랫폼을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
플랫폼 섀시에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.



.다음 단계
부팅 미디어를 교체하는 데 필요한 요구 사항을 검토한 후 를 link:bootmedia-encryption-preshutdown-checks.html["부팅 미디어에서 암호화 키 지원 및 상태를 확인합니다"]수행해야 합니다.
