---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: 교체 절차를 위한 필수 구성 요소를 검토하고 사용 중인 ONTAP 운영 체제 버전에 맞는 올바른 구성 요소를 선택해야 합니다. 
---
= 컨트롤러 교체 요구사항 - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 교체 절차에 대한 요구 사항 및 고려 사항을 검토하십시오.



== 요구 사항

* 모든 선반이 올바르게 작동해야 합니다.
* 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러"라고 함).
* 시스템이 MetroCluster 구성인 경우 해당 섹션을 검토해야 합니다 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["올바른 복구 절차 선택"] 이 절차를 사용해야 하는지 여부를 확인합니다.
* 컨트롤러를 동일한 모델 유형의 컨트롤러로 교체해야 합니다. 컨트롤러만 교체하여 시스템을 업그레이드할 수 없습니다.
* 이 절차에서 드라이브나 쉘프를 변경할 수 없습니다.
* 항상 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 캡처해야 합니다.
+
콘솔 출력은 교체 프로세스 중에 발생할 수 있는 문제를 해결하는 데 사용할 수 있는 절차에 대한 기록을 제공합니다.





== 고려 사항

* 이 절차의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 필요한 경우 스토리지 시스템 위치 상태 표시등(파란색)을 켜서 영향을 받는 스토리지 시스템을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
스토리지 시스템에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.


