---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: FAS50 스토리지 시스템에서 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다. 
---
= 컨트롤러-FAS50을 대체할 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50 스토리지 시스템에서 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다.

컨트롤러 교체 절차에 대한 요구 사항 및 고려 사항을 검토하십시오.

[NOTE]
====
NetApp에서는 작업 중인 장치에서 콘솔 로깅을 활성화하고 이 절차를 수행할 때 다음 조치를 취할 것을 강력히 권장합니다.

* 유지 관리 중에도 AutoSupport 기능을 활성화 상태로 유지하십시오. 이렇게 하면 문제가 발생할 경우 NetApp 지원팀에서 진단 정보를 받을 수 있습니다.
* CLI 세션에 대한 세션 로깅을 활성화하십시오. 이렇게 하면 유지보수 윈도우 중에 수행된 모든 명령과 시스템 출력에 대한 완전한 기록이 생성됩니다. 세션 로깅 활성화 방법에 대한 자세한 내용은 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 최적의 연결을 위해 PuTTY를 구성하는 방법"^]을 참조하십시오.


====


== 요구 사항

* 모든 선반이 올바르게 작동해야 합니다.
* 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러"라고 함).
* 시스템이 MetroCluster 구성인 경우 해당 섹션을 검토해야 합니다 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["올바른 복구 절차 선택"] 이 절차를 사용해야 하는지 여부를 확인합니다.
* 컨트롤러를 동일한 모델 유형의 컨트롤러로 교체해야 합니다. 컨트롤러만 교체하여 시스템을 업그레이드할 수 없습니다.
* 이 절차에서 드라이브나 쉘프를 변경할 수 없습니다.




== 고려 사항

이 절차의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.

* impaired_controller는 교체되는 컨트롤러입니다.
* replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
* healthy_controller는 정상적인 컨트롤러입니다.


.다음 단계
손상된 컨트롤러를 교체하기 위한 요구 사항을 검토한 후에는 다음을 link:controller-replace-shutdown.html["손상된 컨트롤러를 종료합니다"]수행해야 합니다.
