---
permalink: fas9500/nvram_module_or_nvram_dimm_replacement.html 
sidebar: sidebar 
keywords:  
summary: 'NVRAM 모듈은 NVRAM11 및 DIMM과 NVRAM 모듈당 최대 2개의 NVMe SSD Flash Cache 모듈(FlashCache 또는 캐싱 모듈)로 구성됩니다.' 
---
= NVRAM 모듈 및/또는 NVRAM DIMM-FAS9500을 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVRAM 모듈은 NVRAM11 및 DIMM으로 구성됩니다. 장애가 발생한 NVRAM 모듈 또는 NVRAM 모듈 내부의 DIMM을 교체할 수 있습니다. 장애가 발생한 NVRAM 모듈을 교체하려면 섀시에서 모듈을 분리하고 DIMM을 교체 모듈로 옮긴 다음 교체용 NVRAM 모듈을 섀시에 설치해야 합니다.

및 NVRAM DIMM을 교체하려면 NVRAM 모듈을 섀시에서 분리하고 모듈에서 장애가 발생한 DIMM을 교체한 다음 NVRAM 모듈을 다시 설치해야 합니다.

시스템 ID는 NVRAM 모듈에서 파생되므로 모듈을 교체할 경우 시스템에 속한 디스크가 새 시스템 ID로 재할당됩니다.

.시작하기 전에
* 모든 디스크 쉘프가 올바로 작동하고 있어야 합니다.
* 시스템이 HA 쌍 내에 있는 경우 파트너 노드가 교체할 NVRAM 모듈과 연결된 노드를 인수할 수 있어야 합니다.
* 이 절차에서는 다음과 같은 용어를 사용합니다.
+
** 손상된 노드는 유지보수를 수행 중인 노드입니다.
** 정상 노드는 장애가 발생한 노드의 HA 파트너입니다.


* 이 절차에는 새 NVRAM 모듈과 연결된 컨트롤러 모듈에 디스크를 자동 또는 수동으로 재할당하는 단계가 포함되어 있습니다. 이 절차에서 로 지정된 경우 디스크를 재할당해야 합니다. 반환 전에 디스크 재할당을 완료하면 문제가 발생할 수 있습니다.
* 오류가 발생한 구성 요소를 공급업체로부터 받은 교체 FRU 구성 요소로 교체해야 합니다.
* 이 절차의 일부로 디스크 또는 디스크 쉘프를 변경할 수 없습니다.




== 1단계: 장애가 있는 노드를 종료합니다

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다. 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/system-admin/index.html["CLI를 사용한 관리 개요"^].

.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
"기백을 기다리는 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===




== 2단계: NVRAM 모듈을 교체합니다

NVRAM 모듈을 장착하려면 섀시의 슬롯 6에서 모듈을 찾은 다음 특정 단계를 따릅니다.

. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 섀시에서 대상 NVRAM 모듈을 분리합니다.
+
.. 문자 및 번호가 매겨진 캠 버튼을 누릅니다.
+
캠 버튼이 섀시에서 멀어져 있습니다.

.. 캠 래치가 수평 위치에 올 때까지 아래로 돌립니다.
+
NVRAM 모듈은 섀시에서 분리되어 몇 인치 정도 밖으로 이동합니다.

.. 모듈 면의 측면에 있는 당김 탭을 당겨 섀시에서 NVRAM 모듈을 분리합니다.
+





endif::[]

endif::[]
