---
permalink: fas9500/overview.html 
sidebar: sidebar 
keywords: FAS9500 specifications, FAS9500 specs, NetApp FAS9500, FAS9500 hardware 
summary: FAS9500 스토리지 시스템의 주요 사양 
---
= FAS9500 의 주요 사양
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음은 FAS9500 에 대한 선택 사양입니다.  방문하다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] FAS9500 사양의 전체 목록은 (HWU)에서 확인하세요.  이 페이지는 단일 고가용성 쌍을 반영합니다.



=== FAS9500 의 주요 사양

플랫폼 구성: FAS9500 단일 섀시 HA 쌍

최대 원시 용량: 15.0000 PB

메모리: 2048.0000GB

폼 팩터: 2개의 HA 컨트롤러가 있는 8U 섀시

ONTAP 버전: b_startONTAP: 9.16.1P2b_end

PCIe 확장 슬롯: 20개

최소 ONTAP 버전: ONTAP 9.10.1P3



=== 스케일아웃 최대값

|===


| 유형 | HA 쌍 | 원시 용량 | 최대 메모리 


| NAS | 12 | 180.0PB / 159.9PiB | 24576GB 


| SAN | 6 | 90.0 PB / 79.9 PiB | 12288GB 


| HA 쌍 |  | 15.0PB / 13.3PiB | 2048.0000 
|===


=== 아이오



==== 온보드 IO

온보드 IO 데이터가 없습니다.



==== 총 IO

|===


| 규약 | 포트 


| 이더넷 100Gbps | 32 


| 이더넷 25Gbps | 64 


| 이더넷 10Gbps | 64 


| FC 32Gbps | 64 


| NVMe/FC 32Gbps | 64 


|  | 0 


| SAS 12Gbps | 64 
|===


==== 관리 포트

|===


| 규약 | 포트 


| 이더넷 1Gbps | 2 


| RS-232 115Kbps | 6 


| USB 12Mbps | 2 
|===


=== 스토리지 네트워킹 지원

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; NAS가 있는 S3; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== 시스템 환경 사양

* 일반적인 전력: 8004 BTU/hr
* 최악의 경우 전력: 9937 BTU/hr
* 무게: 220.5파운드 100.0kg
* 높이: 8U
* 너비: 19인치 IEC 랙 호환(17.7인치 45.0cm)
* 깊이: 28.8인치(케이블 관리 브래킷 포함 시 36.8인치)
* 작동 온도/고도/습도: 최대 3048m(10000피트) 고도에서 10°C ~ 35°C(50°F ~ 95°F), 상대 습도 8% ~ 90%(비응축)
* 비작동 시 온도/습도: -40°C ~ 70°C (-40°F ~ 158°F), 최대 12,192m (40,000ft), 상대 습도 10% ~ 95% (비응축), 원래 용기 기준
* 음향 소음: 공칭 음향 출력(LwAd): 7.4; 음압(LpAm)(주변 관찰자 위치): 65.0 dB




=== 규정 준수

* 인증 EMC/EMI: AMCA, FCC, ICES, KC, 모로코, VCCI
* 인증 안전: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* 인증 안전/EMC/EMI: EAC, UKRSEPRO
* 인증 안전/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* 표준 EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Part 15 Class A, ICES-003, KS C 9832, KS C 9835
* 표준 안전: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252(파트 1)




=== 고가용성

이더넷 기반 베이스보드 관리 컨트롤러(BMC) 및 ONTAP 관리 인터페이스; 중복 핫스왑 가능 컨트롤러; 중복 핫스왑 가능 전원 공급 장치; 외부 선반을 위한 SAS 연결을 통한 SAS 인밴드 관리;
