---
permalink: fas9500/pci_cards_and_risers_replace.html 
sidebar: sidebar 
keywords:  
summary: 입출력 모듈을 교체하려면 특정 작업 순서를 수행해야 합니다. 
---
= I/O 모듈 교체 - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
입출력 모듈을 교체하려면 특정 작업 순서를 수행해야 합니다.

* 이 절차는 시스템에서 지원하는 모든 버전의 ONTAP에서 사용할 수 있습니다.
* 시스템의 다른 모든 구성 요소가 올바르게 작동해야 합니다. 그렇지 않은 경우 기술 지원 부서에 문의해야 합니다.




== 1단계: 장애가 있는 노드를 종료합니다

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

.이 작업에 대해
노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다. 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].

.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
"기백을 기다리는 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===




== 2단계: I/O 모듈을 교체합니다

I/O 모듈을 교체하려면 섀시 내에서 해당 모듈을 찾아 특정 단계를 따르십시오.

. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 대상 I/O 모듈과 연결된 모든 케이블을 뽑습니다.
+
케이블을 어디에 연결했는지 알 수 있도록 케이블에 레이블을 지정해야 합니다.

. 섀시에서 대상 I/O 모듈을 분리합니다.
+
.. 문자 및 번호가 매겨진 캠 버튼을 누릅니다.
+
캠 버튼이 섀시에서 멀어져 있습니다.

.. 캠 래치가 수평 위치에 올 때까지 아래로 돌립니다.
+
I/O 모듈이 섀시에서 분리되어 I/O 슬롯에서 약 1.3cm 정도 이동합니다.

.. 모듈 면의 측면에 있는 당김 탭을 당겨 섀시에서 I/O 모듈을 분리합니다.
+
입출력 모듈이 있던 슬롯을 추적해야 합니다.

+
.애니메이션 - I/O 모듈 제거/설치
video::0903b1f9-187b-4bb8-9548-ae9b0012bb21[panopto]
+
image::../media/drw_9500_remove_PCIe_module.svg[drw 9500 PCIe 모듈을 제거합니다]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[범례 아이콘 01]
 a| 
문자 및 숫자 I/O 캠 래치



 a| 
image::../media/legend_icon_02.svg[범례 아이콘 02]
 a| 
I/O 캠 래치가 완전히 잠금 해제되었습니다

|===


. 입출력 모듈을 따로 보관해 둡니다.
. I/O 모듈이 문자 및 번호가 매겨진 I/O 캠 래치가 I/O 캠 핀과 맞물릴 때까지 I/O 모듈을 슬롯에 부드럽게 밀어 넣은 다음 I/O 캠 래치를 완전히 위로 밀어 모듈을 제자리에 고정합니다.
. 필요에 따라 입출력 모듈을 다시 장착합니다.




== 3단계: I/O 모듈 교체 후 컨트롤러를 재부팅합니다

I/O 모듈을 교체한 후 컨트롤러 모듈을 재부팅해야 합니다.


NOTE: 새 입출력 모듈이 장애가 발생한 모듈과 다른 모델인 경우 먼저 BMC를 재부팅해야 합니다.

.단계
. 교체 모듈이 이전 모듈과 다른 모델인 경우 BMC를 재부팅합니다.
+
.. LOADER 프롬프트에서 advanced privilege mode: priv set advanced로 변경합니다
.. BMC:'s p reboot'를 재부팅합니다


. LOADER 프롬프트에서 bye 노드를 재부팅합니다
+

NOTE: 이렇게 하면 PCIe 카드 및 기타 구성 요소가 다시 초기화되고 노드가 재부팅됩니다.

. 시스템이 10GbE 클러스터 상호 연결과 40GbE NIC 또는 온보드 포트의 데이터 연결을 지원하도록 구성된 경우 유지보수 모드에서 'nicadmin convert' 명령을 사용하여 이러한 포트를 10GbE 연결로 변환합니다.
+

NOTE: 변환을 완료한 후 유지보수 모드를 종료해야 합니다.

. 노드를 정상 작동 상태로 되돌리십시오: 'storage failover 반환 - ofnode impaired_node_name'
. 자동 반환이 비활성화된 경우 'Storage failover modify -node local -auto-반환 true'를 다시 설정합니다




== 4단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
