---
permalink: fas2800/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: FAS2800 시스템의 부트 미디어를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요. 
---
= 자동 부팅 미디어 복구 요구 사항 - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS2800 시스템의 부트 미디어를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요.  여기에는 올바른 교체 부트 미디어를 가지고 있는지 확인하고, 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 결함이 없는지 확인하고, 온보드 키 관리자(OKM) 또는 외부 키 관리자(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.

자동 부팅 미디어 복구 프로세스는 ONTAP 9.17.1 이상에서만 지원됩니다. 스토리지 시스템에서 이전 버전의 ONTAP 실행 중인 경우 link:bootmedia-replace-workflow.html["수동 부팅 복구 절차"] .

[NOTE]
====
NetApp에서는 작업 중인 장치에서 콘솔 로깅을 활성화하고 이 절차를 수행할 때 다음 조치를 취할 것을 강력히 권장합니다.

* 유지 관리 중에도 AutoSupport 기능을 활성화 상태로 유지하십시오. 이렇게 하면 문제가 발생할 경우 NetApp 지원팀에서 진단 정보를 받을 수 있습니다.
* CLI 세션에 대한 세션 로깅을 활성화하십시오. 이렇게 하면 유지보수 윈도우 중에 수행된 모든 명령과 시스템 출력에 대한 완전한 기록이 생성됩니다. 세션 로깅 활성화 방법에 대한 자세한 내용은 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 최적의 연결을 위해 PuTTY를 구성하는 방법"^]을 참조하십시오.


====
* 장애가 발생한 구성 요소를 NetApp에서 제공한 것과 동일한 용량의 교체 FRU 구성 요소로 교체해야 합니다.
* 장애가 발생한 컨트롤러의 e0S 인터페이스(e0M 렌치 포트)에 결함이 없는지 확인하십시오.
+
e0M 포트는 자동 부팅 복구 프로세스 동안 두 컨트롤러 간 통신에 사용됩니다.

* OKM의 경우 클러스터 전체 암호와 백업 데이터가 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.


* 손상된 부트 미디어를 교체할 때는 올바른 컨트롤러에 명령을 적용하는 것이 중요합니다.
+
** _손상된 컨트롤러_는 유지 관리를 수행하고 있는 컨트롤러입니다.
** 건강한 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.




.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["컨트롤러를 종료합니다"]
