---
permalink: fas2800/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas 2800, post, boot, media, okm, nse, nve, onboard key manager, netapp storage encryption, netapp volume encryption 
summary: '환경 변수를 선택한 후에는 Onboard Key Manager\(OKM\), NetApp Storage Encryption\(NSE\), NetApp Volume Encryption\(NVE\)가 활성화된 시스템 관련 단계를 완료해야 합니다.' 
---
= 필요에 따라 OKM, NSE 및 NVE 복원 - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
환경 변수를 선택한 후에는 이 절차의 시작 부분에서 캡처한 설정을 사용하여 온보드 키 관리자(OKM), NetApp 스토리지 암호화(NSE) 또는 NetApp 볼륨 암호화(NVE)가 활성화된 시스템에 대한 특정 단계를 완료해야 합니다.


NOTE: NSE 또는 NVE를 온보드 키 관리자와 함께 사용할 경우 이 절차를 시작할 때 캡처한 설정을 복원해야 합니다.

.단계
. 콘솔 케이블을 대상 컨트롤러에 연결합니다.
. Loader 프롬프트에서 "boot_ontap" 명령을 사용하여 컨트롤러를 부팅합니다.
. 콘솔 출력을 확인합니다.
+
[cols="1,3"]
|===
| 콘솔에 다음이 표시되는 경우... | 그러면... 


 a| 
로그인 프롬프트
 a| 
7단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
.. 파트너 컨트롤러에 로그인합니다.
.. 'storage failover show' 명령을 사용하여 타겟 컨트롤러가 반환될 준비가 되었는지 확인합니다.


|===
. 콘솔 케이블을 파트너 컨트롤러로 이동하여 'storage failover back - fromnode local -only -CFO -aggregate true local' 명령을 사용하여 타겟 컨트롤러 스토리지를 반환하십시오.
+
** 디스크에 오류가 발생하여 명령이 실패하면 장애가 발생한 디스크를 물리적으로 분리하되, 교체 디스크를 받을 때까지 디스크를 슬롯에 그대로 둡니다.
** CIFS 세션이 열려 있어 명령이 실패한 경우 CIFS 세션을 닫는 방법에 대해 고객에게 확인하십시오.
+

NOTE: CIFS를 종료하면 데이터가 손실될 수 있습니다.

** 파트너가 "준비되지 않음" 상태로 인해 명령이 실패하면, NVMEM이 동기화될 때까지 5분 동안 기다립니다.
** NDMP, SnapMirror 또는 SnapVault 프로세스로 인해 명령이 실패하면 프로세스를 해제합니다. 자세한 내용은 해당 문서 센터를 참조하십시오.


. 3분 정도 기다린 후 'storage failover show' 명령으로 페일오버 상태를 확인한다.
. 클러스터 셸 프롬프트에서 "net int show -is -home false" 명령을 입력하여 홈 컨트롤러 및 포트에 없는 논리 인터페이스를 나열합니다.
+
인터페이스가 로 나열되어 있는 경우 `false`에서 이러한 인터페이스를 홈 포트로 되돌립니다 `net int revert -vserver Cluster -lif _nodename_` 명령.

. 콘솔 케이블을 대상 컨트롤러로 옮기고 rsion -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. 클러스터 셸 프롬프트에서 '스토리지 암호화 디스크 표시'를 사용하여 출력을 검토합니다.
. 보안 키-관리자 키 쿼리 명령을 사용하여 키 관리 서버에 저장된 인증 키의 키 ID를 표시합니다.
+
** 'restored' 칼럼이 'yes/true'인 경우, 사용자는 모두 완료되어 교체 프로세스를 완료할 수 있습니다.
** Key Manager type="external" 및 "restored" column=yes/true 이외의 경우 보안 key-manager external restore 명령을 사용하여 인증 키의 키 ID를 복구한다.
+

NOTE: 명령이 실패하면 고객 지원 센터에 문의하십시오.

** Key Manager type="Onboard" 및 "restored" column = yes/true 이외의 경우, 보안 key-manager 온보드 sync 명령을 사용하여 Key Manager 유형을 다시 동기화한다.
+
보안 키 관리자 키 쿼리를 사용하여 모든 인증 키에 대해 "restored" 열 = "yes/true"인지 확인합니다.



. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 'storage failover -fromnode local' 명령을 사용하여 컨트롤러를 반환하십시오.
. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. 을 사용하여 AutoSupport를 비활성화한 경우 복원합니다 `system node autosupport invoke -node * -type all -message MAINT=END`

