---
permalink: fas2800/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas2800, how to recable the system, how to reassign disks 
summary: 스토리지를 다시 설정하고 디스크 재할당을 확인해야 합니다. 
---
= 시스템을 재할당하고 디스크를 재할당합니다. - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
교체 절차를 완료하고 시스템을 전체 작업으로 복원하려면 스토리지를 재가동하고, 디스크 재할당을 확인하고, NetApp Storage Encryption 구성을 복원(필요한 경우)하고, 새 컨트롤러에 대한 라이센스를 설치해야 합니다. 시스템을 전체 작동 상태로 복원하기 전에 일련의 작업을 완료해야 합니다.



== 1단계: 시스템 회수

컨트롤러 모듈의 스토리지 및 네트워크 연결을 확인합니다.

.단계
. 을 사용하여 케이블이 올바른지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Config Advisor를 다운로드하고 설치합니다.
.. 대상 시스템에 대한 정보를 입력한 다음 데이터 수집 을 클릭합니다.
.. 케이블 연결 탭을 클릭한 다음 출력을 확인합니다. 모든 디스크 쉘프가 표시되고 모든 디스크가 출력에 표시되는지 확인하여 찾은 케이블 연결 문제를 해결합니다.
.. 해당 탭을 클릭하여 다른 케이블을 확인한 다음 Config Advisor의 출력을 확인합니다.






== 2단계: 디스크를 재할당합니다

_replacement_controller를 부팅할 때 시스템 ID 변경을 확인한 다음 변경이 구현되었는지 확인해야 합니다.

. replacement_controller가 유지보수 모드("*>" 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. system ID mismatch: boot_ontap로 인해 시스템 ID를 재정의하라는 메시지가 표시되면 _replacement_controller의 LOADER 프롬프트에서 컨트롤러를 부팅하고 y를 입력합니다
. replacement_controller 콘솔에 'Waiting for 반환...' 메시지가 표시될 때까지 기다린 후 정상적인 컨트롤러에서 새 파트너 시스템 ID가 자동으로 지정되었는지 확인합니다. 'storage failover show
+
명령 출력에는 손상된 컨트롤러에서 시스템 ID가 변경되었다는 메시지와 함께 올바른 이전 및 새 ID가 표시되어야 합니다. 다음 예제에서 node2는 교체를 거쳤으며 새 시스템 ID가 151759706입니다.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 정상적인 컨트롤러에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 모든 코어 덤프를 저장합니다. 'system node run-node_local-node-name_partner savecore'
.. 을(를) 기다립니다 `savecore` 반환 명령을 사용하여 반환이 실행되기 전에 명령을 완료합니다.
+
다음 명령을 입력하여 savecore 명령의 진행 상태를 모니터링할 수 있습니다. 'system node run-node_local-node-name_partner savecore -s'

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. 컨트롤러를 다시 제공합니다.
+
.. 정상적인 컨트롤러에서 교체된 컨트롤러의 스토리지를 다시 제공합니다. 'storage failover 반환 - ofnode_replacement_node_name_'
+
replacement_controller가 스토리지를 다시 가져와 부팅을 완료합니다.

+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 y를 입력해야 합니다.

+

IMPORTANT: 기브백이 거부되면 거부권 문제를 해결하십시오. 거부권이 해결되지 않으면 거부권을 무효화할 수 있습니다.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["사용 중인 ONTAP 9 버전에 맞는 고가용성 구성 콘텐츠를 찾아보십시오"]

.. 기브백이 완료된 후 HA 쌍이 정상 작동 중인지, 그리고 테이크오버가 가능한지, 즉 '스토리지 페일오버 표시'인지 확인합니다
+
'storage failover show' 명령의 출력에는 파트너 메시지에서 변경된 시스템 ID가 포함되지 않아야 합니다.



. 디스크가 제대로 할당되었는지 확인합니다. '스토리지 디스크 표시-소유권'
+
_replacement_controller에 속하는 디스크는 새 시스템 ID를 표시해야 합니다. 다음 예에서는 노드 1이 소유한 디스크에 새 시스템 ID 1873775277이 표시됩니다.

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

