---
permalink: fas2800/nvmem-nvram-battery-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, nvmem, battery, shut, down, impaired, controller, controller, system, aggregates, metrocluster, configuration, reinstall 
summary: 시스템에서 NVMEM 배터리를 교체하려면 컨트롤러 모듈을 시스템에서 분리하고, 배터리를 개봉하고, 배터리를 교체하고, 컨트롤러 모듈을 닫고 교체해야 합니다. 
---
= NVMEM 배터리를 교체합니다. - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템에서 NVMEM 배터리를 교체하려면 컨트롤러 모듈을 시스템에서 분리하고, 배터리를 개봉하고, 배터리를 교체하고, 컨트롤러 모듈을 닫고 교체해야 합니다.

시스템의 다른 모든 구성 요소가 제대로 작동해야 합니다. 그렇지 않은 경우 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"].



== 1단계: 손상된 컨트롤러를 종료합니다

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].

.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=_number_of_hours_down_h' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 손상된 컨트롤러가 HA 쌍의 일부인 경우 정상 컨트롤러의 콘솔에서 '스토리지 페일오버 수정-노드 로컬-자동 반환 거짓'을 자동 반환하도록 해제합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
컨트롤러 모듈 제거 로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl+C를 누른 다음 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===




== 2단계: 컨트롤러 모듈을 분리하고 엽니다

컨트롤러 모듈을 분리하고 엽니다.

.단계
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 케이블을 케이블 관리 장치에 연결하는 후크 및 루프 스트랩을 푼 다음, 케이블이 연결된 위치를 추적하면서 컨트롤러 모듈에서 시스템 케이블과 SFP(필요한 경우)를 분리합니다.
+
케이블 관리 장치에 케이블을 남겨 두면 케이블 관리 장치를 다시 설치할 때 케이블이 정리됩니다.

. 컨트롤러 모듈의 왼쪽과 오른쪽에서 케이블 관리 장치를 분리하여 한쪽에 둡니다.
. 캠 핸들의 래치를 눌러 분리될 때까지 캠 핸들을 완전히 열어 컨트롤러 모듈을 중앙판에서 분리한 다음, 양손으로 컨트롤러 모듈을 섀시 밖으로 반쯤 당깁니다.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[2850 drw PCM 제거 IEOPS 694 설치]

. 컨트롤러 모듈 후면에 있는 NVMEM LED를 확인하십시오.  NV 아이콘을 찾습니다.
+
image::../media/drw_hw_nvram_icon.svg[drw HW NVRAM 아이콘]

+

NOTE: 시스템이 "반환 대기 중" 상태이거나 시스템이 제대로 인수되거나 중지되지 않은 경우(커밋되지 않은 데이터) 컨트롤러에서 전원이 꺼지면 면판의 녹색 NV LED가 깜박이기 시작합니다.  손상된 컨트롤러 모듈이 파트너 컨트롤러 모듈에 의해 성공적으로 인계되지 않은 경우 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]

+
** 컨트롤러 모듈을 섀시에서 분리할 때 녹색 NV 상태 LED가 깜박이기 시작하는 경우:
+
*** 컨트롤러가 파트너 컨트롤러 모듈 또는 손상된 컨트롤러가 share_waiting for Giveback_에 의해 완전히 테이크오버되었는지 확인합니다. 깜박이는 LED를 무시하면 되며 손상된 컨트롤러를 섀시에서 제거할 수 있습니다.


** 녹색 NV LED가 꺼져 있는 경우 손상된 컨트롤러를 섀시에서 분리할 수 있습니다.






== 3단계: NVMEM 배터리를 교체합니다

시스템에서 실패한 NVMEM 배터리를 제거하고 새 NVMEM 배터리로 교체합니다.

.단계
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 섀시에서 제어 모듈을 분리합니다.
. 컨트롤러 모듈을 뒤집어 평평하고 안정적인 곳에 놓습니다.
. 컨트롤러 모듈 측면에 있는 파란색 단추를 눌러 덮개를 연 다음 덮개를 컨트롤러 모듈에서 위로 돌려 분리합니다.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[2850 drw 열린 컨트롤러 모듈 덮개 IEOPS 695]

. 컨트롤러 모듈에서 NVMEM 배터리를 찾습니다.
+
.애니메이션 - NV 배터리를 교체합니다
video::592217fb-4868-4294-a559-af4701725598[panopto]
+
image::../media/drw_2850_replace_nvbattery_IEOPS-715.svg[2850 drw 는 nvbattery IEOPS 715를 대체합니다]

+
[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[범례 아이콘 01]
 a| 
배터리 분리 탭



 a| 
image::../media/legend_icon_02.svg[범례 아이콘 02]
 a| 
배터리 전원 커넥터

|===
. 컨트롤러 모듈에서 결함이 있는 배터리를 분리합니다.
+
.. 컨트롤러 모듈 측면에 있는 파란색 버튼을 누릅니다.
.. 고정 브래킷에서 배터리가 분리될 때까지 배터리를 밀어 올린 다음 컨트롤러 모듈에서 배터리를 들어올립니다.
.. 컨트롤러 모듈에서 배터리를 분리합니다


. 교체용 배터리를 포장에서 꺼냅니다.
교체용 배터리를 설치합니다.
+
.. 배터리 플러그를 컨트롤러 모듈의 소켓에 다시 꽂습니다.
+
플러그가 마더보드의 배터리 소켓에 제대로 잠겼는지 확인합니다.

.. 판금 측면의 고정 브래킷에 배터리를 맞춥니다.
.. 전지 래치가 맞물려 측면 벽의 구멍에 끼워질 때까지 전지 팩을 아래로 밉니다.


. 컨트롤러 모듈 덮개를 다시 설치하고 제자리에 고정합니다.




== 4단계: 컨트롤러 모듈을 재설치합니다

컨트롤러 모듈의 구성 요소를 교체한 후 섀시에 다시 설치합니다.

.단계
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 아직 설치하지 않은 경우 컨트롤러 모듈의 덮개를 다시 끼우십시오.
. 컨트롤러 모듈을 뒤집어 섀시의 입구에 맞춥니다.
. 컨트롤러 모듈의 끝을 섀시의 입구에 맞춘 다음 컨트롤러 모듈을 반쯤 조심스럽게 시스템에 밀어 넣습니다.
+

NOTE: 지시가 있을 때까지 컨트롤러 모듈을 섀시에 완전히 삽입하지 마십시오.

. 필요에 따라 시스템을 다시 연결합니다.
+
미디어 컨버터(QSFP 또는 SFP)를 분리한 경우 광섬유 케이블을 사용하는 경우 다시 설치해야 합니다.

. 컨트롤러 모듈 재설치를 완료합니다.
+
.. 캠 핸들을 열린 위치에 둔 상태에서 컨트롤러 모듈이 중앙판과 완전히 맞닿고 완전히 장착될 때까지 단단히 누른 다음 캠 핸들을 잠금 위치로 닫습니다.
+

NOTE: 커넥터가 손상되지 않도록 컨트롤러 모듈을 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

+
컨트롤러가 섀시에 장착되면 바로 부팅이 시작됩니다.

.. 아직 설치하지 않은 경우 케이블 관리 장치를 다시 설치하십시오.
.. 케이블을 후크와 루프 스트랩으로 케이블 관리 장치에 연결합니다.


. 컨트롤러 모듈을 재부팅합니다.
+

NOTE: 부팅 과정에서 다음과 같은 메시지가 표시될 수 있습니다.

+
** 시스템 ID 불일치 및 시스템 ID 재정의를 요청하는 프롬프트 경고.
** HA 구성에서 유지보수 모드로 전환할 때 정상적인 컨트롤러가 계속 작동 중지되는지 확인해야 한다는 프롬프트 경고 메시지가 표시됩니다. 이 메시지에 안전하게 'y'로 응답할 수 있습니다.






== 5단계: 자동 반환 및 자동 지원을 복원합니다

자동 반환 및 AutoSupport 가 비활성화된 경우 복원합니다.

. 를 사용하여 자동 반환 복원 `storage failover modify -node local -auto-giveback true` 명령.
. AutoSupport 유지보수 윈도우가 트리거된 경우 를 사용하여 윈도우를 종료합니다 `system node autosupport invoke -node * -type all -message MAINT=END` 명령.




== 6단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
