---
permalink: asa250/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: asa a250, post boot media replacement steps for okm, nse, and nve 
summary: '환경 변수를 선택한 후에는 Onboard Key Manager\(OKM\), NetApp Storage Encryption\(NSE\), NetApp Volume Encryption\(NVE\)가 활성화된 시스템 관련 단계를 완료해야 합니다.' 
---
= 암호화 복원 - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
교체 부팅 미디어에서 암호화를 복원합니다.

키 관리자 유형에 따라 시스템의 암호화를 복원하기 위한 적절한 단계를 완료하세요.  시스템에서 어떤 키 관리자를 사용하는지 확실하지 않은 경우 부팅 미디어 교체 절차를 시작할 때 캡처한 설정을 확인하세요.

[role="tabbed-block"]
====
.온보드 키 관리자(OKM)
--
ONTAP 부팅 메뉴에서 Onboard Key Manager(OKM) 구성을 복원합니다.

.시작하기 전에
다음 정보를 준비하세요.

* 클러스터 전체 암호가 입력되었습니다. https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["온보드 키 관리 활성화"]
* https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Onboard Key Manager에 대한 백업 정보입니다"]
* 다음을 사용하여 올바른 암호 문구와 백업 데이터를 가지고 있는지 확인하십시오. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["온보드 키 관리 백업 및 클러스터 전체 암호를 확인하는 방법"] 절차


.단계
*손상된 컨트롤러에 관하여:*

. 손상된 컨트롤러에 콘솔 케이블을 연결하세요.
. ONTAP 부팅 메뉴에서 적절한 옵션을 선택합니다.
+
[cols="1a,2a"]
|===
| ONTAP 버전입니다 | 이 옵션을 선택합니다 


 a| 
ONTAP 9.8 이상
 a| 
옵션 10 을 선택합니다.

.부팅 메뉴의 예를 표시합니다
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
=====


 a| 
ONTAP 9.7 이하
 a| 
숨겨진 옵션을 선택합니다 `recover_onboard_keymanager`

.부팅 메뉴의 예를 표시합니다
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
=====
|===
. 메시지가 표시되면 복구 프로세스를 계속할지 확인하세요.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

=====
. 클러스터 전체의 암호를 두 번 입력합니다.
+
암호를 입력하는 동안 콘솔에 아무런 입력도 표시되지 않습니다.

+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

=====
. 백업 정보를 입력하세요:
+
.. 대시를 포함하여 BEGIN BACKUP 줄부터 END BACKUP 줄까지의 전체 내용을 붙여넣습니다.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
=====
.. 입력이 끝나면 Enter 키를 두 번 누르세요.
+
복구 프로세스가 완료되고 다음 메시지가 표시됩니다.

+
`Successfully recovered keymanager secrets.`

+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
=====
+

WARNING: 표시된 출력이 다음과 다른 경우 진행하지 마십시오. `Successfully recovered keymanager secrets` .  오류를 수정하기 위해 문제 해결을 수행하세요.



. 옵션 선택 `1` 부팅 메뉴에서 ONTAP 으로 부팅을 계속합니다.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. 컨트롤러 콘솔에 다음 메시지가 표시되는지 확인하세요.
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

+
*파트너 컨트롤러에서:*

. 손상된 컨트롤러를 돌려주세요:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`

+
*손상된 컨트롤러에 관하여:*

. CFO 집계만으로 부팅한 후 키 관리자를 동기화합니다.
+
`security key-manager onboard sync`

. 메시지가 표시되면 Onboard Key Manager에 대한 클러스터 전체 암호를 입력합니다.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
=====
+

NOTE: 동기화가 성공하면 추가 메시지 없이 클러스터 프롬프트가 반환됩니다.  동기화에 실패하면 클러스터 프롬프트로 돌아가기 전에 오류 메시지가 나타납니다.  오류가 수정되고 동기화가 성공적으로 실행될 때까지 계속 진행하지 마세요.

. 모든 키가 동기화되었는지 확인하세요.
+
`security key-manager key query -restored false`

+
이 명령은 결과를 반환하지 않습니다.  결과가 나타나면 더 이상 결과가 반환되지 않을 때까지 동기화 명령을 반복합니다.

+
*파트너 컨트롤러에서:*

. 손상된 컨트롤러를 돌려주세요:
+
`storage failover giveback -fromnode local`

. 자동 반환을 비활성화한 경우 복원:
+
`storage failover modify -node local -auto-giveback true`

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.외부 키 관리자(EKM)
--
ONTAP 부팅 메뉴에서 외부 키 관리자 구성을 복원합니다.

.시작하기 전에
다른 클러스터 노드나 백업에서 다음 파일을 수집합니다.

* `/cfcard/kmip/servers.cfg`파일 또는 KMIP 서버 주소 및 포트
* `/cfcard/kmip/certs/client.crt`파일(클라이언트 인증서)
* `/cfcard/kmip/certs/client.key`파일(클라이언트 키)
* `/cfcard/kmip/certs/CA.pem`파일(KMIP 서버 CA 인증서)


.단계
*손상된 컨트롤러에 관하여:*

. 손상된 컨트롤러에 콘솔 케이블을 연결하세요.
. 옵션 선택 `11` ONTAP 부팅 메뉴에서.
+
.부팅 메뉴의 예를 표시합니다
[%collapsible]
=====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
=====
. 메시지가 표시되면 필요한 정보를 수집했는지 확인하세요.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
=====
. 메시지가 표시되면 클라이언트 및 서버 정보를 입력합니다.
+
.. BEGIN 및 END 줄을 포함하여 클라이언트 인증서(client.crt) 파일 내용을 입력합니다.
.. BEGIN 및 END 줄을 포함하여 클라이언트 키(client.key) 파일 내용을 입력합니다.
.. BEGIN 및 END 줄을 포함하여 KMIP 서버 CA(CA.pem) 파일 내용을 입력합니다.
.. KMIP 서버 IP 주소를 입력하세요.
.. KMIP 서버 포트를 입력합니다(기본 포트 5696을 사용하려면 Enter를 누릅니다).
+
.예제 보기
[%collapsible]
=====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
=====
+
복구 프로세스가 완료되고 다음 메시지가 표시됩니다.

+
`Successfully recovered keymanager secrets.`

+
.예제 보기
[%collapsible]
=====
....
System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.
....
=====


. 옵션 선택 `1` 부팅 메뉴에서 ONTAP 으로 부팅을 계속합니다.
+
.예제 프롬프트를 표시합니다
[%collapsible]
=====
....

***************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***************************************************************************

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. 자동 반환을 비활성화한 경우 복원:
+
`storage failover modify -node local -auto-giveback true`

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====
.다음 단계
부팅 미디어에서 암호화를 복원한 후 다음을 link:bootmedia-complete-rma.html["결함이 있는 부품을 NetApp로 반환합니다"]수행해야 합니다.
