---
permalink: asa250/overview.html 
sidebar: sidebar 
keywords: ASA A250 specifications, ASA A250 specs, NetApp ASA A250, ASA A250 hardware 
summary: ASA A250 스토리지 시스템의 주요 사양 
---
= ASA A250 의 주요 사양
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음은 ASA A250 의 선택 사양입니다.  방문하다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] ASA A250 사양의 전체 목록은 (HWU)에서 확인하세요.  이 페이지는 단일 고가용성 쌍을 반영합니다.



=== ASA A250 의 주요 사양

플랫폼 구성: ASA A250 100V 단일 섀시 HA 쌍

최대 원시 용량: 0.7344PB

메모리: 128.0000GB

폼 팩터: 2개의 HA 컨트롤러와 24개의 드라이브 슬롯이 있는 2U 섀시

ONTAP 버전: b_startONTAP: 9.16.1P2b_end

PCIe 확장 슬롯: 4개

최소 ONTAP 버전: ONTAP 9.13.1



=== 스케일아웃 최대값

|===


| 유형 | HA 쌍 | 원시 용량 | 최대 메모리 


| NAS |  |  |  


| SAN | 6 | 4.4PB / 3.9PiB | 768GB 


| HA 쌍 |  | 0.7PB / 0.7파이비 | 128.0000 
|===


=== 아이오



==== 온보드 IO

|===


| 규약 | 포트 


| 이더넷 25Gbps | 4 


| 이더넷 10Gbps | 4 
|===


==== 총 IO

|===


| 규약 | 포트 


| 이더넷 100Gbps | 4 


| 이더넷 25Gbps | 12 


| 이더넷 10Gbps | 4 


| FC 32Gbps | 8 


| NVMe/FC 32Gbps | 8 


|  | 0 
|===


==== 관리 포트

|===


| 규약 | 포트 


| 이더넷 1Gbps | 2 


| RS-232 115Kbps | 4 


| USB 12Mbps | 4 
|===


=== 스토리지 네트워킹 지원

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== 시스템 환경 사양

환경 데이터가 없습니다.



=== 규정 준수

* 인증 EMC/EMI: AMCA, FCC, ICES, KC, 모로코, VCCI
* 인증 안전: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* 인증 안전/EMC/EMI: EAC, UKRSEPRO
* 인증 안전/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* 표준 EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Part 15 Class A, ICES-003, KS C 9832, KS C 9835
* 표준 안전: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252(파트 1)




=== 고가용성

이더넷 기반 베이스보드 관리 컨트롤러(BMC) 및 ONTAP 관리 인터페이스; 중복 핫스왑 가능 컨트롤러; 중복 핫스왑 가능 전원 공급 장치; 외부 선반을 위한 SAS 연결을 통한 SAS 인밴드 관리;
