---
permalink: asa-c400/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: asa c400, verify and set HA state,complete the replacement process 
summary: 키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고 장애가 발생한 부품을 NetApp에 반환해야 합니다. 
---
= 복원 및 교체 프로세스 - ASA C400 을 완료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고 장애가 발생한 부품을 NetApp에 반환해야 합니다.



== 1단계: 섀시의 HA 상태를 확인하고 설정합니다

섀시의 HA 상태를 확인하고 필요한 경우 시스템 구성에 맞게 상태를 업데이트해야 합니다.

. 유지보수 모드의 컨트롤러 모듈 중 하나에서 로컬 컨트롤러 모듈 및 섀시의 HA 상태를 "ha-config show"로 표시합니다
+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 섀시에 대해 표시된 시스템 상태가 시스템 구성과 일치하지 않는 경우:
+
.. 섀시의 HA 상태를 "ha-config modify chassis_HA-state_"로 설정합니다
+
HA-STATE_의 값은 다음 중 하나일 수 있습니다.

+
*** 하
*** mcc
*** mcc-2n
*** 'mcip'입니다
*** 비하


.. 설정이 변경되었는지 확인합니다. ha-config show


. 아직 다시 하지 않았다면 나머지 시스템을 다시 정하십시오.
. 시스템 앞면에 베젤을 다시 설치합니다.




== 2단계: 2노드 MetroCluster 구성에서 애그리게이트를 다시 전환합니다

2노드 MetroCluster 구성에서 FRU 교체를 완료한 후에는 MetroCluster 스위치백 작업을 수행할 수 있습니다. 그러면 이전 사이트의 SVM(Sync-Source Storage Virtual Machine)이 활성 상태이고 로컬 디스크 풀에서 데이터를 제공하는 구성을 정상 운영 상태로 되돌릴 수 있습니다.

이 작업은 2노드 MetroCluster 구성에만 적용됩니다.

.단계
. 모든 노드가 "enabled" 상태(MetroCluster node show)에 있는지 확인합니다
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 모든 SVM에서 재동기화가 완료되었는지 확인합니다. 'MetroCluster vserver show'
. 복구 작업에 의해 수행되는 자동 LIF 마이그레이션이 'MetroCluster check lif show'에 성공적으로 완료되었는지 확인합니다
. 정상적인 클러스터에 있는 모든 노드에서 'MetroCluster 스위치백' 명령을 사용하여 스위치백을 수행합니다.
. 스위치백 작업이 완료되었는지 확인합니다. 'MetroCluster show'
+
클러스터가 "대기 중 - 스위치백" 상태에 있으면 스위치백 작업이 여전히 실행 중입니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
클러스터가 '정상' 상태에 있으면 스위치백 작업이 완료됩니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
스위치백을 완료하는 데 시간이 오래 걸리는 경우 MetroCluster config-replication resync resync-status show 명령을 사용하여 진행 중인 기준선의 상태를 확인할 수 있습니다.

. SnapMirror 또는 SnapVault 구성을 다시 설정합니다.




== 3단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
