---
permalink: c30-60/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, prerequisite, replace the controller module 
summary: AFF C30 또는 AFF C60 시스템에서 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다. 
---
= 컨트롤러 교체 요구 사항 - AFF C30 및 AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C30 또는 AFF C60 시스템에서 컨트롤러를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 시스템의 다른 모든 구성 요소가 올바르게 작동하는지 확인하고, 올바른 교체 컨트롤러가 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 작업이 포함됩니다.

컨트롤러 교체 절차에 대한 요구 사항 및 고려 사항을 검토하십시오.



== 요구 사항

* 모든 선반이 올바르게 작동해야 합니다.
* 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러"라고 함).
* 컨트롤러를 동일한 모델 유형의 컨트롤러로 교체해야 합니다. 컨트롤러만 교체하여 시스템을 업그레이드할 수 없습니다.
* 이 절차에서 드라이브나 쉘프를 변경할 수 없습니다.
* 항상 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 캡처해야 합니다.
+
콘솔 출력은 교체 프로세스 중에 발생할 수 있는 문제를 해결하는 데 사용할 수 있는 절차에 대한 기록을 제공합니다.





== 고려 사항

* 이 절차의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 필요한 경우 스토리지 시스템 위치 상태 표시등(파란색)을 켜서 영향을 받는 스토리지 시스템을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
스토리지 시스템에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.



.다음 단계
AFF C30 또는 AFF C60 컨트롤러를 교체하는 데 필요한 요구사항을 검토한 후에는 을link:controller-replace-shutdown.html["손상된 컨트롤러를 종료합니다"](를) 수행해야 합니다.
