---
permalink: a20-30-50/install-prepare.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, prepare installation 
summary: 사이트 준비, 상자 포장 풀기, 포장 명세서와 상자 내용물 비교, 스토리지 시스템 등록을 통해 AFF A20, AFF A30 또는 AFF A50 저장 장치 시스템 설치를 준비합니다. 
---
= 설치 준비 - AFF A20, AFF A30 및 AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사이트 준비, 상자 포장 풀기, 포장 명세서와 상자 내용물 비교, 스토리지 시스템 등록을 통해 AFF A20, AFF A30 또는 AFF A50 저장 장치 시스템 설치를 준비합니다.



== 1단계: 사이트를 준비합니다

스토리지 시스템을 설치하려면 사용하려는 사이트 및 캐비닛 또는 랙이 구성에 맞는 사양을 충족하는지 확인하십시오.

.단계
. 를 사용하여 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 작업장이 기억 장치 시스템의 환경 및 전기 요구 사항을 충족하는지 확인합니다.
. 스토리지 시스템, 셸프 및 모든 스위치를 저장할 수 있는 충분한 캐비닛 또는 랙 공간이 있는지 확인합니다.
+
** 스토리지 시스템의 경우 2U
** NS224 스토리지 쉘프당 2U
** 대부분의 스위치는 1U




. 필요한 네트워크 스위치를 설치합니다.
+
설치 지침 및 호환성 정보는 를 https://docs.netapp.com/us-en/ontap-systems-switches/index.html["스위치 설명서"^] link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 참조하십시오.





== 2단계: 상자의 포장을 풉니다

스토리지 시스템에 사용할 사이트와 캐비닛 또는 랙이 필요한 사양을 충족하는지 확인한 후 모든 상자의 포장을 풀고 내용물을 포장 명세서에 있는 항목과 비교합니다.

.단계
. 모든 상자를 조심스럽게 열고 정리된 방식으로 내용물을 배치합니다.
. 포장을 푼 내용물과 포장 명세서의 목록을 비교합니다.
+

NOTE: 배송 상자 측면의 QR 코드를 스캔하여 포장 목록을 얻을 수 있습니다.

+
다음 항목은 상자에 표시될 수 있는 내용 중 일부입니다.

+
상자에 들어 있는 모든 항목이 포장 명세서의 목록과 일치하는지 확인합니다. 불일치 사항이 있는 경우 추가 조치를 위해 메모하십시오.

+
[cols="12,9,4"]
|===


| * 하드웨어 * | * 케이블 * |  


 a| 
** 베젤
** 수행할 수 있습니다
** 지침이 포함된 레일 키트(옵션)
** 보관 선반(추가 저장 장치를 주문한 경우)

 a| 
** 관리 이더넷 케이블(RJ-45 케이블)
** 네트워크 케이블
** 전원 코드
** 스토리지 케이블(추가 스토리지를 주문한 경우)
** USB-C 직렬 콘솔 케이블

|  
|===




== 3단계: 스토리지 시스템을 등록합니다

사이트가 스토리지 시스템 사양에 대한 요구 사항을 충족하는지 확인하고 주문한 모든 부품이 있는지 확인한 후에는 스토리지 시스템을 등록해야 합니다.

.단계
. 설치할 모든 컨트롤러의 SSN(시스템 일련 번호)을 찾습니다. 일련 번호는 다음 위치에서 찾을 수 있습니다.
. 일련 번호는 다음 위치에서 찾을 수 있습니다.
+
** 포장 명세서
** 확인 이메일에 입력합니다
** 확인할 수 있습니다
+
image::../media/drw_ssn_label.svg[번호 위치를 보여 주는 시스템 일련 번호의 예입니다]



. 로 이동합니다 http://mysupport.netapp.com/["NetApp Support 사이트"^].
. 다음과 같이 스토리지 시스템을 등록해야 하는지 확인합니다.
+
[cols="1a,2a"]
|===
| 귀하의 경우... | 다음 단계를 따르십시오... 


 a| 
더 많은 워크로드 추가)
 a| 
.. 사용자 이름과 암호를 사용하여 로그인합니다.
.. 시스템 * > * 내 시스템 * 을 선택합니다.
.. 새 일련 번호가 나열되어 있는지 확인합니다.
.. 그렇지 않은 경우 새 NetApp 고객에 대한 지침을 따르십시오.




 a| 
신규 NetApp 고객
 a| 
.. 지금 등록 * 을 클릭하고 계정을 만듭니다.
.. 시스템 * > * 시스템 등록 * 을 선택합니다.
.. 스토리지 시스템의 일련 번호 및 요청된 세부 정보를 입력합니다.


등록이 승인되면 필요한 소프트웨어를 다운로드할 수 있습니다. 승인 프로세스는 최대 24시간이 걸릴 수 있습니다.

|===


.다음 단계
스토리지 시스템을 설치할 준비가 되면 link:install-hardware.html["스토리지 시스템용 하드웨어를 설치합니다"]됩니다.
