---
sidebar: sidebar 
permalink: a20-30-50/install-requirements.html 
keywords: aff a20, aff a30, aff a50, install, setup, cautions 
summary: 작업대 및 선반에 필요한 장비 및 인양 예방 조치를 검토합니다. 
---
= 설치 요구 사항 및 고려 사항 - AFF A20, AFF A30 및 AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20, AFF A30 또는 AFF A50 스토리지 시스템에 대한 요구사항과 고려사항을 검토하십시오.



== 설치에 필요한 장비

기억 장치 시스템을 설치하려면 다음과 같은 장비와 도구가 필요합니다.

* 웹 브라우저에 액세스하여 스토리지 시스템을 구성합니다
* 정전기 방전(ESD) 스트랩
* 플래시
* USB/직렬 연결이 있는 랩톱 또는 콘솔
* NS224 스토리지 쉘프 ID를 설정하기 위한 종이 클립 또는 끝이 뾰족한 볼펜
* Phillips #2 드라이버




== 인양 주의 사항

스토리지 시스템 및 쉘프는 무겁습니다. 이러한 품목을 들어 올리거나 이동할 때는 주의를 기울이십시오.



=== 스토리지 시스템 중량입니다

기억 장치 시스템을 옮기거나 들어올릴 때 필요한 예방 조치를 취하십시오.

A20, A30 또는 A50 저장 장치 시스템은 무게가 최대 27.9kg(61.5lbs)입니다. 보관 시스템을 인양하려면 두 사람 또는 유압 리프트를 사용합니다.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20 를 참조하십시오,A30,or an A50 weight caution icon]



=== 선반 무게

선반을 옮기거나 들어올릴 때 필요한 예방 조치를 취하십시오.

NSM100B 모듈이 포함된 NS224 선반의 무게는 최대 25.8kg(56.8파운드)입니다. 선반을 인양하려면 두 사람이 함께 작업하거나 유압식 리프트를 사용하십시오. 선반 무게의 균형을 맞추기 위해 모든 구성 요소를 선반(전면 및 후면 모두)에 보관하십시오.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224(NSM100b 인양 주의 포함]

.관련 정보
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["안전 정보 및 규정 고지"^]


.다음 단계
스토리지 시스템에 대한 설치 요구 사항 및 고려 사항을 검토한 후link:install-prepare.html["설치를 준비합니다"]
