---
permalink: a20-30-50/install-complete.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, prepare installation 
summary: 스위치와 랩톱에 대한 연결만 있는 클러스터 검색을 사용하거나 스토리지 시스템의 컨트롤러에 직접 연결한 다음 관리 스위치에 연결하여 플랫폼 설정 및 구성을 완료합니다. 
---
= AFF A20, AFF A30 및 AFF A50 등 스토리지 시스템 설치 및 구성을 완료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20, AFF A30 또는 AFF A50 스토리지 시스템을 켜면 클러스터 네트워크를 검색하고 ONTAP 클러스터를 설정할 수 있습니다.



== 1단계: 클러스터 정보 수집

아직 수집하지 않은 경우 클러스터 관리 인터페이스 포트 및 IP 주소 등 클러스터를 구성하는 데 필요한 정보를 수집합니다.

클러스터 설정 프로세스 중에 필요한 값을 를 사용하여 https://docs.netapp.com/us-en/ontap/software_setup/index.html["클러스터 설정 워크시트"^] 기록합니다. 기본값이 제공되는 경우 해당 값을 사용하거나 직접 입력할 수 있습니다.



== 2단계: 클러스터 네트워크를 검색합니다

검색 프로세스를 통해 네트워크에서 스토리지 시스템 컨트롤러를 검색할 수 있습니다.

[role="tabbed-block"]
====
.옵션 1: 네트워크 검색이 활성화되었습니다
--
랩톱에서 네트워크 검색을 사용하도록 설정한 경우 자동 클러스터 검색을 사용하여 설정 및 구성을 완료할 수 있습니다.

.단계
. 랩톱을 관리 스위치에 연결하고 네트워크 컴퓨터 및 장치에 액세스합니다.
. 나열된 ONTAP 아이콘을 선택하여 다음을 검색합니다.
+
image::../media/drw_autodiscovery_controler_select_ieops-1849.svg[Windows 파일 탐색기로 컨트롤러를 검색하는 방법]

+
.. 파일 탐색기를 엽니다.
.. 왼쪽 창에서 * 네트워크 * 를 클릭하고 마우스 오른쪽 버튼을 클릭한 후 * 새로 고침 * 을 선택합니다.
.. ONTAP 아이콘을 두 번 클릭하고 화면에 표시된 인증서를 수락합니다.
+

NOTE: xxxxx는 타겟 노드의 스토리지 시스템 일련 번호입니다.



+
System Manager가 열립니다.



--
.옵션 2: 네트워크 검색이 활성화되지 않았습니다
--
랩톱에서 네트워크 검색이 활성화되어 있지 않은 경우 ONTAP CLI(Command Line Interface) 클러스터 설정 마법사를 사용하여 구성 및 설정을 완료합니다.

.시작하기 전에
랩톱이 시리얼 콘솔 포트에 연결되어 있고 컨트롤러 전원이 켜져 있는지 확인합니다. 자세한 내용은 을 link:install-power-hardware.html#step-2-power-on-the-controllers["스토리지 시스템의 전원을 켭니다"] 참조하십시오.

.단계
노드 중 하나에 초기 노드 관리 IP 주소를 할당합니다.

[cols="1,2"]
|===
| 관리 네트워크에 DHCP가 있는 경우... | 그러면... 


 a| 
구성됨
 a| 
새 컨트롤러에 할당된 IP 주소를 기록합니다.



 a| 
구성되지 않았습니다
 a| 
. PuTTY, 터미널 서버 또는 해당 환경에 해당하는 를 사용하여 콘솔 세션을 엽니다.
+

NOTE: PuTTY 구성 방법을 모르는 경우 노트북 또는 콘솔의 온라인 도움말을 확인하십시오.

. 첫 번째 노드의 콘솔에 연결합니다.
+
노드가 부팅된 다음 콘솔에서 클러스터 설정 마법사가 시작됩니다.

. 클러스터 설정 마법사에서 물으면 노드의 관리 IP 주소를 입력합니다.


|===
--
====


== 3단계: 클러스터 구성

NetApp은 System Manager를 사용하여 새 클러스터를 설정할 것을 권장합니다. 설치 지침은 을 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["System Manager를 사용하여 새 클러스터에서 ONTAP를 구성합니다"^] 참조하십시오.

System Manager는 노드 관리 IP 주소 할당, 클러스터 초기화, 로컬 계층 생성, 프로토콜 구성, 연결된 스토리지의 초기 프로비저닝 등 클러스터 설정 및 구성을 위한 간단하고 쉬운 워크플로를 제공합니다.

.다음 단계
클러스터가 초기화되면 을 다운로드하고 실행하여 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] 설정을 확인하십시오.
