---
permalink: c250/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff c250, check onboard encryption keys as needed 
summary: 손상된 컨트롤러를 종료하고 온보드 암호화 키의 상태를 확인하기 전에 손상된 컨트롤러의 상태를 확인하고, 자동 반환을 비활성화하고, 시스템이 실행 중인 ONTAP의 버전을 확인해야 합니다. 
---
= 암호화 키 지원 및 상태 확인 - AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템의 데이터 보안을 유지하려면 부팅 미디어에서 암호화 키 지원 및 상태를 확인해야 합니다. ONTAP 버전이 NVE(NetApp 볼륨 암호화)를 지원하는지 확인하고 컨트롤러를 종료하기 전에 키 관리자가 활성 상태인지 확인합니다.



== 1단계: 사용 중인 ONTAP 버전이 NetApp 볼륨 암호화를 지원하는지 확인합니다

사용 중인 ONTAP 버전이 NetApp 볼륨 암호화(NVE)를 지원하는지 확인하십시오. 이 정보는 올바른 ONTAP 이미지를 다운로드하는 데 중요합니다.

. 다음 명령을 실행하여 ONTAP 버전이 암호화를 지원하는지 확인합니다.
+
`version -v`

+
출력에 포함된 `1Ono-DARE` 경우 NVE는 사용 중인 클러스터 버전에서 지원되지 않습니다.

. NVE가 시스템에서 지원되는지 여부에 따라 다음 작업 중 하나를 수행합니다.
+
** NVE가 지원되는 경우 NetApp 볼륨 암호화로 ONTAP 이미지를 다운로드합니다.
** NVE가 지원되지 않는 경우 NetApp 볼륨 암호화 없이 * ONTAP 이미지 * 를 다운로드하십시오.






== 단계 2: 컨트롤러를 종료해도 안전한지 확인합니다

컨트롤러를 안전하게 종료하려면 먼저 EKM(External Key Manager) 또는 OKM(Onboard Key Manager)이 활성 상태인지 확인합니다. 그런 다음 사용 중인 키 관리자를 확인하고, 적절한 키 정보를 표시하고, 인증 키의 상태에 따라 조치를 취합니다.

. 시스템에서 활성화된 키 관리자를 확인합니다.
+
[cols="1a,2a"]
|===
| ONTAP 버전입니다 | 이 명령을 실행합니다 


 a| 
ONTAP 9.14.1 이상
 a| 
`security key-manager keystore show`

** EKM을 사용하면 `EKM` 이 명령 출력에 표시됩니다.
** OKM을 사용하면 `OKM` 이 명령 출력에 표시됩니다.
** 키 관리자가 설정되어 있지 않으면 `No key manager keystores configured` 명령 출력에 이 표시됩니다.




 a| 
ONTAP 9.13.1 이하
 a| 
`security key-manager show-key-store`

** EKM을 사용하면 `external` 이 명령 출력에 표시됩니다.
** OKM을 사용하면 `onboard` 이 명령 출력에 표시됩니다.
** 키 관리자가 설정되어 있지 않으면 `No key managers configured` 명령 출력에 이 표시됩니다.


|===
. 시스템에 키 관리자가 구성되었는지 여부에 따라 다음 옵션 중 하나를 선택합니다.
+
[role="tabbed-block"]
====
.키 관리자가 구성되지 않았습니다
--
손상된 컨트롤러를 안전하게 종료할 수 있습니다. 로 이동합니다. link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"]

--
.외부 또는 Onboard Key Manager가 구성되었습니다
--
.. 다음 query 명령을 입력하여 키 관리자에 인증 키의 상태를 표시합니다.
+
`security key-manager key query`

.. 키 관리자의 열에 있는 값의 출력을 `Restored` 확인합니다.
+
이 열은 키 관리자에 대한 인증 키(EKM 또는 OKM)가 성공적으로 복원되었는지 여부를 나타냅니다.



--
====


. 시스템에서 External Key Manager 또는 Onboard Key Manager를 사용하는지 여부에 따라 다음 옵션 중 하나를 선택합니다.
+
[role="tabbed-block"]
====
.외부 키 관리자
--
열에 표시되는 출력 값에 따라 `Restored` 적절한 단계를 따릅니다.

[cols="1a,2a"]
|===
| 열의 출력 값 `Restored` | 다음 단계를 따르십시오... 


 a| 
`true`
 a| 
손상된 컨트롤러를 안전하게 종료할 수 있습니다. 로 이동합니다. link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"]



 a| 
을 제외한 모든 항목 `true`
 a| 
.. 다음 명령을 사용하여 외부 키 관리 인증 키를 클러스터의 모든 노드에 복원합니다.
+
`security key-manager external restore`

+
명령이 실패하면 에 문의하십시오. http://mysupport.netapp.com/["NetApp 지원"^]

.. 명령을 입력하여 열에 `true` 모든 인증 키가  `security key-manager key query`표시되는지 확인합니다 `Restored`.
+
모든 인증 키가 있는 경우 `true` 손상된 컨트롤러를 안전하게 종료할 수 있습니다. 로 이동합니다. link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"]



|===
--
.Onboard Key Manager(온보드 키 관리자
--
열에 표시되는 출력 값에 따라 `Restored` 적절한 단계를 따릅니다.

[cols="1a,2a"]
|===
| 열의 출력 값 `Restored` | 다음 단계를 따르십시오... 


 a| 
`true`
 a| 
OKM 정보를 수동으로 백업합니다.

.. 를 입력하여 고급 모드로 `set -priv advanced` 이동한 다음 메시지가 나타나면 를 입력합니다 `Y`.
.. 다음 명령을 입력하여 키 관리 정보를 표시합니다.
+
`security key-manager onboard show-backup`

.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다.
+
OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.

.. 손상된 컨트롤러를 안전하게 종료할 수 있습니다. 로 이동합니다. link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"]




 a| 
을 제외한 모든 항목 `true`
 a| 
.. Onboard security key-manager sync 명령을 입력합니다.
+
`security key-manager onboard sync`

.. 메시지가 표시되면 32자의 영숫자 온보드 키 관리 암호를 입력합니다.
+
암호를 제공할 수 없는 경우 에 문의하십시오 http://mysupport.netapp.com/["NetApp 지원"^].

.. 열에 `true` 모든 인증 키가 표시되는지 `Restored` 확인합니다.
+
`security key-manager key query`

.. 유형이 표시되는지 확인한 `Key Manager` `onboard`다음 OKM 정보를 수동으로 백업합니다.
.. 명령을 입력하여 키 관리 백업 정보를 표시합니다.
+
`security key-manager onboard show-backup`

.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다.
+
OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.

.. 손상된 컨트롤러를 안전하게 종료할 수 있습니다. 로 이동합니다. link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"]


|===
--
====

