---
permalink: c250/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff c250, how to recable the system, how to reassign disks 
summary: 스토리지를 다시 설정하고 디스크 재할당을 확인해야 합니다. 
---
= 시스템을 재할당하고 디스크를 재할당합니다 - AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지를 재설정하고 디스크 재할당을 확인하여 교체 절차를 계속합니다.



== 1단계: 시스템 회수

컨트롤러 모듈의 스토리지 및 네트워크 연결을 확인합니다.

.단계
. 을 사용하여 케이블이 올바른지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Config Advisor를 다운로드하고 설치합니다.
.. 대상 시스템에 대한 정보를 입력한 다음 데이터 수집 을 클릭합니다.
.. 케이블 연결 탭을 클릭한 다음 출력을 확인합니다. 모든 디스크 쉘프가 표시되고 모든 디스크가 출력에 표시되는지 확인하여 찾은 케이블 연결 문제를 해결합니다.
.. 해당 탭을 클릭하여 다른 케이블을 확인한 다음 Config Advisor의 출력을 확인합니다.






== 2단계: 디스크를 재할당합니다

스토리지 시스템이 HA 쌍 내에 있는 경우, 절차 종료 시 기브백이 발생하면 새 컨트롤러 모듈의 시스템 ID가 자동으로 디스크에 할당됩니다. _replacement_controller를 부팅할 때 시스템 ID 변경을 확인한 다음 변경이 구현되었는지 확인해야 합니다.

이 절차는 HA 쌍에서 ONTAP를 실행하는 시스템에만 적용됩니다.

. replacement_controller가 유지보수 모드("*>" 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. system ID mismatch에 의한 시스템 ID 재정의를 묻는 메시지가 나타나면 _replacement_controller의 LOADER 프롬프트에서 컨트롤러를 부팅하고 "y"를 입력합니다.
. replacement_controller 콘솔에 'Waiting for 반환...' 메시지가 표시될 때까지 기다린 후 정상적인 컨트롤러에서 새 파트너 시스템 ID가 자동으로 지정되었는지 확인합니다. 'storage failover show
+
명령 출력에는 손상된 컨트롤러에서 시스템 ID가 변경되었다는 메시지와 함께 올바른 이전 및 새 ID가 표시되어야 합니다. 다음 예제에서 node2는 교체를 거쳤으며 새 시스템 ID가 151759706입니다.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 정상적인 컨트롤러에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 모든 코어 덤프를 저장합니다. 'system node run-node_local-node-name_partner savecore'
.. 반환 명령을 실행하기 전에 'avecore' 명령이 완료될 때까지 기다리십시오.
+
다음 명령을 입력하여 savecore 명령의 진행 상태를 모니터링할 수 있습니다. 'system node run-node_local-node-name_partner savecore -s'

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. 스토리지 시스템에 스토리지 또는 볼륨 암호화가 구성된 경우 온보드 키 관리를 사용하는지 또는 외부 키 관리를 사용하는지 여부에 따라 다음 절차 중 하나를 사용하여 스토리지 또는 볼륨 암호화 기능을 복원해야 합니다.
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["온보드 키 관리 암호화 키를 복원합니다"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["외부 키 관리 암호화 키를 복원합니다"^]


. 컨트롤러를 다시 제공합니다.
+
.. 정상적인 컨트롤러에서 교체된 컨트롤러의 스토리지를 다시 제공합니다. 'storage failover 반환 - ofnode_replacement_node_name_'
+
replacement_controller가 스토리지를 다시 가져와 부팅을 완료합니다.

+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 y를 입력해야 합니다.

+

NOTE: 기브백이 거부되면 거부권을 재정의할 수 있습니다.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["사용 중인 ONTAP 9 버전에 맞는 고가용성 구성 콘텐츠를 찾아보십시오"]

.. 기브백이 완료된 후 HA 쌍이 정상 작동 중인지, 그리고 테이크오버가 가능한지, 즉 '스토리지 페일오버 표시'인지 확인합니다
+
'storage failover show' 명령의 출력에는 파트너 메시지에서 변경된 시스템 ID가 포함되지 않아야 합니다.



. 디스크가 제대로 할당되었는지 확인합니다. '스토리지 디스크 표시-소유권'
+
_replacement_controller에 속하는 디스크는 새 시스템 ID를 표시해야 합니다. 다음 예에서는 노드 1이 소유한 디스크에 새 시스템 ID 1873775277이 표시됩니다.

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. 시스템이 MetroCluster 구성인 경우 컨트롤러 상태 'MetroCluster node show'를 모니터링한다
+
MetroCluster 구성을 정상 상태로 되돌리려면 교체 후 몇 분 정도 걸리며, 이 경우 각 컨트롤러에 구성된 상태가 표시되며 DR 미러링이 활성화되고 정상 모드가 표시됩니다. MetroCluster node show-fields node-systemid 명령 출력은 MetroCluster 구성이 정상 상태로 돌아갈 때까지 이전 시스템 ID를 표시합니다.

. 컨트롤러가 MetroCluster 구성에 있는 경우 MetroCluster 상태에 따라 원래 소유자가 재해 사이트의 컨트롤러인 경우 DR 홈 ID 필드에 디스크의 원래 소유자가 표시되는지 확인합니다.
+
다음 두 조건이 모두 참인 경우 이 작업이 필요합니다.

+
** MetroCluster 구성이 전환 상태입니다.
** replacement_controller는 재해 사이트에 있는 디스크의 현재 소유자입니다.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["4노드 MetroCluster 구성에서 HA 테이크오버 및 MetroCluster 스위치오버 중에 디스크 소유권이 변경됩니다"]



. 시스템이 MetroCluster 구성인 경우 각 컨트롤러가 'MetroCluster node show-fields configuration-state'로 구성되어 있는지 확인합니다
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 각 컨트롤러에 대해 예상되는 볼륨이 'vol show-node-name'인지 확인합니다
. 재부팅 시 자동 테이크오버 기능을 사용하지 않도록 설정한 경우 정상 컨트롤러에서 활성화하십시오. 'storage failover modify -node replacement -node -name -onreboot true'

