---
permalink: asa-r2-a1k/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: ASA A1K 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 
---
= 부팅 미디어 교체 요구 사항 - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A1K 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항을 충족해야 합니다. 여기에는 올바른 교체 부팅 미디어가 있는지 확인, 컨트롤러에 결함 있는 클러스터 포트가 없는지 확인, Onboard Key Manager(OKM) 또는 External Key Manager(EKM) 활성화 여부 확인이 포함됩니다.

다음 요구 사항을 검토하십시오.

* 장애가 발생한 부팅 미디어를 NetApp에서 받은 교체 부팅 미디어로 교체해야 합니다.
* 손상된 컨트롤러에 결함이 있는 클러스터 포트가 없어야 합니다.
* 다음 방법 중 하나를 사용하여 Onboard Key Manger(OKM) 또는 EKM(Eternal Key Manager)이 구성되었는지 확인합니다.
+
** 시스템 관리자에게 OKM 또는 EKM이 설정되어 있는지 물어볼 수 있습니다.
** OKM이 설정되어 있는지 확인하려면 을 `security key-manager onboard show`사용합니다.
** EKM이 활성화되어 있는지 확인하려면 를 `security key-manager external show`사용합니다.


* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.




.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["컨트롤러를 종료합니다"]
