---
permalink: asa-r2-a1k/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa r2 a1k, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: 하드웨어 교체를 완료하고 유지 관리 모드로 부팅한 후에는 교체 컨트롤러의 하위 수준 시스템 구성을 확인하고 필요에 따라 시스템 설정을 재구성합니다. 
---
= 시스템 구성 - ASA A1K을 복원하고 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어 교체를 완료한 후 교체 컨트롤러의 하위 수준 시스템 구성을 확인하고 필요에 따라 시스템 설정을 재구성합니다.



== 1단계: HA 구성 설정 확인

컨트롤러 모듈의 HA 상태를 확인하고 필요한 경우 시스템 구성과 일치하도록 상태를 업데이트해야 합니다.

. 유지보수 모드로 부팅: `boot_ontap maint`
+
.. _부팅 계속?_이 표시되면 를 입력합니다 `y`.
+
시스템 ID mismatch_warning 메시지가 표시되면 를 입력합니다 `y`.



.  `sysconfig -v`표시 내용을 입력하고 캡처합니다.
+

NOTE: _Personality mismatch_가 표시되면 고객 지원에 문의하십시오.

.  `sysconfig -v`출력에서 어댑터 카드 정보를 교체용 컨트롤러의 카드 및 위치와 비교합니다.
. 모든 구성요소가 동일한 상태를 `ha-config show` 표시하는지 확인합니다. `HA`
+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 컨트롤러 모듈의 표시된 시스템 상태가 시스템 구성과 일치하지 않으면 컨트롤러 모듈의 HA 상태를 "ha-config modify controller ha-state"로 설정합니다
+
HA 상태의 값은 다음 중 하나일 수 있습니다.

+
** 하
** `mcc` (지원되지 않음)
** `mccip` (ASA 시스템에서는 지원되지 않음)
** `non-ha` (지원되지 않음)


. 컨트롤러 모듈의 표시된 시스템 상태가 시스템 구성과 일치하지 않으면 컨트롤러 모듈의 HA 상태를 "ha-config modify controller ha-state"로 설정합니다
. 설정이 변경되었는지 확인합니다. ha-config show




== 2단계: 디스크 목록을 확인합니다

. 어댑터가 를 사용하여 모든 디스크에 대한 경로를 나열하는지 `storage show disk -p` 확인합니다.
+
문제가 있는 경우 케이블을 확인하고 케이블을 다시 장착합니다.

. 유지 관리 모드를 `halt` 종료합니다.

