---
permalink: asa-r2-a1k/io-module-add.html 
sidebar: sidebar 
keywords: asa r2 a1k, add I/O module 
summary: ASA A1K 시스템에 I/O 모듈을 추가하여 네트워크 연결을 개선하고 데이터 트래픽 처리 능력을 확장하십시오. 
---
= 입출력 모듈 추가 - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A1K 시스템에 I/O 모듈을 추가하여 네트워크 연결을 개선하고 데이터 트래픽 처리 능력을 확장하십시오.

사용 가능한 빈 슬롯이 있거나 모든 슬롯이 완전히 채워진 경우 ASA A1K 스토리지 시스템에 입출력 모듈을 추가할 수 있습니다. 이 작업에 관하여

필요한 경우 스토리지 시스템 위치 상태 표시등(파란색)을 켜서 영향을 받는 스토리지 시스템을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.

스토리지 시스템의 위치 LED는 각 컨트롤러에 하나씩 2개 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.



== 단계 1: 손상된 컨트롤러 모듈을 종료합니다

손상된 컨트롤러 모듈을 종료하거나 인계합니다.

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

.이 작업에 대해
* SAN 시스템을 사용하는 경우 손상된 컨트롤러 SCSI 블레이드에 대한 이벤트 메시지를 확인해야  `cluster kernel-service show`합니다. priv advanced 모드에서 명령을 실행하면 `cluster kernel-service show` 해당 노드의 노드 이름link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["쿼럼 상태입니다"], 해당 노드의 가용성 상태 및 해당 노드의 작동 상태가 표시됩니다.
+
각 SCSI 블레이드 프로세스는 클러스터의 다른 노드와 함께 쿼럼에 있어야 합니다. 교체를 진행하기 전에 모든 문제를 해결해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].


.단계
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다.

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 자동 환불 비활성화:
+
.. 정상 컨트롤러의 콘솔에서 다음 명령을 입력하세요.
+
`storage failover modify -node _impaired_node_name_ -auto-giveback false`

.. 입력하다 `y` _자동 환불을 비활성화하시겠습니까?_라는 메시지가 표시되면


. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트
 a| 
정상적인 컨트롤러에서 손상된 컨트롤러를 인계하거나 중지합니다.

`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

_-halt true_parameter는 Loader 프롬프트를 표시합니다.

|===




== 2단계: 새 입출력 모듈을 추가합니다

스토리지 시스템에 사용 가능한 슬롯이 있는 경우 사용 가능한 슬롯 중 하나에 새 입출력 모듈을 설치합니다. 모든 슬롯이 사용 중인 경우 기존 입출력 모듈을 제거하여 공간을 확보한 다음 새 입출력 모듈을 설치합니다.

.시작하기 전에
* 에서 새 입출력 모듈이 사용 중인 스토리지 시스템 및 ONTAP 버전과 호환되는지 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 확인하십시오.
* 여러 슬롯을 사용할 수 있는 경우 에서 슬롯 우선 순위를 확인합니다 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 입출력 모듈에 사용할 수 있는 최상의 모듈을 사용하십시오.
* 다른 모든 구성 요소가 제대로 작동하는지 확인합니다.
* NetApp 에서 받은 교체 구성 요소가 있는지 확인하세요.


[role="tabbed-block"]
====
.사용 가능한 슬롯에 입출력 모듈을 추가합니다
--
사용 가능한 슬롯이 있는 스토리지 시스템에 새 입출력 모듈을 추가할 수 있습니다.

.단계
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 케이블 관리 트레이 안쪽에 있는 버튼을 당기고 아래로 돌려 케이블 관리 트레이를 아래로 돌립니다.
. 캐리어에서 타겟 슬롯 블랭킹 모듈을 탈거하십시오.
+
.. 대상 슬롯에서 블랭킹 모듈의 캠 래치를 누르십시오.
.. 캠 래치를 모듈에서 최대한 멀리 돌립니다.
.. 캠 레버 입구에 손가락을 넣고 엔클로저 밖으로 모듈을 당겨 엔클로저에서 모듈을 분리합니다.


. 입출력 모듈을 설치합니다.
+
.. I/O 모듈을 인클로저 슬롯 입구의 가장자리에 맞춥니다.
.. 모듈을 인클로저 끝까지 슬롯에 부드럽게 밀어 넣은 다음 캠 래치를 위로 끝까지 돌려 모듈을 제자리에 잠급니다.


. 지정된 장치에 입출력 모듈을 케이블로 연결합니다.
+

NOTE: 사용하지 않는 I/O 슬롯에 열 문제가 발생하지 않도록 보호물이 설치되어 있는지 확인합니다.

. 케이블 관리 트레이를 닫힘 위치까지 돌립니다.
. Loader 프롬프트에서 노드를 재부팅합니다.
+
`bye`

+

NOTE: 그러면 I/O 모듈 및 기타 구성 요소가 다시 초기화되고 노드가 재부팅됩니다.

. 파트너 컨트롤러에서 컨트롤러를 반납합니다.
+
`storage failover giveback -ofnode target_node_name`

. 컨트롤러 B에 대해 이 단계를 반복합니다
. 정상 상태의 노드에서 자동 반환을 해제한 경우 복원합니다.
+
`storage failover modify -node local -auto-giveback _true_`

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.완전히 채워진 시스템에 입출력 모듈을 추가합니다
--
기존 입출력 모듈을 제거하고 새 입출력 모듈을 설치하여 완전히 채워진 시스템에 입출력 모듈을 추가할 수 있습니다.

.이 작업에 대해
완전히 채워진 시스템에 새 입출력 모듈을 추가하기 위한 다음 시나리오를 이해해야 합니다.

[cols="1,2"]
|===
| 시나리오 | 작업이 필요합니다 


 a| 
NIC-NIC(동일한 포트 수)
 a| 
LIF는 컨트롤러 모듈이 종료되면 자동으로 마이그레이션됩니다.



 a| 
NIC-NIC(포트 수가 다름)
 a| 
선택한 LIF를 다른 홈 포트에 영구적으로 재할당합니다. 자세한 내용은 을 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF 마이그레이션"^] 참조하십시오.



 a| 
스토리지 입출력 모듈에 대한 NIC
 a| 
에 설명된 대로 System Manager를 사용하여 LIF를 다른 홈 포트로 영구적으로 마이그레이션합니다 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF 마이그레이션"^].

|===
.단계
. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 대상 I/O 모듈의 케이블을 뽑습니다.
. 케이블 관리 트레이 안쪽에 있는 버튼을 당기고 아래로 돌려 케이블 관리 트레이를 아래로 돌립니다.
. 섀시에서 대상 I/O 모듈을 분리합니다.
+
.. 캠 래치 버튼을 누릅니다.
.. 캠 래치를 모듈에서 최대한 멀리 돌립니다.
.. 캠 레버 입구에 손가락을 넣고 엔클로저 밖으로 모듈을 당겨 엔클로저에서 모듈을 분리합니다.
+
입출력 모듈이 있던 슬롯을 추적해야 합니다.



. I/O 모듈을 엔클로저의 대상 슬롯에 설치합니다.
+
.. 모듈을 인클로저 슬롯 입구의 가장자리에 맞춥니다.
.. 모듈을 인클로저 끝까지 슬롯에 부드럽게 밀어 넣은 다음 캠 래치를 위로 끝까지 돌려 모듈을 제자리에 잠급니다.


. 지정된 장치에 입출력 모듈을 케이블로 연결합니다.
. 제거 및 설치 단계를 반복하여 컨트롤러의 추가 모듈을 교체합니다.
. 케이블 관리 트레이를 닫힘 위치까지 돌립니다.
. LOADER 프롬프트에서 컨트롤러를 재부팅합니다. _ bye _
+
이렇게 하면 PCIe 카드 및 기타 구성 요소가 다시 초기화되고 노드가 재부팅됩니다.

+

NOTE: 재부팅 중 문제가 발생하는 경우 를 참조하십시오 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["Burt 1494308 - I/O 모듈 교체 중에 환경 종료가 트리거될 수 있습니다"]

. 파트너 컨트롤러에서 컨트롤러를 반납합니다.
+
`storage failover giveback -ofnode target_node_name`

. 비활성화된 경우 자동 반환 활성화:
+
`storage failover modify -node local -auto-giveback true`

. 다음 중 하나를 수행합니다.
+
** NIC 입출력 모듈을 제거하고 새 NIC 입출력 모듈을 설치한 경우 각 포트에 대해 다음 네트워크 명령을 사용하십시오.
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** NIC 입출력 모듈을 제거하고 스토리지 입출력 모듈을 설치한 경우 에 설명된 대로 NS224 셸프를 설치하고 link:../ns224/hot-add-shelf-overview.html["핫 애드 워크플로우"]연결합니다.


. 컨트롤러 B에 대해 이 단계를 반복합니다


--
====