= 


ONTAP를 실행하는 2노드 MetroCluster 구성에서는 시스템을 정상 운영 상태로 되돌리기 전에 디스크를 새 컨트롤러의 시스템 ID로 수동으로 재할당해야 합니다.

이 절차는 ONTAP를 실행하는 2노드 MetroCluster 구성의 시스템에만 적용됩니다.

이 절차에서 올바른 노드에 대한 명령을 실행해야 합니다.

* impaired_node는 유지 관리를 수행하는 노드입니다.
* replacement_node는 이 절차의 일부로 손상된 노드를 교체한 새 노드입니다.
* healthy_node는 손상된 노드의 DR 파트너입니다.


.단계
. 아직 재부팅하지 않았다면 _replacement_node를 재부팅하고 "Ctrl-C"를 입력하여 부팅 프로세스를 중단한 다음 표시된 메뉴에서 유지보수 모드로 부팅하는 옵션을 선택하십시오.
+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 Y를 입력해야 합니다.

. 정상 노드인 MetroCluster node show-fields node-systemid, dr-partner-systemid에서 기존 시스템 ID를 봅니다
+
이 예에서 Node_B_1은 이전 시스템 ID가 11807329인 이전 노드입니다.

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. 손상된 노드의 유지보수 모드 프롬프트에서 새 시스템 ID를 확인합니다. "디스크 쇼"
+
이 예에서 새 시스템 ID는 118065481입니다.

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. disk show 명령인 'disk reassign-s old system ID'에서 얻은 시스템 ID 정보를 사용하여 디스크 소유권(FAS 시스템의 경우) 또는 LUN 소유권(FlexArray 시스템의 경우)을 재할당합니다
+
위의 예시에서 명령어의 내용은 '디스크 재할당-s 118073209'이다

+
계속하라는 메시지가 나타나면 Y로 응답할 수 있습니다.

. 디스크(또는 FlexArray LUN)가 올바르게 할당되었는지 확인합니다. disk show-a입니다
+
replacement_node에 속한 디스크에 _replacement_node의 새 시스템 ID가 표시되는지 확인합니다. 다음 예에서는 system-1에서 소유한 디스크에 새 시스템 ID 118065481이 표시됩니다.

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. 정상 노드에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 코어 덤프가 저장되었는지 확인합니다. 'system node run-node_local-node-name_partner savecore'
+
명령 출력에 savecore가 진행 중임을 나타내는 경우 savecore가 완료될 때까지 기다린 다음 반환 명령을 실행합니다. 'system node run-node_local-node-name_partner savecore -s command'를 사용하여 savecore의 진행률을 모니터링할 수 있습니다.</info>

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. replacement_node가 유지보수 모드(*> 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. replacement_node: boot_ontap를 부팅합니다
. replacement_node가 완전히 부팅된 후 스위치백(MetroCluster 스위치백)을 수행합니다
. MetroCluster 설정 'MetroCluster node show-fields configuration-state'를 확인한다
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Data ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 두 클러스터에 대한 상태 경고 '시스템 상태 알림 표시'를 확인합니다
.. MetroCluster가 구성되어 있고 'MetroCluster show'(정상 모드)로 설정되어 있는지 확인합니다
.. 'MetroCluster check run'이라는 MetroCluster check을 수행한다
.. MetroCluster 체크 표시 결과를 MetroCluster check show로 출력한다
.. Config Advisor를 실행합니다. NetApp Support 사이트 의 Config Advisor 페이지로 이동합니다 http://support.netapp.com/NOW/download/tools/config_advisor/["support.netapp.com/NOW/download/tools/config_advisor/"].
+
Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.



. 스위치오버 작업 시뮬레이션:
+
.. 노드 프롬프트에서 고급 권한 레벨 'Set-Privilege Advanced'로 변경합니다
+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 "y"로 응답해야 합니다.

.. simulate parameter: MetroCluster switchover-simulate로 스위치백 동작을 수행한다
.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다



