= 1단계: 시스템 시간을 설정하고 확인합니다
:allow-uri-read: 


하드웨어 교체를 완료한 후, 교체 컨트롤러의 하위 수준 시스템 구성을 확인하고 필요에 따라 시스템 설정을 재구성합니다.



== 1단계: 시스템 시간을 설정하고 확인합니다

교체 컨트롤러 모듈의 시간과 날짜를 HA 쌍의 정상 컨트롤러 모듈 또는 독립형 구성의 안정적인 시간 서버와 확인해야 합니다. 시간과 날짜가 일치하지 않으면 시간 차이로 인해 클라이언트가 중단되는 것을 방지하기 위해 교체 컨트롤러 모듈에서 해당 날짜와 시간을 재설정해야 합니다.

.이 작업에 대해
올바른 시스템에 다음 단계에 있는 명령을 적용하는 것이 중요합니다.

* replacement_node는 이 절차의 일부로 손상된 노드를 교체한 새 노드입니다.
* healthy_node는 _replacement_node의 HA 파트너입니다.


.단계
. refacement_node가 LOADER 프롬프트에 있지 않으면 시스템을 LOADER 프롬프트로 중단합니다.
. Healthy_node에서 시스템 시간을 확인합니다. `cluster date show`
+
날짜와 시간은 구성된 시간대를 기준으로 합니다.

. LOADER 프롬프트에서, _replacement_node:sHow date의 날짜와 시간을 확인하십시오
+
날짜 및 시간은 GMT로 제공됩니다.

. 필요한 경우 교체 노드의 날짜(GMT)를 'SET DATE_MM/dd/yyyy_'로 설정합니다
. 필요한 경우 교체 노드의 시간을 GMT 단위로 'SET TIME_hh:mm:ss_'로 설정합니다
. LOADER 프롬프트에서 _replacement_node의 날짜 및 시간을 확인합니다. `date`
+
날짜 및 시간은 GMT로 제공됩니다.





== 2단계: 컨트롤러의 HA 상태를 확인하고 설정합니다

컨트롤러 모듈의 HA 상태를 확인하고 필요한 경우 시스템 구성과 일치하도록 상태를 업데이트해야 합니다.

. 교체 컨트롤러 모듈의 유지보수 모드에서 모든 구성 요소가 동일한 'HA' 상태 즉, ha-config show를 표시하는지 확인합니다
+
[cols="1,2"]
|===
| 시스템이 다음 상태인 경우: | 모든 구성요소의 HA 상태는... 


 a| 
HA 쌍
 a| 
HA



 a| 
4개 이상의 노드로 구성된 MetroCluster FC 구성
 a| 
MCC



 a| 
MetroCluster IP 구성
 a| 
mcip

|===
. 컨트롤러 모듈의 표시된 시스템 상태가 시스템 구성과 일치하지 않으면 컨트롤러 모듈의 HA 상태를 "ha-config modify controller_ha-state_"로 설정하십시오
. 섀시의 표시된 시스템 상태가 시스템 구성과 일치하지 않으면 섀시의 HA 상태를 "ha-config modify chassis_ha-state_"로 설정합니다

