= ONTAP 9.15 이상을 실행하는 시스템에서 NVE 또는 NSE를 확인하십시오
:allow-uri-read: 


손상된 컨트롤러를 종료하고 온보드 암호화 키의 상태를 확인하기 전에 손상된 컨트롤러의 상태를 확인하고, 자동 반환을 비활성화하고, 실행 중인 ONTAP 버전을 확인해야 합니다.

노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].



== ONTAP 9.15 이상을 실행하는 시스템에서 NVE 또는 NSE를 확인하십시오

손상된 컨트롤러를 종료하기 전에 시스템에 보안 키 관리자가 활성화되어 있는지 또는 암호화된 디스크가 있는지 확인해야 합니다.



== 보안 키 관리자 구성을 확인합니다

.단계
. 키 관리자가 _security key-manager keystore show_command를 사용하여 활성 상태인지 확인합니다. 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/ontap-cli/security-key-manager-keystore-show.html["보안 키 관리자 keystore show man page"^]
+

NOTE: 추가 키 관리자 유형이 있을 수 있습니다. 형식은 `KMIP` `AKV`, 및 `GCP`입니다. 이러한 유형을 확인하는 프로세스는 확인 `external` 또는 `onboard` 키 관리자 유형과 동일합니다.

+
** 출력이 표시되지 않으면 로 link:bootmedia-shutdown.html["손상된 컨트롤러를 종료합니다"] 이동하여 손상된 노드를 종료합니다.
** 명령에 출력이 표시되면 시스템이 활성 상태이므로 `security key-manager` 유형 및 상태를 표시해야 `Key Manager` 합니다.


. security key -manager key query_command 를 사용하여 active 에 대한 정보를 `Key Manager` 표시합니다.
+
** 유형이 표시되고 열이 표시되면 `Key Manager` `external` `Restored` `true`손상된 컨트롤러를 종료해도 안전합니다.
** 형식이 표시되고 열이 표시되면 `Key Manager` `onboard` `Restored` `true`몇 가지 추가 단계를 완료해야 합니다.
** 형식이 표시되고 열에 이 이외의 내용이 표시되면 `Key Manager` `external` `Restored` `true`몇 가지 추가 단계를 완료해야 합니다.
** 형식이 표시되고 열에 이 이외의 내용이 표시되면 `Key Manager` `onboard` `Restored` `true`몇 가지 추가 단계를 완료해야 합니다.


. 유형이 표시되고 열이 표시되면 `Key Manager` `onboard` `Restored` `true`OKM 정보를 수동으로 백업합니다.
+
.. 계속 진행하라는 메시지가 나타나면 Enter 키를 `y` 누릅니다. `set -priv advanced`
.. 명령을 입력하여 키 관리 정보를 표시합니다. _security key-manager onboard show-backup_
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 손상된 컨트롤러를 안전하게 종료할 수 있습니다.


. 형식이 표시되고 열에 다음 이외의 내용이 표시되는 경우 `Key Manager` `onboard` `Restored` `true`:
+
.. Onboard security key-manager sync command:_security key-manager Onboard sync _ 를 입력합니다
+

NOTE: 프롬프트에서 32자 영숫자 온보드 키 관리 암호를 입력합니다. 암호를 제공할 수 없는 경우 NetApp 지원에 문의하십시오. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 열에 모든 인증 키가 표시되는지 `Restored` `true` 확인합니다. `security key-manager key query`
.. 유형이 표시되는지 확인한 `Key Manager` `onboard`다음 OKM 정보를 수동으로 백업합니다.
.. 명령을 입력하여 키 관리 백업 정보를 표시합니다. _security key-manager onboard show-backup_
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 컨트롤러를 안전하게 종료할 수 있습니다.


. 형식이 표시되고 열에 다음 이외의 내용이 표시되는 경우 `Key Manager` `external` `Restored` `true`:
+
.. 외부 키 관리 인증 키를 클러스터의 모든 노드에 복원: '보안 키 관리자 외부 복원
+
명령이 실패하면 에서 NetApp 지원 팀에 문의하십시오. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 모든 인증 키에 대해 _ security key - manager key query _ 가 표시되는지 `Restored` `true` 확인합니다
.. 손상된 컨트롤러를 안전하게 종료할 수 있습니다.



