= 1단계: 컨트롤러 모듈을 분리합니다
:allow-uri-read: 


하드 드라이브 및 컨트롤러 모듈을 손상된 섀시에서 새 섀시로 이동하고 손상된 섀시를 손상된 섀시와 동일한 모델의 새 섀시로 교체합니다.



== 1단계: 컨트롤러 모듈을 분리합니다

컨트롤러 모듈을 교체하거나 컨트롤러 모듈 내부에 있는 구성요소를 교체할 때 섀시에서 컨트롤러 모듈을 분리해야 합니다.

. 섀시 앞면에서 엄지 손가락으로 각 드라이브를 단단히 눌러 정지가 느껴질 때까지 밀어넣습니다. 이렇게 하면 드라이브가 섀시 중앙판에 단단히 고정됩니다.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[시트 디스크 드라이브]

. 장애가 있는 컨트롤러 모듈 후면의 슬롯 4/5에 있는 상태 LED가 꺼져 있는지 황색 NVRAM을 확인합니다. NV 아이콘을 찾습니다.
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[NVRAM 주의 및 상태 LED 위치 그래픽]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["설명선 번호 1, 너비 = 30px"]
 a| 
NVRAM 상태 LED



 a| 
image:../media/legend_icon_02.svg["설명선 번호 1, 너비 = 30px"]
 a| 
NVRAM 주의 LED

|===
+

NOTE: NVRAM 상태 LED가 깜박이는 경우 컨트롤러 모듈이 올바르게 전환되지 않았거나 중지되었음을 의미할 수 있습니다(커밋되지 않은 데이터). 손상된 컨트롤러 모듈이 파트너 컨트롤러 모듈에 의해 성공적으로 인수되지 않은 경우 이 절차를 계속하기 전에 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"] .

+
손상된 컨트롤러 모듈에서 NVRAM 상태 LED의 일반적인 동작은 다음과 같습니다.

+
** 컨트롤러 모듈에서 전원이 제거되고 스토리지 시스템이 "반환 대기 중" 상태이거나 컨트롤러 모듈이 테이크오버되거나 제대로 중지되지 않은 경우(커밋되지 않은 데이터) NVRAM 상태 LED가 깜박입니다.
** 컨트롤러 모듈이 섀시에서 분리되면 NVRAM 상태 LED가 깜박이며 컨트롤러 모듈이 제대로 전환되지 않거나 정지될 수 있습니다(커밋되지 않은 데이터). 컨트롤러 모듈이 파트너 컨트롤러 모듈이나 손상된 컨트롤러 모듈에 의해 완전히 테이크오버되었는지 확인합니다. `waiting for giveback` 그런 다음 깜박이는 LED를 무시할 수 있으며 컨트롤러 모듈을 섀시에서 분리할 수 있습니다.


. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 컨트롤러 모듈 전원 공급 장치(PSU)에서 컨트롤러 모듈 전원 공급 장치 케이블을 뽑습니다.
+

NOTE: 시스템에 DC 전원이 있는 경우 PSU에서 전원 블록을 분리합니다.

. 컨트롤러 모듈에서 시스템 케이블과 SFP 및 QSFP 모듈(필요한 경우)을 뽑아 케이블이 연결된 위치를 추적합니다.
+
케이블 관리 장치에 케이블을 남겨 두면 케이블 관리 장치를 다시 설치할 때 케이블이 정리됩니다.

. 컨트롤러 모듈에서 케이블 관리 장치를 분리합니다.
. 양쪽 잠금 래치를 아래로 누른 다음 두 래치를 동시에 아래로 돌립니다.
+
컨트롤러 모듈이 섀시에서 약간 꺼냅니다.

+
image::../media/drw_a70-90_pcm_remove_replace_ieops-1365.svg[컨트롤러 분리 그래픽]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["설명선 번호 1, 너비 = 30px"]
| 잠금 래치 


 a| 
image:../media/legend_icon_02.svg["설명선 번호 2, 너비 = 30px"]
 a| 
잠금 핀

|===
. 컨트롤러 모듈을 섀시에서 밀어 꺼내고 평평하고 안정적인 표면에 놓습니다.
+
컨트롤러 모듈 하단을 섀시 밖으로 밀어낼 때 지지하는지 확인합니다.

. 섀시의 다른 컨트롤러 모듈에 대해 이 단계를 반복합니다.




== 2단계: 드라이브를 새 섀시로 이동합니다

이전 섀시의 각 베이 입구에서 새 섀시의 동일한 베이 입구로 드라이브를 이동해야 합니다.

. 시스템 전면에서 베젤을 조심스럽게 분리합니다.
. 드라이브 분리:
+
.. LED 아래에 있는 캐리어 면의 상단에 있는 분리 단추를 누릅니다.
.. 캠 핸들을 완전히 열린 위치로 당겨 중앙판에서 드라이브를 분리한 다음 드라이브를 섀시에서 조심스럽게 밀어 꺼냅니다.
+
섀시에서 드라이브를 분리하여 섀시에서 밀어냅니다.

+

NOTE: 드라이브를 분리할 때는 항상 두 손을 사용하여 무게를 지탱하십시오.

+

NOTE: 드라이브는 충격에 약합니다. 손상을 방지하기 위해 가능한 한 적게 취급하십시오.



. 각 드라이브의 드라이브 베이를 추적하고 정전기가 없는 카트 또는 테이블에 드라이브를 따로 둡니다.




== 3단계: 장비 랙 또는 시스템 캐비닛 내에서 섀시를 교체합니다

교체 섀시를 설치하려면 먼저 장비 랙 또는 시스템 캐비닛에서 기존 섀시를 분리해야 합니다.

. 섀시 장착 지점에서 나사를 분리합니다.
. 두 사람이 있는 상태에서 이전 섀시를 시스템 캐비닛 또는 장비 랙의 랙 레일에서 밀어 낸 다음 한쪽에 둡니다.
. 시스템 캐비닛 또는 장비 랙의 랙 레일에 섀시를 부착하여 두 사람이 교체용 섀시를 장비 랙 또는 시스템 캐비닛에 설치합니다.
. 섀시를 장비 랙 또는 시스템 캐비닛에 완전히 밀어 넣습니다.
. 이전 섀시에서 분리한 나사를 사용하여 섀시의 전면을 장비 랙 또는 시스템 캐비닛에 고정합니다.
. 이전 섀시의 드라이브를 교체용 섀시에 설치합니다.
+
.. 이전 섀시의 드라이브를 새 섀시의 동일한 베이 구멍에 맞춥니다.


. 드라이브를 섀시 안으로 부드럽게 밀어 넣습니다.
+
캠 핸들이 체결되어 위쪽으로 회전합니다.

+
.. 드라이브를 섀시 안으로 끝까지 밀어 넣은 다음 캠 핸들을 위로 밀어 드라이브 캐리어에 대고 잠급니다.
+
캠 핸들이 드라이브 캐리어 전면과 올바르게 정렬되도록 캠 핸들을 천천히 닫아야 합니다. 보안 상태가 되면 딸깍 소리가 납니다.

.. 시스템의 나머지 드라이브에 대해 이 과정을 반복합니다.


. 아직 설치하지 않은 경우 베젤을 설치합니다.




== 4단계: 컨트롤러 모듈을 다시 설치합니다

컨트롤러 모듈을 다시 설치하고 재부팅합니다.

. 공기 덕트를 끝까지 돌려 완전히 닫혔는지 확인합니다.
+
컨트롤러 모듈 판금과 수평을 이루어야 합니다.

. 컨트롤러 모듈의 끝을 섀시의 입구에 맞춘 다음 컨트롤러 모듈을 반쯤 조심스럽게 시스템에 밀어 넣습니다.
+

NOTE: 지시가 있을 때까지 컨트롤러 모듈을 섀시에 완전히 삽입하지 마십시오.

. 필요에 따라 시스템을 다시 연결합니다.
+
트랜시버(QSFP 또는 SFP)를 제거한 경우 광섬유 케이블을 사용하는 경우 트랜시버를 다시 설치해야 합니다.

. 컨트롤러 모듈 재설치를 완료합니다.
+
.. 컨트롤러 모듈이 중앙판과 만나 완전히 장착될 때까지 섀시 안으로 단단히 밀어 넣습니다.
+
컨트롤러 모듈이 완전히 장착되면 잠금 래치가 상승합니다.



+

NOTE: 커넥터가 손상되지 않도록 컨트롤러 모듈을 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

+
.. 잠금 래치를 위쪽으로 돌려 잠금 위치에 놓습니다.


. 전원 코드를 전원 공급 장치에 연결합니다.
+

NOTE: DC 전원 공급 장치가 있는 경우 컨트롤러 모듈이 섀시에 완전히 장착된 후 전원 공급 장치에 전원 블록을 다시 연결합니다.

+
전원이 복원되면 컨트롤러 모듈이 부팅됩니다. LOADER 프롬프트로 부팅되는 경우 명령을 사용하여 컨트롤러를 `boot_ontap` 재부팅합니다.

. 'storage failover modify -node local -auto-반환 true' 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 기능을 복구합니다.
. AutoSupport가 설정된 경우 명령을 사용하여 자동 케이스 생성을 복원/억제 `system node autosupport invoke -node * -type all -message MAINT=END` 해제합니다.
. 이전 단계를 반복하여 새 섀시에 두 번째 컨트롤러를 설치합니다.

