= 1단계: 손상된 컨트롤러를 종료합니다
:allow-uri-read: 


이 절차를 사용하여 장애가 발생한 입출력 모듈을 교체하십시오.

* 스토리지 시스템에서 지원하는 모든 ONTAP 버전에 이 절차를 사용할 수 있습니다.
* 스토리지 시스템의 다른 모든 구성 요소가 제대로 작동해야 합니다. 그렇지 않은 경우 기술 지원 부서에 문의해야 합니다.




== 1단계: 손상된 컨트롤러를 종료합니다

다음 옵션 중 하나를 사용하여 컨트롤러를 종료하거나 손상된 컨트롤러를 인수합니다.

[role="tabbed-block"]
====
.옵션 1: 대부분의 시스템
--
손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

.이 작업에 대해
* SAN 시스템을 사용하는 경우 손상된 컨트롤러 SCSI 블레이드에 대한 이벤트 메시지를 확인해야  `cluster kernel-service show`합니다.  `cluster kernel-service show`priv advanced 모드에서 명령을 실행하면 노드 이름, 해당 노드의 쿼럼 상태, 해당 노드의 가용성 상태 및 해당 노드의 작동 상태가 표시됩니다.
+
각 SCSI 블레이드 프로세스는 클러스터의 다른 노드와 함께 쿼럼에 있어야 합니다. 교체를 진행하기 전에 모든 문제를 해결해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].


.단계
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다. `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다. `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
+

NOTE: 자동 반환을 비활성화하시겠습니까?_가 표시되면 'y'를 입력합니다.

. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===


--
.옵션 2: 컨트롤러가 MetroCluster에 있습니다
--
손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].
* MetroCluster 설정이 있는 경우 MetroCluster 설정 상태가 구성되어 있고 해당 노드가 설정 및 정상 상태('MetroCluster node show')인지 확인해야 합니다.


.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===


--
====


== 2단계: 장애가 발생한 입출력 모듈을 교체합니다

I/O 모듈을 교체하려면 컨트롤러 모듈 내에서 해당 모듈을 찾아 특정 단계의 순서를 따릅니다.

. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 대상 I/O 모듈의 케이블을 뽑습니다.
+
케이블의 출처를 알 수 있도록 케이블에 레이블을 붙여야 합니다.

. 케이블 관리 트레이 안쪽에 있는 버튼을 당기고 아래로 돌려 케이블 관리 트레이를 아래로 돌립니다.
. 컨트롤러 모듈에서 I/O 모듈을 분리합니다.
+

NOTE: 다음 그림에서는 수평 및 수직 I/O 모듈 분리를 보여 줍니다. 일반적으로 하나의 입출력 모듈만 제거합니다.

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[입출력 모듈을 분리합니다]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["설명선 번호 1, 너비 = 30px"]
 a| 
캠 잠금 버튼

|===
+
.. 캠 래치 버튼을 누릅니다.
+
캠 래치가 컨트롤러 모듈에서 멀어집니다.

.. 캠 래치를 최대한 아래로 돌립니다. 수평 모듈의 경우 캠을 모듈에서 최대한 멀리 돌립니다.
.. 손가락을 캠 레버 입구에 넣고 모듈을 컨트롤러 모듈에서 당겨 모듈을 분리합니다.
+
입출력 모듈이 있던 슬롯을 추적해야 합니다.



. 입출력 모듈을 따로 보관해 둡니다.
. 교체용 입출력 모듈을 타겟 슬롯에 설치합니다.
+
.. 입출력 모듈을 슬롯의 가장자리에 맞춥니다.
.. 모듈을 조심스럽게 슬롯에 밀어 넣고, 캠 래치를 위로 끝까지 돌려 모듈을 제자리에 잠급니다.


. I/O 모듈에 케이블을 연결합니다.
. 제거 및 설치 단계를 반복하여 컨트롤러의 추가 모듈을 교체합니다.
. 케이블 관리 트레이를 잠금 위치로 돌립니다.




== 3단계: 컨트롤러를 재부팅합니다

I/O 모듈을 교체한 후 컨트롤러 모듈을 재부팅해야 합니다.


NOTE: 새 입출력 모듈이 장애가 발생한 모듈과 다른 모델인 경우 먼저 BMC를 재부팅해야 합니다.

.단계
. 교체 모듈이 이전 모듈과 다른 모델인 경우 BMC를 재부팅합니다.
+
.. LOADER 프롬프트에서 advanced 권한 모드:_set privilege advanced_로 변경합니다
.. BMC:_SP 재부팅 _ 을(를) 재부팅합니다


. LOADER 프롬프트에서 node:_bye_를 재부팅합니다
+

NOTE: 그러면 I/O 카드 및 기타 구성 요소가 다시 초기화되고 노드가 재부팅됩니다.

+

NOTE: 변환을 완료한 후 유지보수 모드를 종료해야 합니다.

. 노드를 정상 작업:_스토리지 페일오버 반환 - ofnode impaired_node_name _
. 자동 반환이 비활성화된 경우 다시 활성화하십시오. _ 스토리지 페일오버 수정 -node local-auto-given true _




== 4단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
