= 1단계: 손상된 컨트롤러를 종료합니다
:allow-uri-read: 


슬롯 8의 컨트롤러 후면에 있는 시스템 관리 모듈에는 시스템 관리를 위한 온보드 구성 요소와 외부 관리용 포트가 포함되어 있습니다. 손상된 시스템 관리 모듈을 교체하거나 부팅 미디어를 교체하려면 대상 컨트롤러를 종료해야 합니다.

시스템 관리 모듈에는 다음과 같은 온보드 구성 요소가 있습니다.

* 부팅 미디어를 사용하면 컨트롤러 모듈을 분리하지 않고도 부팅 미디어를 교체할 수 있습니다.
* BMC
* 관리 스위치


시스템 관리 모듈에는 외부 관리를 위한 다음과 같은 포트도 포함되어 있습니다.

* RJ45 시리얼
* USB 시리얼(Type-C)
* USB Type-A(부팅 복구)
* e0M RJ45 이더넷


시스템 관리 모듈 또는 부팅 미디어를 교체하려면 손상된 컨트롤러를 종료해야 합니다.

.시작하기 전에
* 이 절차에서는 다음과 같은 용어를 사용합니다.
+
** 손상된 컨트롤러는 유지 관리를 수행하는 컨트롤러입니다.
** 정상적인 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.


* 다른 모든 시스템 구성 요소가 제대로 작동해야 합니다.
* 파트너 컨트롤러가 손상된 컨트롤러를 인계할 수 있어야 합니다.
* 오류가 발생한 구성 요소를 공급업체로부터 받은 교체 FRU 구성 요소로 교체해야 합니다.




== 1단계: 손상된 컨트롤러를 종료합니다

다음 옵션 중 하나를 사용하여 컨트롤러를 종료하거나 손상된 컨트롤러를 인수합니다.

[role="tabbed-block"]
====
.옵션 1: 대부분의 시스템
--
손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

.이 작업에 대해
* SAN 시스템을 사용하는 경우 손상된 컨트롤러 SCSI 블레이드에 대한 이벤트 메시지를 확인해야  `cluster kernel-service show`합니다.  `cluster kernel-service show`priv advanced 모드에서 명령을 실행하면 노드 이름, 해당 노드의 쿼럼 상태, 해당 노드의 가용성 상태 및 해당 노드의 작동 상태가 표시됩니다.
+
각 SCSI 블레이드 프로세스는 클러스터의 다른 노드와 함께 쿼럼에 있어야 합니다. 교체를 진행하기 전에 모든 문제를 해결해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].


.단계
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다. `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다. `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
+

NOTE: 자동 반환을 비활성화하시겠습니까?_가 표시되면 'y'를 입력합니다.

. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===


--
.옵션 2: 컨트롤러가 MetroCluster에 있습니다
--
손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].
* MetroCluster 설정이 있는 경우 MetroCluster 설정 상태가 구성되어 있고 해당 노드가 설정 및 정상 상태('MetroCluster node show')인지 확인해야 합니다.


.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===


--
====


== 2단계: 손상된 시스템 관리 모듈을 교체합니다

손상된 시스템 관리 모듈을 교체합니다.

. 섀시 앞면에서 엄지 손가락으로 각 드라이브를 단단히 눌러 정지가 느껴질 때까지 밀어넣습니다. 이렇게 하면 드라이브가 섀시 중앙판에 단단히 고정됩니다.
+

NOTE: 계속하기 전에 NVRAM 디스테이징이 완료되었는지 확인하십시오.

+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[DRW A800 드라이브 장착형 IEOPS 960]

. 섀시 후면으로 이동합니다. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 컨트롤러 모듈을 3인치 정도 당겨 전원을 분리합니다.
+

NOTE: 시스템에 DC 전원 공급 장치가 있는 경우 PSU에서 전원 케이블 블록을 분리합니다.

+
.. 양쪽 잠금 래치를 아래로 누른 다음 두 래치를 동시에 아래로 돌립니다.
.. 컨트롤러 모듈을 섀시에서 3인치 정도 당겨 전원을 분리합니다.


. 케이블 관리 트레이 안쪽의 양쪽에 있는 단추를 당겨 케이블 관리 트레이를 아래로 돌린 다음 트레이를 아래로 돌립니다.
. 시스템 관리 모듈을 분리합니다.
+
.. 시스템 관리 모듈에 연결된 모든 케이블을 분리합니다. 모듈을 다시 설치할 때 케이블을 올바른 포트에 연결할 수 있도록 케이블이 연결된 위치에 레이블을 확인하십시오.
+
image::../media/drw_70-90_sys-mgmt_remove_ieops-1817.svg[시스템 관리 모듈을 교체합니다]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[설명선 번호 1]
 a| 
시스템 관리 모듈 캠 래치

|===


. 시스템 관리 모듈을 분리합니다.
+
.. 시스템 관리 캠 버튼을 누릅니다. 캠 레버가 섀시에서 멀어집니다.
.. 캠 레버를 완전히 아래로 돌립니다.
.. 손가락을 캠 레버에 대고 모듈을 똑바로 당겨 시스템에서 빼냅니다.
.. 부팅 미디어에 액세스할 수 있도록 시스템 관리 모듈을 정전기 방지 매트 위에 놓습니다.


. 부팅 미디어를 교체 시스템 관리 모듈로 이동합니다.
+
image::../media/drw_a70-90_sys-mgmt_replace_ieops-1373.svg[부팅 미디어를 교체합니다]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[설명선 번호 1]
 a| 
시스템 관리 모듈 캠 래치



 a| 
image::../media/legend_icon_02.svg[설명선 번호 2]
 a| 
부트 미디어 잠금 버튼



 a| 
image::../media/legend_icon_03.svg[설명선 번호 3]
 a| 
미디어를 부팅합니다

|===
+
.. 파란색 잠금 버튼을 누르십시오. 부트 미디어가 위쪽으로 약간 회전합니다.
.. 부팅 미디어를 위로 돌려 소켓에서 꺼냅니다.
.. 교체 시스템 관리 모듈에 부팅 미디어를 설치합니다.
+
... 부트 미디어의 가장자리를 소켓 하우징에 맞춘 다음 조심스럽게 소켓에 똑바로 밀어 넣습니다.
... 잠금 버튼이 맞물릴 때까지 부트 미디어를 아래쪽으로 돌립니다. 필요한 경우 파란색 잠금 장치를 누릅니다.




. 시스템 관리 모듈을 설치합니다.
+
.. 교체 시스템 관리 모듈의 가장자리를 시스템 입구에 맞추고 컨트롤러 모듈에 부드럽게 밀어 넣습니다.
.. 캠 래치가 I/O 캠 핀과 맞물리기 시작할 때까지 모듈을 슬롯에 부드럽게 밀어 넣은 다음 캠 래치를 위로 끝까지 돌려 모듈을 제자리에 잠급니다.


. 시스템 관리 모듈을 재구성합니다.
+

NOTE: 시스템에 DC 전원 공급 장치가 있는 경우 전원 케이블 블록을 PSU에 다시 연결합니다.

. 컨트롤러 모듈을 섀시에 다시 설치합니다.
. 케이블 관리 트레이를 닫힘 위치까지 돌립니다.




== 3단계: 컨트롤러 모듈을 재부팅합니다

컨트롤러 모듈을 재부팅합니다.

. LOADER 프롬프트에서 _bye_를 입력합니다.
. 스토리지:_storage failover 반환 -ofnode_impaired_node_name__을(를) 되돌려 컨트롤러를 정상 작동 상태로 되돌립니다
. 를 사용하여 자동 반환 복원 `storage failover modify -node local -auto-giveback true` 명령.
. AutoSupport 유지보수 윈도우가 트리거된 경우 를 사용하여 윈도우를 종료합니다 `system node autosupport invoke -node * -type all -message MAINT=END` 명령.




== 4단계: 라이센스를 설치하고 제품 번호를 등록합니다

장애가 있는 노드가 표준(노드 잠김) 라이센스가 필요한 ONTAP 기능을 사용하는 경우 노드에 대한 새 라이센스를 설치해야 합니다. 표준 라이센스가 있는 기능의 경우 클러스터의 각 노드에 기능에 대한 자체 키가 있어야 합니다.

.이 작업에 대해
라이센스 키를 설치할 때까지 표준 라이센스가 필요한 기능을 노드에서 계속 사용할 수 있습니다. 그러나 이 기능에 대한 라이센스가 있는 클러스터에서 노드가 유일한 노드인 경우에는 해당 기능에 대한 구성을 변경할 수 없습니다. 또한 노드에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 가능한 한 빨리 노드에 대한 교체 라이센스 키를 설치해야 합니다.

.시작하기 전에
라이센스 키는 28자 형식이어야 합니다.

라이센스 키를 설치할 수 있는 90일의 유예 기간이 있습니다. 유예 기간이 지나면 모든 이전 라이센스가 무효화됩니다. 유효한 라이센스 키를 설치한 후 유예 기간이 끝나기 전에 모든 키를 24시간 동안 설치해야 합니다.

.단계
. 새 라이센스 키가 필요한 경우 에서 교체용 라이센스 키를 받으십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp Support 사이트"] My Support(내 지원) 섹션에서 Software licenses(소프트웨어 라이센스) 를 선택합니다.
+

NOTE: 필요한 새 라이센스 키는 자동으로 생성되어 파일의 이메일 주소로 전송됩니다. 30일 이내에 라이센스 키가 포함된 이메일을 받지 못한 경우 기술 지원 부서에 문의하십시오.

. 각 라이선스 키를 '+시스템 라이선스 추가 라이선스 코드 라이선스 키, 라이선스 키...+'로 설치합니다
. 필요한 경우 이전 라이센스를 제거합니다.
+
.. 미사용 라이선스 확인:'라이선스 정리 - 미사용 - 시뮬레이션
.. 목록이 올바르면 사용하지 않는 사용권의 'license clean-up-unused'를 삭제합니다


. NetApp Support에 시스템 일련 번호를 등록합니다.
+
** AutoSupport가 활성화된 경우 AutoSupport 메시지를 전송하여 일련 번호를 등록합니다.
** AutoSupport가 활성화되어 있지 않으면 를 호출합니다 https://mysupport.netapp.com["NetApp 지원"] 일련 번호를 등록합니다.






== 5단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://mysupport.netapp.com/site/info/rma["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
