= 1단계: 시스템 회수
:allow-uri-read: 


저장 장치, 네트워크 연결을 다시 설정하고 컨트롤러를 되돌려 교체 절차를 계속합니다.



== 1단계: 시스템 회수

컨트롤러 모듈의 스토리지 및 네트워크 연결 케이블을 다시 연결합니다.

.단계
. 스토리지 및 네트워크 연결에 컨트롤러 모듈을 다시 연결합니다.
. 을 사용하여 케이블이 올바른지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Config Advisor를 다운로드하고 설치합니다.
.. 대상 시스템에 대한 정보를 입력한 다음 데이터 수집 을 클릭합니다.
.. 케이블 연결 탭을 클릭한 다음 출력을 확인합니다. 모든 디스크 쉘프가 표시되고 모든 디스크가 출력에 표시되는지 확인하여 찾은 케이블 연결 문제를 해결합니다.
.. 해당 탭을 클릭하여 다른 케이블을 확인한 다음 Config Advisor의 출력을 확인합니다.






== 단계 2: 컨트롤러를 되돌립니다

. 스토리지 시스템에 Encryption이 구성되어 있는 경우 다음 절차에 따라 스토리지 또는 볼륨 암호화 기능을 복원하여 시스템을 재부팅해야 합니다.
+
.. 메뉴로 부팅하고 옵션 10을 실행합니다
.. 암호 및 백업 데이터를 입력한 다음 정상 부팅을 수행합니다. 을 참조하십시오. https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["온보드 키 관리 암호화 키를 복원합니다"]
.. CFO만 반환을 수행합니다
.. Onboard Sync를 수행하고 SVM-KEK가 true로 설정되어 있는지 확인합니다. 를 참조하십시오 https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["MB 교체 후 반환 실패 - 키 관리자에 의해 작업이 거부되었습니다"]
.. 반환 SFO, (강제 없음)


. 시스템에 Encryption이 구성되어 있지 않으면 다음 절차를 수행하여 시스템을 재부팅합니다.
+
.. 메뉴로 부팅하고 옵션 1을 실행합니다.
.. 컨트롤러를 다시 제공합니다.
.. 정상적인 컨트롤러에서 교체된 컨트롤러의 스토리지를 다시 제공합니다. 'storage failover 반환 - ofnode_replacement_node_name_'
+
replacement_controller가 스토리지를 다시 가져와 부팅을 완료합니다.

+

NOTE: 기브백이 거부되면 거부권을 재정의할 수 있습니다.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["사용 중인 ONTAP 9 버전에 맞는 고가용성 구성 콘텐츠를 찾아보십시오"]

.. 기브백이 완료된 후 HA 쌍이 정상 작동 중인지, 그리고 테이크오버가 가능한지, 즉 '스토리지 페일오버 표시'인지 확인합니다


. 시스템이 MetroCluster 구성인 경우 컨트롤러 상태 'MetroCluster node show'를 모니터링한다
+
MetroCluster 구성을 정상 상태로 되돌리려면 교체 후 몇 분 정도 걸리며, 이 경우 각 컨트롤러에 구성된 상태가 표시되며 DR 미러링이 활성화되고 정상 모드가 표시됩니다. MetroCluster node show-fields node-systemid 명령 출력은 MetroCluster 구성이 정상 상태로 돌아갈 때까지 이전 시스템 ID를 표시합니다.

. 컨트롤러가 MetroCluster 구성에 있는 경우 MetroCluster 상태에 따라 원래 소유자가 재해 사이트의 컨트롤러인 경우 DR 홈 ID 필드에 디스크의 원래 소유자가 표시되는지 확인합니다.
+
다음 두 조건이 모두 참인 경우 이 작업이 필요합니다.

+
** MetroCluster 구성이 전환 상태입니다.
** replacement_controller는 재해 사이트에 있는 디스크의 현재 소유자입니다.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["4노드 MetroCluster 구성에서 HA 테이크오버 및 MetroCluster 스위치오버 중에 디스크 소유권이 변경됩니다"]



. 시스템이 MetroCluster 구성인 경우 각 컨트롤러가 'MetroCluster node show-fields configuration-state'로 구성되어 있는지 확인합니다
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 각 컨트롤러에 대해 예상되는 볼륨이 'vol show-node-name'인지 확인합니다
. 재부팅 시 자동 테이크오버 기능을 사용하지 않도록 설정한 경우 정상 컨트롤러에서 활성화하십시오. 'storage failover modify -node replacement -node -name -onreboot true'

