= 
:allow-uri-read: 


부팅 미디어가 손상된 경우 파트너 노드에서 ONTAP 이미지를 복원합니다.

.이 작업에 대해
노드의 부팅 미디어가 손상된 경우 Loader 프롬프트에서 부팅 프로세스가 멈추고 부팅 오류 메시지가 표시됩니다.

이러한 부팅 오류 메시지가 표시되면 파트너 노드에서 ONTAP 이미지를 복원해야 합니다.

.부팅 오류 메시지의 예를 표시합니다
[%collapsible]
====
....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....
====
.단계
. Loader 프롬프트에서 다음 명령을 입력합니다.
+
`boot_recovery -partner`

+
화면에 다음 메시지가 표시됩니다.

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Loader가 로컬 클러스터 포트를 구성하고 파트너 노드에서 실행할 때 부팅 미디어 복구 프로세스를 `netboot` 모니터링합니다.
+
netboot가 실행 중이면 `Starting BMR` 메시지가 표시됩니다.

. 암호화 방법에 따라 시스템 구성과 일치하는 옵션을 선택합니다.
+
[role="tabbed-block"]
====
.암호화 없음
--
암호화가 감지되지 않으면 키 관리 없이 부팅 미디어 복구 프로세스가 계속됩니다.

파트너 노드에서 백업 구성, env 파일, MDB 및 RDB를 복구하면서 복구 프로세스를 계속 모니터링합니다.

복구 프로세스가 완료되면 노드가 재부팅됩니다. 다음 메시지는 복구에 성공했음을 나타냅니다.

....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....
--
.온보드 키 관리자(OKM)
--
Onboard Key Manager(OKM)가 감지되면 다음과 같은 프롬프트가 표시됩니다.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Bootmenu 옵션 프롬프트에서 를 `Y` 입력하여 bootmedia 복구 옵션을 사용할 것인지 확인합니다.
.. 메시지가 표시되면 온보드 키 관리자에 대한 암호를 입력하고 암호를 다시 입력하여 확인합니다.
+
.암호 프롬프트의 예를 표시합니다
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====
.. 파트너 노드에서 백업 구성, env 파일, MDB 및 RDB를 복구하면서 복구 프로세스를 계속 모니터링합니다.
+
복구 프로세스가 완료되면 노드가 재부팅됩니다. 다음 메시지는 복구에 성공했음을 나타냅니다.

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.
....


--
.외부 키 관리자(EKM)
--
EKM이 구성된 경우 다음 프롬프트가 표시됩니다.

....
Error when fetching key manager config from partner <IP>: 28

Has key manager been configured on this system? {y|n}
....
.. EKM이 구성된 경우 를 `Y` 입력합니다.
+
....
key manager is configured.
Entering Bootmenu Option 11...
....
+
설치 중에 처음 사용한 EKM 설정을 묻는 메시지가 나타납니다.

.. 메시지가 나타나면 각 EKM 구성 설정을 입력합니다.
.. 클러스터 UUID 및 Keystore UUID의 속성이 올바른지 확인합니다.
+
*** 파트너 노드에서 다음 명령을 사용하여 클러스터 UUID를 검색합니다.
+
`cluster identity show`

*** 파트너 노드에서 다음 명령을 사용하여 Keystore UUID를 검색합니다.
+
`vserver show -type admin`

+
`key-manager keystore show -vserver <nodename>`

*** 파트너 노드를 사용할 수 없는 경우 Mroot-AK 키를 사용하여 UUID를 검색합니다.
+
**** 클러스터 UUID의 경우 다음 명령을 입력합니다.
+
`x-NETAPP-ClusterName: <cluster name>`

**** Keystore UUID에 다음 명령을 입력합니다.
+
`x-NETAPP-KeyUsage: MROOT-AK`





.. 메시지가 표시되면 Keystore UUID 및 클러스터 UUID 값을 입력합니다.
.. 키가 성공적으로 복원되었는지 여부에 따라 다음 작업 중 하나를 수행합니다.
+
*** 키가 성공적으로 복원되면 복구 프로세스가 계속되고 노드를 재부팅합니다. 4단계를 진행합니다.
*** 키가 성공적으로 복원되지 않으면 시스템이 중지되고 오류 및 경고 메시지가 표시됩니다. 복구 프로세스를 다시 실행합니다.
+
.키 복구 오류 및 경고 메시지의 예를 표시합니다
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...

WARNING: kmip_init: authentication keys might not be available.

System cannot connect to key managers.

ERROR: kmip_init: halting this system with encrypted mroot...

Terminated

Uptime: 11m32s

System halting...

LOADER-B>
....
=====




--
====


. 노드를 재부팅할 때 시스템이 다시 온라인 상태이고 작동 중인지 확인하여 부팅 미디어 복구가 성공적인지 확인합니다.
. 손상된 컨트롤러를 다시 설치하여 정상 작동으로 되돌립니다.
+
`storage failover giveback -ofnode _impaired_node_name_`..

. 자동 반환이 비활성화된 경우 다시 활성화하십시오.
+
`storage failover modify -node local -auto-giveback true`..

. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=END`..


