= 
:allow-uri-read: 


.단계
. 시스템에서 활성화된 키 관리자를 확인합니다.
+
[cols="1a,2a"]
|===
| ONTAP 버전입니다 | 이 명령을 실행합니다 


 a| 
ONTAP 9.14.1 이상
 a| 
`security key-manager keystore show`

** EKM을 사용하면 `EKM` 이 명령 출력에 표시됩니다.
** OKM을 사용하면 `OKM` 이 명령 출력에 표시됩니다.
** 키 관리자가 설정되어 있지 않으면 `No key manager keystores configured` 명령 출력에 이 표시됩니다.




 a| 
ONTAP 9.13.1 이하
 a| 
`security key-manager show-key-store`

** EKM을 사용하면 `external` 이 명령 출력에 표시됩니다.
** OKM을 사용하면 `onboard` 이 명령 출력에 표시됩니다.
** 키 관리자가 설정되어 있지 않으면 `No key managers configured` 명령 출력에 이 표시됩니다.


|===
. 시스템에 키 관리자가 구성되어 있는지 여부에 따라 다음 중 하나를 수행합니다.
+
*키 관리자가 구성되지 않은 경우:*

+
손상된 컨트롤러를 안전하게 종료하고 종료 절차를 진행할 수 있습니다.

+
*키 관리자가 구성된 경우(EKM 또는 OKM):*

+
.. 키 관리자에서 인증 키 상태를 표시하려면 다음 쿼리 명령을 입력하세요.
+
`security key-manager key query`

.. 출력을 검토하고 값을 확인하세요. `Restored` 열.  이 열은 키 관리자(EKM 또는 OKM)의 인증 키가 성공적으로 복원되었는지 여부를 나타냅니다.


. 귀하의 주요 관리자 유형에 따라 적절한 절차를 완료하세요.
+
[role="tabbed-block"]
====
.외부 키 관리자(EKM)
--
다음 단계를 값에 따라 완료하세요. `Restored` 열.

*모든 키가 표시되는 경우 `true` 복원된 열에서:*

손상된 컨트롤러를 안전하게 종료하고 종료 절차를 진행할 수 있습니다.

* 키가 다른 값을 표시하는 경우 `true` 복원된 열에서:*

.. 클러스터의 모든 노드에 외부 키 관리 인증 키를 복원합니다.
+
`security key-manager external restore`

+
명령이 실패하면 NetApp 지원팀에 문의하세요.

.. 모든 인증 키가 복원되었는지 확인하세요.
+
`security key-manager key query`

+
확인해주세요 `Restored` 열 표시 `true` 모든 인증 키에 대해.

.. 모든 키가 복구되면 손상된 컨트롤러를 안전하게 종료하고 종료 절차를 진행할 수 있습니다.


--
.온보드 키 관리자(OKM)
--
다음 단계를 값에 따라 완료하세요. `Restored` 열.

*모든 키가 표시되는 경우 `true` 복원된 열에서:*

.. OKM 정보를 백업하세요.
+
... 고급 권한 모드로 전환:
+
`set -priv advanced`

+
입력하다 `y` 계속하라는 메시지가 표시되면.

... 키 관리 백업 정보를 표시합니다.
+
`security key-manager onboard show-backup`

... 백업 정보를 별도의 파일이나 로그 파일에 복사합니다.
+
교체 절차 중에 OKM을 수동으로 복구해야 하는 경우 이 백업 정보가 필요합니다.

... 관리자 모드로 돌아가기:
+
`set -priv admin`



.. 손상된 컨트롤러를 안전하게 종료하고 종료 절차를 진행할 수 있습니다.


* 키가 다른 값을 표시하는 경우 `true` 복원된 열에서:*

.. 온보드 키 관리자를 동기화합니다.
+
`security key-manager onboard sync`

+
메시지가 표시되면 32자리 영숫자로 구성된 온보드 키 관리 암호를 입력하세요.

+

NOTE: 이는 Onboard Key Manager를 처음 구성할 때 생성한 클러스터 전체 암호문구입니다.  이 암호가 없으면 NetApp 지원팀에 문의하세요.

.. 모든 인증 키가 복원되었는지 확인하세요.
+
`security key-manager key query`

+
확인해주세요 `Restored` 열 표시 `true` 모든 인증 키 및 `Key Manager` 유형이 표시됩니다 `onboard` .

.. OKM 정보를 백업하세요.
+
... 고급 권한 모드로 전환:
+
`set -priv advanced`

+
입력하다 `y` 계속하라는 메시지가 표시되면.

... 키 관리 백업 정보를 표시합니다.
+
`security key-manager onboard show-backup`

... 백업 정보를 별도의 파일이나 로그 파일에 복사합니다.
+
교체 절차 중에 OKM을 수동으로 복구해야 하는 경우 이 백업 정보가 필요합니다.

... 관리자 모드로 돌아가기:
+
`set -priv admin`



.. 손상된 컨트롤러를 안전하게 종료하고 종료 절차를 진행할 수 있습니다.


--
====

