= NVE 구성을 검증합니다
:allow-uri-read: 


손상된 컨트롤러를 종료하기 전에 시스템에 NetApp Volume Encryption(NVE) 또는 NetApp Storage Encryption(NSE)이 활성화되어 있는지 확인해야 합니다. 그렇다면 구성을 확인해야 합니다.

. 클러스터의 모든 볼륨에 NVE가 사용되고 있는지 확인합니다. 'volume show-is-encrypted true'
+
출력에 표시되는 볼륨이 하나라도 있으면 NVE가 구성되어 NVE 구성을 확인해야 합니다. 나열된 볼륨이 없으면 NSE가 구성되어 있고 사용 중인지 확인합니다.

. NSE 설정 및 사용 여부 확인:'Storage encryption disk show
+
** 명령 출력에 모드 및 키 ID 정보가 포함된 드라이브 세부 정보가 표시되는 경우 NSE가 구성되어 있으며 NSE 구성을 확인하고 사용 중인 것입니다.
** 디스크가 표시되지 않으면 NSE가 구성되지 않은 것입니다.
** NVE와 NSE가 구성되지 않은 경우 NSE 키로 보호되는 드라이브가 없으므로 손상된 컨트롤러를 종료하는 것이 안전합니다.






=== NVE 구성을 검증합니다

. 키 관리 서버에 저장되어 있는 인증 키의 키 ID를 보안 키 관리자 키 쿼리 로 표시합니다
+

NOTE: ONTAP 9.6 릴리스 후에는 추가 키 관리자 유형이 있을 수 있습니다. KMIP, AKV, GCP 등이 있다. 이러한 유형의 확인 과정은 외부 또는 온보드 키 관리자 유형을 확인하는 과정과 같습니다.

+
** 키 관리자 유형이 외형이고 복원된 칼럼에 예라고 표시되면 손상된 컨트롤러를 차단하는 것이 안전합니다.
** 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(Yes)가 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형이 '내장'으로 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 추가 단계를 완료해야 합니다.


. 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(yes)가 표시되면 OKM 정보를 수동으로 백업합니다.
+
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 키 관리 정보(보안 키 관리자 온보드 show-backup)를 표시하려면 명령을 입력합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 손상된 컨트롤러를 종료합니다.


. 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. 외부 키 관리 인증 키를 클러스터의 모든 노드에 복원: '보안 키 관리자 외부 복원
+
명령이 실패하면 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 모든 인증 키에 대해 복원된 열이 예(보안 키 관리자 키 쿼리)와 같은지 확인합니다
.. 손상된 컨트롤러를 종료합니다.


. 키 관리자 유형에 '온보드'가 표시되고 '복원된' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. Onboard security key-manager sync command:'security key-manager 온보딩 sync'를 입력한다
+

NOTE: 프롬프트에 고객의 온보드 키 관리 암호를 입력합니다. 암호를 제공할 수 없는 경우 NetApp Support에 문의하십시오. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 모든 인증 키에 대해 복원됨 열에 예(yes)가 표시되는지 확인합니다. 보안 키 관리자 키 쿼리(ecurity key-manager key-query)
.. 키 관리자 유형에 온보드(Onboard)이 표시되는지 확인한 다음 OKM 정보를 수동으로 백업합니다.
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 명령을 입력하여 키 관리 백업 정보 '보안 키 관리자 온보드 show-backup'을 표시합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.






=== NSE 구성을 확인합니다

. 키 관리 서버에 저장된 인증 키의 키 ID를 '보안 키 관리자 키 쿼리 키 유형 NSE-AK'로 표시합니다
+

NOTE: ONTAP 9.6 릴리스 후에는 추가 키 관리자 유형이 있을 수 있습니다. KMIP, AKV, GCP 등이 있다. 이러한 유형의 확인 과정은 외부 또는 온보드 키 관리자 유형을 확인하는 과정과 같습니다.

+
** 키 관리자 유형이 외형이고 복원된 칼럼에 예라고 표시되면 손상된 컨트롤러를 차단하는 것이 안전합니다.
** 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(Yes)가 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.
** 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되면 몇 가지 추가 단계를 완료해야 합니다.


. 키 관리자 유형에 온보드(Onboard)이 표시되고 복원된(Restored) 열에 예(yes)가 표시되면 OKM 정보를 수동으로 백업합니다.
+
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 키 관리 정보(보안 키 관리자 온보드 show-backup)를 표시하려면 명령을 입력합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.


. 키 관리자 유형에 '외부'가 표시되고 '복원됨' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. Onboard security key-manager sync command:'security key-manager external sync'를 입력한다
+
명령이 실패하면 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 모든 인증 키에 대해 복원된 열이 예(보안 키 관리자 키 쿼리)와 같은지 확인합니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.


. 키 관리자 유형에 '온보드'가 표시되고 '복원된' 열에 '예'가 아닌 다른 항목이 표시되는 경우:
+
.. Onboard security key-manager sync command:'security key-manager 온보딩 sync'를 입력한다
+
프롬프트에 고객의 온보드 키 관리 암호를 입력합니다. 암호를 제공할 수 없는 경우 NetApp Support에 문의하십시오.

+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. 모든 인증 키에 대해 복원됨 열에 예(yes)가 표시되는지 확인합니다. 보안 키 관리자 키 쿼리(ecurity key-manager key-query)
.. 키 관리자 유형에 온보드(Onboard)이 표시되는지 확인한 다음 OKM 정보를 수동으로 백업합니다.
.. Advanced Privilege Mode로 이동하여 'et-priv advanced'라는 메시지가 표시되면 y를 입력합니다
.. 명령을 입력하여 키 관리 백업 정보 '보안 키 관리자 온보드 show-backup'을 표시합니다
.. 백업 정보의 내용을 별도의 파일이나 로그 파일에 복사합니다. OKM을 수동으로 복구해야 하는 재해 시나리오에서 이 구성 이 필요합니다.
.. 'Set-priv admin' 모드로 돌아갑니다
.. 컨트롤러를 안전하게 종료할 수 있습니다.



