= 
:allow-uri-read: 


입출력이 진행되는 동안 장애가 발생한 드라이브를 중단 없이 교체할 수 있습니다.

.시작하기 전에
* 설치할 드라이브는 스토리지 시스템에서 지원해야 합니다.
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

* SED(자체 암호화 드라이브) 인증이 활성화된 경우 ONTAP 설명서의 SED 교체 지침을 사용해야 합니다.
+
ONTAP 설명서의 지침은 SED를 교체하기 전과 후에 수행해야 하는 추가 단계를 설명합니다.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["CLI를 통한 NetApp 암호화 개요"^]

* 스토리지 시스템의 다른 모든 구성 요소가 올바르게 작동해야 합니다. 그렇지 않은 경우 이 절차를 계속하기 전에 에 문의해야 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"] 합니다.
* 분리하려는 드라이브가 실패했는지 확인합니다.
+
'storage disk show-Broken' 명령을 실행하여 드라이브 실패를 확인할 수 있습니다. 오류가 발생한 드라이브가 실패한 드라이브 목록에 나타납니다. 그렇지 않으면 기다린 다음 명령을 다시 실행해야 합니다.

+

NOTE: 드라이브 유형 및 용량에 따라 장애가 발생한 드라이브 목록에 드라이브가 표시되는 데 최대 몇 시간이 걸릴 수 있습니다.



.이 작업에 대해
* 장애가 발생한 드라이브를 교체할 때 드라이브를 분리하고 교체 드라이브를 삽입하면 스토리지 시스템에서 드라이브가 제거되었음을 인식할 수 있도록 70초 정도 기다려야 합니다.
* 가장 좋은 방법은 드라이브를 핫 스와핑하기 전에 DQP(Disk Qualification Package)의 현재 버전을 설치하는 것입니다.
+
현재 버전의 DQP를 설치하면 시스템이 새로 인증된 드라이브를 인식하고 사용할 수 있습니다. 이렇게 하면 드라이브가 인식되지 않으므로 최신 드라이브 정보가 없는 경우 및 드라이브 파티셔닝 예방에 대한 시스템 이벤트 메시지가 표시되지 않습니다. 또한 DQP는 최신 버전이 아닌 드라이브 펌웨어에 대해서도 알려줍니다.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp 다운로드: 디스크 검증 패키지"^]

* 모범 사례는 FRU 구성 요소를 교체하기 전에 시스템에 최신 버전의 NVMe 쉘프 모듈(NSM) 펌웨어와 드라이브 펌웨어를 사용하는 것입니다.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

+
[NOTE]
====
펌웨어를 쉘프와 해당 구성요소를 지원하지 않는 버전으로 되돌리지 마십시오.

====
* 최신 버전이 아닌 펌웨어 버전이 있는 새 드라이브에서 드라이브 펌웨어가 중단 없이 자동으로 업데이트됩니다.
+

NOTE: 드라이브 펌웨어 검사는 2분마다 수행됩니다.

* 필요한 경우 스토리지 시스템 위치 상태 표시등(파란색)을 켜서 영향을 받는 스토리지 시스템을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
스토리지 시스템에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.


