= 
:allow-uri-read: 


이 절차를 사용하려면 스토리지 시스템에서 ONTAP 9.17.1 이상을 실행하고 있어야 하며, 스토리지 시스템이 실행 중인 ONTAP 버전의 모든 요구 사항을 충족해야 합니다.


NOTE: 스토리지 시스템이 ONTAP 9.17.1 이상을 실행하고 있지 않거나 스토리지 시스템에서 실행 중인 ONTAP 버전의 모든 요구 사항을 충족하지 않는 경우 이 절차를 사용할 수 없으며 link:io-module-replace.html["I/O 모듈 교체 절차"]을 사용해야 합니다.

[role="tabbed-block"]
====
.ONTAP 9.17.1 또는 9.18.1RC
--
* 슬롯 4에 있는 고장난 클러스터 및 HA I/O 모듈을 동일한 I/O 모듈로 핫 스왑하고 있습니다. I/O 모듈 유형은 변경할 수 없습니다.
* 클러스터 및 HA I/O 모듈에 오류가 발생한 컨트롤러(손상된 컨트롤러)가 이미 정상적인 파트너 컨트롤러를 인수했어야 합니다. I/O 모듈에 장애가 발생한 경우 테이크오버가 자동으로 수행되었어야 합니다.
+
2노드 클러스터의 경우 스토리지 시스템에서 어느 컨트롤러에 I/O 모듈 장애가 발생했는지 구분할 수 없으므로 어느 컨트롤러든 테이크오버를 시작할 수 있습니다. 핫 스왑은 I/O 모듈 장애가 발생한 컨트롤러(손상된 컨트롤러)가 정상 컨트롤러를 테이크오버한 경우에만 지원됩니다. I/O 모듈을 핫 스왑하는 것이 중단 없이 복구할 수 있는 유일한 방법입니다.

+
손상된 컨트롤러가 건강한 컨트롤러를 성공적으로 인수했는지 확인하려면 다음을 입력하세요.  `storage failover show` 명령.

+
실패한 I/O 모듈이 어느 컨트롤러에 있는지 확실하지 않은 경우 문의하세요.  https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"] .

* 스토리지 시스템 구성에는 슬롯 4에 클러스터와 HA I/O 모듈이 하나만 있어야 하며, 클러스터와 HA I/O 모듈이 두 개가 있어서는 안 됩니다.
* 스토리지 시스템은 2노드(스위치리스 또는 스위치드) 클러스터 구성이어야 합니다.
* 스토리지 시스템의 다른 모든 구성 요소가 올바르게 작동해야 합니다. 그렇지 않은 경우 이 절차를 계속하기 전에 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"].


--
.ONTAP 9.18.1GA 이상
--
* 클러스터, HA 및 클라이언트에 사용되는 포트 조합에 관계없이 모든 슬롯에서 이더넷 I/O 모듈을 동등한 I/O 모듈로 핫 스왑할 수 있습니다. I/O 모듈 유형은 변경할 수 없습니다.
+
스토리지 또는 MetroCluster에 사용되는 포트가 있는 Ethernet I/O 모듈은 핫 스왑을 지원하지 않습니다.

* 스토리지 시스템(스위치리스 또는 스위치드 클러스터 구성)에는 스토리지 시스템에 대해 지원되는 수의 노드가 있을 수 있습니다.
* 클러스터의 모든 노드는 동일한 ONTAP 버전(ONTAP 9.18.1GA 이상)을 실행하거나 동일한 ONTAP 버전의 서로 다른 패치 레벨을 실행해야 합니다.
+
클러스터의 노드가 서로 다른 ONTAP 버전을 실행하는 경우 혼합 버전 클러스터로 간주되며 I/O 모듈 핫 스왑은 지원되지 않습니다.



* 스토리지 시스템의 컨트롤러는 다음 두 가지 상태 중 하나일 수 있습니다.
+
** 두 컨트롤러 모두 I/O(데이터 제공)를 실행할 수 있습니다.
** 테이크오버가 장애가 발생한 I/O 모듈로 인해 발생했고 컨트롤러가 정상적으로 작동하는 경우 두 컨트롤러 중 하나가 테이크오버 상태에 있을 수 있습니다.
+
특정 상황에서 ONTAP은 장애가 발생한 I/O 모듈로 인해 두 컨트롤러 중 하나를 자동으로 테이크오버할 수 있습니다. 예를 들어, 장애가 발생한 I/O 모듈에 모든 클러스터 포트가 포함되어 있는 경우(해당 컨트롤러의 모든 클러스터 링크가 다운되는 경우) ONTAP은 자동으로 테이크오버를 수행합니다.





* 스토리지 시스템의 다른 모든 구성 요소가 올바르게 작동해야 합니다. 그렇지 않은 경우 이 절차를 계속하기 전에 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"].


--
====