= 
:allow-uri-read: 


교체용 클러스터와 슬롯 4의 HA I/O 모듈을 온라인으로 전환하고, 모듈 포트가 성공적으로 초기화되었는지 확인하고, 슬롯 4의 전원이 켜져 있는지 확인한 다음, 모듈이 온라인 상태이고 인식되는지 확인합니다.

.단계
. 교체 클러스터와 HA I/O 모듈을 온라인으로 전환합니다.
+
.. 다음 명령을 입력하세요:
+
`system controller slot module insert -node _impaired_node_name_ -slot _slot_name_`

.. 입력하다 `y` _계속하시겠습니까?_라는 메시지가 표시되면
+
출력에서는 클러스터와 HA I/O 모듈이 성공적으로 온라인 상태가 되었는지(전원이 켜지고, 초기화되고, 서비스에 들어갔는지) 확인해야 합니다.

+
예를 들어, 다음 명령은 노드 2(손상된 컨트롤러)의 슬롯 4를 온라인으로 전환하고 프로세스가 성공했다는 메시지를 표시합니다.

+
[listing]
----
node2::> system controller slot module insert -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----


. 클러스터와 HA I/O 모듈의 각 포트가 성공적으로 초기화되었는지 확인하세요.
+
`event log show -event \*hotplug.init*`

+

NOTE: 필요한 펌웨어 업데이트와 포트 초기화가 완료되기까지 몇 분이 걸릴 수 있습니다.

+
출력에는 클러스터 및 HA I/O 모듈의 각 포트에 대해 기록된 hotplug.init.success EMS 이벤트가 표시되어야 합니다.  `_hotplug.init.success:_` 에서  `_Event_` 열.

+
예를 들어, 다음 출력은 클러스터 및 HA I/O 모듈 포트 e4b 및 e4a에 대한 초기화가 성공했음을 보여줍니다.

+
[listing]
----
node2::> event log show -event *hotplug.init*

Time                Node             Severity      Event

------------------- ---------------- ------------- ---------------------------

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4b" in slot 4 succeeded

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e4a" in slot 4 succeeded

2 entries were displayed.
----
. I/O 모듈 슬롯 4가 전원이 켜져 있고 작동할 준비가 되었는지 확인하세요.
+
`system controller slot module show`

+
출력에는 슬롯 4 상태가 다음과 같이 표시되어야 합니다.  `_powered-on_` 따라서 교체 클러스터와 HA I/O 모듈을 작동할 준비가 되었습니다.

. 교체 클러스터와 HA I/O 모듈이 온라인이고 인식되는지 확인합니다.
+
손상된 컨트롤러의 콘솔에서 명령을 입력하세요:

+
`system controller config show -node local -slot4`

+
교체 클러스터와 HA I/O 모듈이 성공적으로 온라인 상태가 되고 인식되면 슬롯 4에 대한 포트 정보를 포함한 I/O 모듈 정보가 출력에 표시됩니다.

+
예를 들어, 다음과 비슷한 출력이 표시됩니다.

+
[listing]
----
node2::> system controller config show -node local -slot 4

Node: node2
Sub- Device/
Slot slot Information
---- ---- -----------------------------
   4    - Dual 40G/100G Ethernet Controller CX6-DX
                  e4a MAC Address: d0:39:ea:59:69:74 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2807GJFM-B
                  e4b MAC Address: d0:39:ea:59:69:75 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2809G26F-A
                  Device Type:        CX6-DX PSID(NAP0000000027)
                  Firmware Version:   22.44.1700
                  Part Number:        111-05341
                  Hardware Revision:  20
                  Serial Number:      032403001370
----

