= 
:allow-uri-read: 


실패한 클러스터와 HA I/O 모듈을 안전하게 제거할 수 있도록 스토리지 시스템과 I/O 모듈 슬롯 4를 준비합니다.

. 적절하게 접지합니다.
. 실패한 클러스터와 HA I/O 모듈에서 케이블을 분리합니다.
+
나중에 이 과정에서 케이블을 같은 포트에 다시 연결할 수 있도록 케이블에 라벨을 붙이세요.

. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
예를 들어, 다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다.

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. 손상된 컨트롤러의 콘솔에서 자동 반환을 비활성화합니다.
+
`storage failover modify -node local -auto-giveback false`

+

NOTE: 자동 반환을 비활성화하시겠습니까?_가 표시되면 'y'를 입력합니다.

. 슬롯 4에 있는 실패한 클러스터와 HA 모듈을 서비스에서 제거하고 전원을 꺼서 제거할 준비를 합니다.
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

+

NOTE: _계속하시겠습니까?_라는 메시지가 표시되면 다음을 입력하세요.  `y` .

+
예를 들어, 다음 명령은 노드2(손상된 컨트롤러)의 슬롯 4에 있는 모듈을 제거할 준비를 하고, 제거해도 안전하다는 메시지를 표시합니다.

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----
. 슬롯 4의 실패한 클러스터와 HA 모듈의 전원이 꺼져 있는지 확인하세요.
+
`system controller slot module show`

+
출력은 다음과 같아야 합니다.  `_powered-off_` 슬롯 4의 실패한 모듈에 대한 상태 열에 있습니다.


