= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF 시스템
--
AFF A-Series 및 C-Series 모델은 가상화 환경을 위해 구축된 강력한 스케일아웃 플랫폼이며 NetApp ONTAP 구성에서 독립 시스템 또는 고성능 계층으로 구축할 수 있습니다. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["AFF 시스템에 대해 자세히 알아보십시오"]..

.AFF A20, AFF A30, AFF A50
ONTAP 9.16.1부터 제공됩니다

.AFF C30, AFF C60
ONTAP 9.16.1부터 제공됩니다

.AFF A1K, AFF A70 및 AFF A90의 약어입니다
ONTAP 9.15.1부터 제공됩니다

.AFF A150
ONTAP 9.13.1, ONTAP 9.12.1P1, ONTAP 9.11.1P8, ONTAP 9.10.1P12부터 제공됩니다

.AFF A900
ONTAP 9.10.1부터 제공됩니다

.AFF A250 및 AFF A800
ONTAP 9.8부터 제공됩니다

.AFF A400
ONTAP 9.7부터 제공됩니다

.AFF C250, AFF C400, AFF C800
ONTAP 9.12.1P1, ONTAP 9.13.1 GA부터 제공됩니다

--
.ASA r2 시스템
--
ASA R2 시스템은 통합 하드웨어 및 소프트웨어 솔루션을 제공하여 SAN 전용 고객의 요구 사항에 맞는 간소화된 환경을 제공합니다. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"]..

.ASA A1K, ASA A70, ASA A90
ONTAP 9.16.0부터 제공됩니다

--
.ASA 시스템
--
ASA A-Series 및 C-Series 모델은 FCP 또는 iSCSI 프로토콜을 사용하여 엔터프라이즈 미션 크리티컬 데이터베이스 및 기타 SAN 워크로드에 지속적인 데이터 가용성을 제공하는 단순화된 전용 SAN 경험을 제공합니다. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["ASA 시스템에 대해 자세히 알아보십시오"]..

.ASA A150, ASA A250, ASA A400, ASA A900
ONTAP 9.13.1부터 사용 가능

.ASA C250, C400, C800
ONTAP 9.13.1P1부터 제공됩니다

--
.FAS 시스템
--
FAS 시스템은 계층화, 백업 및 재해 복구를 위한 최상의 솔루션인 효율적이고 안전한 2차 스토리지를 제공합니다. link:https:://www.netapp.com/data-storage/fas/["FAS 시스템에 대해 자세히 알아보십시오"]..

.FAS70 및 FAS90
ONTAP 9.15.1부터 제공됩니다

.FAS9500
ONTAP 9.11.1, ONTAP 9.10.1P3부터 제공됩니다

.FAS8300 및 FAS700
ONTAP 9.7부터 제공됩니다

.FAS2820
ONTAP 9.13.1부터 사용 가능

.FAS2700
ONTAP 9.13.1부터 사용 가능

--
====