= 


. [[auto_check3_step17]]자동 부팅 중에 'loader>' 프롬프트에서 노드를 중지하려면 'Ctrl-C'를 누릅니다.
. [[step18]] 로더 프롬프트에서 유지보수 모드로 전환합니다.
+
boot_ONTAP maint를 선택합니다

. [[19단계]] 유지보수 모드에서 현재 타겟 모드에 있는 이전에 설정된 이니시에이터 포트를 모두 표시합니다.
+
'ucadmin 쇼'

+
포트를 다시 이니시에이터 모드로 변경합니다.

+
'ucadmin modify -m fc -t initiator -f <adapter name>'

. [[step20]] 포트가 이니시에이터 모드로 변경되었는지 확인합니다.
+
'ucadmin 쇼'

. [[step21]]유지보수 모드 종료:
+
"중지"

. [[auto_check3_step22]] 로더 프롬프트 부팅 시:
+
부트 ONTAP

+
이제 부팅 시 노드에서 이전에 할당되었으며 예상대로 부팅할 수 있는 모든 디스크를 감지할 수 있습니다.

. [[auto_check3_step23] 외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node1의 루트 애그리게이트에서 node3이 부팅되도록 node1 애그리게이트를 루트 애그리게이트로 설정합니다. 루트 애그리게이트를 설정하려면 부팅 메뉴로 이동하여 옵션 '5'를 선택하여 유지보수 모드로 전환하십시오.
+

CAUTION: * 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다. *

+
다음 절차에서는 노드 3이 노드 1의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 유지보수 모드로 전환:
+
boot_ONTAP maint를 선택합니다

.. 노드 1 애그리게이트에 대한 RAID, plex 및 체크섬 정보를 확인합니다.
+
'gagr status-r'입니다

.. node1 애그리게이트의 상태를 확인합니다.
+
'기정 상태'입니다

.. 필요한 경우 node1 애그리게이트를 온라인 상태로 전환합니다.
+
'aggr_online root_aggr_from_<node1>'

.. 노드 3이 원래 루트 애그리게이트로부터 부팅하지 않도록 합니다.
+
'<root_aggr_on_node3> 오프라인 집계'

.. 노드 1의 루트 애그리게이트를 노드 3의 새 루트 애그리게이트로 설정합니다.
+
'aggr options aggr_from_<node1> root'

.. 노드 3의 루트 애그리게이트가 오프라인 상태이고 노드 1에서 가져온 디스크의 루트 애그리게이트가 온라인 상태이고 루트:
+
'기정 상태'입니다

+

NOTE: 이전 하위 단계를 수행하지 않으면 노드 3이 내부 루트 애그리게이트에서 부팅되거나 시스템에서 새 클러스터 구성이 있다고 가정하거나 클러스터 구성을 확인하라는 메시지가 표시될 수 있습니다.

+
다음은 명령 출력의 예입니다.

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



