= 노드 1의 원래 애그리게이트는 업그레이드 완료 후 노드 4에서 소유합니다




== 노드 1의 원래 애그리게이트는 업그레이드 완료 후 노드 4에서 소유합니다

업그레이드 절차를 마치면 노드 3이 원래 노드 1을 홈 노드로 사용했던 새로운 애그리게이트 홈 노드가 됩니다. 업그레이드 후에 재배치할 수 있습니다.

다음과 같은 상황에서 노드 1을 노드 3이 아닌 홈 노드로 사용하여 애그리게이트를 제대로 재배치할 수 없습니다.

* 3단계에서는 애그리게이트를 노드 2에서 노드 3으로 재배치합니다. 재배치되는 일부 애그리게이트는 노드 1을 홈 노드로 사용합니다. 예를 들어, 이러한 집계를 aggr_node_1이라고 할 수 있습니다. 3단계 중에 aggr_node_1의 재배치가 실패하고 재배치를 강제할 수 없는 경우, 애그리게이트는 노드 2에 남겨집니다.
* 4단계 후 노드 2가 노드 4로 교체된 경우 노드 2가 교체되면 노드 4가 노드 3이 아닌 홈 노드로 온라인 상태가 됩니다.


스토리지 페일오버가 활성화된 후 다음 단계를 수행하여 6단계 이후에 잘못된 소유권 문제를 해결할 수 있습니다.

.단계
. 다음 명령을 입력하여 애그리게이트 목록을 가져옵니다.
+
'Storage aggregate show-nodes <node4> - is-home true'

+
올바르게 재배치되지 않은 애그리게이트를 확인하려면 섹션에서 가져온 노드 1의 홈 소유자가 있는 애그리게이트 목록을 참조하십시오 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 그런 다음 위의 명령의 출력과 비교합니다.

. 1단계의 출력과 섹션에서 node1에 대해 캡처한 출력을 비교합니다 link:prepare_nodes_for_upgrade.html["업그레이드할 노드를 준비합니다"] 그리고 올바르게 재배치되지 않은 모든 애그리게이트를 확인할 수 있습니다.
. [[auto_aggr_relocate_fail_Step3] 노드 4에 남아 있는 애그리게이트를 재배치합니다.
+
'storage aggregate relocation start-node <node4> - aggr <aggr_node_1> - destination <node3>'

+
이 재배치 중에는 '-ndo-controller-upgrade' 매개 변수를 사용하지 마십시오.

. 노드 3이 이제 애그리게이트의 홈 소유자가 되는지 확인합니다.
+
'Storage aggregate show-aggregate <aggr1, aggr2, aggr3...> - fields home-name'이 있습니다

+
'<aggr1, aggr2, aggr3...>'은 노드 1을 원래 홈 소유자로 가지고 있는 집계 목록입니다.

+
노드 3이 홈 소유자로 없는 애그리게이트는 에서 동일한 재배치 명령을 사용하여 노드 3으로 재배치할 수 있습니다 <<auto_aggr_relocate_fail_Step3,3단계>>.


