= 


랙에 노드 3을 설치하고, 노드 1의 연결을 노드 3으로 전송하고, 노드 3을 부팅하고, ONTAP를 설치해야 합니다. 그런 다음 노드 1의 스페어 디스크, 루트 볼륨에 속한 디스크 및 이전에 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 재할당해야 합니다.

노드 1에 설치된 ONTAP 9의 버전이 같지 않으면 노드 3을 netboot 해야 합니다. 노드3을 설치한 후 웹 서버에 저장된 ONTAP 9 이미지에서 부팅합니다. 그런 다음 부팅 미디어 장치에 올바른 파일을 다운로드하여 나중에 시스템을 부팅할 수 있습니다. 을 참조하십시오 link:prepare_for_netboot.html["netboot를 준비합니다"].

그러나 노드 1에 설치된 ONTAP 9의 이후 버전이 같거나 동일한 경우에는 노드 3을 netboot 할 필요가 없습니다.


NOTE: * 중요 *: 스토리지 어레이에 연결된 V-Series 시스템이나 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어를 사용하여 시스템을 업그레이드하는 경우 시스템을 완료해야 합니다 <<man_install3_step1,1단계>> 부터 까지 <<man_install3_step5,5단계>>에서 이 섹션을 그대로 둡니다 <<man_install3_step6,6단계>> 및 의 지침을 따릅니다 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"] 필요에 따라 유지보수 모드에서 명령을 입력합니다. 그런 다음 이 섹션으로 돌아가서 을(를) 다시 시작해야 합니다 <<man_install3_step7,7단계>>. 그러나 스토리지 디스크가 있는 시스템을 업그레이드하는 경우 이 전체 섹션을 완료한 다음 로 이동하십시오 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"], 클러스터 프롬프트에서 명령 입력

.단계
. [[man_install3_step1]] 노드 3의 랙 공간이 있는지 확인합니다.
+
노드 1과 노드 2가 별도의 섀시에 있는 경우 노드 1과 동일한 랙 위치에 노드 3을 배치할 수 있습니다. 그러나 노드 1이 노드 2가 있는 동일한 섀시에 있는 경우 노드 3을 노드 1의 위치와 가까운 자체 랙 공간에 넣어야 합니다.

. [[step2]] 노드 모델의 _설치 및 설치 지침_ 에 따라 랙에 노드 3을 설치합니다.
+

NOTE: 동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 3뿐만 아니라 섀시에 노드 4를 설치합니다. 그렇지 않으면 노드 3을 부팅할 때 노드는 이중 섀시 구성에 있는 것처럼 작동하며 노드 4를 부팅할 때 노드 간의 상호 연결이 나타나지 않습니다.

. [[step3]] 노드 3을 케이블로 연결하고 노드 1에서 노드 3으로 연결을 이동합니다.
+
다음 참조는 올바른 케이블 연결에 도움이 됩니다. 로 이동합니다 link:other_references.html["참조"] 링크를 클릭합니다.

+
** _설치 및 설치 지침_ 또는 _FlexArray 가상화 설치 요구 사항 및 노드3 플랫폼에 대한 참조_.
** 디스크 쉘프 가이드를 참조하십시오.
** ONTAP 9 고가용성 구성 가이드 _


+
다음 연결부에 케이블을 연결합니다.

+
** 콘솔(원격 관리 포트)
** 클러스터 포트
** 데이터 포트
** 클러스터 및 노드 관리 포트
** 스토리지
** SAN 구성: iSCSI 이더넷 및 FC 스위치 포트
+

NOTE: 대부분의 플랫폼 모델에는 고유한 상호 연결 카드 모델이 있으므로 상호 연결 카드 또는 클러스터 인터커넥트 케이블 연결을 노드 1에서 노드 3으로 이동할 필요가 없습니다. MetroCluster 구성의 경우 FC-VI 케이블 연결을 노드 1에서 노드 3으로 이동해야 합니다. 새 호스트에 FC-VI 카드가 없는 경우 FC-VI 카드를 이동해야 할 수 있습니다.



. [[man_install3_step4]]노드 3의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단하여 부팅 환경 프롬프트에 액세스합니다.
+
동일한 섀시에 두 노드가 있는 시스템으로 업그레이드하는 경우 노드 4도 재부팅됩니다. 그러나 노드 4 부팅은 나중까지 무시할 수 있습니다.

+

NOTE: 노드 3을 부팅할 때 다음과 같은 경고 메시지가 나타날 수 있습니다.

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]에 경고 메시지가 표시되면 <<man_install3_step4,4단계>>에서 다음 작업을 수행합니다.
+
.. NVRAM 배터리 부족 이외의 다른 문제를 나타내는 콘솔 메시지를 확인하고 필요한 경우 수정 조치를 수행합니다.
.. 배터리가 충전되고 부팅 프로세스가 완료될 때까지 기다립니다.
+

NOTE: * 주의 *: 지연을 무시하지 마십시오. 배터리를 충전하지 않으면 데이터가 손실될 수 있습니다.



. [[man_install3_step6]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 시스템이... | 그러면... 


| 디스크 및 백엔드 스토리지가 없습니다 | 7단계부터 12단계까지 건너뛰고 로 이동합니다 <<man_install3_step13,13단계>>. 


| 는 스토리지 어레이에 연결된 FlexArray 가상화 소프트웨어가 설치된 V-Series 시스템 또는 시스템입니다  a| 
.. 로 이동합니다 link:set_fc_uta_uta2_config_node3.html["노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다"] 하위 섹션을 완료합니다 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["노드 3에서 FC 포트를 구성합니다"] 및 link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["노드 3의 UTA/UTA2 포트를 확인하고 구성합니다"]시스템에 맞게.
.. 이 섹션으로 돌아가 나머지 단계를 완료합니다 <<man_install3_step7,7단계>>.


* 중요 *: ONTAP 가상화 소프트웨어를 사용하여 V-Series 또는 시스템에서 FlexArray를 부팅하기 전에 FC 온보드 포트, CNA 온보드 포트 및 CNA 카드를 재구성해야 합니다.

|===
. [[man_install3_step7]] 새 노드의 FC 이니시에이터 포트를 스위치 영역에 추가합니다.
+
시스템에 테이프 SAN이 있는 경우 이니시에이터에 대해 조닝이 필요합니다. 자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. [[man_install3_step8]] 스토리지 시스템에 FC 이니시에이터 포트를 새 호스트로 추가하여 스토리지 LUN을 새 호스트에 매핑합니다.
+
자세한 내용은 스토리지 배열 및 조닝 설명서를 참조하십시오.

. [[man_install3_step9]] 스토리지 배열의 어레이 LUN과 연결된 호스트 또는 볼륨 그룹에서 WWPN(World Wide Port Name) 값을 수정합니다.
+
새 컨트롤러 모듈을 설치하면 각 온보드 FC 포트에 연결된 WWPN 값이 변경됩니다.

. [[man_install3_step10]] 구성에서 스위치 기반 조닝을 사용하는 경우 새 WWPN 값을 반영하도록 조닝을 조정합니다.
. [[man_install3_step11]] 이제 스토리지 LUN이 노드 3에 표시되는지 확인합니다.
+
'Sysconfig-v'입니다

+
각 FC 이니시에이터 포트에 표시되는 모든 스토리지 LUN이 표시됩니다. 어레이 LUN이 표시되지 않으면 이 섹션의 뒷부분에 있는 노드 1에서 노드 3으로 디스크를 재할당할 수 없습니다.

. [[man_install3_step12]] Ctrl-C를 눌러 부팅 메뉴를 표시하고 유지보수 모드를 선택합니다.
. [[man_install3_step13]] 유지보수 모드 프롬프트에서 다음 명령을 입력합니다.
+
"중지"

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. [[man_install3_step14]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드할 시스템이...에 있는 경우 | 그러면... 


| 이중 섀시 구성(다른 섀시 내 컨트롤러 포함) | 로 이동합니다 <<man_install3_step15,15단계>>. 


| 단일 섀시 구성(동일한 섀시 내 컨트롤러 포함)  a| 
.. 콘솔 케이블을 노드 3에서 노드 4로 전환합니다.
.. 노드 4의 전원을 켠 다음 콘솔 터미널에서 Ctrl-C를 눌러 부팅 프로세스를 중단한 다음, 부팅 환경 프롬프트에 액세스합니다.
+
두 컨트롤러가 동일한 섀시에 있는 경우 전원이 이미 켜져 있어야 합니다.

+
* 참고 *: 부팅 환경 프롬프트에 node4를 그대로 둡니다. 에서 node4로 돌아갑니다 link:install_boot_node4.html["노드 4를 설치하고 부팅합니다"].

.. 에 경고 메시지가 표시되는 경우 <<man_install3_step4,4단계>>의 지침을 따릅니다 <<man_install3_step5,5단계>>
.. 콘솔 케이블을 노드 4에서 노드 3으로 다시 전환합니다.
.. 로 이동합니다 <<man_install3_step15,15단계>>.


|===
. [[man_install3_step15]]ONTAP에 대한 노드 3을 구성합니다.
+
세트 기본값

. [[man_install3_step16]] NSE(NetApp Storage Encryption)를 이 구성에서 사용 중인 경우 'setup bootarg.storageencryption.support' 명령을 'true'로 설정해야 하며, node1 구성이 로드된 후 부트 루프를 방지하려면 kmip.init.maxwait` 변수를 'off'로 설정해야 합니다.
+
에테네 부타그 storageencryption.support true

+
'셋프 kmip.init.maxwait off'

. [[man_install3_step17]] 노드 3에 설치된 ONTAP 버전이 노드 1에 설치된 ONTAP 9 버전과 같거나 이후인 경우 디스크를 새 노드 3에 나열하고 재할당합니다.
+
부트 ONTAP

+

WARNING: * 경고 *: 이 새 노드가 다른 클러스터 또는 HA 쌍에서 사용된 적이 있으면 계속하기 전에 "wipeconfig"를 실행해야 합니다. 그렇지 않으면 서비스 운영 중단이나 데이터 손실이 발생할 수 있습니다. 교체 컨트롤러가 이전에 사용된 경우, 특히 7-Mode에서 ONTAP를 실행 중인 컨트롤러의 경우 기술 지원 부서에 문의하십시오.

. [[man_install3_step18]] Ctrl-C를 눌러 부팅 메뉴를 표시합니다.
. [[man_install3_step19]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 업그레이드 중인 시스템의 경우... | 그러면... 


| node3의 올바른 또는 현재 ONTAP 버전이 _NOT_에 있지 않습니다 | 로 이동합니다 <<man_install3_step20,20단계>>. 


| 노드 3의 ONTAP 버전이 올바르고 현재 버전입니다 | 로 이동합니다 <<man_install3_step25,25단계>>. 
|===
. [[man_install3_step20]] 다음 작업 중 하나를 선택하여 netboot 연결을 구성합니다.
+

NOTE: 관리 포트와 IP를 netboot 연결로 사용해야 합니다. 데이터 LIF IP를 사용하지 마십시오. 업그레이드를 수행하는 동안 데이터 중단이 발생할 수 있습니다.

+
[cols="35,65"]
|===
| DHCP(Dynamic Host Configuration Protocol)가 다음과 같은 경우 | 그러면... 


| 실행 중입니다 | 부트 환경 프롬프트에 'ifconfig e0M-auto'를 입력하여 연결을 자동으로 구성합니다 


| 실행 중이 아닙니다 | 부트 환경 프롬프트에 다음 명령을 입력하여 연결을 수동으로 구성합니다. 'ifconfig e0M -addr=<filer_addr> -mask=<netmask> -GW=<gateway> -DNS=<DNS_addr> domain=<DNS_domain>'<filer_addr>'은 스토리지 시스템의 IP 주소입니다. "<netmask>"는 스토리지 시스템의 네트워크 마스크입니다. '<gateway>'는 스토리지 시스템의 게이트웨이입니다. "<dns_addr>"은 네트워크에 있는 이름 서버의 IP 주소입니다. '<dns_domain>'은 DNS(Domain Name Service) 도메인 이름입니다. 이 선택적 매개 변수를 사용하는 경우 netboot 서버 URL에 정규화된 도메인 이름이 필요하지 않습니다. 서버의 호스트 이름만 있으면 됩니다. * 참고 *: 인터페이스에 다른 매개 변수가 필요할 수 있습니다. 펌웨어 프롬프트에 "help ifconfig"를 입력하여 세부 정보를 확인합니다. 
|===
. [[man_install3_step21]] 노드 3에서 netboot 수행:
+
[cols="35,65"]
|===
| 대상... | 그러면... 


| FAS/AFF8000 시리즈 시스템 | "netboot\http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| 기타 모든 시스템 | "netboot\http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
"<path_to_the_web-Accessible_directory>"는 에서 "<ONTAP_version>_image.tgz"를 다운로드한 위치로 이어져야 합니다 link:prepare_for_netboot.html#man_netboot_Step1["1단계"] netboot_에 대한 준비 섹션에서

+

NOTE: 부팅을 중단하지 마십시오.

. [[man_install3_step22]] 부팅 메뉴에서 옵션 * (7) 새 소프트웨어 설치 * 를 먼저 선택합니다.
+
이 메뉴 옵션은 새 ONTAP 이미지를 다운로드하여 부팅 장치에 설치합니다.

+

NOTE: 다음 메시지는 무시하십시오.

+
[listing]
----
This procedure is not supported for Non-Disruptive Upgrade on an HA pair.
----
+
참고 사항은 ONTAP의 무중단 업그레이드에는 적용되고 컨트롤러 업그레이드에는 적용되지 않습니다.

+

NOTE: 항상 netboot를 사용하여 새 노드를 원하는 이미지로 업데이트합니다. 다른 방법을 사용하여 새 컨트롤러에 이미지를 설치할 경우 잘못된 이미지가 설치될 수 있습니다. 이 문제는 모든 ONTAP 릴리스에 적용됩니다.

. [[man_install3_step23]] 절차를 계속하라는 메시지가 나타나면 y를 입력하고 패키지를 입력하라는 메시지가 나타나면 다음 URL을 입력합니다.
+
'\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. [[man_install3_step24]] 다음 하위 단계를 완료합니다.
+
.. 다음 프롬프트가 표시되면 "n"을 입력하여 백업 복구를 건너뜁니다.
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 다음 프롬프트가 표시되면 y를 입력하여 재부팅합니다.
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
부팅 장치가 다시 포맷되고 구성 데이터를 복원해야 하기 때문에 컨트롤러 모듈이 재부팅되지만 부팅 메뉴에서 중지됩니다.



. [[man_install3_step25]] * (5) Maintenance mode boot * 를 "5"로 입력하고 부팅을 계속하라는 메시지가 나타나면 y 를 입력합니다.
. [[man_install3_step26]] 계속하기 전에 로 이동하십시오 link:set_fc_uta_uta2_config_node3.html["노드 3에 FC 또는 UTA/UTA2 구성을 설정합니다"] 노드의 FC 또는 UTA/UTA2 포트를 필요에 따라 변경합니다.
+
이 섹션에서 권장한 대로 변경하고 노드를 재부팅한 다음 유지보수 모드로 전환합니다.

. [[man_install3_step27]] 노드 3의 시스템 ID를 찾습니다.
+
'디스크 쇼-A'

+
다음 예와 같이 노드의 시스템 ID와 해당 디스크에 대한 정보가 표시됩니다.

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: 명령을 입력하면 '디스크 없음 일치 옵션 -a'라는 메시지가 표시될 수 있습니다. 이 메시지는 오류 메시지가 아니므로 절차를 계속할 수 있습니다.

. [[man_install3_step28]]에서 노드 1의 스페어, 루트에 속한 디스크 및 이전에 노드 2로 재배치되지 않은 모든 비루트 애그리게이트를 다시 할당합니다 link:relocate_non_root_aggr_node1_node2.html["노드 1에서 노드 2로 비루트 애그리게이트를 재배치합니다"].
+
시스템에 공유 디스크가 있는지 여부에 따라 적절한 "디스크 재할당" 명령 형식을 입력합니다.

+
[cols="35,65"]
|===
| 디스크 유형이... | 그런 다음 명령을 실행합니다... 


| 공유 디스크를 사용합니다 | disk reassign -s <node1_sysid> -d <node3_sysid> -p <node2_sysid>' 


| 공유 디스크 사용 안 됨 | disk reassign -s <node1_sysid> -d <node3_sysid>' 
|===
+
"<node1_sysid>" 값에 대해 에서 캡처한 정보를 사용합니다 link:record_node1_information.html["노드1 정보를 기록합니다"]. '<node3_sysid>'의 값을 구하려면 'sysconfig' 명령을 사용합니다.

+

NOTE: '-p' 옵션은 공유 디스크가 있는 경우에만 유지보수 모드에서 필요합니다.

+
"디스크 재할당" 명령은 "<node1_sysid>"가 현재 소유자인 디스크만 다시 할당합니다.

+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]]n'을 입력합니다.
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]] y를 입력합니다
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]] y를 입력합니다.
. [[man_install3_step32] 외부 디스크가 있는 시스템에서 내부 및 외부 디스크를 지원하는 시스템(예: AFF A800 시스템)으로 업그레이드하는 경우 node1 애그리게이트를 root로 설정하여 node3이 node1의 루트 애그리게이트에서 부팅되도록 합니다.
+

WARNING: * 경고 *: 표시된 정확한 순서대로 다음 하위 단계를 수행해야 합니다. 그렇지 않으면 운영 중단이나 데이터 손실이 발생할 수 있습니다.

+
다음 절차에서는 노드 3이 노드 1의 루트 애그리게이트에서 부팅되도록 설정합니다.

+
.. 노드 1 애그리게이트에 대한 RAID, plex 및 체크섬 정보를 확인합니다.
+
'gagr status-r'입니다

.. node1 애그리게이트의 상태를 확인합니다.
+
'기정 상태'입니다

.. 필요한 경우 node1 애그리게이트를 온라인 상태로 전환합니다.
+
'aggr_online <root_aggr_from_node1>'

.. 노드 3이 원래 루트 집합인 '< root_aggr_on_node3>'에서 부팅되지 않도록 합니다
.. 노드 1의 루트 애그리게이트를 노드 3의 새 루트 애그리게이트로 설정합니다.
+
'aggr_from_node1> root' 옵션을 선택합니다

.. 노드 3의 루트 애그리게이트가 오프라인 상태이고 노드 1에서 가져온 디스크의 루트 애그리게이트가 온라인 상태이고 루트:
+
'기정 상태'입니다

+

NOTE: 이전 하위 단계를 수행하지 않으면 노드 3이 내부 루트 애그리게이트에서 부팅되거나 시스템에서 새 클러스터 구성이 있다고 가정하거나 클러스터 구성을 확인하라는 메시지가 표시될 수 있습니다.

+
다음은 명령 출력의 예입니다.



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]] 컨트롤러와 섀시가 "ha"로 구성되었는지 확인합니다.
+
하구성 쇼

+
다음 예제에서는 ha-config show 명령의 출력을 보여 줍니다.

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
시스템은 HA 쌍 또는 독립형 구성에 관계없이 PROM에 기록합니다. 독립 실행형 시스템 또는 HA 쌍 내의 모든 구성 요소에서 상태가 동일해야 합니다.

+
컨트롤러 및 섀시가 "ha"로 구성되지 않은 경우 다음 명령을 사용하여 구성을 수정하십시오.

+
ha-config controller ha

+
하구성 수정 섀시 하

+
MetroCluster 구성이 있는 경우 다음 명령을 사용하여 컨트롤러 및 섀시를 수정합니다.

+
하구성 수정 컨트롤러 MCC

+
하구성 수정 새시 MCC

. [[man_install3_step34]] 노드 3의 메일박스를 제거합니다.
+
'데일박스 파기 지역

+
콘솔에 다음 메시지가 표시됩니다.

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35] 프롬프트에서 "y"를 입력하여 로컬 사서함을 제거할 것인지 확인합니다.
. [[man_install3_step36]] 유지보수 모드 종료:
+
"중지"

+
부팅 환경 프롬프트에서 시스템이 중지됩니다.

. [[man_install3_step37]] 노드2에서 시스템 날짜, 시간 및 시간대를 확인합니다.
+
다

. [[man_install3_step38]]노드 3에서 부팅 환경 프롬프트에서 날짜를 확인합니다.
+
날짜

. [[man_install3_step39]] 필요한 경우 노드 3의 날짜를 설정합니다.
+
'날짜 설정 < mm/dd/yyyy>'

. [[man_install3_step40]] 노드 3에서 부팅 환경 프롬프트에서 시간을 확인합니다.
+
'시간'입니다

. [[man_install3_step41]] 필요한 경우 노드 3의 시간을 설정합니다.
+
'세트 시간<hh:mm:ss>'

. [[man_install3_step42]]에 설명된 대로 파트너 시스템 ID가 올바르게 설정되었는지 확인합니다 <<man_install3_step28,28단계>> 언더-p 스위치:
+
'printenv partner-sysid

. [[man_install3_step43]] 필요한 경우 노드 3의 파트너 시스템 ID를 설정합니다.
+
'setenv PARTNER-sysid <node2_sysid>'

+
설정을 저장합니다.

+
'사베에프'

. [[man_install3_step44]] 부트 환경 프롬프트에서 부팅 메뉴에 액세스합니다.
+
boot_ontap 메뉴

. [[man_install3_step45]] 부팅 메뉴에서 * (6) 백업 구성에서 플래시 업데이트 * 옵션을 선택하고 프롬프트에서 '6'을 입력합니다.
+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]] 프롬프트에 y를 입력합니다.
+
부팅이 정상적으로 진행되면 시스템에서 시스템 ID 불일치를 확인하라는 메시지를 표시합니다.

+

NOTE: 시스템이 두 번 재부팅된 후 불일치 경고가 표시될 수 있습니다.

. [[man_install3_step47]] 다음 예와 같이 불일치를 확인합니다.
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
노드가 재부팅 1회 과정을 거치는 동안 정상적으로 부팅될 수 있습니다.

. [[man_install3_step48]]노드 3에 로그인합니다.

