= 


노드 2에서 노드 3으로 애그리게이트를 재배치한 후에는 노드 2가 소유한 NAS 데이터 LIF를 노드 3으로 이동해야 합니다.

원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 3에서 노드 4로 LIF를 이동하고 노드 4를 온라인 상태로 설정한 후 LIF가 정상 작동하는지 확인해야 합니다.

.단계
. [[step1]] 노드 중 하나에 다음 명령을 입력하고 출력을 캡처하여 node2가 소유한 모든 NAS 데이터 LIF를 나열합니다.
+
'network interface show-data-protocol nfs|cifs-home-node<node2>'

+
다음 예제에서는 node2의 명령 출력을 보여 줍니다.

+
[listing]
----
cluster::> network interface show -data-protocol nfs|cifs -home-node node2
              Logical     Status      Network             Current  Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node     Port     Home
 -----------  ----------  ----------  ------------------  -------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node2    a0a      true
              data1       up/up       10.63.0.50/18       node2    e0c      true
              rads1       up/up       10.63.0.51/18       node2    e1a      true
              rads2       up/down     10.63.0.52/24       node2    e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node2    e0c      true
              lif2        up/up       172.17.176.121/24   node2    e1a      true
----
. [[step2]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드2의 경우 | 그러면... 


| 인터페이스 그룹 또는 VLAN이 구성되어 있습니다 | 로 이동합니다 <<man_move_lif_2_3_step3,3단계>>. 


| 인터페이스 그룹 또는 VLAN이 구성되어 있지 않습니다 | 3단계를 건너뛰고 로 이동합니다 <<man_move_lif_2_3_step4,4단계>>. 
|===
. [[man_move_lif_2_3_step3]]노드 2의 인터페이스 그룹 및 VLAN에 호스팅된 NAS 데이터 LIF를 마이그레이션하려면 다음 단계를 수행하십시오.
+
.. [[man_move_lif_2_3_substeepa]] 노드 2의 인터페이스 그룹에 호스팅된 데이터 LIF를 노드 3의 포트로 마이그레이션: 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
'network interface migrate-vserver <Vserver_NAME> -lif <LIF_name> -destination-node <node3> – destination-port <NetPort | ifgrp>'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_move_lif_2_3_substepa,하위 단계 A>> 각 노드에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver <Vserver_NAME> -lif <LIF_name> -home-node <node3> -homedport <NetPort | ifgrp>'

.. [[man_move_lif_2_3_substeepc]] 노드 2의 VLAN에 호스팅된 모든 LIF를 노드 3의 포트로 마이그레이션 합니다. 노드 3에서는 각 LIF에 대해 다음 명령을 한 번 입력하여 VLAN과 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
'network interface migrate-vserver <Vserver_NAME> -lif <LIF_name> -destination-node <node3> – destination-port <NetPort | ifgrp>'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_move_lif_2_3_substepc,하위 단계 c>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver <Vserver_NAME> -lif <LIF_name> -home-node <node3> -homedport <NetPort | ifgrp>'



. [[man_move_lif_2_3_step4]] 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가 구성된 경우... | 그러면... 


| NAS | 완료 <<man_move_lif_2_3_step5,5단계>> 부터 까지 <<man_move_lif_2_3_step8,8단계>>. 


| 산 | 5단계 - 8단계를 건너 뛴 다음 완료합니다 <<man_move_lif_2_3_step9,9단계>>. 


| NAS 및 SAN 모두 지원 | 완료 <<man_move_lif_2_3_step5,5단계>> 부터 까지 <<man_move_lif_2_3_step9,9단계>>. 
|===
. [[man_move_lif_2_3_step5]] 플랫폼에서 동일하지 않은 데이터 포트가 있는 경우 브로드캐스트 도메인에 포트를 추가합니다.
+
'network port broadcast-domain add-ports-IPSpace <IPspace_name> - broadcast-domain mgmt-ports <node:port>'

+
다음 예에서는 노드 "6280-1"의 포트 "e0a"와 노드 "8060-1"의 포트 "e0i"를 IPspace "Default"의 브로드캐스트 도메인 "mgmt"에 추가합니다.

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default
           -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. [[step6]]각 LIF에 대해 다음 명령을 한 번 입력하여 각 NAS 데이터 LIF를 노드 3으로 마이그레이션합니다.
+
'network interface migrate-vserver <Vserver_NAME> -lif <LIF_name> -destination-node <node3> -destination-port <NetPort | ifgrp>'

. [[step7]] 두 노드 중 하나에 다음 명령을 입력하고 출력을 검사하여 NAS LIF가 올바른 포트로 이동되었으며 LIF의 상태가 UP인지 확인하십시오.
+
'network interface show-curr-node <node3> - data-protocol cifs | nfs'

. [[man_move_lif_2_3_step8]]LIF가 다운된 경우, 각 LIF에 대해 다음 명령을 한 번 입력하여 LIF의 관리 상태를 "UP"으로 설정하십시오.
+
'network interface modify -vserver <Vserver_NAME> -lif <LIF_name> -status-admin up'

. [[man_move_lif_2_3_step9]] 인터페이스 그룹 또는 VLAN이 구성된 경우 다음 하위 단계를 완료합니다.
+
.. 인터페이스 그룹에서 VLAN을 제거합니다.
+
'network port vlan delete-node <node_name> -port <ifgrp> -vlan-id <VLAN_ID>'

.. 다음 명령을 입력하고 출력을 검사하여 노드에 구성된 인터페이스 그룹이 있는지 확인합니다.
+
'network port ifgrp show-node <node_name>-ifgrp <ifgrp_name>-instance'

+
다음 예에서와 같이 노드에 대한 인터페이스 그룹 정보가 표시됩니다.

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node2
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: MAC_address
    ort Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. 노드에 인터페이스 그룹이 구성되어 있는 경우 인터페이스 그룹 이름과 그룹에 할당된 포트를 기록한 다음 각 포트에 대해 다음 명령을 한 번 입력하여 포트를 삭제합니다.
+
'network port ifgrp remove-port-node <node_name>-ifgrp <ifgrp_name>-port <port_name>'




