= 


설정이 올바른지 확인하려면 HA 쌍을 활성화해야 합니다. 또한 노드 3과 노드 4가 서로의 스토리지에 액세스할 수 있고 클러스터의 다른 노드에 속하는 데이터 LIF가 소유하지 않는지 확인해야 합니다. 또한 노드 3이 노드 1의 애그리게이트를 소유하고, 노드 4가 노드 2의 애그리게이트를 소유하고, 두 노드의 볼륨이 온라인 상태인지 확인해야 합니다.

.단계
. 노드 중 하나에 다음 명령을 입력하여 스토리지 페일오버를 설정합니다.
+
'Storage failover modify -enabled true-node <node3>'

. 스토리지 페일오버가 설정되었는지 확인합니다.
+
'스토리지 페일오버 쇼'

+
다음 예에서는 스토리지 페일오버가 설정된 경우의 명령 출력을 보여 줍니다.

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 다음 작업 중 하나를 수행합니다.
+
|===
| 클러스터가 인 경우... | 설명 


| 2노드 클러스터 | "cluster ha modify -configured true"라는 두 노드 중 하나에 다음 명령을 입력하여 클러스터 고가용성을 사용하도록 설정합니다 


| 2개 이상의 노드가 있는 클러스터 | 로 이동합니다 <<man_ensure_setup_Step4,4단계>>. 
|===
. [[man_sify_setup_Step4]] 다음 명령을 입력하고 출력을 검사하여 node3과 node4가 동일한 클러스터에 속해 있는지 확인합니다.
+
'클러스터 쇼'

. 다음 명령을 입력하고 출력을 검사하여 node3과 node4가 서로의 스토리지에 액세스할 수 있는지 확인합니다.
+
'Storage failover show - fields local-missing-disks, partner-missing-disks'

. 다음 명령을 입력하고 출력을 검사하여 node3과 node4가 클러스터의 다른 노드에서 소유하는 데이터 LIF를 소유하지 않는지 확인합니다.
+
네트워크 인터페이스 쇼

+
노드 3이나 노드 4에서 클러스터의 다른 노드가 소유한 데이터 LIF가 있으면 'network interface revert' 명령을 사용하여 데이터 LIF를 홈 소유자에게 되돌리십시오.

. 노드 3이 노드 1의 애그리게이트를 소유하고 있고 노드 4가 노드 2의 애그리게이트를 소유하고 있는지 확인합니다.
+
'Storage aggregate show-owner-name <node3>''Storage aggregate show-owner-name <node4>'

. 볼륨이 오프라인 상태인지 확인합니다.
+
'volume show-node <node3> - state offline''volume show-node <node4> - state offline'

. 오프라인 상태인 볼륨이 있으면 에서 캡처한 오프라인 볼륨 목록과 비교합니다 link:prepare_nodes_for_upgrade.html#step19d["19단계(d)"] 에서 업그레이드할 노드를 준비하고 필요에 따라 각 볼륨에 대해 다음 명령을 한 번 입력하여 오프라인 볼륨을 온라인 상태로 전환합니다.
+
'volume online-vserver <vserver-name> - volume <volume_name>'

. 각 노드에 대해 다음 명령을 입력하여 새 노드에 대한 새 라이센스를 설치합니다.
+
'system license add-license-code <license_code, license_code, license_code...>'

+
license-code 매개변수는 28개의 대문자 알파벳 문자 키 목록을 허용합니다. 한 번에 하나의 라이센스를 추가하거나, 각 라이센스 키를 쉼표로 구분하여 한 번에 여러 라이센스를 추가할 수 있습니다.

. NSE(NetApp Storage Encryption)를 구성에서 사용 중인 경우 'kmip.init.maxwait` 변수'를 사용하지 않고 'setup.storageenv.storageencryption.support'명령을 "true"로 설정합니다(의 경우) link:install_boot_node3.html#step16["16단계"] /_Install 및 boot node3_) 변수를 재설정해야 합니다. set diag;systemshell-node<node-name> -command sudo kenv -u -p kmip.init.maxwait`
. 원래 노드에서 이전 라이센스를 모두 제거하려면 다음 명령 중 하나를 입력합니다.
+
'System license clean-up-unused-expired''system license delete-serial-number <node_serial_number>-package <licensable_package>'를 입력합니다

+
** 만료된 라이센스를 모두 삭제하려면 다음을 입력합니다.
+
'시스템 사용권 정리 - 만료됨'

** 사용하지 않는 라이선스를 모두 삭제하려면 다음을 입력합니다.
+
'시스템 라이센스 정리 - 미사용

** 클러스터에서 특정 라이센스를 삭제하려면 노드에서 다음 명령을 입력합니다.
+
'system license delete-serial-number <node1-serial-number>-package * ''system license delete-serial-number <node2-serial-number>-package *'

+
다음 출력이 표시됩니다.

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
모든 패키지를 제거하려면 y를 입력하십시오.



. 다음 명령을 입력하고 출력을 확인하여 라이센스가 올바르게 설치되었는지 확인합니다.
+
'시스템 사용권 프로그램'

+
에서 캡처한 출력과 출력을 비교할 수 있습니다 link:prepare_nodes_for_upgrade.html#step30["30단계"] 의 _ 업그레이드 _ 을(를) 위해 노드를 준비합니다.

. 두 노드에서 다음 명령을 수행하여 SP를 구성합니다.
+
'System service-processor network modify -node <node-name>'

+
로 이동합니다 link:other_references.html["참조"] SP 및 _ONTAP 9 명령에 대한 자세한 내용은 시스템 관리 참조_에 링크하기 위해 '시스템 서비스 프로세서 네트워크 수정' 명령에 대한 자세한 내용은 수동 페이지 참조_를 참조하십시오.

. 새 노드 중 하나에 대해 다음 작업을 수행합니다.
+
.. 다음 명령을 입력하여 고급 권한 수준을 입력합니다.
+
세트 프리빌리지 고급

.. 다음 명령을 입력합니다.
+
'storage failover modify -node <node-name> -cifs-ndo-duration default | medium | low'

+
*** 시스템에서 작업 부하의 50% ~ 75%가 4KB 이하인 경우 '중간'을 입력합니다.
*** 시스템의 작업 부하가 75%에서 100%로 4KB 이하인 경우 'low'를 입력합니다.


.. 다음 명령을 입력하여 admin 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다

.. 변경 사항이 적용되도록 시스템을 재부팅합니다.


. 새 노드에서 스위치가 없는 클러스터를 설정하려면 로 이동하십시오 link:other_references.html["참조"] _Network Support 사이트_에 연결하고 스위치가 없는 2노드 클러스터_로 전환 의 지침을 따르십시오.


노드 3과 노드 4에서 스토리지 암호화가 설정된 경우 의 단계를 완료합니다 link:set_up_storage_encryption_new_controller.html["새 컨트롤러 모듈에서 스토리지 암호화를 설정합니다"]. 그렇지 않으면 의 단계를 완료합니다 .
