= 


노드 2를 폐기하려면 노드 2를 올바르게 종료하고 랙 또는 섀시에서 제거해야 합니다. 클러스터가 SAN 환경에 있는 경우 SAN LIF도 삭제해야 합니다.

.단계
. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가... | 그러면... 


| 2노드 클러스터 | 로 이동합니다 <<man_retire_2_Step2,2단계>>. 


| 2개 이상의 노드가 있는 클러스터 | 로 이동합니다 <<man_retire_2_Step9,9단계>>. 
|===
. [[man_Retire_2_Step2]] 두 노드 중 하나에 다음 명령을 입력하여 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

. 다음 명령을 입력하고 출력을 확인하여 클러스터 HA가 비활성화되었는지 확인합니다.
+
군산쇼

+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
High Availability Configured: false
----
. 다음 명령을 입력하고 출력을 검사하여 노드 2에 현재 epsilon이 있는지 확인합니다.
+
'클러스터 쇼'

+
다음 예에서는 node2에 epsilon 이 있음을 보여 줍니다.

+
[listing]
----
cluster*::> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -----------
node1                true    true          false
node2                true    true          true

Warning: Cluster HA has not been configured. Cluster HA must be configured on a two-node cluster to ensure data access availability in the event of storage failover. Use the "cluster ha modify -configured true" command to configure cluster HA.

2 entries were displayed.
----
. 노드 2가 epsilon을 포함하는 경우 epsilon을 노드 3으로 전송할 수 있도록 노드에 "false"로 표시합니다.
+
'cluster modify-node <node2>-epsilon FALSE

. 노드 3에서 epsilon 'true'를 표시하여 epsilon을 노드 3으로 전송:
+
'cluster modify-node <node3>-epsilon TRUE

. 스위치가 없는 2노드 클러스터인지 확인합니다.
+
'network options switchless-cluster show'

+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
이 명령의 값은 시스템의 물리적 상태와 일치해야 합니다.

. 스위치가 없는 2노드 클러스터인지 확인합니다.
+
'network options switchless-cluster show'

+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
이 명령의 값은 시스템의 물리적 상태와 일치해야 합니다.

. [[man_Retire_2_Step9]] 관리자 수준으로 돌아가기:
+
'Set-Privilege admin'입니다

. 두 컨트롤러 중 하나에 'system node halt-node <node2>' 명령을 입력하여 노드 2를 중단합니다
. 노드 2가 완전히 종료된 후 섀시 또는 랙에서 분리합니다. 업그레이드가 완료된 후 노드 2를 사용 중단할 수 있습니다. 을 참조하십시오 link:decommission_old_system.html["기존 시스템을 폐기합니다"].

