= 


노드 1을 폐기하려면 노드 2와 HA 쌍을 비활성화하고 노드 1을 적절하게 종료한 다음 랙 또는 섀시에서 제거해야 합니다.

.단계
. 클러스터의 노드 수 확인:
+
'클러스터 쇼'

+
다음 예에서와 같이 시스템이 클러스터의 노드를 표시합니다.

+
[listing]
----
cluster::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.
----
. [[man_Retire_1_step2]] 해당되는 경우 스토리지 페일오버를 해제합니다.
+
[cols="35,65"]
|===
| 클러스터가... | 그러면... 


| 2노드 클러스터  a| 
.. 두 노드 중 하나에 다음 명령을 입력하여 클러스터 고가용성을 사용하지 않도록 설정합니다.


클러스터 하 수정-구성 거짓

.. 스토리지 페일오버 해제:


'Storage failover modify-node <node1> - enabled false'



| 2개 이상의 노드가 있는 클러스터 | 스토리지 페일오버 해제:'스토리지 페일오버 수정 - 노드 <node1> 설정 false' 
|===
. 스토리지 페일오버가 비활성화되었는지 확인:
+
'스토리지 페일오버 쇼'

+
다음 예는 노드에 대해 스토리지 페일오버가 비활성화되었을 때 'storage failover show' 명령의 출력을 보여줍니다.

+
[listing]
----
 cluster::> storage failover show
                               Takeover
 Node           Partner        Possible State Description
 -------------- -------------- -------- -------------------------------------
 node1          node2          false    Connected to node2, Takeover
                                        is not possible: Storage failover is
                                        disabled

 node2          node1          false    Node owns partner's aggregates as part
                                        of the nondisruptive controller upgrade
                                        procedure. Takeover is not possible:
                                        Storage failover is disabled
 2 entries were displayed.
----
. 데이터 LIF 상태를 확인합니다.
+
'network interface show-role data-currr-node <node2> - home-node <node1>'

+
LIF가 다운되었는지 확인하려면 * Status Admin/Oper * 열을 확인하십시오. LIF가 다운된 경우 에 문의하십시오 link:troubleshoot.html["그을음 문제"] 섹션을 참조하십시오.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가... | 그러면... 


| 2노드 클러스터 | 로 이동합니다 <<man_retire_1_step6,6단계>>. 


| 2개 이상의 노드가 있는 클러스터 | 로 이동합니다 <<man_retire_1_step8,8단계>>. 
|===
. [[man_Retire_1_step6]]두 노드 중 하나에서 고급 권한 수준에 액세스합니다.
+
세트 프리빌리지 고급

. [[7단계]] 클러스터 HA가 비활성화되었는지 확인:
+
군산쇼

+
다음과 같은 메시지가 표시됩니다.

+
[listing]
----
High Availability Configured: false
----
+
클러스터 HA가 비활성화되지 않았으면 반복합니다 <<man_retire_1_step2,2단계>>.

. [[man_Retire_1_step8]] 노드 1에 현재 epsilon 이 있는지 확인:
+
'클러스터 쇼'

+
노드의 수가 짝수인 클러스터에서 타이 가능성이 있기 때문에 노드 하나에 epsilon이라는 추가 분수 투표 중량이 있습니다. 을 참조하십시오 link:other_references.html["참조"] 자세한 내용은 _시스템 관리 참조_에 대한 링크를 참조하십시오.

+

NOTE: 4노드 클러스터가 있는 경우 epsilon은 클러스터의 다른 HA 쌍의 노드에 있을 수 있습니다.

+
다음 예에서는 node1에 epsilon 이 있음을 보여 줍니다.

+
[listing]
----
 cluster::*> cluster show

 Node                 Health  Eligibility  Epsilon
 -------------------- ------- ------------ ------------
 node1                true    true         true
 node2                true    true         false
----
. node1에 epsilon이 있으면 해당 노드가 node2로 전송될 수 있도록 노드에 epsilon 'false'를 표시합니다.
+
'cluster modify-node <node1>-epsilon FALSE

. 노드 2에서 epsilon 'true'를 표시하여 epsilon을 노드 2로 전송:
+
'cluster modify-node <node2>-epsilon TRUE

. 노드 2에 대한 변경 사항이 발생했는지 확인합니다.
+
'클러스터 쇼'

+
[listing]
----
 cluster::*> cluster show
 Node                 Health  Eligibility  Epsilon
 -------------------- ------- ------------ ------------
 node1                true    true         false
 node2                true    true         true
----
+
이제 node2의 epsilon은 참이고 node1의 epsilon은 거짓이어야 합니다.

. 스위치가 없는 2노드 클러스터인지 확인합니다.
+
'network options switchless-cluster show'

+
[listing]
----
 cluster::*> network options switchless-cluster show

 Enable Switchless Cluster: false/true
----
+
이 명령의 값은 시스템의 물리적 상태와 일치해야 합니다.

. 관리자 수준으로 돌아가기:
+
'Set-Privilege admin'입니다

. node1 프롬프트에서 node1을 중단합니다.
+
'System node halt-node <node1>'

+

WARNING: *주의*: 노드1이 노드2와 동일한 섀시에 있는 경우 전원 스위치를 사용하거나 전원 케이블을 당겨 섀시의 전원을 끄지 마십시오. 이렇게 하면 데이터를 제공하는 노드 2가 중단되며

. 시스템을 중지할지 묻는 메시지가 표시되면 y를 입력합니다.
+
부팅 환경 프롬프트에서 노드가 중지됩니다.

. 노드 1에 부팅 환경 프롬프트가 표시되면 섀시 또는 랙에서 분리합니다.
+
업그레이드가 완료된 후 노드 1을 사용 중단할 수 있습니다. 을 참조하십시오 link:decommission_old_system.html["기존 시스템을 폐기합니다"].


