= 
:allow-uri-read: 


노드 1을 노드 3으로 교체하려면 먼저 storage aggregate relocation 명령을 사용하여 비루트 애그리게이트를 노드 1에서 노드 2로 이동한 다음 재배치를 확인해야 합니다.

.단계
. [[1단계]] 다음 하위 단계를 완료하여 비루트 애그리게이트를 재배치합니다.
+
.. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

.. 다음 명령을 입력합니다.
+
'storage aggregate relocation start-node <node1> - destination <node2> - aggregate-list * -ndo-controller-upgrade true'

.. 메시지가 나타나면 y를 입력합니다.
+
재배치가 백그라운드에서 수행됩니다. Aggregate를 재배치하는 데 몇 초에서 몇 분 정도 걸릴 수 있습니다. 이 시간은 클라이언트 정전과 비운영 시간 부분을 모두 포함합니다. 명령을 실행해도 오프라인 또는 제한된 애그리게이트는 재배치되지 않습니다.

.. 다음 명령을 입력하여 admin 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



. node1에서 다음 명령을 입력하여 재배치 상태를 확인합니다.
+
'Storage aggregate relocation show-node <node1>'를 선택합니다

+
이 출력은 재배치된 후 Aggregate에 대해 Done을 표시합니다.

+

NOTE: 노드 1이 소유한 모든 비루트 애그리게이트가 노드 2로 재배치될 때까지 기다린 후 다음 단계로 넘어갑니다.

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 재배치... | 그러면... 


| 성공적으로 모든 애그리게이트를 완료했습니다 | 로 이동합니다 <<man_relocate_1_2_step4,4단계>>. 


| 거부권을 행사하는 모든 애그리게이트 중 하나에 장애가 발생하거나 거부되는 애그리게이트가 있습니다  a| 
.. EMS 로그에서 수정 조치를 확인합니다.
.. 수정 조치를 수행합니다.
.. 장애가 발생하거나 거부된 Aggregate 재배치: 'Storage aggregate Relocation start-node <node1> - destination <node2> - aggregate-list * -ndo-controller-upgrade true
.. 메시지가 나타나면 y를 입력합니다.
.. 관리자 수준으로 돌아가기: 'Set-Privilege admin' 필요한 경우 다음 방법 중 하나를 사용하여 재배치를 수행할 수 있습니다.
+
*** 거부권 확인 무시: 스토리지 집계 재배치 시작-재정의-실제 -ndo-controller-upgrade
*** 스토리지 애그리게이트 재배치 start-override-destination-checks true-ndo-controller-upgrade'라는 타겟 검사를 재정의합니다




을 참조하십시오 link:other_references.html["참조"] 스토리지 애그리게이트 재배치 명령에 대한 자세한 내용은 _Disks 및 Aggregates Power Guide_ 및 _ONTAP 9 명령에 대한 링크를 참조하십시오.

|===
. [[man_relocate_1_2_step4]]루트가 아닌 모든 애그리게이트가 온라인 상태이고 노드 2의 상태가 온라인인지 확인합니다.
+
'Storage aggregate show-node <node2> - state online-root false'

+
다음 예제에서는 노드 2의 루트 이외의 애그리게이트가 온라인 상태인 것을 보여 줍니다.

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr_1
           744.9GB 744.8GB      0% online       5 node2            raid_dp,
                                                                   normal
aggr_2     825.0GB 825.0GB      0% online       1 node2            raid_dp,
                                                                   normal
2 entries were displayed.
----
+
노드 2에서 애그리게이트가 오프라인 상태가 되거나 외부 상태가 된 경우, 각 애그리게이트에 대해 노드 2의 다음 명령을 사용하여 온라인 상태로 전환합니다.

+
'Storage aggregate online-aggregate <aggr_name>'

. node2에서 다음 명령을 입력하고 해당 출력을 검사하여 node2에서 모든 볼륨이 온라인 상태인지 확인합니다.
+
'volume show-node <node2> - state offline(볼륨 표시 노드 <node2> - 상태 오프라인)

+
노드 2에 오프라인 볼륨이 있는 경우 각 볼륨에 대해 한 번씩 노드 2에서 다음 명령을 사용하여 온라인으로 전환합니다.

+
'volume online-vserver <vserver-name> - volume <volume-name>'

+
이 명령에 사용할 vserver-name은 이전 'volume show' 명령의 출력에서 확인할 수 있습니다.

. 노드 2에서 다음 명령을 입력합니다.
+
'Storage failover show-node <node2>'를 선택합니다

+
출력에는 다음 메시지가 표시됩니다.

+
[listing]
----
Node owns partner's aggregates as part of the nondisruptive controller upgrade procedure.
----
. 노드 1이 온라인인 루트 이외의 Aggregate를 소유하지 않는지 확인합니다.
+
스토리지 집계 show-owner-name <node1>-ha-policy SFO-state online

+
이미 노드 2로 재배치되었던 온라인 비 루트 애그리게이트는 출력에 표시되지 않아야 합니다.


