= 


원격 LIF는 업그레이드 절차 중에 SAN LUN의 트래픽을 처리합니다. 업그레이드 중에 클러스터 또는 서비스 상태를 위해 SAN LIF를 이동할 필요가 없습니다. SAN LIF는 새 포트에 매핑되지 않으면 이동하지 않습니다. 노드 4를 온라인으로 설정한 후 LIF가 정상 작동하는지 확인합니다.

.단계
. 노드 3에서 소유하지 않은 모든 NAS 데이터 LIF를 표시하려면 두 노드 중 하나에 다음 명령을 입력하고 출력을 캡처합니다.
+
네트워크 인터페이스 show-role data-curr-node node3은 -home false입니다

. 다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 노드2의 경우 | 설명 


| 인터페이스 그룹 또는 VLAN이 구성되어 있었습니다 | 로 이동합니다 <<man_lif_verify_4_Step3,3단계>>. 


| 인터페이스 그룹 또는 VLAN이 구성되지 않았습니다 | 3단계를 건너뛰고 로 이동합니다 <<man_lif_verify_4_Step4,4단계>>. 
|===
. [[man_lif_verify_4_Step3] 다음 단계에 따라 원래 노드 3에서 노드 4로 노드 2에 있던 인터페이스 그룹 및 VLAN에 호스팅된 NAS 데이터 LIF를 모두 마이그레이션합니다.
+
.. [[man_lif_verify_4_substa]] 인터페이스 그룹의 node2에 이미 속해 있는 node3에 호스팅된 모든 LIF를 노드 4의 포트로 마이그레이션: 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에서 LIF를 호스팅할 수 있습니다.
+
'network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node node4 –destination-port <NetPort | ifgrp>'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_4_substepa,하위 단계 A>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver <vserver_name> -lif <datalif_name> -home-node node4 home-port <NetPort | ifgrp>'

.. [[man_lif_verify_4_substeepc]] 이전에 VLAN 포트의 node2에 속해 있던 node3에 호스팅된 모든 LIF를 노드 4의 포트로 마이그레이션합니다. 노드 4에서는 각 LIF에 대해 다음 명령을 한 번 입력하여 동일한 네트워크에 LIF를 호스팅할 수 있습니다.
+
'network interface migrate -vserver <vserver_name> -lif <datalif_name> -destination-node node4 –destination-port <NetPort | ifgrp>'

.. 에서 LIF의 홈 포트 및 홈 노드를 수정합니다 <<man_lif_verify_4_substepc,하위 단계 c>> 각 LIF에 대해 다음 명령을 입력하여 현재 LIF를 호스팅하는 포트 및 노드에 대해 다음을 수행합니다.
+
'network interface modify -vserver <vserver_name> -lif <datalif_name> -home-node <node4>home-port <NetPort | ifgrp>'



. [[man_lif_verify_4_Step4]]다음 작업 중 하나를 수행합니다.
+
[cols="35,65"]
|===
| 클러스터가 구성된 경우... | 그러면... 


| NAS | 완료 <<man_lif_verify_4_Step5,5단계>> 부터 까지 <<man_lif_verify_4_Step8,8단계>>, 9단계를 건너뛰고 완료합니다 <<man_lif_verify_4_Step10,10단계>> 부터 까지 <<man_lif_verify_4_Step13,13단계>>. 


| 산 | 5단계 - 8단계를 건너뛰고 완료합니다 <<man_lif_verify_4_Step9,9단계>> 부터 까지 <<man_lif_verify_4_Step13,13단계>>. 


| NAS 및 SAN 모두 지원 | 완료 <<man_lif_verify_4_Step5,5단계>> 부터 까지 <<man_lif_verify_4_Step13,13단계>>. 
|===
. [[man_lif_verify_4_Step5]] 플랫폼에서 동일하지 않은 데이터 포트가 있는 경우 다음 명령을 입력하여 브로드캐스트 도메인에 포트를 추가합니다.
+
'network port broadcast-domain add-ports-IPSpace <IPspace_name> - broadcast-domain mgmt ports <node:port>'

+
다음 예에서는 노드 "6280-1"의 포트 "e0a"와 노드 "8060-1"의 포트 "e0i"를 IPspace에서 브로드캐스트 도메인 관리에 추가합니다. 기본값:

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. 각 LIF에 대해 다음 명령을 한 번 입력하여 각 NAS 데이터 LIF를 노드 4로 마이그레이션합니다.
+
'network interface migrate-vserver <vserver-name> -lif <datalif-name> -destination-node <node4> -destination-port <NetPort | ifgrp> -home-node <node4>'

. 데이터 마이그레이션이 영구한지 확인:
+
'network interface modify -vserver <vserver_name> -lif <datalif_name> -home-port <NetPort | ifgrp>'

. [[man_lif_verify_4_Step8]] 다음 명령어를 입력하여 모든 네트워크 포트를 나열하고 출력을 확인하여 모든 링크의 상태를 "up"으로 확인한다.
+
네트워크 포트 쇼

+
다음 예에서는 일부 LIF가 작동 중지되어 있는 'network port show' 명령의 출력을 보여 줍니다.

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. [[man_lif_verify_4_Step9] 'network port show' 명령의 출력에 새 노드에서 사용할 수 없고 이전 노드에 있는 네트워크 포트가 표시되면 다음 하위 단계를 완료하여 이전 네트워크 포트를 삭제합니다.
+
.. 다음 명령을 입력하여 고급 권한 수준을 입력합니다.
+
세트 프리빌리지 고급

.. 각 이전 네트워크 포트에 대해 다음 명령을 한 번 입력합니다.
+
'network port delete-node <node_name> - port <port_name>'

.. 다음 명령을 입력하여 admin 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



. [[man_lif_verify_4_Step10]] 다음 하위 단계를 완료하여 SAN LIF가 노드 4의 올바른 포트에 있는지 확인합니다.
+
.. 다음 명령을 입력합니다.
+
네트워크 인터페이스 show-data-protocol iscsi | fcp-home-node node4

+
시스템은 다음 예제와 유사한 출력을 반환합니다.

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node3         a0a     true
            data1        up/up    10.63.0.50/18      node3         e0c     true
            rads1        up/up    10.63.0.51/18      node3         e1a     true
            rads2        up/down  10.63.0.52/24      node3         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node3         e0c     true
            lif2         up/up    172.17.176.121/24  node3
----
.. 노드 4에 SAN LIF 또는 SAN LIF 그룹이 노드 2에 없는 포트에 있는 경우 다음 명령 중 하나를 입력하여 해당 LIF를 노드 4의 적절한 포트로 이동합니다.
+
... LIF 상태를 아래로 설정합니다.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> -status -admin down'

... 포트 세트에서 LIF를 제거합니다.
+
' remove-vserver <vserver_name> - 포트셋 <포트셋_이름> -포트-이름 <포트_이름>'

... 다음 명령 중 하나를 입력합니다.
+
**** 단일 LIF 이동:
+
'network interface modify -lif <lif_name> - home-port <new_home_port>'

**** 존재하지 않거나 잘못된 단일 포트에 있는 모든 LIF를 새 포트로 이동:
+
'{-home-port <port_on_node2> -home-node <node2> -role data} -home-port <new_home_port_on_node4>' 네트워크 인터페이스 수정

**** 포트 세트에 LIF를 다시 추가합니다.
+
'<add-vserver_name> - 포트셋 <포트셋_이름> -포트-이름 <포트_이름>'







+

NOTE: SAN LIF를 원래 포트와 동일한 링크 속도를 가진 포트로 이동해야 합니다.

. LIF가 다음 명령을 입력하여 노드에서 트래픽을 허용하고 전송할 수 있도록 모든 LIF의 상태를 "Up"으로 수정합니다.
+
'network interface modify -vserver <vserver_name> -home-port <port_name> -home-node <node4>lif <lif_name> -status-admin up'

. SAN LIF가 올바른 포트로 이동되었으며, 두 노드 중 하나에 다음 명령을 입력하고 출력을 검사하여 LIF 상태가 'UP'인지 확인하십시오.
+
'network interface show-home-node <node4> - role data'

. [[man_lif_verify_4_Step13] LIF가 다운된 경우 각 LIF에 대해 다음 명령을 한 번 입력하여 LIF의 관리 상태를 'up'으로 설정하십시오.
+
'network interface modify -vserver <vserver_name> -lif <lif_name> -status -admin up'


