= 
:allow-uri-read: 


장애가 발생한 I/O 모듈을 안전하게 제거할 수 있도록 스토리지 시스템과 I/O 모듈 슬롯을 준비하십시오.

.단계
. 적절하게 접지합니다.
. 케이블에 라벨을 붙여 케이블이 연결된 위치를 식별한 다음 대상 I/O 모듈에서 모든 케이블을 분리하십시오.
+
[NOTE]
====
I/O 모듈에 오류가 발생해야 합니다(포트가 링크 다운 상태여야 함). 그러나 링크가 여전히 활성화되어 있고 마지막으로 작동하는 클러스터 포트가 포함되어 있는 경우 케이블을 분리하면 자동 테이크오버가 트리거됩니다.

케이블을 분리한 후 5분 정도 기다려 테이크오버 또는 LIF 페일오버가 완전히 완료되었는지 확인한 후 이 절차를 진행하십시오.

====
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
예를 들어, 다음 AutoSupport 메시지는 2시간 동안 자동 케이스 생성을 억제합니다.

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. 파트너 노드가 테이크오버된 경우 자동 반환을 비활성화합니다.
+
[cols="1,2"]
|===
| 만약... | 그러면... 


 a| 
어느 한쪽 컨트롤러가 자동으로 파트너를 인수한 경우
 a| 
자동 환불 비활성화:

.. 파트너를 인수한 컨트롤러의 콘솔에서 다음 명령을 입력합니다.
+
`storage failover modify -node local -auto-giveback false`

.. 입력하다 `y` _자동 환불을 비활성화하시겠습니까?_라는 메시지가 표시되면




 a| 
두 컨트롤러 모두 I/O(데이터 제공)를 실행하고 있습니다
 a| 
다음 단계로 이동합니다.

|===
. 장애가 발생한 I/O 모듈을 서비스에서 제거하고 전원을 꺼서 제거 준비를 합니다.
+
.. 다음 명령을 입력하세요:
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. 입력하다 `y` _계속하시겠습니까?_라는 메시지가 표시되면
+
예를 들어, 다음 명령은 node 2(손상된 컨트롤러)의 슬롯 7에 있는 장애가 발생한 모듈을 제거할 수 있도록 준비하고 제거해도 안전하다는 메시지를 표시합니다.

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 7

Warning: IO_2X_100GBE_NVDA_NIC module in slot 7 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. 장애가 발생한 I/O 모듈의 전원이 꺼져 있는지 확인합니다.
+
`system controller slot module show`

+
출력 결과에는 오류가 발생한 모듈과 해당 슬롯 번호에 대해  `_status_` 열에  `_powered-off_`이(가) 표시되어야 합니다.


