---
permalink: c190/chassis-replace-complete-rma.html 
sidebar: sidebar 
keywords: aff c190, verify and set HA state, run diagnostics 
summary: 섀시의 HA 상태를 확인하고 시스템 수준 진단을 실행해야 합니다. 
---
= 구성 복원 및 확인 - AFF C190
:icons: font
:imagesdir: ../media/


[role="lead"]
섀시의 HA 상태를 확인하고 시스템 수준 진단을 실행해야 합니다.



== 1단계: 섀시의 HA 상태를 확인하고 설정합니다

섀시의 HA 상태를 확인하고 필요한 경우 시스템 구성에 맞게 상태를 업데이트해야 합니다.

. 유지보수 모드의 경우, 두 컨트롤러 모듈 중 하나에서 로컬 컨트롤러 모듈 및 섀시의 HA 상태를 표시합니다.
+
``ha-config show *’’입니다

+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 섀시에 대해 표시된 시스템 상태가 시스템 구성과 일치하지 않는 경우:
+
.. 섀시의 HA 상태를 설정합니다.
+
``ha-config modify chassis_HA-state_*'

+
'_HA-state_'의 값은 다음 중 하나일 수 있습니다.

+
*** 하
*** 비하


.. 설정이 변경되었는지 확인합니다.
+
``ha-config show *’’입니다



. 아직 다시 하지 않았다면 나머지 시스템을 다시 정하십시오.
. 다음 단계는 시스템 구성에 따라 다릅니다.
+
[cols="1,2"]
|===
| 시스템이 다음 상태인 경우: | 그러면... 


 a| 
독립형 구성
 a| 
.. 유지 관리 모드 종료:
+
' * halt * '

.. 로 이동합니다 link:chassis_replace.html[""교체 프로세스를 완료합니다"].




 a| 
두 번째 컨트롤러 모듈과 HA 쌍
 a| 
유지보수 모드 종료: ' * halt * '

LOADER 프롬프트가 나타납니다.

|===




== 2단계: 시스템 수준 진단 프로그램을 실행합니다

새 섀시를 설치한 후 상호 연결 진단을 실행해야 합니다.

시스템 레벨 진단을 시작하려면 시스템에 LOADER 메시지가 표시되어야 합니다.

진단 절차의 모든 명령은 구성 요소를 교체하는 컨트롤러에서 실행됩니다.

. 수리할 컨트롤러가 로더 프롬프트에 있지 않은 경우 다음 단계를 수행하십시오.
+
.. 표시된 메뉴에서 유지보수 모드 옵션을 선택합니다.
.. 컨트롤러가 유지보수 모드로 부팅된 후 컨트롤러를 중지합니다.
+
' * halt * '

+
명령을 실행한 후 시스템이 로더 프롬프트에서 중지될 때까지 기다려야 합니다.

+

NOTE: 부팅 프로세스 중에 프롬프트에 "y"로 안전하게 응답할 수 있습니다.



. HA 구성을 사용하는 경우 두 번째 컨트롤러에서 이전 단계를 반복합니다.
+

NOTE: 인터커넥트 테스트를 실행하려면 두 컨트롤러가 유지보수 모드여야 합니다.

. LOADER 프롬프트에서 시스템 수준 진단이 제대로 작동하도록 특별히 설계된 특수 드라이버를 액세스합니다.
+
'* boot_diags*'

+
부팅 프로세스 중에 유지보수 모드 프롬프트(*>)가 나타날 때까지 프롬프트에 "y"로 안전하게 응답할 수 있습니다.

. 유지보수 모드 프롬프트에서 상호 연결 진단 테스트를 활성화합니다.
+
'* sldiag 장치 수정 - dev 상호 연결 - sel 활성화*'

+
상호 연결 테스트는 기본적으로 비활성화되어 있으며 별도로 실행하려면 활성화되어 있어야 합니다.

. 유지보수 모드 프롬프트에서 상호 연결 진단 테스트를 실행합니다.
+
'* sldiag 장치 run-dev interconnect*'

+
하나의 컨트롤러에서만 상호 연결 테스트를 실행해야 합니다.

. 섀시 교체로 인한 하드웨어 문제가 없는지 확인합니다.
+
'* sldiag 장치 상태 - 개발 상호 연결 - 긴 상태 실패 *

+
시스템 수준 진단은 테스트 실패가 없을 경우 프롬프트로 돌아가거나 구성 요소 테스트로 인한 전체 실패 상태를 표시합니다.

. 이전 단계의 결과에 따라 계속 진행합니다.
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
실패없이 완료되었습니다
 a| 
.. 상태 로그 지우기:
+
'* sldiag 장치 clearstatus*'

.. 로그가 지워졌는지 확인합니다.
+
'* sldiag 장치 상태 *'

+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 두 컨트롤러 모두에서 유지보수 모드를 종료합니다.
+
' * halt * '

+
LOADER 프롬프트가 표시됩니다.

+

NOTE: 계속하기 전에 두 컨트롤러의 유지보수 모드를 종료해야 합니다.

.. LOADER 프롬프트에서 두 컨트롤러 모두에 대해 다음 명령을 입력합니다.
+
' * bye * '

.. 컨트롤러를 정상 작동 상태로 되돌립니다.


|===
+
[cols="1,2"]
|===
| 시스템에서 ONTAP를 실행 중인 경우... | 그러면... 


 a| 
클러스터에서 노드 2개 사용
 a| 
다음 명령을 실행합니다.

``node:::> cluster ha modify -configured true * '

' * node:::> 스토리지 페일오버 수정 - node Node0 설정 true *



 a| 
클러스터에 2개 이상의 노드가 있습니다
 a| 
다음 명령을 실행합니다.

' * node:::> 스토리지 페일오버 수정 - node Node0 설정 true *



 a| 
독립형 구성
 a| 
이 특정 작업에 대한 추가 단계가 없습니다. 시스템 수준 진단을 완료했습니다.



 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 유지 관리 모드 종료:
+
' * halt * '

.. 완전 종료를 수행한 다음 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결한 다음 스토리지 시스템의 전원을 켭니다.
.. 시스템 수준 진단 테스트를 다시 실행하십시오.


|===




== 3단계: 장애가 발생한 부품을 NetApp에 반환

부품을 교체한 후 키트와 함께 제공된 RMA 지침에 따라 오류가 발생한 부품을 NetApp에 반환할 수 있습니다. 기술 지원 부서(에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양) 교체 절차에 대한 추가 지원이 필요한 경우.
