---
permalink: a700/controller-replace-complete-system-restoration.html 
sidebar: sidebar 
keywords: aff a700, fas9000, storage encryption, licenses, storage encryption, volume encryption, serial number, metrocluster, switchback 
summary: '교체 절차를 완료하고 시스템을 전체 작업으로 복원하려면 스토리지를 재구성하고 NetApp Storage Encryption 구성을 복원한 다음(필요한 경우) 새 컨트롤러에 대한 라이센스를 설치해야 합니다.' 
---
= 시스템 복원 완료 - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
교체 절차를 완료하고 시스템을 전체 작업으로 복원하려면 스토리지를 재구성하고 NetApp Storage Encryption 구성을 복원한 다음(필요한 경우) 새 컨트롤러에 대한 라이센스를 설치해야 합니다. 시스템을 전체 작동 상태로 복원하기 전에 일련의 작업을 완료해야 합니다.



== 1단계: ONTAP에서 교체 노드에 대한 라이센스를 설치합니다

장애가 발생한 노드가 표준(노드 잠김) 라이센스가 필요한 ONTAP 기능을 사용 중인 경우 _replacement_node에 대한 새 라이센스를 설치해야 합니다. 표준 라이센스가 있는 기능의 경우 클러스터의 각 노드에 기능에 대한 자체 키가 있어야 합니다.

.이 작업에 대해
라이센스 키를 설치하기 전까지는 표준 라이센스가 필요한 기능을 _replacement_node에서 계속 사용할 수 있습니다. 그러나 손상된 노드가 클러스터의 유일한 노드인 경우 해당 기능에 대한 라이센스가 있으면 기능을 변경할 수 없습니다.

또한 노드에서 라이센스가 없는 기능을 사용하면 라이센스 계약을 준수하지 않을 수 있으므로 가능한 한 빨리 _replacement_node에 교체 라이센스 키 또는 키를 설치해야 합니다.

라이센스 키는 28자 형식이어야 합니다.

라이센스 키를 설치할 수 있는 90일의 유예 기간이 있습니다. 유예 기간이 지나면 모든 이전 라이센스가 무효화됩니다. 유효한 라이센스 키를 설치한 후 유예 기간이 끝나기 전에 모든 키를 24시간 동안 설치해야 합니다.

노드가 MetroCluster 구성에 있고 사이트의 모든 노드를 교체한 경우 스위치백 전_replacement_node 또는 노드에 라이센스 키를 설치해야 합니다.

.단계
. 새 라이센스 키가 필요한 경우 에서 교체용 라이센스 키를 받으십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp Support 사이트"] My Support(내 지원) 섹션에서 Software licenses(소프트웨어 라이센스) 를 선택합니다.
+

NOTE: 필요한 새 라이센스 키는 자동으로 생성되어 파일의 이메일 주소로 전송됩니다. 30일 이내에 라이센스 키가 포함된 이메일을 받지 못한 경우 기술 지원 부서에 문의하십시오.

. 각 라이선스 키를 '+시스템 라이선스 추가 라이선스 코드 라이선스 키, 라이선스 키...+'로 설치합니다
. 필요한 경우 이전 라이센스를 제거합니다.
+
.. 미사용 라이선스 확인:'라이선스 정리 - 미사용 - 시뮬레이션
.. 목록이 올바르면 사용하지 않는 사용권의 'license clean-up-unused'를 삭제합니다






== 2단계: LIF 확인 및 일련 번호 등록

replacement_node를 서비스로 반환하기 전에 LIF가 홈 포트에 있는지 확인하고, AutoSupport가 설정된 경우 _replacement_node의 일련 번호를 등록하고, 자동 반환 기능을 재설정해야 합니다.

.단계
. 논리 인터페이스가 홈 서버 및 포트에 대해 'network interface show-is-home false'라는 보고를 하는지 확인합니다
+
LIF가 FALSE로 표시되면 해당 LIF를 홈 포트로 되돌립니다. `network interface revert -vserver * -lif *`

. NetApp Support에 시스템 일련 번호를 등록합니다.
+
** AutoSupport가 활성화된 경우 AutoSupport 메시지를 전송하여 일련 번호를 등록합니다.
** AutoSupport가 활성화되어 있지 않으면 를 호출합니다 https://mysupport.netapp.com["NetApp 지원"] 일련 번호를 등록합니다.


. AutoSupport 유지보수 윈도우가 트리거된 경우 를 사용하여 윈도우를 종료합니다 `system node autosupport invoke -node * -type all -message MAINT=END` 명령.
. 자동 반환이 비활성화된 경우 'Storage failover modify -node local -auto-반환 true'를 다시 설정합니다




== 3단계: (MetroCluster만 해당): 2노드 MetroCluster 구성에서 애그리게이트 되돌리기

2노드 MetroCluster 구성에서 FRU 교체를 완료한 후에는 MetroCluster 스위치백 작업을 수행할 수 있습니다. 그러면 이전 사이트의 SVM(Sync-Source Storage Virtual Machine)이 활성 상태이고 로컬 디스크 풀에서 데이터를 제공하는 구성을 정상 운영 상태로 되돌릴 수 있습니다.

이 작업은 2노드 MetroCluster 구성에만 적용됩니다.

.단계
. 모든 노드가 "enabled" 상태(MetroCluster node show)에 있는지 확인합니다
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 모든 SVM에서 재동기화가 완료되었는지 확인합니다. 'MetroCluster vserver show'
. 복구 작업에 의해 수행되는 자동 LIF 마이그레이션이 'MetroCluster check lif show'에 성공적으로 완료되었는지 확인합니다
. 정상적인 클러스터에 있는 모든 노드에서 'MetroCluster 스위치백' 명령을 사용하여 스위치백을 수행합니다.
. 스위치백 작업이 완료되었는지 확인합니다. 'MetroCluster show'
+
클러스터가 "대기 중 - 스위치백" 상태에 있으면 스위치백 작업이 여전히 실행 중입니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
클러스터가 '정상' 상태에 있으면 스위치백 작업이 완료됩니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
스위치백을 완료하는 데 시간이 오래 걸리는 경우 MetroCluster config-replication resync resync-status show 명령을 사용하여 진행 중인 기준선의 상태를 확인할 수 있습니다.

. SnapMirror 또는 SnapVault 구성을 다시 설정합니다.




== 4단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다.  https://mysupport.netapp.com/site/info/rma["부품 반환 및 교체"]자세한 내용은 페이지를 참조하십시오.
