---
permalink: a700/maintain-overview.html 
sidebar: sidebar 
keywords: aff A700 maintenance, maintenance, repairing A700, repairing aff A700, replace aff A700 components, replace aff A700 components 
summary: ASA A700 하드웨어 유지보수 
---
= AFF A700 하드웨어 유지보수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A700 스토리지 시스템의 경우 다음 구성 요소에 대해 유지보수 절차를 수행할 수 있습니다.



== 미디어를 부팅합니다

부팅 매체는 시스템이 부팅될 때 사용하는 1차 및 2차 부팅 이미지 파일 세트를 저장합니다.



== 캐싱 모듈

시스템이 모듈이 오프라인으로 전환되었다는 단일 AutoSupport(ASUP) 메시지를 등록할 때 컨트롤러의 캐시 모듈을 교체해야 합니다.



== 섀시

섀시는 컨트롤러/CPU 장치, 전원 공급 장치 및 I/O와 같은 모든 컨트롤러 구성 요소를 수용하는 물리적 인클로저입니다



== 컨트롤러

컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 ONTAP 기능을 구현합니다.



== DCPM

DCPM(디스테이징 컨트롤러 전원 모듈)에는 NVRAM11 배터리가 포함되어 있습니다.



== DIMM

메모리 불일치가 있거나 DIMM에 결함이 있는 경우 DIMM(Dual In-line Memory Module)을 교체해야 합니다.



== 팬

팬이 컨트롤러를 냉각시킵니다.



== 입출력 모듈

I/O 모듈(입출력 모듈)은 컨트롤러와 다양한 장치 또는 시스템 사이에서 컨트롤러와 데이터를 교환해야 하는 중개자 역할을 하는 하드웨어 구성 요소입니다.



== LED USB

LED USB 모듈은 콘솔 포트 및 시스템 상태에 대한 연결을 제공합니다.



== NVRAM

NVRAM 모듈(비휘발성 임의 액세스 메모리)을 사용하면 컨트롤러가 전원 사이클 또는 시스템 재부팅 전반에 걸쳐 데이터를 보존할 수 있습니다.



== 전원 공급 장치

전원 공급 장치는 컨트롤러 쉘프에 이중 전원을 제공합니다.



== 실시간 시계 배터리

실시간 시계 배터리는 전원이 꺼져 있을 경우 시스템 날짜 및 시간 정보를 보존합니다.



== X91148A 모듈

X91148A 모듈은 컨트롤러와 데이터를 교환해야 하는 다양한 장치 또는 시스템 간의 중간 역할을 하는 I/O 모듈입니다.
