---
permalink: fas-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the boot media 
summary: FAS70 또는 FAS90 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요. 
---
= 자동 부팅 미디어 복구 요구 사항 - FAS70 및 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70 또는 FAS90 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요구 사항을 충족하는지 확인하십시오. 여기에는 올바른 교체 부트 미디어를 가지고 있는지, 손상된 컨트롤러의 클러스터 포트가 제대로 작동하는지, 그리고 Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.

자동 부팅 미디어 복구 프로세스는 ONTAP 9.17.1 이상에서만 지원됩니다. 스토리지 시스템에서 이전 버전의 ONTAP 실행 중인 경우 link:bootmedia-replace-workflow.html["수동 부팅 복구 절차"] .

다음 요구 사항을 검토하십시오.

* 장애가 발생한 부팅 미디어를 NetApp에서 받은 교체 부팅 미디어로 교체해야 합니다.
* 클러스터 포트는 자동 부팅 복구 프로세스 동안 두 컨트롤러 간 통신에 사용됩니다. 손상된 컨트롤러의 클러스터 포트가 제대로 작동하는지 확인하십시오.
* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* 손상된 부트 미디어를 교체할 때는 올바른 컨트롤러에 명령을 적용하는 것이 중요합니다.
+
** _손상된 컨트롤러_는 유지 관리를 수행하고 있는 컨트롤러입니다.
** 건강한 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.




.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["컨트롤러를 종료합니다"]
