---
permalink: fas-70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas70, fas90, how to recable the system, how to reassign disks 
summary: 시스템을 재부팅합니다. 
---
= 컨트롤러-FAS70 및 FAS90을 돌려줍니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 및 네트워크 연결을 확인한 다음 컨트롤러를 반납합니다.



== 컨트롤러를 반납합니다

활성화된 경우 암호화를 재설정하고 컨트롤러를 정상 작동 상태로 되돌립니다.

[role="tabbed-block"]
====
.암호화 없음
--
. Loader 프롬프트에서 를 입력합니다 `boot_ontap`.
. 콘솔 메시지가 중지되면 <enter> 키를 누릅니다.
+
** _login_prompt가 표시되면 이 섹션 끝에 있는 다음 단계로 이동합니다.
** _waiting for Giveback_이 표시되면 <enter> 키를 누르고 파트너 노드에 로그인한 후 이 섹션 끝에 있는 다음 단계로 이동합니다.


. 손상된 컨트롤러를 다시 보관하여 정상 작동으로 되돌립니다 `storage failover giveback -ofnode _impaired_node_name_`.
. 자동 반환이 비활성화되어 있는 경우, 다음과 같이 다시 활성화하십시오 `storage failover modify -node local -auto-giveback true`.
. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.온보드 암호화(OKM)
--
. Loader 프롬프트에서 를 입력합니다 `boot_ontap maint`.
. Loader 프롬프트에서 ONTAP 메뉴로 부팅하고 `boot_ontap menu` 옵션 10을 선택합니다.
. OKM 암호를 입력합니다. 이 암호를 고객으로부터 받거나 에 문의할 수 https://support.netapp.com["NetApp 지원"] 있습니다.
+

NOTE: 암호를 묻는 메시지가 두 번 표시됩니다.

. 메시지가 나타나면 백업 키 데이터를 입력합니다.
. 부팅 메뉴에서 일반 부팅에 대한 옵션을 입력합니다 `1`.
. when_waiting for Giveback_이 표시되면 <enter> 키를 누릅니다.
. 콘솔 케이블을 파트너 노드로 이동하고 로 `admin`로그인합니다.
. 복구 노드의 모든 코어 덤프가 고급 모드로 이동하여 저장되었는지 확인합니다." `set -privilege advanced` `run local partner savecore`
. 관리자 레버로 돌아가기 `set privilege admin`:.
. CFO 애그리게이트(루트 애그리게이트)만 반환합니다. `storage failover giveback -fromnode local -only-cfo-aggregates true`
+
** 오류가 발생하면 에 문의하십시오 https://support.netapp.com["NetApp 지원"].


. 반환 보고서가 완료된 후 5분 동안 기다린 다음 페일오버 상태와 반환 상태를 확인합니다 `storage failover show`. 및 `storage failover show-giveback`.
. 콘솔 케이블을 교체 노드로 이동하고 를 입력합니다 `security key-manager onboard sync`
+

NOTE: 클러스터에 대한 OKM의 클러스터 전체 암호를 묻는 메시지가 표시됩니다.

. 다음 명령을 사용하여 키의 상태를 확인합니다 `security key-manager key query -key-type svm-KEK`.
+
restored_column에 _true_를 제외한 내용이 표시되면 에 https://support.netapp.com["NetApp 지원"]문의하십시오.

. 손상된 컨트롤러를 다시 보관하여 정상 작동으로 되돌립니다 `storage failover giveback -ofnode _impaired_node_name_`.
. 자동 반환이 비활성화되어 있는 경우, 다음과 같이 다시 활성화하십시오 `storage failover modify -node local -auto-giveback true`.
. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.외부 키 관리자(EKM)
--
. 루트 볼륨이 External Key Manager로 암호화되고 콘솔 케이블이 교체 노드에 연결된 경우 option을 `boot_ontap menu` 입력하고 선택합니다 `11`.
. 또는 `n` 다음 질문에 답합니다. `y`
+
/cfcard/kMIP/certs/client.crt 파일의 복사본이 있습니까? {y/n}

+
/cfcard/kMIP/certs/client.key 파일의 복사본이 있습니까? {y/n}

+
/cfcard/kMIP/certs/ca.pem 파일의 사본이 있습니까? {y/n}

+
또는

+
/cfcard/kMIP/servers.cfg 파일의 복사본이 있습니까? {y/n}

+
KMIP 서버 주소를 알고 계십니까? {y/n}

+
KMIP 포트를 아십니까? {y/n}

+

NOTE: 문제가 있는 경우 에 https://support.netapp.com["NetApp 지원"] 문의하십시오.

. 다음에 대한 정보를 제공합니다.
+
** 클라이언트 인증서(client.crt) 파일 내용
** 클라이언트 키(client.key) 파일 내용
** KMIP 서버 CA(CA.pem) 파일 콘텐츠입니다.
** KMIP 서버의 IP 주소입니다.
** KMIP 서버의 포트입니다.


. 시스템이 처리되면 부팅 메뉴가 표시됩니다. 정상 부팅의 경우 '1'을 선택하십시오.
. 인수 상태를 확인합니다 `storage failover show`.
. 복구 노드의 모든 코어 덤프가 고급 모드로 이동하여 저장되었는지 확인합니다." `set -privilege advanced` `run local partner savecore`
. 손상된 컨트롤러를 다시 보관하여 정상 작동으로 되돌립니다 `storage failover giveback -ofnode _impaired_node_name_`.
. 자동 반환이 비활성화되어 있는 경우, 다음과 같이 다시 활성화하십시오 `storage failover modify -node local -auto-giveback true`.
. AutoSupport가 활성화된 경우 자동 케이스 생성을 복원/억제 해제: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====