---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: 작업대 및 선반에 필요한 장비 및 인양 예방 조치를 검토합니다. 
---
= 설치 요구사항 - FAS70 및 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70 또는 FAS90 스토리지 시스템 및 스토리지 선반에 필요한 장비 및 인양 예방 조치를 검토합니다.



== 설치에 필요한 장비

기억 장치 시스템을 설치하려면 다음과 같은 장비와 도구가 필요합니다.

* 웹 브라우저에 액세스하여 스토리지 시스템을 구성합니다
* 정전기 방전(ESD) 스트랩
* 플래시
* USB/직렬 연결이 있는 랩톱 또는 콘솔
* Phillips #2 드라이버




== 인양 주의 사항

스토리지 시스템 및 쉘프는 무겁습니다. 이러한 품목을 들어 올리거나 이동할 때는 주의를 기울이십시오.



=== 스토리지 시스템 중량입니다

기억 장치 시스템을 옮기거나 들어올릴 때 필요한 예방 조치를 취하십시오.

FAS70 또는 FAS90 저장 장치 시스템의 무게는 최대 28.5kg(62.83파운드)입니다. 시스템을 인양하려면 두 사람 또는 유압 리프트를 사용합니다.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[FAS70 및 FAS90 인양 주의 아이콘]



=== 선반 무게

선반을 옮기거나 들어올릴 때 필요한 예방 조치를 취하십시오.

NS224 선반의 무게는 최대 30.29kg(66.78lbs)입니다. 선반을 인양하려면 두 사람이 함께 작업하거나 유압식 리프트를 사용하십시오. 선반 무게의 균형을 맞추기 위해 모든 구성 요소를 선반(전면 및 후면 모두)에 보관하십시오.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 인양 주의]

DS460C 선반의 무게는 최대 181.1kg(260.4lbs)입니다. 보관 선반을 들어 올리려면 최대 5명까지 앉거나 유압식 리프트가 필요할 수 있습니다. 선반 무게의 균형을 잃지 않도록 모든 구성 요소를 보관 선반(전면 및 후면 모두)에 보관하십시오.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C 인양 주의]

.관련 정보
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["안전 정보 및 규정 고지"^]


.다음 단계
하드웨어 요구 사항을 검토한 후link:install-prepare.html["FAS70 또는 FAS90 스토리지 시스템 설치를 준비합니다"]
