---
permalink: asa900/overview.html 
sidebar: sidebar 
keywords: ASA A900 specifications, ASA A900 specs, NetApp ASA A900, ASA A900 hardware 
summary: ASA A900 스토리지 시스템의 주요 사양 
---
= ASA A900 의 주요 사양
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음은 ASA A900 의 선택 사양입니다.  방문하다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] ASA A900 사양의 전체 목록은 (HWU)에서 확인하세요.  이 페이지는 단일 고가용성 쌍을 반영합니다.



=== ASA A900 의 주요 사양

플랫폼 구성: ASA A900 단일 섀시 HA 쌍

최대 원시 용량: 14.6880 PB

메모리: 2048.0000GB

폼 팩터: 2개의 HA 컨트롤러가 있는 8U 섀시

ONTAP 버전: b_startONTAP: 9.16.1P2b_end

PCIe 확장 슬롯: 20개

최소 ONTAP 버전: ONTAP 9.13.1



=== 스케일아웃 최대값

|===


| 유형 | HA 쌍 | 원시 용량 | 최대 메모리 


| NAS |  |  |  


| SAN | 6 | 88.1페타바이트 / 78.3파이바이트 | 12288GB 


| HA 쌍 |  | 14.7PB / 13.0PiB | 2048.0000 
|===


=== 아이오



==== 온보드 IO

온보드 IO 데이터가 없습니다.



==== 총 IO

|===


| 규약 | 포트 


| 이더넷 100Gbps | 32 


| 이더넷 25Gbps | 64 


| 이더넷 10Gbps | 64 


| FC 32Gbps | 64 


| NVMe/FC 32Gbps | 64 


|  | 0 


| SAS 12Gbps | 64 
|===


==== 관리 포트

|===


| 규약 | 포트 


| 이더넷 1Gbps | 2 


| RS-232 115Kbps | 6 


| USB 12Mbps | 2 
|===


=== 스토리지 네트워킹 지원

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== 시스템 환경 사양

* 일반적인 전력: 8004 BTU/hr
* 최악의 경우 전력: 9937 BTU/hr
* 무게: 220.5 lbbr/100.0 kg
* 높이: 8U
* 너비: 19인치 IEC 랙 호환(17.7인치 45.0cm)
* 깊이: 28.8인치(케이블 관리 브래킷 포함 시 36.8인치)
* 작동 온도/고도/습도: 10°C ~ 35°C/50°F ~ 95°F) atbr/= 3048mbr/= 10000 ft) 고도; 8% ~ 80%br/상대 습도, 비응축
* 비작동 온도/습도: -40°C ~ 70°C(-40°F ~ 158°F) 최대 12192m(40000피트)<br/>10% ~ 95% 상대 습도, 비응축, 원래 용기에 보관
* 음향 소음: 공표된 음향 전력(LwAd): 7.4;br/음압(LpAm)(방관자 위치): 65.0dB




=== 규정 준수

* 인증 EMC/EMI: AMCA, FCC, ICES, KC, 모로코, VCCI
* 인증 안전: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* 인증 안전/EMC/EMI: EAC, UKRSEPRO
* 인증 안전/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* 표준 EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Part 15 Class A, ICES-003, KS C 9832, KS C 9835
* 표준 안전: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 No. 60950-1, CAN/CSA C22.2 No. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252(파트 1)




=== 고가용성

이더넷 기반 베이스보드 관리 컨트롤러(BMC) 및 ONTAP 관리 인터페이스; 중복 핫스왑 가능 컨트롤러; 중복 핫스왑 가능 전원 공급 장치; SAS 연결을 통한 SAS 인밴드 관리;
