---
permalink: asa900/bootmedia_recovery_image.html 
sidebar: sidebar 
keywords:  
summary: 복구 이미지에서 손상된 컨트롤러를 부팅하는 절차는 시스템이 2노드 MetroCluster 구성에 있는지 여부에 따라 다릅니다. 
---
= 복구 이미지를 부팅합니다. - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
USB 드라이브에서 ONTAP 이미지를 부팅하고 파일 시스템을 복원하며 환경 변수를 확인해야 합니다.

. LOADER 프롬프트에서 USB 플래시 드라이브에서 복구 이미지를 부팅하십시오: "boot_recovery"
+
이미지는 USB 플래시 드라이브에서 다운로드됩니다.

. 메시지가 표시되면 이미지 이름을 입력하거나 화면의 괄호 안에 표시된 기본 이미지를 그대로 사용합니다.
. var 파일 시스템을 복구합니다.
+
[cols="1,2"]
|===
| 시스템에 다음 기능이 있는 경우: | 그러면... 


 a| 
네트워크 연결
 a| 
.. 백업 구성을 복원하라는 메시지가 나타나면 'y'를 누릅니다.
.. '/etc/ssh/ssh_host_ecDSA_key'를 덮어쓸지 묻는 메시지가 나타나면 'y'를 누릅니다.
.. 복원 백업이 성공했는지 확인하는 메시지가 나타나면 'y'를 누릅니다.
.. 복원된 구성 복사를 묻는 메시지가 나타나면 'Y'를 누릅니다.
.. 손상된 컨트롤러를 고급 권한 수준(Set-Privilege Advanced)으로 설정합니다
.. 복구 백업 명령 'system node restore-backup-node local-target-address impaired_node_ip_address'를 실행합니다
.. 손상된 컨트롤러를 관리자 수준으로 되돌리려면: 'Set-Privilege admin'을 선택합니다
.. 복원된 구성을 사용할 것인지 묻는 메시지가 나타나면 'y'를 누릅니다.
.. 손상된 컨트롤러를 재부팅하라는 메시지가 나타나면 'y'를 누릅니다.




 a| 
네트워크 연결이 없습니다
 a| 
.. 백업 구성을 복원하라는 메시지가 나타나면 "n"을 누릅니다.
.. 시스템에서 메시지가 표시되면 시스템을 재부팅합니다.
.. 표시된 메뉴에서 * Update flash from backup config * (sync flash) 옵션을 선택합니다.
+
업데이트를 계속하라는 메시지가 나타나면 y를 누릅니다.





 a| 
네트워크 연결이 없고 MetroCluster IP 구성에 있습니다
 a| 
.. 백업 구성을 복원하라는 메시지가 나타나면 "n"을 누릅니다.
.. 시스템에서 메시지가 표시되면 시스템을 재부팅합니다.
.. iSCSI 스토리지 연결이 연결될 때까지 기다립니다.
+
다음 메시지가 표시되면 계속 진행할 수 있습니다.

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. 표시된 메뉴에서 * Update flash from backup config * (sync flash) 옵션을 선택합니다.
+
업데이트를 계속하라는 메시지가 나타나면 y를 누릅니다.



|===
. 환경 변수가 예상대로 설정되었는지 확인합니다.
+
.. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
.. printenv 명령을 사용하여 환경 변수 설정을 확인합니다.
.. 환경 변수가 예상대로 설정되어 있지 않으면 'etenv_env_enEnvironment_variable_name__changed_value_' 명령으로 변경하십시오.
.. saveenv 명령을 사용하여 변경 내용을 저장합니다.


. 다음 항목은 시스템 구성에 따라 다릅니다.
+
** 시스템에 온보드 키 관리자, NSE 또는 NVE가 구성된 경우 로 이동합니다 xref:bootmedia_encryption_restore.adoc[OKM, NSE 및 NVE를 위한 부팅 후 미디어 교체 단계]
** 시스템에 온보드 키 관리자, NSE 또는 NVE가 구성되어 있지 않은 경우 이 섹션의 단계를 완료하십시오.


. LOADER 프롬프트에서 boot_ontap 명령을 입력합니다.
+
[cols="1,2"]
|===
| 표시되는 내용... | 그러면... 


 a| 
로그인 프롬프트
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
.. 파트너 컨트롤러에 로그인합니다.
.. 'storage failover show' 명령을 사용하여 타겟이 반환 준비가 되었는지 확인합니다.


|===
. 콘솔 케이블을 파트너 컨트롤러에 연결합니다.
. 스토리지 페일오버 반환 -fromnode local 명령을 사용하여 컨트롤러를 다시 제공합니다.
. 클러스터 프롬프트에서 net int -is -home false 명령을 사용하여 논리 인터페이스를 확인합니다.
+
인터페이스가 "false"로 나열되는 경우 net int revert 명령을 사용하여 해당 인터페이스를 홈 포트로 되돌립니다.

. 콘솔 케이블을 수리된 시스템 종료로 옮기거나 해당 구성에 적합한 절차에 따라 손상된 컨트롤러를 인수하십시오. version -v 명령을 실행하여 ONTAP 버전을 확인합니다.
. 스토리지 페일오버 modify -node local -auto -반환 true 명령을 사용하여 자동 반환 기능을 해제한 경우 이 반환 작업을 복구합니다.

