---
permalink: a150/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 섀시를 교체하려면 컨트롤러를 종료해야 합니다. 
---
= 컨트롤러 종료 - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성에 적합한 절차에 따라 컨트롤러를 종료하거나 손상된 컨트롤러를 인수하십시오.



== 옵션 1: 대부분의 구성

이 절차는 2개 노드 구성이 있는 시스템을 위한 것입니다. 클러스터를 서비스할 때 정상 종료에 대한 자세한 내용은 을 참조하십시오 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["스토리지 시스템을 정상적으로 종료하고 전원을 켭니다. 해결 가이드 - NetApp 기술 자료"].

.시작하기 전에
* 필요한 사용 권한과 자격 증명이 있는지 확인합니다.
+
** ONTAP에 대한 로컬 관리자 자격 증명입니다.
** 각 컨트롤러에 대한 BMC 접근성


* 교체에 필요한 도구와 장비가 있는지 확인합니다.
* 시스템을 종료하기 전에 다음을 수행해야 합니다.
+
** 추가 를 수행합니다 https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["시스템 상태 점검"].
** ONTAP를 시스템의 권장 릴리스로 업그레이드합니다.
** 모두 해결 https://activeiq.netapp.com/["Active IQ Wellness 알림 및 위험"]. 시스템 구성 요소의 LED와 같은 현재 시스템에 있는 모든 결함을 기록해 둡니다.




.단계
. SSH를 통해 클러스터에 로그인하거나 로컬 콘솔 케이블과 랩톱/콘솔을 사용하여 클러스터의 노드에서 로그인합니다.
. 모든 클라이언트/호스트에서 NetApp 시스템의 데이터에 액세스하지 못하도록 합니다.
. 외부 백업 작업을 일시 중지합니다.
. AutoSupport가 활성화된 경우 케이스 생성을 억제하고 시스템이 오프라인이 될 것으로 예상되는 기간을 표시합니다.
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 모든 클러스터 노드의 SP/BMC 주소 식별:
+
`system service-processor show -node * -fields address`

. 클러스터 쉘을 종료합니다.
+
`exit`

. 이전 단계의 출력에 나열된 노드의 IP 주소를 사용하여 SP/BMC over SSH에 로그인하여 진행 상황을 모니터링합니다.
+
콘솔/랩톱을 사용하는 경우 동일한 클러스터 관리자 자격 증명을 사용하여 컨트롤러에 로그인합니다.

. 손상된 섀시에 있는 2개의 노드를 중지합니다.
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: StrictSync 모드에서 운영되는 SnapMirror 동기식 클러스터를 사용하는 클러스터의 경우: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 다음이 표시되면 클러스터의 각 컨트롤러에 대해 * y * 를 입력합니다.
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 각 컨트롤러가 멈출 때까지 기다린 후 LOADER 프롬프트가 표시됩니다.




== 옵션 2: 컨트롤러가 MetroCluster 구성에 있습니다


NOTE: 시스템이 2노드 MetroCluster 구성인 경우 이 절차를 사용하지 마십시오.

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공할 수 있도록 컨트롤러를 인수해야 합니다.

* 노드가 2개 이상인 클러스터가 있는 경우 쿼럼에 있어야 합니다. 클러스터가 쿼럼에 없거나 정상 컨트롤러에 자격 및 상태에 대해 FALSE가 표시되는 경우 손상된 컨트롤러를 종료하기 전에 문제를 해결해야 합니다(참조) link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["노드를 클러스터와 동기화합니다"^].
* MetroCluster 설정이 있는 경우 MetroCluster 설정 상태가 구성되어 있고 해당 노드가 설정 및 정상 상태('MetroCluster node show')인지 확인해야 합니다.


.단계
. AutoSupport가 활성화된 경우 'system node AutoSupport invoke -node * -type all-message MAINT=number_of_hours_downh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
다음 AutoSupport 메시지는 두 시간 동안 자동 케이스 생성을 억제합니다: ' cluster1: * > system node AutoSupport invoke - node * -type all-message MAINT=2h'

. 정상적인 컨트롤러의 콘솔에서 'Storage failover modify – node local - auto-반환 false'를 자동으로 반환합니다
. 손상된 컨트롤러를 로더 프롬프트로 가져가십시오.
+
[cols="1,2"]
|===
| 손상된 컨트롤러가 표시되는 경우... | 그러면... 


 a| 
LOADER 메시지가 표시됩니다
 a| 
다음 단계로 이동합니다.



 a| 
반환 대기 중...
 a| 
Ctrl-C를 누른 다음 메시지가 나타나면 y를 누릅니다.



 a| 
시스템 프롬프트 또는 암호 프롬프트(시스템 암호 입력)
 a| 
정상적인 컨트롤러 'storage failover takeover -ofnode_impaired_node_name_'에서 손상된 컨트롤러를 인수하거나 중단합니다

손상된 컨트롤러에 기브백을 기다리는 중... 이 표시되면 Ctrl-C를 누른 다음 y를 응답합니다.

|===

