---
permalink: a150/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고 시스템 수준 진단을 실행하고, 애그리게이트를 다시 전환하고, 장애가 발생한 부품을 NetApp에 반환해야 합니다. 
---
= 구성을 복원 및 확인합니다 - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고 시스템 수준 진단을 실행하고, 애그리게이트를 다시 전환하고, 장애가 발생한 부품을 NetApp에 반환해야 합니다.



== 1단계: 섀시의 HA 상태를 확인하고 설정합니다

섀시의 HA 상태를 확인하고 필요한 경우 시스템 구성에 맞게 상태를 업데이트해야 합니다.

. 유지보수 모드의 컨트롤러 모듈 중 하나에서 로컬 컨트롤러 모듈 및 섀시의 HA 상태를 "ha-config show"로 표시합니다
+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 섀시에 대해 표시된 시스템 상태가 시스템 구성과 일치하지 않는 경우:
+
.. 섀시의 HA 상태를 "ha-config modify chassis_HA-state_"로 설정합니다
+
HA 상태의 값은 다음 중 하나일 수 있습니다.

+
*** 하
*** mcc
*** mcc-2n
*** 'mcip'입니다
*** 비하


.. 설정이 변경되었는지 확인합니다. ha-config show


. 아직 다시 하지 않았다면 나머지 시스템을 다시 정하십시오.
. 다음 단계는 시스템 구성에 따라 다릅니다.
+
[cols="1,2"]
|===
| 시스템이 다음 상태인 경우: | 그러면... 


 a| 
독립형 구성
 a| 
.. 유지보수 모드를 종료합니다
.. 로 이동합니다 link:chassis_replace.html[""교체 프로세스를 완료합니다"].




 a| 
두 번째 컨트롤러 모듈과 HA 쌍
 a| 
유지보수 모드 종료: 정지하십시오. 로더 프롬프트가 나타납니다.

|===




== 2단계: 시스템 수준 진단 프로그램을 실행합니다

새 섀시를 설치한 후 상호 연결 진단을 실행해야 합니다.

시스템 레벨 진단을 시작하려면 시스템에 LOADER 메시지가 표시되어야 합니다.

진단 절차의 모든 명령은 구성 요소를 교체하는 컨트롤러에서 실행됩니다.

. 수리할 컨트롤러가 로더 프롬프트에 있지 않은 경우 다음 단계를 수행하십시오.
+
.. 표시된 메뉴에서 유지보수 모드 옵션을 선택합니다.
.. 컨트롤러가 유지보수 모드로 부팅된 후 컨트롤러를 정지시킵니다
+
명령을 실행한 후 시스템이 로더 프롬프트에서 중지될 때까지 기다려야 합니다.

+

NOTE: 부팅 프로세스 중에 프롬프트에 "y"로 안전하게 응답할 수 있습니다.



. HA 구성을 사용하는 경우 두 번째 컨트롤러에서 이전 단계를 반복합니다.
+

NOTE: 인터커넥트 테스트를 실행하려면 두 컨트롤러가 유지보수 모드여야 합니다.

. LOADER 프롬프트에서 시스템 수준 진단이 제대로 작동하도록 특별히 설계된 특수 드라이버('BOOT_DIAGS')에 액세스합니다
+
부팅 프로세스 중에 유지보수 모드 프롬프트(*>)가 나타날 때까지 프롬프트에 "y"로 안전하게 응답할 수 있습니다.

. 유지보수 모드 프롬프트에서 상호 연결 진단 테스트를 활성화합니다. 'sldiag device modify -dev interconnect -sel enable'
+
상호 연결 테스트는 기본적으로 비활성화되어 있으며 별도로 실행하려면 활성화되어 있어야 합니다.

. 유지 관리 모드 프롬프트에서 상호 연결 진단 테스트를 실행합니다. 'ldiag device run-dev interconnect'
+
하나의 컨트롤러에서만 상호 연결 테스트를 실행해야 합니다.

. 섀시 교체로 인한 하드웨어 문제가 없는지 확인합니다. 'ldiag device status-dev interconnect-long-state failed'
+
시스템 수준 진단은 테스트 실패가 없을 경우 프롬프트로 돌아가거나 구성 요소 테스트로 인한 전체 실패 상태를 표시합니다.

. 이전 단계의 결과에 따라 계속 진행합니다.
+
[cols="1,2"]
|===
| 시스템 수준 진단이 테스트되는 경우... | 그러면... 


 a| 
실패없이 완료되었습니다
 a| 
.. 상태 로그 'ldiag device clearstatus'를 지웁니다
.. 'ldiag device status'라는 로그가 지워졌는지 확인한다
+
다음과 같은 기본 응답이 표시됩니다.

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 두 컨트롤러 모두에서 유지보수 모드를 종료합니다. '중지'
+
LOADER 프롬프트가 표시됩니다.

+

NOTE: 계속하기 전에 두 컨트롤러의 유지보수 모드를 종료해야 합니다.

.. LOADER 프롬프트에서 두 컨트롤러 모두에 대해 bye 명령을 입력합니다
.. 컨트롤러를 정상 작동 상태로 되돌립니다.


|===
+
[cols="1,2"]
|===
| 시스템에서 ONTAP를 실행 중인 경우... | 그러면... 


 a| 
클러스터에서 노드 2개 사용
 a| 
'node::::> cluster ha modify -configured true" "node::::> storage failover modify -node Node0 -enabled true"라는 명령을 실행합니다



 a| 
클러스터에 2개 이상의 노드가 있습니다
 a| 
''node:::> storage failover modify -node Node0 -enabled true' 명령을 실행합니다



 a| 
2노드 MetroCluster 구성의 경우
 a| 
다음 단계를 진행합니다. MetroCluster 스위치백 절차는 교체 프로세스의 다음 작업에서 수행됩니다.



 a| 
독립형 구성
 a| 
이 특정 작업에 대한 추가 단계가 없습니다.

시스템 수준 진단을 완료했습니다.



 a| 
테스트 실패가 발생했습니다
 a| 
문제의 원인을 확인합니다.

.. 유지보수 모드를 종료합니다
.. 완전 종료를 수행한 다음 전원 공급 장치를 분리합니다.
.. 시스템 수준 진단 프로그램 실행 시 확인된 모든 고려 사항, 케이블이 안전하게 연결되어 있는지, 하드웨어 구성 요소가 스토리지 시스템에 올바르게 설치되어 있는지 확인합니다.
.. 전원 공급 장치를 다시 연결한 다음 스토리지 시스템의 전원을 켭니다.
.. 시스템 수준 진단 테스트를 다시 실행하십시오.


|===




== 3단계: 2노드 MetroCluster 구성에서 애그리게이트를 다시 전환합니다

2노드 MetroCluster 구성에서 FRU 교체를 완료한 후에는 MetroCluster 스위치백 작업을 수행할 수 있습니다. 그러면 이전 사이트의 SVM(Sync-Source Storage Virtual Machine)이 활성 상태이고 로컬 디스크 풀에서 데이터를 제공하는 구성을 정상 운영 상태로 되돌릴 수 있습니다.

이 작업은 2노드 MetroCluster 구성에만 적용됩니다.

.단계
. 모든 노드가 "enabled" 상태(MetroCluster node show)에 있는지 확인합니다
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 모든 SVM에서 재동기화가 완료되었는지 확인합니다. 'MetroCluster vserver show'
. 복구 작업에 의해 수행되는 자동 LIF 마이그레이션이 'MetroCluster check lif show'에 성공적으로 완료되었는지 확인합니다
. 정상적인 클러스터에 있는 모든 노드에서 'MetroCluster 스위치백' 명령을 사용하여 스위치백을 수행합니다.
. 스위치백 작업이 완료되었는지 확인합니다. 'MetroCluster show'
+
클러스터가 "대기 중 - 스위치백" 상태에 있으면 스위치백 작업이 여전히 실행 중입니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
클러스터가 '정상' 상태에 있으면 스위치백 작업이 완료됩니다.

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
스위치백을 완료하는 데 시간이 오래 걸리는 경우 MetroCluster config-replication resync resync-status show 명령을 사용하여 진행 중인 기준선의 상태를 확인할 수 있습니다.

. SnapMirror 또는 SnapVault 구성을 다시 설정합니다.




== 4단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
