---
permalink: asa-r2-70-90/bootmedia-replace-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, replace the boot media 
summary: 부팅 미디어를 교체하기 전에 시스템 관리 모듈을 제거하여 실패한 부팅 미디어를 찾습니다. 
---
= 부팅 미디어(ASA A70 및 ASA A90)를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
부팅 미디어를 교체하려면 시스템 뒷면에서 시스템 관리 모듈을 분리하고 손상된 부팅 미디어를 제거한 다음 시스템 관리 모듈에 교체 부팅 미디어를 설치해야 합니다.

.단계
부팅 매체는 시스템 관리 모듈 내부에 있으며 시스템에서 모듈을 제거하여 액세스합니다.

image::../media/drw_a70-90_boot_media_remove_replace_ieops-1367.svg[부팅 미디어를 교체합니다. 그래픽 교체]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[설명선 번호 1]
 a| 
시스템 관리 모듈 캠 래치



 a| 
image::../media/legend_icon_02.svg[설명선 번호 2]
 a| 
부트 미디어 잠금 버튼



 a| 
image::../media/legend_icon_03.svg[설명선 번호 3]
 a| 
미디어를 부팅합니다

|===
. 섀시 앞면에서 엄지 손가락으로 각 드라이브를 단단히 눌러 정지가 느껴질 때까지 밀어넣습니다. 이렇게 하면 드라이브가 섀시 중앙판에 단단히 고정됩니다.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[DRW A800 드라이브 장착형 IEOPS 960]

. 섀시 후면으로 이동합니다. 아직 접지되지 않은 경우 올바르게 접지하십시오.
. 컨트롤러 모듈을 3인치 정도 당겨 컨트롤러 모듈의 전원을 분리합니다.
+
.. 두 컨트롤러 모듈 잠금 래치를 누른 다음 두 래치를 동시에 아래로 돌립니다.
.. 컨트롤러 모듈을 섀시에서 3인치 정도 당겨 전원을 분리합니다.
.. 시스템 관리 모듈에 연결된 모든 케이블을 분리합니다. 모듈을 다시 설치할 때 케이블을 올바른 포트에 연결할 수 있도록 케이블이 연결된 위치에 레이블을 붙여야 합니다.
.. 케이블 관리 트레이 안쪽의 양쪽에 있는 단추를 당겨 케이블 관리 트레이를 아래로 돌린 다음 트레이를 아래로 돌립니다.
.. 시스템 관리 캠 버튼을 누릅니다. 캠 레버가 섀시에서 멀어집니다.
.. 캠 레버를 완전히 아래로 돌려 컨트롤러 모듈에서 시스템 관리 모듈을 분리합니다.
.. 부팅 미디어에 액세스할 수 있도록 시스템 관리 모듈을 정전기 방지 매트 위에 놓습니다.


. 관리 모듈에서 부팅 미디어를 분리합니다.
+
.. 파란색 잠금 버튼을 누르십시오.
.. 부팅 미디어를 위로 돌려 소켓에서 밀어 꺼낸 다음 한쪽에 둡니다.


. 교체 부팅 미디어를 시스템 관리 모듈에 설치합니다.
+
.. 부트 미디어의 가장자리를 소켓 하우징에 맞춘 다음 조심스럽게 소켓에 똑바로 밀어 넣습니다.
.. 부트 미디어를 잠금 버튼 쪽으로 돌립니다.
.. 잠금 버튼을 누르고 부트 미디어를 아래로 완전히 돌린 다음 잠금 버튼을 놓습니다.


. 시스템 관리 모듈을 다시 설치합니다.
+
.. 케이블 관리 트레이를 닫힘 위치까지 돌립니다.
.. 시스템 관리 모듈을 재구성합니다.



