---
permalink: c800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c800, verify and set HA state, run diagnostics, complete the replacement process 
summary: 키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고, 진단을 실행하고, 장애가 발생한 부품을 NetApp에 반환해야 합니다. 
---
= 복원 및 교체 프로세스(AFF C800)를 완료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키트와 함께 제공된 RMA 명령에 설명된 대로 섀시의 HA 상태를 확인하고, 진단을 실행하고, 장애가 발생한 부품을 NetApp에 반환해야 합니다.



== 1단계: 섀시의 HA 상태를 확인하고 설정합니다

섀시의 HA 상태를 확인하고 필요한 경우 시스템 구성에 맞게 상태를 업데이트해야 합니다.

. 유지보수 모드의 컨트롤러 모듈 중 하나에서 로컬 컨트롤러 모듈 및 섀시의 HA 상태를 "ha-config show"로 표시합니다
+
HA 상태는 모든 구성 요소에 대해 동일해야 합니다.

. 섀시에 대해 표시된 시스템 상태가 시스템 구성과 일치하지 않는 경우:
+
.. 섀시의 HA 상태를 "ha-config modify chassis_HA-state_"로 설정합니다
+
HA 상태의 값은 다음 중 하나일 수 있습니다.

+
*** 하
*** mcc
*** 'mcip'입니다
*** 비하


.. 설정이 변경되었는지 확인합니다. ha-config show


. 아직 다시 하지 않았다면 나머지 시스템을 다시 정하십시오.
. 시스템 앞면에 베젤을 다시 설치합니다.




== 2단계: 진단 유틸리티를 실행합니다

시스템의 구성 요소를 교체한 후에는 해당 구성 요소에 대한 진단 테스트를 실행해야 합니다.

진단 프로그램을 시작하려면 시스템에 LOADER 메시지가 표시되어야 합니다.

진단 절차의 모든 명령은 구성 요소를 교체하는 컨트롤러에서 실행됩니다.

.단계
. 서비스되는 컨트롤러가 LOADER 프롬프트에 있지 않으면 'system node halt-node node node_name' 컨트롤러를 재부팅합니다
+
명령을 실행한 후 시스템이 로더 프롬프트에서 중지될 때까지 기다려야 합니다.

. LOADER 프롬프트에서 시스템 수준 진단이 제대로 작동하도록 특별히 설계된 특수 드라이버('BOOT_DIAGS')에 액세스합니다
. 표시된 메뉴에서 * Scan System * 을 선택하여 진단 테스트 실행을 활성화합니다.
. 표시된 메뉴에서 * Test Memory * 를 선택합니다.
. 이전 단계의 결과에 따라 계속 진행합니다.
+
** 테스트에 실패한 경우 오류를 수정한 다음 테스트를 다시 실행하십시오.
** 테스트에서 오류가 없다고 보고된 경우 메뉴에서 재부팅을 선택하여 시스템을 재부팅합니다.






== 3단계: 장애가 발생한 부품을 NetApp에 반환

키트와 함께 제공된 RMA 지침에 설명된 대로 오류가 발생한 부품을 NetApp에 반환합니다. 를 참조하십시오 https://["부품 반품 및 앰프, 교체"] 페이지를 참조하십시오.
