---
permalink: fas2600/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas2600, prerequisite, replace the controller module 
summary: 교체 절차를 위한 필수 구성 요소를 검토하고 사용 중인 ONTAP 운영 체제 버전에 맞는 올바른 구성 요소를 선택해야 합니다. 
---
= 컨트롤러 모듈 교체 개요 - FAS2600
:icons: font
:imagesdir: ../media/


[role="lead"]
교체 절차를 위한 필수 구성 요소를 검토하고 사용 중인 ONTAP 운영 체제 버전에 맞는 올바른 구성 요소를 선택해야 합니다.

* 모든 드라이브 쉘프가 올바로 작동하고 있어야 합니다.
* 시스템이 HA 쌍인 경우 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러" 절차라고 함).
* 이 절차에는 시스템 구성에 따라 드라이브를 _replacement_controller에 자동으로 또는 수동으로 재할당하는 단계가 포함되어 있습니다.
+
절차의 지시에 따라 드라이브 재할당을 수행해야 합니다.

* 오류가 발생한 구성 요소를 공급업체로부터 받은 교체 FRU 구성 요소로 교체해야 합니다.
* 컨트롤러 모듈을 동일한 모델 유형의 컨트롤러 모듈로 교체해야 합니다. 컨트롤러 모듈만 교체하면 시스템을 업그레이드할 수 없습니다.
* 이 절차의 일부로 드라이브 또는 드라이브 쉘프를 변경할 수 없습니다.
* 이 절차에서는 _ replacement_controller가 이전 컨트롤러 모듈과 동일한 버전의 ONTAP에서 부팅되도록 부팅 장치를 손상된 컨트롤러에서 _replacement_controller로 이동합니다.
* 올바른 시스템에 다음 단계에 있는 명령을 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.


* 컨트롤러의 콘솔 출력을 항상 텍스트 파일로 캡처해야 합니다.
+
교체 프로세스 중에 발생할 수 있는 문제를 해결할 수 있도록 절차에 대한 기록을 제공합니다.


