---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: 'ASA A20, ASA A30 또는 ASA A50 스토리지 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항과 고려 사항을 충족해야 합니다. 올바른 교체 부팅 미디어가 있는지 확인, 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 문제가 없는지 확인, Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되었는지 확인하는 것이 포함됩니다.' 
---
= 요구 사항 - ASA A20, ASA A30 및 ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20, ASA A30 또는 ASA A50 스토리지 시스템에서 부팅 미디어를 교체하기 전에 올바른 교체를 위해 필요한 요구 사항과 고려 사항을 충족해야 합니다. 올바른 교체 부팅 미디어가 있는지 확인, 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 문제가 없는지 확인, Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되었는지 확인하는 것이 포함됩니다.



== 요구 사항

* 장애가 발생한 구성 요소를 NetApp에서 제공한 것과 동일한 용량의 교체 FRU 구성 요소로 교체해야 합니다.
* 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 결함이 있을 수 없습니다.
+
e0S 포트는 자동 부팅 복구에 사용됩니다.

* 다음 방법 중 하나를 사용하여 Onboard Key Manger(OKM) 또는 EKM(Eternal Key Manager)이 구성되었는지 확인합니다.
+
** 시스템 관리자에게 OKM 또는 EKM이 설정되어 있는지 물어볼 수 있습니다.
** OKM이 설정되어 있는지 확인하려면 을 `security key-manager onboard show`사용합니다.
** EKM이 활성화되어 있는지 확인하려면 를 `security key-manager external show`사용합니다.


* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.






== 고려 사항

* 다음 단계의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 유지 관리를 수행하는 컨트롤러입니다.
** healy_controller는 손상된 컨트롤러의 HA 파트너입니다.


* 필요한 경우 플랫폼 섀시 위치(파란색) LED를 켜서 영향을 받는 플랫폼을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
플랫폼 섀시에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.



.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["손상된 컨트롤러를 종료합니다"]



== 요구 사항

* 장애가 발생한 구성 요소를 NetApp에서 제공한 것과 동일한 용량의 교체 FRU 구성 요소로 교체해야 합니다.
* 손상된 컨트롤러의 e0S(e0M 렌치) 포트에 결함이 있을 수 없습니다.
+
e0S 포트는 자동 부팅 복구에 사용됩니다.

* 다음 방법 중 하나를 사용하여 Onboard Key Manger(OKM) 또는 EKM(Eternal Key Manager)이 구성되었는지 확인합니다.
+
** 시스템 관리자에게 OKM 또는 EKM이 설정되어 있는지 물어볼 수 있습니다.
** OKM이 설정되어 있는지 확인하려면 을 `security key-manager onboard show`사용합니다.
** EKM이 활성화되어 있는지 확인하려면 를 `security key-manager external show`사용합니다.


* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.






== 고려 사항

* 다음 단계의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 유지 관리를 수행하는 컨트롤러입니다.
** healy_controller는 손상된 컨트롤러의 HA 파트너입니다.


* 필요한 경우 플랫폼 섀시 위치(파란색) LED를 켜서 영향을 받는 플랫폼을 물리적으로 찾을 수 있습니다. SSH를 사용하여 BMC에 로그인하고 명령을 입력합니다 `system location-led _on_`.
+
플랫폼 섀시에는 조작자 디스플레이 패널에 1개, 각 컨트롤러에 하나씩 3개의 위치 LED가 있습니다. 위치 LED가 30분 동안 켜져 있습니다.

+
명령을 입력하여 이러한 기능을 해제할 수 `system location-led _off_` 있습니다. LED가 켜져 있는지 또는 꺼져 있는지 확실하지 않은 경우 명령을 입력하여 LED의 상태를 확인할 수 `system location-led show` 있습니다.


