---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: 'ASA A20, ASA A30 또는 ASA A50 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요구 사항과 고려 사항을 충족하는지 확인하십시오. 여기에는 올바른 교체 부트 미디어를 가지고 있는지, 손상된 컨트롤러의 e0S(e0M 렌치) 포트가 제대로 작동하는지, 그리고 Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.' 
---
= 부팅 미디어 교체 요구 사항 - ASA A20, ASA A30 및 ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20, ASA A30 또는 ASA A50 스토리지 시스템의 부트 미디어를 교체하기 전에 성공적인 교체를 위한 필수 요구 사항과 고려 사항을 충족하는지 확인하십시오. 여기에는 올바른 교체 부트 미디어를 가지고 있는지, 손상된 컨트롤러의 e0S(e0M 렌치) 포트가 제대로 작동하는지, 그리고 Onboard Key Manager(OKM) 또는 External Key Manager(EKM)가 활성화되어 있는지 확인하는 것이 포함됩니다.

다음 요구 사항을 검토하십시오.

* 장애가 발생한 구성 요소를 NetApp에서 제공한 것과 동일한 용량의 교체 FRU 구성 요소로 교체해야 합니다.
* e0S(e0M 렌치) 포트는 자동 부팅 복구 프로세스 동안 두 컨트롤러 간 통신에 사용됩니다. 손상된 컨트롤러의 e0S 포트가 제대로 작동하는지 확인하십시오.
* OKM의 경우 OKM 암호 파일 내용이 필요합니다.
* EKM의 경우 파트너 노드에서 다음 파일의 복사본이 필요합니다.
+
** /cfcard/kMIP/servers.cfg 파일.
** /cfcard/kMIP/cert/client.crt 파일.
** /cfcard/kMIP/certs/client.key 파일.
** /cfcard/kMIP/certs/ca.pem 파일.


* 손상된 부트 미디어를 교체할 때는 올바른 컨트롤러에 명령을 적용하는 것이 중요합니다.
+
** _손상된 컨트롤러_는 유지 관리를 수행하고 있는 컨트롤러입니다.
** 건강한 컨트롤러는 손상된 컨트롤러의 HA 파트너입니다.




.다음 단계
부팅 미디어 요구 사항을 검토한 후link:bootmedia-shutdown-bmr.html["손상된 컨트롤러를 종료합니다"]
