---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: ASA A20, ASA A30 또는 ASA A50 스토리지 시스템의 컨트롤러를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요.  여기에는 시스템의 다른 모든 구성 요소가 제대로 작동하는지 확인하고, 올바른 교체 컨트롤러를 가지고 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 것이 포함됩니다. 
---
= 컨트롤러 교체 요구 사항 - ASA A20, ASA A30 및 ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20, ASA A30 또는 ASA A50 스토리지 시스템의 컨트롤러를 교체하기 전에 성공적인 교체에 필요한 요구 사항을 충족하는지 확인하세요.  여기에는 시스템의 다른 모든 구성 요소가 제대로 작동하는지 확인하고, 올바른 교체 컨트롤러를 가지고 있는지 확인하고, 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 저장하는 것이 포함됩니다.

컨트롤러 교체 절차와 관련된 요구 사항 및 고려 사항을 검토해야 합니다.



== 요구 사항

* 모든 선반이 올바르게 작동해야 합니다.
* 정상적인 컨트롤러는 교체되는 컨트롤러를 인수할 수 있어야 합니다("손상된 컨트롤러"라고 함).
* 컨트롤러를 동일한 모델 유형의 컨트롤러로 교체해야 합니다. 컨트롤러만 교체하여 시스템을 업그레이드할 수 없습니다.
* 이 절차에서 드라이브나 쉘프를 변경할 수 없습니다.
* 항상 컨트롤러의 콘솔 출력을 텍스트 로그 파일에 캡처해야 합니다.
+
콘솔 출력은 교체 프로세스 중에 발생할 수 있는 문제를 해결하는 데 사용할 수 있는 절차에 대한 기록을 제공합니다.





== 고려 사항

* 이 절차의 명령을 올바른 컨트롤러에 적용하는 것이 중요합니다.
+
** impaired_controller는 교체되는 컨트롤러입니다.
** replacement_controller는 손상된 컨트롤러를 교체하는 새로운 컨트롤러입니다.
** healthy_controller는 정상적인 컨트롤러입니다.




.다음 단계
손상된 컨트롤러를 교체하기 위한 요구 사항을 검토한 후에는 다음을 link:controller-replace-shutdown.html["손상된 컨트롤러를 종료합니다"]수행해야 합니다.
