---
permalink: asa-c250/maintain-overview.html 
sidebar: sidebar 
keywords: asa C250 maintenance, maintenance, repairing C250, repairing asa C250, replace asa C250 components, replace asa C250 components 
summary: ASA C250 하드웨어 유지보수 
---
= ASA C250 하드웨어를 유지 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C250 스토리지 시스템의 하드웨어를 유지 관리하여 장기적인 안정성과 최적의 성능을 보장하십시오. 고장난 구성 요소 교체와 같은 정기적인 유지 관리 작업을 수행하면 다운타임과 데이터 손실을 방지하는 데 도움이 됩니다.

유지 관리 절차는 ASA C250 스토리지 시스템이 ONTAP 환경에 스토리지 노드로 이미 배포되었다고 가정합니다.



== 시스템 구성 요소

ASA C250 스토리지 시스템의 경우 다음 구성 요소에 대한 유지보수 절차를 수행할 수 있습니다.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["부팅 미디어 - 자동 복구"]
 a| 
부팅 미디어에는 스토리지 시스템이 부팅하는 데 사용하는 기본 및 보조 ONTAP 이미지 파일 세트가 저장됩니다. 자동 복구 중에 시스템은 파트너 노드에서 부팅 이미지를 가져와 적절한 부팅 메뉴 옵션을 자동으로 실행하여 교체 부팅 미디어에 이미지를 설치합니다. 자동 부팅 미디어 복구 프로세스는 ONTAP 9.18.1 이상에서만 지원됩니다. 스토리지 시스템이 이전 버전의 ONTAP를 실행 중인 경우 link:bootmedia-replace-workflow.html["수동 부팅 복구 절차"]을 사용하십시오.



 a| 
link:bootmedia-replace-workflow.html["부팅 미디어 - 수동 복구"]
 a| 
부팅 미디어에는 스토리지 시스템이 부팅하는 데 사용하는 기본 및 보조 ONTAP 이미지 파일 세트가 저장됩니다. 수동 복구 시에는 USB 드라이브에서 스토리지 시스템을 부팅하고 파일 시스템 이미지와 구성을 수동으로 복원합니다. 스토리지 시스템이 ONTAP 9.18.1 이상을 실행 중인 경우 link:bootmedia-replace-workflow-bmr.html["자동 부팅 복구 절차"]을 사용하십시오.



 a| 
link:chassis-replace-workflow.html["섀시"]
 a| 
섀시는 컨트롤러/CPU 장치, 전원 공급 장치 및 I/O와 같은 모든 컨트롤러 구성 요소를 수용하는 물리적 인클로저입니다



 a| 
link:controller-replace-workflow.html["컨트롤러"]
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 ONTAP 기능을 구현합니다.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
메모리 불일치가 있거나 DIMM에 결함이 있는 경우 DIMM(Dual In-line Memory Module)을 교체해야 합니다.



 a| 
link:drive-replace.html["드라이브"]
 a| 
드라이브는 물리적 데이터 저장 미디어를 제공하는 장치입니다.



 a| 
link:fan-replace.html["팬"]
 a| 
팬이 컨트롤러를 냉각시킵니다.



 a| 
link:mezzanine-replace.html["메자닌 카드"]
 a| 
메자닌 카드는 다른 플러그인 카드에 직접 연결되는 인쇄 회로 기판입니다.



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM 배터리"]
 a| 
NVMEM 배터리는 AC 전원이 차단될 경우 캐시된 데이터를 보존하는 역할을 합니다.



 a| 
link:power-supply-replace.html["전원 공급 장치"]
 a| 
전원 공급 장치는 컨트롤러 쉘프에 이중 전원을 제공합니다.



 a| 
link:rtc-battery-replace.html["실시간 시계 배터리"]
 a| 
실시간 시계 배터리는 전원이 꺼져 있을 경우 시스템 날짜 및 시간 정보를 보존합니다.

|===