---
permalink: a300/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a300, shutdown the controllers 
summary: 섀시를 교체하려면 컨트롤러를 종료해야 합니다. 
---
= 컨트롤러 종료 -- AFF A300
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
섀시를 교체하려면 컨트롤러를 종료해야 합니다.



== 옵션 1: 컨트롤러를 종료합니다

이 절차는 2-노드, 비-MetroCluster 구성에 한해서만 적용됩니다. 두 개 이상의 노드가 있는 시스템의 경우 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["4노드 클러스터에서 1개의 HA 쌍을 정상 종료하여 전원을 켜는 방법"^].

.시작하기 전에
필요한 사항:

* ONTAP에 대한 로컬 관리자 자격 증명입니다.
* 스토리지 암호화를 사용하는 경우 NetApp 온보드 키 관리(OKM) 클러스터 전체 암호 구문
* 각 컨트롤러에 대한 SP/BMC 액세스 가능성
* 모든 클라이언트/호스트에서 NetApp 시스템의 데이터에 액세스하지 못하도록 합니다.
* 외부 백업 작업을 일시 중지합니다.
* 교체에 필요한 공구 및 장비



NOTE: 시스템이 FabricPool 클라우드 계층으로 사용되는 NetApp StorageGRID 또는 ONTAP S3인 경우 를 참조하십시오 https://kb.netapp.com/onprem/ontap/hardware/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage#["스토리지 시스템을 정상적으로 종료하고 전원을 켭니다 해결 설명서"] 이 절차를 수행한 후


NOTE: FlexArray 스토리지 LUN을 사용하는 경우 이 절차를 수행한 후 해당 시스템에 대해 수행할 종료 절차는 해당 공급업체의 스토리지 시스템 설명서를 참조하십시오.


NOTE: SSD를 사용하는 경우 을 참조하십시오 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU490["SU490: (영향: 위험) SSD 모범 사례: 2개월 이상 전원을 끈 경우 드라이브 고장 및 데이터 손실 위험을 피하십시오"]

시스템을 종료하기 전에 다음을 수행해야 합니다.

* 추가 를 수행합니다 https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["시스템 상태 점검"].
* ONTAP를 시스템의 권장 릴리스로 업그레이드합니다.
* 모두 해결 https://activeiq.netapp.com/["Active IQ Wellness 알림 및 위험"]. 시스템 구성 요소의 LED와 같은 현재 시스템에 있는 모든 결함을 기록해 둡니다.


.단계
. SSH를 통해 클러스터에 로그인하거나 로컬 콘솔 케이블과 랩톱/콘솔을 사용하여 클러스터의 노드에서 로그인합니다.
. AutoSupport를 끄고 시스템이 오프라인 상태로 될 것으로 예상되는 시간을 표시합니다.
+
`system node autosupport invoke -node * -type all -messages "MAINT=8h Power Maintenance"`

. 모든 노드의 SP/BMC 주소 확인:
+
`system service-processor show -node * -fields address`

. 클러스터 쉘을 종료합니다. `exit`
. 이전 단계의 출력에 나열된 노드의 IP 주소를 사용하여 SSH를 통해 SP/BMC에 로그인합니다.
+
콘솔/노트북을 사용하는 경우 동일한 클러스터 관리자 자격 증명을 사용하여 컨트롤러에 로그인합니다.

+

NOTE: 진행 상황을 모니터링할 수 있도록 모든 SP/BMC 연결에 대한 SSH 세션을 엽니다.

. 클러스터의 모든 노드 중지:
+
`system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`.

+

NOTE: StrictSync 모드에서 작동하는 SnapMirror Synchronous를 사용하는 클러스터의 경우: `system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 클러스터의 각 컨트롤러에 대해 * y * 를 입력합니다 `_Warning: Are you sure you want to halt node "cluster name-controller number"?
{y|n}:_`
. 각 컨트롤러가 멈출 때까지 기다린 후 LOADER 프롬프트가 표시됩니다.
. PSU 켜기/끄기 스위치가 없는 경우 각 PSU를 끄거나 전원 코드를 뽑습니다.
. 각 PSU에서 전원 코드를 뽑습니다.
. 손상된 섀시의 모든 컨트롤러의 전원이 꺼져 있는지 확인합니다.




== 옵션 2: 컨트롤러는 2노드 MetroCluster 구성에 있습니다

손상된 컨트롤러를 종료하려면 컨트롤러 상태를 확인하고, 필요한 경우 컨트롤러 전원을 전환하여 정상적인 컨트롤러가 손상된 컨트롤러 스토리지에서 데이터를 계속 제공하도록 해야 합니다.

.이 작업에 대해
* NetApp Storage Encryption을 사용하는 경우 의 "FIPS 드라이브 또는 SED를 보호되지 않는 모드로 되돌리기" 섹션의 지침에 따라 MSID를 재설정해야 합니다 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["CLI를 통한 NetApp 암호화 개요"^].
* 정상 컨트롤러에 전원을 공급하려면 이 절차의 마지막에 전원 공급 장치를 켜 두어야 합니다.


.단계
. MetroCluster 상태를 확인하여 장애가 있는 컨트롤러가 자동으로 정상 컨트롤러(MetroCluster show)로 전환되었는지 확인합니다
. 자동 절체가 발생했는지 여부에 따라 다음 표에 따라 진행합니다.
+
[cols="1,2"]
|===
| 컨트롤러 손상 여부 | 그러면... 


 a| 
가 자동으로 전환되었습니다
 a| 
다음 단계를 진행합니다.



 a| 
가 자동으로 전환되지 않았습니다
 a| 
정상 컨트롤러 MetroCluster 절체 기능을 통해 계획된 절체 동작을 수행한다



 a| 
가 자동으로 전환되지 않고, 'MetroCluster switchover' 명령으로 전환을 시도했으며, 스위치오버가 거부되었습니다
 a| 
거부권 메시지를 검토하고 가능한 경우 문제를 해결한 후 다시 시도하십시오. 문제를 해결할 수 없는 경우 기술 지원 부서에 문의하십시오.

|===
. 정상적인 클러스터에서 'MetroCluster 환원 단계 집계' 명령을 실행하여 데이터 애그리게이트를 재동기화합니다.
+
[listing]
----
controller_A_1::> metrocluster heal -phase aggregates
[Job 130] Job succeeded: Heal Aggregates is successful.
----
+
치유가 거부되면 '-override-vetoes' 매개 변수를 사용하여 'MetroCluster 환원' 명령을 재실행할 수 있습니다. 이 선택적 매개 변수를 사용하는 경우 시스템은 복구 작업을 방지하는 모든 소프트 베인을 재정의합니다.

. MetroCluster operation show 명령을 사용하여 작업이 완료되었는지 확인합니다.
+
[listing]
----
controller_A_1::> metrocluster operation show
    Operation: heal-aggregates
      State: successful
Start Time: 7/25/2016 18:45:55
   End Time: 7/25/2016 18:45:56
     Errors: -
----
. 'storage aggregate show' 명령을 사용하여 애그리게이트의 상태를 확인하십시오.
+
[listing]
----
controller_A_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 mcc1-a2          raid_dp, mirrored, normal...
----
. MetroCluster 환원 단계 루트 애그리게이트( heal-phase root-aggregate) 명령을 사용하여 루트 애그리게이트를 수정합니다.
+
[listing]
----
mcc1A::> metrocluster heal -phase root-aggregates
[Job 137] Job succeeded: Heal Root Aggregates is successful
----
+
치유가 거부되면 -override-vetoes 매개변수를 사용하여 'MetroCluster 환원' 명령을 재실행할 수 있습니다. 이 선택적 매개 변수를 사용하는 경우 시스템은 복구 작업을 방지하는 모든 소프트 베인을 재정의합니다.

. 대상 클러스터에서 'MetroCluster operation show' 명령을 사용하여 환원 작업이 완료되었는지 확인합니다.
+
[listing]
----

mcc1A::> metrocluster operation show
  Operation: heal-root-aggregates
      State: successful
 Start Time: 7/29/2016 20:54:41
   End Time: 7/29/2016 20:54:42
     Errors: -
----
. 손상된 컨트롤러 모듈에서 전원 공급 장치를 분리합니다.

