---
permalink: ns224/change-shelf-id.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, change, shelf, id, system, ontap, unown, spare, offline, aggregate, change an ns224 drive shelf id 
summary: 'ONTAP가 아직 실행되지 않거나 시스템에 케이블로 연결되기 전에 쉘프를 핫 추가할 때 시스템의 쉘프 ID를 변경할 수 있습니다. ONTAP가 실행 중일 때(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음) 쉘프 ID를 변경할 수도 있고, 쉘프의 모든 드라이브가 소유되지 않은 상태, 스페어 또는 오프라인 애그리게이트의 일부일 때도 변경할 수 있습니다.' 
---
= 쉘프 ID-NS224 쉘프를 변경합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP가 아직 실행되지 않거나 시스템에 케이블로 연결되기 전에 쉘프를 핫 추가할 때 시스템의 쉘프 ID를 변경할 수 있습니다. 또한 ONTAP가 가동 중이고 실행 중일 때(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음) 쉘프 ID를 변경할 수 있으며 쉘프의 모든 드라이브가 소유 안 됨, 스페어 또는 오프라인 애그리게이트의 일부임

.시작하기 전에
* ONTAP가 실행 중인 경우(컨트롤러 모듈을 사용하여 데이터를 제공할 수 있음), 쉘프의 모든 드라이브가 소유되지 않은 애그리게이트, 스페어 또는 오프라인 애그리게이트의 일부인지 확인해야 합니다.
+
'storage disk show -shelf_shelf_number_' 명령을 사용하여 드라이브의 상태를 확인할 수 있습니다. Container Type 컬럼의 출력은 실패한 드라이브인 경우 SPare 또는 Broken을 표시해야 합니다. 또 컨테이너 이름과 소유자 칼럼에는 대시가 있어야 합니다.

* 한쪽 면을 곧게 편 종이 클립 또는 좁은 볼펜이 필요합니다.
+
종이 클립이나 볼펜으로 오퍼레이터 디스플레이 패널(ODP)의 LED 오른쪽에 있는 작은 구멍을 통해 쉘프 ID 버튼에 액세스할 수 있습니다.



.이 작업에 대해
* 유효한 쉘프 ID는 00부터 99까지입니다.
* 쉘프 ID는 HA 쌍 내에서 고유해야 합니다.
* 쉘프 ID가 적용되려면 쉘프 전원을 껐다가 다시 켜야 합니다(두 전원 코드를 모두 뽑고 적절한 시간을 기다린 다음 다시 연결해야 함).
+
전원 코드를 다시 연결하기 전에 대기하는 시간은 이 절차의 뒷부분에서 설명하는 ONTAP 상태에 따라 달라집니다.

+

NOTE: NS224 선반에는 전원 공급 장치에 전원 스위치가 없습니다.



.단계
. 쉘프 전원이 아직 켜져 있지 않은 경우 전원을 켭니다.
+
먼저 전원 코드를 선반에 연결한 다음 전원 코드 고정장치에 전원 코드를 고정한 다음 전원 코드를 다른 전원에 연결하여 안정성을 확보할 수 있습니다.

. 왼쪽 엔드 캡을 제거하여 LED의 오른쪽에 있는 작은 구멍을 찾습니다.
. 쉘프 ID의 첫 번째 번호를 변경합니다.
+
.. 종이 클립이나 볼펜을 작은 구멍에 삽입합니다.
.. 디지털 디스플레이의 첫 번째 숫자가 깜박일 때까지 단추를 누른 다음 단추를 놓습니다.
+
숫자가 깜박일 때까지 최대 15초가 걸릴 수 있습니다. 그러면 쉘프 ID 프로그래밍 모드가 활성화됩니다.

+

NOTE: ID가 깜빡이는 데 15초 이상 걸리는 경우 버튼을 다시 길게 눌러 완전히 누르십시오.

.. 버튼을 눌렀다가 놓으면 0에서 9 사이의 원하는 번호에 도달할 때까지 숫자가 앞으로 이동합니다.
+
각 누름 및 해제 시간은 1초 단위로 짧게 설정할 수 있습니다.

+
첫 번째 숫자가 계속 깜박입니다.



. 쉘프 ID의 두 번째 번호를 변경합니다.
+
.. 디지털 디스플레이에서 두 번째 숫자가 깜박일 때까지 버튼을 계속 누릅니다.
+
숫자가 깜박일 때까지 최대 3초가 걸릴 수 있습니다.

+
디지털 디스플레이의 첫 번째 숫자가 깜박임을 멈춥니다.

.. 버튼을 눌렀다가 놓으면 0에서 9 사이의 원하는 번호에 도달할 때까지 숫자가 앞으로 이동합니다.
+
두 번째 숫자가 계속 깜박입니다.



. 원하는 번호를 잠그고 두 번째 번호의 깜박임이 멈출 때까지 버튼을 길게 눌러 프로그래밍 모드를 종료합니다.
+
숫자가 깜박임을 멈추는 데 최대 3초가 걸릴 수 있습니다.

+
디지털 디스플레이의 두 숫자가 깜박이기 시작하고 ODP의 황색 LED가 약 5초 후에 켜지면서 보류 중인 쉘프 ID가 아직 적용되지 않았음을 알려줍니다.

. 쉘프 전원을 껐다가 다시 켜 쉘프 ID가 적용되도록 합니다.
+
쉘프의 두 전원 공급 장치에서 전원 코드를 뽑고 적절한 시간을 기다린 다음 쉘프 전원 공급 장치에 다시 연결하여 전원을 껐다가 켜야 합니다.

+
전원 코드가 꽂으면 전원 공급 장치의 전원이 켜집니다. 이색 LED가 녹색으로 켜져야 합니다.

+
** ONTAP가 아직 실행되지 않았거나 shelf(시스템에 아직 케이블로 연결되지 않은)를 핫 추가할 경우, 10초 이상 기다리십시오.
** ONTAP가 실행 중이고(컨트롤러를 사용하여 데이터를 제공할 수 있는 경우) 쉘프의 모든 드라이브가 소유되지 않은 경우, 스페어 또는 오프라인 애그리게이트의 일부일 경우 70초 이상 기다려야 합니다.
+
이 시간 동안 ONTAP는 이전 쉘프 주소를 적절히 삭제하고 새 쉘프 주소의 복사본을 업데이트할 수 있습니다.



. 왼쪽 엔드 캡을 다시 장착합니다.

