---
permalink: ns224/hot-add-aff-prepare.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff systems, preparation 
summary: 'RoCE를 지원하는 PCIe 카드 또는 I/O 모듈을 설치하고, 포트를 구성하고, 기존 셸프의 케이블을 다시 연결하고, 필요한 경우 자동 드라이브 할당을 비활성화하여 NS224 셸프를 AFF 시스템에 핫 추가(hot-add)할 준비를 하십시오.' 
---
= AFF 시스템에 NS224 셸프를 핫애드하는 준비 과정 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NS224 셸프를 AFF 시스템에 핫 애드하기 전에 RoCE를 지원하는 스토리지 포트가 충분한지 확인하고, 스토리지 용도로 구성하고, 새 셸프에 맞게 기존 구성을 최적화하십시오.



== 준비물

AFF 시스템에 NS224 셸프를 핫 추가하기 위한 준비에는 새 셸프를 물리적으로 설치하기 전에 스토리지 연결 인프라를 확인하고 구성하는 작업이 포함됩니다. 이러한 작업을 통해 HA 쌍에 필요한 RoCE 지원 이더넷 포트가 있는지 확인하고 시스템이 추가 스토리지 용량을 지원하도록 구성됩니다.

완료해야 할 구체적인 준비 작업은 플랫폼 모델, 현재 구성 및 추가할 쉘프 개수에 따라 다릅니다.

RoCE 지원 PCIe 카드 또는 I/O 모듈을 설치합니다:: 시스템에 RoCE를 지원하는 이더넷 포트가 충분히 있는지 확인하십시오(각 컨트롤러의 셸프당 2개). 추가 포트가 필요한 경우 올바른 컨트롤러 슬롯에 RoCE 지원 PCIe 카드 또는 I/O 모듈을 설치하십시오.
스토리지용으로 RoCE 지원 포트를 구성합니다:: NS224 셸프를 연결하는 데 RoCE를 지원하는 전용 포트가 아닌 일반 포트를 사용하는 경우, 해당 포트를 네트워킹 용도가 아닌 스토리지 용도로 구성하십시오. 이 작업은 시스템에 영향을 주지 않고 수행할 수 있습니다.
기존 쉘프의 케이블을 뽑습니다:: 일부 플랫폼 모델의 경우, RoCE 지원 PCIe 카드 또는 I/O 모듈을 추가로 설치한 후 슬롯 장애에 대한 복원력을 확보하기 위해 기존 쉘프의 서로 다른 슬롯에 있는 두 세트의 포트에 걸쳐 케이블을 다시 연결해야 할 수 있습니다.
자동 드라이브 할당을 비활성화합니다:: 드라이브 소유권을 수동으로 할당할 계획이라면 셸프를 핫 추가하기 전에 자동 드라이브 할당을 비활성화하십시오.

