---
permalink: ns224/hot-add-aff-prepare-a900.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff systems, preparation, roce, aff a900 
summary: RoCE 지원 I/O 모듈을 설치하고, 포트를 구성하고, 기존 셸프의 케이블을 다시 연결하고, 자동 드라이브 할당을 비활성화하여 AFF A900 시스템에 NS224 셸프를 핫 애드할 수 있도록 준비하십시오. 
---
= AFF A900 시스템에 NS224 선반을 핫애드 방식으로 장착할 수 있도록 준비하십시오.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A900 시스템에 NS224 셸프를 핫 애드할 수 있도록 준비하려면 RoCE를 지원하는 스토리지 포트가 충분한지 확인하고, 스토리지 용도로 구성하고, 최적의 연결을 위해 기존 셸프의 케이블을 다시 연결하고, 자동 드라이브 할당을 비활성화하십시오.



== RoCE 지원 I/O 모듈 설치

시스템에서 RoCE 지원 PCIe 카드 또는 I/O 모듈 사용을 지원하는 경우, HA 쌍에는 핫 추가하려는 쉘프 수를 지원할 수 있는 충분한 RoCE 지원 이더넷 포트가 있어야 합니다.

.단계
. 핫 추가할 각 쉘프에 대해 각 컨트롤러에 RoCE 지원 포트가 2개 있는지 확인합니다.
+
이러한 포트는 시스템에서 지원하는 대로 컨트롤러 온보드, RoCE 지원 PCIe 카드, 둘의 조합 또는 RoCE 지원 I/O 모듈에 있을 수 있습니다.

. HA 쌍에 사용 가능한 RoCE 지원 포트가 충분하지 않은 경우, 시스템에서 지원하는 올바른 컨트롤러 슬롯에 추가 PCIe 카드 또는 I/O 모듈을 설치하십시오.
+
.. 시스템에 맞는 컨트롤러 슬롯을 확인하십시오.  https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]를 참조하십시오.
.. PCIe 카드 또는 I/O 모듈 설치 지침은 시스템 설명서를 참조하십시오.






== 스토리지용으로 RoCE 지원 포트를 구성합니다

일부 시스템에서는 RoCE 지원 PCIe 카드 또는 I/O 모듈을 지원되는 컨트롤러 슬롯에 설치하면 RoCE 지원 포트가 자동으로 스토리지 용도로 설정됩니다. 하지만 포트가 스토리지 용도로 올바르게 구성되었는지 확인하려면 이 절차를 완료해야 합니다.

스토리지 사용을 위해 비전용 RoCE 지원 포트를 구성하는 것은 무중단 절차입니다. 컨트롤러 중 하나 또는 둘 다 유지 관리 모드에 있지 않는 한 컨트롤러를 재부팅할 필요가 없습니다. 이 절차는 두 컨트롤러 모두 유지 관리 모드가 아닌 상태를 가정합니다.

향후 스토리지 용도에서 네트워킹 용도로 포트를 변경해야 하는 경우 명령 `storage port modify -node _node_name_ -port _port_name_ -mode network`을 사용하십시오.

.단계
. 각 컨트롤러에 RoCE를 지원하는 추가 PCIe 카드 또는 I/O 모듈을 설치했는지 확인하십시오.
. SSH 또는 시리얼 콘솔 포트를 사용하여 클러스터에 로그인합니다.
. HA 쌍의 비전용 포트가 스토리지 용도로 구성되어 있는지 확인하려면 명령 `storage port show`을 입력하십시오.
+
명령 출력은 ONTAP 버전에 따라 다릅니다.

+
** **ONTAP 9.8 이상:** 스토리지 용도로 구성된 비전용 포트가 `storage`  `Mode` 열에 표시됩니다. 스토리지 용도로 구성되지 않은 포트는 `network`  `Mode` 열에 표시됩니다.
** **ONTAP 9.7:** 스토리지 용도로 구성된 비전용 포트는 `false` 열과 `Is Dedicated?` `enabled` 열에 `State` 표시됩니다. 스토리지 용도로 구성되지 않은 포트는 `false` 열과 `Is Dedicated?` `disabled` 열에 `State` 표시됩니다.


. 전용 포트가 아닌 포트가 스토리지 용도로 구성되어 있으면 이 절차는 완료됩니다. 그렇지 않은 경우 다음 단계를 완료하여 포트를 구성하십시오.
. 컨트롤러 중 하나에서 전용이 아닌 포트를 스토리지 용도로 구성하십시오. 구성하려는 각 포트에 대해 해당 명령을 반복해야 합니다.
+
[cols="1,3"]
|===
| HA 쌍이 실행 중인 경우... | 이 명령 사용... 


 a| 
ONTAP 9.8 이상
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 두 번째 컨트롤러에 대해서도 이전 단계를 반복합니다.
. 명령어 `storage port show`를 입력하여 두 컨트롤러의 비전용 포트가 스토리지 용도로 구성되어 있는지 확인하십시오.
+
명령 출력은 ONTAP 버전에 따라 다릅니다.

+
** **ONTAP 9.8 이상:** 스토리지 용도로 구성된 비전용 포트는  `storage`이(가)  `Mode` 열에 표시됩니다.
** **ONTAP 9.7:** 스토리지 용도로 구성된 비전용 포트는 `false`  `Is Dedicated?` 열과 `enabled`  `State` 열에 표시됩니다.






== 기존 쉘프의 케이블을 뽑습니다

A900 HA 쌍에 쉘프를 핫 추가할 경우, 여러 RoCE 지원 I/O 모듈 간의 연결 균형을 맞추기 위해 기존 쉘프의 케이블을 재배선해야 합니다.

* 두 번째 셸프를 핫 추가하는 경우 첫 번째 셸프는 슬롯 2와 10에 걸쳐 케이블을 다시 연결해야 합니다. 두 번째 셸프의 경우 이 절차에서는 기존 셸프가 각 컨트롤러의 슬롯 2에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.
* 네 번째 쉘프를 핫 추가하는 경우 세 번째 쉘프를 슬롯 1과 11에 다시 케이블로 연결해야 합니다. 네 번째 쉘프의 경우 이 절차에서는 세 번째 쉘프가 각 컨트롤러의 슬롯 1에 케이블로 연결되어 있다고 가정합니다.


.단계
. 두 번째 셸프나 네 번째 셸프를 핫 추가할 경우 다음 중 하나를 수행합니다.
+
** 두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 2과 슬롯 10에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.
+
... 컨트롤러 A에서 케이블을 슬롯 2 포트 b(e2b)에서 슬롯 10 포트 b(e10b)로 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** 4번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 1와 슬롯 11에 있는 RoCE 지원 I/O 모듈에서 세 번째 쉘프를 재장착할 수 있습니다.
+
... 컨트롤러 A에서 케이블을 슬롯 1 포트 b(e1b)에서 슬롯 11 포트 b(e11b)로 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




. 을 사용하여 재연결된 쉘프가 올바르게 연결되었는지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
케이블 연결 오류가 발생하면 제공된 수정 조치를 따르십시오.





== 자동 드라이브 할당을 비활성화합니다

드라이브 소유권을 수동으로 할당해야 하는지 또는 스토리지 시스템에 대한 드라이브 소유권 정책의 자동 할당을 이해하려면 로 이동합니다 https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["디스크 소유권 자동 할당 정보"^].

.단계
. 자동 드라이브 할당이 설정되었는지 'Storage disk option show'를 확인합니다
+
두 노드 중 하나에서 명령을 입력할 수 있습니다.

+
자동 드라이브 할당이 활성화된 경우, 출력 결과는 각 노드의  `Auto Assign` 열에  `on`를 표시합니다.

. 자동 드라이브 할당이 설정된 경우 'storage disk option modify -node_node_name_-autostassign off'를 비활성화합니다
+
두 노드 모두에서 자동 드라이브 할당을 해제해야 합니다.



.다음 단계
link:hot-add-aff-install.html["쉘프를 설치하십시오"]로 이동하십시오.
