---
permalink: ns224/hot-remove-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, drive, aggregate, ha, pair, serving, data, i/o, hot-remove an ns224 
summary: '드라이브에서 애그리게이트를 제거한 NS224 드라이브 쉘프를 HA 쌍에서 데이터를 처리하고 \(I/O가 진행 중\) 데이터를 핫 제거할 수 있습니다.' 
---
= Shelf-NS224 쉘프 핫 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브에서 애그리게이트를 제거한 NS224 드라이브 쉘프를 HA 쌍에서 데이터를 처리하고 I/O가 진행 중인 상태에서 핫 제거할 수 있습니다.

.시작하기 전에
* HA 쌍이 테이크오버 상태가 될 수 없습니다.
* 분리할 쉘프의 모든 애그리게이트(드라이브가 스페어 드라이브여야 함)를 드라이브에서 제거해야 합니다.
+

NOTE: 제거하는 쉘프에서 이 절차를 수행하면 시스템에서 다중 디스크 패닉이 발생할 수 있습니다.

+
'storage aggregate offline-aggregate_aggregate_name_' 명령과 'storage aggregate delete-aggregate_aggregate_name_' 명령을 차례로 사용할 수 있습니다.

* 시스템이 시스템 캐비닛에 제공된 경우, 수납장 후면 업권에 쉘프를 고정하는 나사를 분리하려면 십자 드라이버가 필요합니다.


.이 작업에 대해
* 둘 이상의 쉘프를 핫 제거할 경우, 한 번에 하나씩 쉘프를 제거합니다.
* * 모범 사례: * 가장 좋은 방법은 제거할 쉘프의 드라이브에서 애그리게이트를 제거한 후 드라이브 소유권을 제거하는 것입니다.
+
스페어 드라이브에서 소유권 정보를 제거하면 드라이브를 다른 노드에 적절히 통합할 수 있습니다(필요한 경우).

+
드라이브에서 소유권을 제거하는 절차는 디스크에서 확인하실 수 있으며 콘텐츠를 집계합니다.

+
https://["디스크 및 애그리게이트 개요"^]




NOTE: 이 절차를 수행하려면 자동 드라이브 할당을 비활성화해야 합니다. 이 절차를 마치면(쉘프를 제거한 후) 자동 드라이브 할당을 다시 활성화할 수 있습니다.

* 필요한 경우 셸프의 위치(파란색) LED를 켜서 해당 셸프를 물리적으로 찾을 수 있습니다. 'Storage shelf location-led modify-shelf-name_shelf_name_-led-status on'
+
해당 셸프의 '_shelf_name_'을 모르는 경우 'storage shelf show' 명령어를 실행한다.

+
선반에는 3개의 위치 LED가 있습니다. 하나는 운영자 디스플레이 패널에, 다른 하나는 각 NSM 모듈에 있습니다. 위치 LED가 30분 동안 켜져 있습니다. 같은 명령을 입력해도 끄기 옵션을 사용하여 해제할 수 있습니다.

* 전용 RoCE가 아닌 포트(컨트롤러, RoCE 지원 PCIe 카드, 두 모듈 결합 또는 I/O 모듈)에서 쉘프를 분리한 후에는 네트워킹을 위해 이러한 포트를 재구성할 수 있습니다.
+

NOTE: HA 쌍이 ONTAP 9.6 버전을 실행 중인 경우 컨트롤러를 한 번에 하나씩 재부팅해야 합니다. HA 9.7 ONTAP 이상을 실행 중인 경우 하나 또는 두 컨트롤러가 유지보수 모드가 아닌 한 컨트롤러를 재부팅하지 않아도 됩니다. 이 절차에서는 두 컨트롤러가 유지보수 모드에 있지 않다고 가정합니다.



.단계
. 적절하게 접지합니다.
. 분리한 쉘프의 드라이브에 애그리게이트가 없고(스페어) 소유권이 제거되었는지 확인합니다.
+
.. shelf disk show -shelf_shelf_number_'에서 제거할 모든 드라이브를 나열하려면 다음 명령을 입력합니다
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

.. 출력을 확인하여 드라이브에 애그리게이트가 없는지 확인합니다.
+
Aggregate가 없는 드라이브는 '컨테이너 이름' 열에 대시가 있습니다.

.. 출력을 확인하여 드라이브에서 소유권이 제거되었는지 확인합니다.
+
소유권이 없는 드라이브는 소유자 열에 대시가 있습니다.

+

NOTE: 드라이브에 오류가 발생하면 컨테이너 유형 열에 깨진 드라이브가 표시됩니다. (오류가 발생한 드라이브는 소유권이 없습니다.)

+
다음 출력에서는 분리 중인 쉘프(쉘프 2)의 드라이브가 쉘프 분리 시 올바른 상태입니다. 애그리게이트는 모든 드라이브에서 제거되므로 각 드라이브의 '컨테이너 이름' 열에 대시가 표시됩니다. 소유권은 모든 드라이브에서도 제거되므로 각 드라이브의 소유자 열에 대시가 나타납니다.



+
[listing]
----
cluster1::> storage disk show -shelf 2

           Usable           Disk     Container   Container
Disk         Size Shelf Bay Type     Type        Name       Owner
-------- -------- ----- --- ------   ----------- ---------- ---------
...
2.2.4           -     2   4 SSD-NVM  spare                -         -
2.2.5           -     2   5 SSD-NVM  spare                -         -
2.2.6           -     2   6 SSD-NVM  broken               -         -
2.2.7           -     2   7 SSD-NVM  spare                -         -
...
----
. 분리할 쉘프를 물리적으로 찾습니다.
. 분리할 선반에서 케이블을 분리합니다.
+
.. 전원 코드가 AC 전원 공급 장치인 경우 전원 코드 고정 장치를 열거나 DC 전원 공급 장치인 경우 두 개의 나비 나사를 푼 다음 전원 공급 장치에서 전원 코드를 뽑습니다.
+
전원 공급 장치에는 전원 스위치가 없습니다.

.. 스토리지 케이블 연결 끊기(쉘프에서 컨트롤러로).


. 랙이나 캐비닛에서 쉘프를 물리적으로 제거합니다.
+

NOTE: 완전히 장착된 NS224 선반은 최대 30.29kg(66.78lbs)의 중량을 지탱할 수 있으며, 유압 리프트를 들거나 사용하려면 2명이 필요합니다. 선반 무게가 불균형하게 되므로 선반 무게를 줄이기 위해 선반 구성 요소(선반 전면 또는 후면의)를 제거하지 마십시오.

+

NOTE: 시스템을 캐비닛에 운송한 경우, 먼저 쉘프를 뒷면 업권에 고정하는 두 개의 필립스 나사를 풀어야 합니다. 나사는 하단 NSM 모듈의 내부 선반 벽에 있습니다. 나사에 접근하려면 두 NSM 모듈을 모두 제거해야 합니다.

. 둘 이상의 쉘프를 제거할 경우 2-5단계를 반복합니다.
+
그렇지 않으면 다음 단계로 이동합니다.

. 드라이브에서 소유권을 제거할 때 자동 드라이브 할당을 비활성화한 경우 '스토리지 디스크 옵션 수정 - 자동 할당 설정'을 다시 활성화합니다
+
두 컨트롤러 모듈 모두에서 명령을 실행합니다.

. 다음 하위 단계를 완료하여 네트워킹용으로 비전용 RoCE 가능 포트를 재구성할 수 있습니다.
+
그렇지 않으면 이 절차를 수행합니다.

+
.. 현재 스토리지에 사용하도록 구성된 비전용 포트의 이름을 'Storage port show'로 확인합니다
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

+

NOTE: 스토리지에 사용하도록 구성된 비전용 포트는 다음과 같이 출력에 표시됩니다. HA 쌍이 ONTAP 9.8 이상을 실행 중인 경우 비전용 포트는 "모드" 열에 "스토리지"를 표시합니다. HA 쌍이 ONTAP 9.7 또는 9.6을 실행 중인 경우, '전용 여부'에 '거짓'을 표시하는 비전용 포트는 무엇입니까 '상태' 열에 '활성화됨'도 표시됩니다.

.. HA 쌍이 실행 중인 ONTAP 버전에 해당하는 일련의 단계를 완료하십시오.
+
[cols="1,2"]
|===
| HA 쌍이 실행 중인 경우... | 그러면... 


 a| 
ONTAP 9.8 이상
 a| 
... 첫 번째 컨트롤러 모듈에서 네트워킹용 비전용 포트를 'STORAGE PORT MODIFY-NODE_NODE NAME_-PORT_PORT NAME_-MODE NETWORK'로 재구성한다
+
재구성하는 각 포트에 대해 이 명령을 실행해야 합니다.

... 위의 단계를 반복하여 두 번째 컨트롤러 모듈의 포트를 재구성합니다.
... 하위 단계 8C로 이동하여 모든 포트 변경 사항을 확인합니다.




 a| 
ONTAP 9.7
 a| 
... 첫 번째 컨트롤러 모듈에서 네트워킹용 비전용 포트를 'STORAGE PORT DISABLE-NODE_NODE NAME_-PORT_PORT NAME_'로 재구성합니다
+
재구성하는 각 포트에 대해 이 명령을 실행해야 합니다.

... 위의 단계를 반복하여 두 번째 컨트롤러 모듈의 포트를 재구성합니다.
... 하위 단계 8C로 이동하여 모든 포트 변경 사항을 확인합니다.




 a| 
ONTAP 9.6 버전입니다
 a| 
... 첫 번째 컨트롤러 모듈에서 네트워킹용 RoCE 가능 포트를 'STORAGE PORT DISABLE-NODE_NODE NAME_-PORT_PORT NAME_'로 재구성합니다
+
재구성하는 각 포트에 대해 이 명령을 실행해야 합니다.

... 컨트롤러 모듈을 재부팅하여 포트 변경사항을 적용합니다.
+
'시스템 노드 reboot-node_node name_-reason_reason_for the reboot'

+

NOTE: 다음 단계를 진행하기 전에 재부팅이 완료되어야 합니다. 재부팅에는 최대 15분이 소요될 수 있습니다.

... 첫 번째 단계(a)를 반복하여 두 번째 컨트롤러 모듈의 포트를 재구성합니다.
... 두 번째 단계(b)를 반복하여 포트 변경 사항을 적용하려면 두 번째 컨트롤러를 재부팅합니다.
... 하위 단계 8C로 이동하여 모든 포트 변경 사항을 확인합니다.


|===
.. 두 컨트롤러 모듈의 비전용 포트가 네트워킹용으로 재구성되었는지 확인합니다. 'Storage port show'
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

+
HA 쌍이 ONTAP 9.8 이상을 실행 중인 경우 비전용 포트는 Mode 열에 network를 표시합니다.

+
HA 쌍이 ONTAP 9.7 또는 9.6을 실행 중인 경우, '전용 여부'에 '거짓'을 표시하는 비전용 포트는 무엇입니까 칼럼은 또한 '상태' 칼럼에 '비활성화'를 표시합니다.




