---
permalink: ns224/install-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, install, hot-add an ns224 drive shelf 
summary: HA 쌍이 특정 요구사항을 충족하고 HA 쌍에 적용할 수 있는 준비 작업이 완료된 후에 NS224 드라이브 쉘프를 핫 추가할 수 있습니다. 
---
= 핫 애드온 NS224 쉘프용 쉘프를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NS224 쉘프를 캐비닛이나 통신 랙에 설치하고 전원 코드를 연결하고(쉘프에 자동으로 전원 공급) 쉘프 ID를 설정해야 합니다.

.시작하기 전에
* 한 면이 곧게 펴진 종이 클립이나 끝이 좁은 볼펜 클립이 있는지 확인하십시오.
+
선반 ID를 변경하려면 종이 클립이나 볼펜 펜을 사용하여 ODP(Operator Display Panel) 뒤에 있는 선반 ID(선반 ID) 변경 단계에 액세스합니다.

* 완전 장착된 NS224 선반은 무게가 최대 30.29kg(66.78lbs)이며 유압 리프트를 들어 올리거나 사용하려면 2명이 필요합니다. 선반 무게가 불균형하게 되므로 선반 무게를 줄이기 위해 선반 구성 요소(선반 전면 또는 후면의)를 제거하지 마십시오.


.단계
. 키트와 함께 제공된 지침에 따라 필요한 경우 선반용 레일 키트를 설치합니다.
+

NOTE: 쉘프를 플랜지 장착 하지 마십시오.

. 쉘프 설치:
+
.. 선반의 후면을 레일에 놓은 다음 하단에서 선반을 지지하고 캐비닛이나 텔코 랙에 밀어 넣습니다.
+
여러 쉘프를 설치하는 경우 첫 번째 쉘프를 컨트롤러 바로 위에 놓습니다. 두 번째 쉘프를 컨트롤러 바로 아래에 배치합니다. 추가 선반에 대해 이 패턴을 반복합니다.

.. 키트에 포함된 장착 나사를 사용하여 캐비닛이나 텔코 랙에 쉘프를 고정합니다.


. 전원 연결:
+
.. 전원 코드를 선반에 연결하고 제자리에 고정합니다.
+
AC 전원 공급 장치인 경우 전원 코드 고정 장치로 고정합니다.

+
DC 전원 공급 장치인 경우 두 개의 나비 나사로 제자리에 고정합니다.

.. 복원력을 위해 전원 코드를 다른 전원에 연결합니다.
+
선반이 전원에 연결되면 전원이 켜지고 전원 스위치가 없습니다. 올바르게 작동하면 전원 공급 장치의 이중 LED가 녹색으로 켜집니다.



. 쉘프 ID를 HA 쌍 내의 고유 번호로 설정합니다.
+
자세한 지침은 을 참조하십시오 link:change-shelf-id.html["쉘프 ID-NS224 쉘프를 변경합니다"^].

+
.. 왼쪽 엔드 캡을 제거하고 LED 오른쪽에 있는 작은 구멍을 찾습니다.
.. 종이 클립 또는 유사한 도구의 끝을 작은 구멍에 삽입하여 선반 ID 버튼에 닿게 합니다.
.. 디지털 디스플레이의 첫 번째 숫자가 깜박일 때까지 단추를 최대 15초 동안 누른 다음 버튼에서 손을 뗍니다.
+
ID가 깜빡이는 데 15초 이상 걸리는 경우 버튼을 다시 길게 눌러 완전히 누르십시오.

.. 버튼을 눌렀다가 놓으면 0에서 9 사이의 원하는 번호에 도달할 때까지 숫자가 앞으로 이동합니다.
.. 4c 및 4D의 하위 단계를 반복하여 쉘프 ID의 두 번째 번호를 설정합니다.
+
숫자가 깜박이려면 최대 3초(15초 대신)가 걸릴 수 있습니다.

.. 두 번째 숫자의 깜박임이 멈출 때까지 버튼을 누르고 있습니다.
+
약 5초 후 두 숫자가 깜박이기 시작하고 ODP의 황색 LED가 켜집니다.

.. 쉘프 전원을 껐다가 다시 켜 쉘프 ID가 적용되도록 합니다.
+
선반에서 두 전원 코드를 모두 뽑고 10초 정도 기다린 다음 다시 연결해야 합니다.

+
전원 공급 장치로 전원이 복원되면 두 색 LED가 녹색으로 켜집니다.





.다음 단계
핫 애드 쉘프에 케이블을 연결합니다. 로 이동합니다. link:cable-overview-hot-add-shelf.html["핫 애드 케이블 연결 개요"]
