---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: HA 쌍이 특정 요구사항을 충족하고 HA 쌍에 적용할 수 있는 준비 작업이 완료된 후에 NS224 드라이브 쉘프를 핫 추가할 수 있습니다. 
---
= 핫 애드온 NS224 쉘프를 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NS224 쉘프를 핫 추가하기 전에 HA 쌍에 적합한 준비 작업을 완료합니다.

해당 준비 작업이 완료되면 로 이동합니다 link:prepare-hot-add-shelf.html["핫 애드용 쉘프를 설치합니다"].



== RoCE 지원 PCIe 카드 또는 I/O 모듈을 설치합니다

플랫폼 모델에서 RoCE 지원 PCIe 카드 또는 I/O 모듈 사용을 지원하는 경우, 핫 애드할 쉘프 수를 지원할 수 있는 RoCE 지원 이더넷 포트가 HA 쌍에 충분해야 합니다.

.단계
. 핫 추가할 각 쉘프에 대해 각 컨트롤러에 RoCE 지원 포트가 2개 있는지 확인합니다.
+
이들 포트는 플랫폼 모델에서 지원하는 대로 컨트롤러, RoCE 지원 PCIe 카드, 두 가지를 결합한 포트 또는 RoCE 지원 I/O 모듈 상에 추가할 수 있습니다.

. HA 쌍에 사용 가능한 RoCE 지원 포트가 충분하지 않은 경우, 플랫폼 모델에서 지원하는 대로 추가 PCIe 카드 또는 I/O 모듈을 올바른 컨트롤러 슬롯에 설치합니다.
+
.. 사용 중인 플랫폼 모델에 적합한 컨트롤러 슬롯을 식별합니다. 을 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.
.. PCIe 카드 또는 I/O 모듈 설치 지침은 플랫폼 모델 설명서를 참조하십시오.






== 스토리지용으로 RoCE 지원 포트를 구성합니다

HA 쌍에 NS224 쉘프를 핫 추가하는 데 사용할 수 없는 전용 RoCE 지원 이더넷 포트가 있는 경우, 스토리지용으로 포트를 구성해야 합니다(네트워킹용 아님).

.시작하기 전에
* 각 컨트롤러에 RoCE 지원 PCIe 카드 또는 I/O 모듈을 추가로 설치했는지 확인합니다.


.이 작업에 대해
* 일부 플랫폼 모델의 경우, RoCE 지원 PCIe 카드 또는 I/O 모듈을 컨트롤러의 지원되는 슬롯에 설치하면 포트가 자동으로 스토리지 사용(네트워킹 대신)으로 기본 설정됩니다. 단, 다음 절차를 완료하여 RoCE 지원 포트가 저장소용으로 구성되었는지 확인하는 것이 좋습니다.
* HA 쌍에서 비전용 RoCE 지원 포트를 스토리지로 구성되지 않음을 확인할 경우 무중단 구성 절차를 통해 포트를 구성할 수 있습니다. 하나 또는 두 컨트롤러가 유지보수 모드에 있지 않는 한 컨트롤러를 재부팅하지 않아도 됩니다. 이 절차에서는 두 컨트롤러가 유지보수 모드에 있지 않다고 가정합니다.
* 나중에 스토리지 사용에서 네트워킹 사용으로 포트를 변경해야 하는 경우에는 명령을 입력합니다. `storage port modify -node _node_name_ -port _port_name_ -mode network`


.단계
. SSH 또는 시리얼 콘솔 포트를 사용하여 클러스터에 로그인합니다.
. 다음 명령을 입력하여 HA 쌍의 비전용 포트가 스토리지용으로 구성되었는지 확인합니다.
+
`storage port show`

+
** HA 쌍이 ONTAP 9.8 이상을 실행 중인 경우 비전용 포트는 "모드" 열에 "저장"을 표시합니다.
** HA 쌍에서 ONTAP 9.7을 실행 중인 경우 `Is Dedicated?` 열에 표시되는 비전용 포트도 `State` 열에 표시됩니다 `enabled`. `false`
+
[NOTE]
====
비전용 포트가 스토리지 용도로 구성되지 않은 경우 명령 출력에 다음이 표시됩니다.

*** HA 쌍이 ONTAP 9.8 이상을 실행 중인 경우 비전용 포트는 Mode 열에 network를 표시합니다.
*** HA 쌍에서 ONTAP 9.7을 실행 중인 경우 `Is Dedicated?`` 열에 표시되는 비전용 포트도 `State` 열에 표시됩니다 `disabled`. `false`


====


. 비전용 포트가 스토리지에 사용하도록 구성된 경우 이 절차를 수행합니다.
+
그렇지 않은 경우 다음 단계를 완료하여 포트를 구성해야 합니다.

. 다음 컨트롤러 중 하나에서 스토리지용으로 비전용 포트를 구성합니다.
+
구성할 각 포트에 대해 해당 명령을 반복해야 합니다.

+
[cols="1,3"]
|===
| HA 쌍이 실행 중인 경우... | 이 명령 사용... 


 a| 
ONTAP 9.8 이상
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 두 번째 컨트롤러에 대해서도 이전 단계를 반복합니다.
. 두 컨트롤러의 비전용 포트가 스토리지용으로 구성되었는지 확인합니다. `storage port show`
+
** HA 쌍이 ONTAP 9.8 이상을 실행 중인 경우 비전용 포트는 "모드" 열에 "저장"을 표시합니다.
** HA 쌍에서 ONTAP 9.7을 실행 중인 경우 `Is Dedicated?` 열에 표시되는 비전용 포트도 `State` 열에 표시됩니다 `enabled`. `false`






== 기존 쉘프의 케이블을 뽑습니다

쉘프를 핫 추가하기 전에 플랫폼 모델에 따라 다른 슬롯에 있는 두 개의 포트 세트에 걸쳐 기존 쉘프를 다시 장착할 수 있습니다(RoCE 지원 PCIe 카드 또는 I/O 모듈을 추가로 설치한 후). 이렇게 하면 슬롯 장애에 대한 복원력을 확보할 수 있습니다.

.시작하기 전에
* 각 컨트롤러에 RoCE 지원 PCIe 카드 또는 I/O 모듈을 추가로 설치했는지 확인합니다.
* 설치한 RoCE 지원 PCIe 카드 또는 I/O 모듈의 비전용 포트가 스토리지용으로 구성되었는지 확인합니다.


.이 작업에 대해
* 재연결은 쉘프에 다중 경로-HA 연결이 있는 경우 중단 없는 절차입니다.
* 이 절차 중에는 항상 쉘프와의 연결을 유지할 수 있도록 한 번에 하나의 케이블을 이동합니다.
+

NOTE: 케이블을 한 포트에서 분리하여 다른 포트에 꽂는 시간 사이에는 케이블을 이동할 필요가 없습니다.

* 필요한 경우 에서 해당 플랫폼 모델의 셸프 케이블 그림을 참조하십시오 link:cable-overview-hot-add-shelf.html["핫 애드 케이블 연결 개요"].


.단계
. 플랫폼 모델에 해당하는 경우 서로 다른 슬롯에 있는 RoCE 지원 포트 2세트에서 기존 셸프의 연결을 재연결할 수 있습니다.


* AFF 시스템의 경우:
+
[role="tabbed-block"]
====
.AFF A1K 를 참조하십시오
--
두 번째 셸프나 네 번째 셸프를 핫 추가할 경우 다음 중 하나를 수행합니다.


NOTE: AFF A1K HA 쌍이 있고 세 번째 쉘프를 핫 추가하고 각 컨트롤러에 세 번째 또는 네 번째 RoCE 지원 I/O 모듈을 설치하는 경우, 세 번째 쉘프는 세 번째 또는 세 번째 및 네 번째 I/O 모듈에만 연결됩니다. 기존 쉘프를 재장착할 필요가 없습니다.

** 두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 11과 슬롯 10에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 11에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 11 포트 b(e11b)에서 슬롯 10 포트 b(e10b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** 4번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 9와 슬롯 8에 있는 RoCE 지원 I/O 모듈에서 세 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 세 번째 쉘프가 각 컨트롤러의 슬롯 9에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 9 포트 b(e9b)에서 슬롯 8 포트 b(e8b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.AFF A70, AFF A90 또는 AFF C80
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 11과 슬롯 8에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 11에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 11 포트 b(e11b)에서 슬롯 8 포트 b(e8b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
.AFF A800 또는 AFF C800
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 5와 슬롯 3에 있는 RoCE 지원 포트 2세트에 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 5에 있는 RoCE 가능 PCIe 카드에 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 5 포트 b(e5b)에서 슬롯 3 포트 b(e3b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
.AFF A700
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 3과 슬롯 7에 있는 RoCE 지원 포트 2세트에 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 3에 있는 RoCE 가능 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 3 포트 b(e3b)에서 슬롯 7 포트 b(e7b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
.AFF A400 또는 AFF C400
--
두 번째 쉘프를 핫 추가할 경우 플랫폼 모델에 따라 다음 중 하나를 수행합니다.

** AFF A400:
+
각 컨트롤러의 RoCE 지원 포트 2세트, 온보드 e0c/e0d 및 슬롯 5에서 첫 번째 쉘프를 재연결합니다.

+
하위 단계에서는 각 컨트롤러의 기존 쉘프가 RoCE 지원 온보드 포트 e0c/e0d에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 포트 e0d를 슬롯 5 포트 b(e5b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** AFF C400의 경우:
+
각 컨트롤러에서 슬롯 4와 슬롯 5에 있는 RoCE 지원 포트 2개에서 첫 번째 쉘프를 재연결합니다.

+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 4에 있는 RoCE 지원 포트에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 4 포트 A(e4a)에서 슬롯 5 포트 b(e5b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.AFF A900
--
두 번째 셸프나 네 번째 셸프를 핫 추가할 경우 다음 중 하나를 수행합니다.

** 두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 2과 슬롯 10에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 2에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 2 포트 b(e2b)에서 슬롯 10 포트 b(e10b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** 4번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 1와 슬롯 11에 있는 RoCE 지원 I/O 모듈에서 세 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 세 번째 쉘프가 각 컨트롤러의 슬롯 1에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 1 포트 b(e1b)에서 슬롯 11 포트 b(e11b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.AFF A30, AFF C30, AFF A50 또는 AFF C60
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 3과 슬롯 1에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 3에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 3 포트 b(e3b)에서 슬롯 1 포트 b(e1b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
====


* ASA 시스템의 경우:
+
[role="tabbed-block"]
====
.ASA A1K 를 참조하십시오
--
두 번째 셸프나 네 번째 셸프를 핫 추가할 경우 다음 중 하나를 수행합니다.


NOTE: ASA A1K HA 쌍이 있고 세 번째 쉘프를 핫 추가하고 각 컨트롤러에 세 번째 또는 네 번째 RoCE 지원 I/O 모듈을 설치하는 경우, 세 번째 쉘프는 세 번째 또는 세 번째 및 네 번째 I/O 모듈에만 연결됩니다. 기존 쉘프를 재장착할 필요가 없습니다.

** 두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 11과 슬롯 10에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 11에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 11 포트 b(e11b)에서 슬롯 10 포트 b(e10b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** 4번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 9와 슬롯 8에 있는 RoCE 지원 I/O 모듈에서 세 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 세 번째 쉘프가 각 컨트롤러의 슬롯 9에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 9 포트 b(e9b)에서 슬롯 8 포트 b(e8b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.ASA A70 또는 ASA A90
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 11과 슬롯 8에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 11에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 11 포트 b(e11b)에서 슬롯 8 포트 b(e8b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
.ASA A800 또는 ASA C800
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 5와 슬롯 3에 있는 RoCE 지원 포트 2세트에 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 5에 있는 RoCE 가능 PCIe 카드에 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 5 포트 b(e5b)에서 슬롯 3 포트 b(e3b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
.ASA A400 또는 ASA C400
--
두 번째 쉘프를 핫 추가할 경우 플랫폼 모델에 따라 다음 중 하나를 수행합니다.

** ASA A400:
+
각 컨트롤러의 RoCE 지원 포트 2세트, 온보드 e0c/e0d 및 슬롯 5에서 첫 번째 쉘프를 재연결합니다.

+
하위 단계에서는 각 컨트롤러의 기존 쉘프가 RoCE 지원 온보드 포트 e0c/e0d에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 포트 e0d를 슬롯 5 포트 b(e5b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** ASA C400의 경우:
+
각 컨트롤러에서 슬롯 4와 슬롯 5에 있는 RoCE 지원 포트 2개에서 첫 번째 쉘프를 재연결합니다.

+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 4에 있는 RoCE 지원 포트에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 4 포트 A(e4a)에서 슬롯 5 포트 b(e5b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.ASA A900
--
두 번째 셸프나 네 번째 셸프를 핫 추가할 경우 다음 중 하나를 수행합니다.

** 두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 2과 슬롯 10에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 2에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 2 포트 b(e2b)에서 슬롯 10 포트 b(e10b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


** 4번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 1와 슬롯 11에 있는 RoCE 지원 I/O 모듈에서 세 번째 쉘프를 재장착할 수 있습니다.
+
하위 단계에서는 세 번째 쉘프가 각 컨트롤러의 슬롯 1에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

+
... 컨트롤러 A에서 슬롯 1 포트 b(e1b)에서 슬롯 11 포트 b(e11b)로 케이블을 이동합니다.
... 컨트롤러 B에서 동일한 케이블 이동을 반복합니다




--
.ASA A30 또는 ASA A50
--
두 번째 쉘프를 핫 추가할 경우, 각 컨트롤러의 슬롯 3과 슬롯 1에 있는 RoCE 지원 I/O 모듈에서 첫 번째 쉘프를 재장착할 수 있습니다.

하위 단계에서는 기존 쉘프가 각 컨트롤러의 슬롯 3에 있는 RoCE 지원 I/O 모듈에 케이블로 연결되어 있다고 가정합니다.

.. 컨트롤러 A에서 슬롯 3 포트 b(e3b)에서 슬롯 1 포트 b(e1b)로 케이블을 이동합니다.
.. 컨트롤러 B에서 동일한 케이블 이동을 반복합니다


--
====


. 을 사용하여 재연결된 쉘프가 올바르게 연결되었는지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
케이블 연결 오류가 발생하면 제공된 수정 조치를 따르십시오.





== 자동 드라이브 할당을 비활성화합니다

핫 애드할 NS224 쉘프에 드라이브 소유권을 수동으로 할당하는 경우 자동 드라이브 할당을 사용하지 않도록 설정해야 합니다.

드라이브 소유권을 수동으로 할당해야 하는지 또는 스토리지 시스템에 대한 드라이브 소유권 정책의 자동 할당을 이해하려면 로 이동합니다 https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["디스크 소유권 자동 할당 정보"^].

.단계
. 자동 드라이브 할당이 설정되었는지 'Storage disk option show'를 확인합니다
+
두 노드 중 하나에서 명령을 입력할 수 있습니다.

+
자동 드라이브 할당이 활성화된 경우 출력이 각 노드에 대해 열에 표시됩니다 `on` `Auto Assign` .

. 자동 드라이브 할당이 설정된 경우 'storage disk option modify -node_node_name_-autostassign off'를 비활성화합니다
+
두 노드 모두에서 자동 드라이브 할당을 해제해야 합니다.


