---
permalink: ns224/requirements-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement 
summary: NS224 드라이브 쉘프를 핫 추가하려면 HA 쌍이 특정 요구사항을 충족해야 합니다. 
---
= 핫 애드온 NS224 쉘프의 요구사항 및 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
쉘프를 핫 추가하기 전에 요구사항과 모범 사례를 검토해야 합니다.



== 요구 사항

NS224 쉘프를 핫 추가하려면 HA 쌍이 특정 요구사항을 충족해야 합니다.

* * 지원되는 ONTAP 버전 *: ONTAP의 플랫폼 모델 및 버전은 핫 애드인 NS224 셸프 및 드라이브를 지원해야 합니다. 을 참조하십시오 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]
* * 쉘프 수 *: HA 쌍은 지원되는 최대 쉘프 수보다 적어야 합니다. 적어도 핫 추가할 셸프 수가 더 적어야 합니다.
+
쉘프를 핫 추가한 후에는 HA 쌍에서 지원하는 최대 쉘프 수를 초과할 수 없습니다. 을 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.

* * 케이블 *:
+
** 쉘프를 연결하는 데 사용할 케이블 수와 유형이 올바른지 확인하십시오. 을 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.
** NS224 쉘프가 이미 있는 HA 쌍에 쉘프를 핫 추가하는 경우, HA 쌍에 스토리지 케이블 연결 오류 메시지가 있을 수 없으며 다중 경로 HA로 케이블로 연결되어야 합니다.
+
를 실행하여 스토리지 케이블 연결 오류 메시지 및 취해야 할 수정 조치를 확인할 수  https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^] 있습니다.







== 모범 사례

NS224 쉘프를 핫 추가하기 전에 다음 모범 사례를 숙지하십시오.

* * 모범 사례: * 모범 사례는 선반을 핫 추가하기 전에 의 최신 버전을 https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["디스크 검증 패키지"^] 설치하는 것입니다.
+
현재 버전의 DQP를 설치하면 시스템이 새로 인증된 드라이브를 인식하고 사용할 수 있습니다. 이렇게 하면 드라이브가 인식되지 않으므로 최신 드라이브 정보가 없는 경우 및 드라이브 파티셔닝 예방에 대한 시스템 이벤트 메시지가 표시되지 않습니다. 또한 DQP는 최신 버전이 아닌 드라이브 펌웨어에 대해서도 알려줍니다.

* * 모범 사례: * 모범 사례는 선반을 핫 애드하기 전과 후에 실행하는 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^] 것입니다.
+
쉘프를 핫 추가하기 전에 Active IQ Config Advisor를 실행하면 기존 ENET(셸프 이더넷) 연결의 스냅샷이 제공되며, NSM(NVMe 쉘프 모듈) 펌웨어 버전을 확인하고, HA 쌍에서 이미 사용 중인 쉘프 ID를 확인할 수 있습니다.

+
쉘프를 핫 추가한 후 Active IQ Config Advisor를 실행하면 쉘프가 올바로 연결되었는지, 쉘프 ID가 HA 쌍 내에서 고유한지 확인할 수 있습니다.

* * 모범 사례: * 모범 사례는 새 셸프를 추가하기 전에 스토리지 시스템에 및 의 최신 버전을 설치하는 https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NVMe 쉘프 모듈(NSM) 펌웨어"^] https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["드라이브 펌웨어"^] 것입니다.
+

NOTE: 펌웨어를 쉘프와 해당 구성요소를 지원하지 않는 버전으로 되돌리지 마십시오.


