---
permalink: ns224/service-replace-nsm100.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, impair, nvme, module, nsm, nondisruptive, drive, i/o, nsm, replace an nsm module 
summary: 'NS224 드라이브 쉘프의 전원이 켜져 있고 I/O가 진행 중인 동안 손상된 NVMe 쉘프 모듈\(NSM\)을 중단 없이 교체할 수 있습니다.' 
---
= NSM 모듈—NS224 쉘프를 교체합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
NS224 드라이브 쉘프의 장애가 발생한 NVMe 쉘프 모듈(NSM)을 전원이 켜져 있고 I/O가 진행 중인 동안 중단 없이 교체할 수 있습니다.

.시작하기 전에
* 장애가 발생한 NSM 모듈을 제거할 때 셸프가 연결을 유지할 수 있도록 셸프의 파트너 NSM 모듈이 가동 및 실행되고 있어야 하며 케이블이 올바르게 연결되어 있어야 합니다.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]

* 시스템의 다른 모든 구성 요소가 제대로 작동해야 합니다.


.이 작업에 대해
* NSM 모듈을 교체하려면 손상된 NSM 모듈에서 교체용 NSM 모듈로 DIMM, 팬 및 전원 공급 장치를 이동하는 작업이 포함됩니다.
+
실시간 클럭(RTC) 배터리 또는 부팅 미디어를 이동하지 않습니다. 교체 NSM 모듈에 사전 설치되어 제공됩니다.

* NSM(NVMe 쉘프 모듈)을 제거하고 설치하는 데 최소 70초가 소요됩니다.
+
그러면 ONTAP에서 NSM 제거 이벤트를 처리할 수 있는 충분한 시간이 허용됩니다.

* * 모범 사례: * FRU 구성 요소를 교체하기 전에 시스템에 최신 버전의 NVMe 쉘프 모듈(NSM) 펌웨어 및 드라이브 펌웨어를 사용하는 것이 가장 좋습니다.
+
[NOTE]
====
펌웨어를 쉘프와 해당 구성요소를 지원하지 않는 버전으로 되돌리지 마십시오.

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

====
* 최신 버전이 아닌 펌웨어 버전이 있는 새 NSM 모듈에서 Shelf(NSM) 펌웨어가 중단 없이 자동으로 업데이트됩니다.
+
NSM 모듈 펌웨어 검사는 10분마다 수행됩니다. NSM 모듈 펌웨어 업데이트는 최대 30분 정도 걸릴 수 있습니다.

* 필요한 경우 셸프의 위치(파란색) LED를 켜서 해당 셸프를 물리적으로 찾을 수 있습니다. 'Storage shelf location-led modify-shelf-name_shelf_name_-led-status on'
+
해당 셸프의 'helf_name'을 모르는 경우 'storage shelf show' 명령어를 실행한다.

+
선반에는 3개의 위치 LED가 있습니다. 하나는 운영자 디스플레이 패널에, 다른 하나는 각 NSM 모듈에 있습니다. 위치 LED가 30분 동안 켜져 있습니다. 같은 명령을 입력해도 끄기는 되지만 '해제' 옵션을 사용하면 끌 수 있습니다.

* 교체 NSM 모듈의 포장을 풀 때 실패한 NSM 모듈을 반환할 때 사용할 모든 포장재를 보관하십시오.
+
교체 절차에 대한 RMA 번호 또는 추가 도움이 필요한 경우, 에서 기술 지원 팀에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양).

* 다음 비디오나 작성된 단계를 사용하여 NSM 모듈을 교체할 수 있습니다.
+
https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=f57693b3-b164-4014-a827-aa86002f4b34["NS224 드라이브 쉘프의 NSM 모듈 교체"^]



.단계
. 적절하게 접지합니다.
. 손상된 NSM 모듈을 물리적으로 식별합니다.
+
시스템이 시스템 콘솔에 어떤 모듈이 손상되었는지 나타내는 경고 메시지를 기록합니다. 또한 드라이브 쉘프 오퍼레이터 디스플레이 패널과 손상된 모듈의 주의(황색) LED가 켜집니다.

. 손상된 NSM 모듈에서 케이블을 분리합니다.
+
.. 전원 코드 고정대를 열어 전원 공급 장치에서 전원 코드를 분리한 다음, 전원 공급 장치에서 전원 코드를 뽑습니다.
+
전원 공급 장치에는 전원 스위치가 없습니다.

.. NSM 모듈 포트에서 스토리지 케이블 연결을 분리합니다.
+
각 케이블이 연결된 NSM 모듈 포트를 기록해 둡니다. 이 절차의 뒷부분에서 교체 NSM 모듈의 동일한 포트에 케이블을 다시 연결합니다.



. 쉘프에서 NSM 모듈을 제거합니다.
+
.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 분리하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍에 대고(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
+
래칭 메커니즘이 올라와 선반에 있는 래치 핀을 지웁니다.

.. NSM 모듈이 선반에서 약 1/3이 될 때까지 부드럽게 당긴 후 양손으로 NSM 모듈 측면을 잡고 무게를 지탱한 다음 평평하고 안정적인 표면에 놓습니다.
+
당기기 시작 시 래칭 메커니즘 암은 NSM 모듈에서 연장되어 완전히 확장된 위치에 고정됩니다.



. 교체용 NSM 모듈의 포장을 풀고 손상된 NSM 모듈 근처의 평평한 표면에 설치합니다.
. 손상된 NSM 모듈의 커버와 교체용 NSM 모듈을 각 덮개의 나비나사를 풀어 엽니다.
+

NOTE: NSM 모듈 덮개의 FRU 레이블은 DIMM 및 팬의 위치를 표시합니다.

. 손상된 NSM 모듈에서 교체 NSM 모듈로 DIMM을 이동합니다.
+
.. DIMM을 교체 NSM 모듈에 같은 방향으로 삽입할 수 있도록 슬롯에 있는 DIMM의 방향을 확인합니다.
.. DIMM 슬롯의 양 끝에 있는 이젝터 탭을 천천히 밀어 슬롯에서 DIMM을 꺼낸 다음 슬롯에서 DIMM을 들어 꺼냅니다.
+

NOTE: DIMM 회로 보드 구성 요소에 압력이 가해질 수 있으므로 모서리 또는 가장자리로 DIMM을 조심스럽게 잡습니다. 이젝터 탭이 열린 위치에 있습니다.

.. DIMM의 모서리를 잡고 교체용 NSM 모듈의 슬롯에 DIMM을 똑바로 삽입합니다.
+
DIMM 하단의 노치가 핀에서 슬롯의 탭과 정렬되어야 합니다.

+
올바르게 삽입되면 DIMM은 쉽게 장착되지만 슬롯에 단단히 고정되어야 합니다. 그렇지 않은 경우 DIMM을 재장착합니다.

.. 이젝터 탭이 DIMM 양쪽 끝의 노치 위에 걸릴 때까지 DIMM의 상단 가장자리를 조심스럽게 누르십시오.
.. 나머지 DIMM에 대해 단계 7a - 7d를 반복합니다.


. 장애가 발생한 NSM 모듈에서 교체 NSM 모듈로 팬을 이동합니다.
+
.. 파란색 터치 포인트가 있는 측면에서 팬을 단단히 잡고 수직으로 들어올려 소켓에서 분리합니다.
+
팬을 들어올리기 전에 팬을 앞뒤로 부드럽게 흔들어서 분리해야 할 수 있습니다.

.. 팬을 교체용 NSM 모듈의 가이드에 맞춘 다음 팬 모듈 커넥터가 소켓에 완전히 장착될 때까지 아래로 누릅니다.
.. 나머지 팬에 대해 하위 단계 8a 및 8b를 반복합니다.


. 각 NSM 모듈의 덮개를 닫고 각 나비나사를 조입니다.
. 손상된 NSM 모듈에서 교체 NSM 모듈로 전원 공급 장치를 이동합니다.
+
.. 캠 핸들을 열림(수평) 위치로 돌린 다음 잡습니다.
.. 엄지 손가락으로 파란색 탭을 눌러 잠금 장치를 해제합니다.
.. 다른 손으로 무게를 지탱하면서 NSM 모듈에서 전원 공급 장치를 꺼냅니다.
.. 양손으로 전원 공급 장치의 가장자리를 교체용 NSM 모듈의 입구에 맞춘 후 지지하십시오.
.. 잠금 장치가 딸깍 소리를 내며 제자리에 고정될 때까지 전원 공급 장치를 NSM 모듈에 부드럽게 밀어 넣습니다.
+

NOTE: 과도한 힘을 가하지 마십시오. 또는 내부 커넥터가 손상될 수 있습니다.

.. 캠 핸들을 닫힘 위치로 돌립니다.


. 교체 NSM 모듈을 쉘프에 삽입합니다.
+
.. 래칭 메커니즘 암이 완전히 확장된 위치에 잠겨 있는지 확인하십시오.
.. NSM 모듈의 무게가 셸프에서 완전히 지지될 때까지 양손으로 NSM 모듈을 선반에 부드럽게 밀어 넣습니다.
.. NSM 모듈을 선반에 밀어 넣어 멈출 때까지 기다립니다(선반 후면에서 약 2.5cm).
+
NSM 모듈을 밀어 넣을 수 있도록 각 핑거 루프(래칭 메커니즘 암)의 전면에 있는 주황색 탭에 엄지 손가락을 올려 놓을 수 있습니다.

.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 삽입하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍을 통해(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
.. 걸쇠가 정지 상태에서 걸리도록 앞으로 부드럽게 밉니다.
.. 래칭 메커니즘의 상단과 엄지 손가락을 분리한 다음 래칭 메커니즘이 제자리에 고정될 때까지 계속 밉니다.
+
NSM 모듈은 셸프에 완전히 삽입되어 셸프의 모서리와 같은 높이가 되어야 합니다.



. NSM 모듈에 케이블을 다시 연결합니다.
+
.. 동일한 NSM 모듈 포트 2개에 스토리지 케이블을 다시 연결합니다.
+
케이블은 커넥터 당김 탭이 위를 향하도록 삽입됩니다. 케이블이 올바르게 삽입되면 딸깍 소리가 나면서 제자리에 고정됩니다.

.. 전원 코드를 전원 공급 장치에 다시 연결한 다음 전원 코드 고정 장치로 전원 코드를 고정합니다.
+
올바르게 작동하면 전원 공급 장치의 이중 LED가 녹색으로 켜집니다.

+
또한 두 NSM 모듈 포트 LNK(녹색) LED가 모두 켜집니다. LNK LED가 켜지지 않으면 케이블을 다시 연결합니다.



. 선반 작동 디스플레이 패널의 주의(황색) LED가 더 이상 켜지지 않는지 확인합니다.
+
NSM 모듈이 재부팅되면 운영자 디스플레이 패널 주의 LED가 꺼집니다. 이 작업은 3~5분 정도 걸릴 수 있습니다.

. Active IQ Config Advisor를 실행하여 NSM 모듈의 케이블이 올바르게 연결되었는지 확인합니다.
+
케이블 연결 오류가 발생하면 제공된 수정 조치를 따르십시오.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 다운로드: Config Advisor"^]


