---
permalink: ns224/service-replace-fan.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, fan, nondisruptive, power, i/o, progress, replace, replace a fan 
summary: 전원이 켜진 NS224 드라이브 쉘프 및 I/O가 진행 중인 동안 장애가 발생한 팬을 중단 없이 교체할 수 있습니다. 
---
= 팬 NS224 쉘프를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전원이 켜진 NS224 드라이브 쉘프 및 I/O가 진행 중인 동안 장애가 발생한 팬을 중단 없이 교체할 수 있습니다.

.시작하기 전에
* 장애가 발생한 FRU(타겟 NSM 모듈)를 사용하여 NSM 모듈을 제거할 때 셸프가 연결을 유지할 수 있도록 셸프의 파트너 NSM 모듈이 가동 및 실행 중이고 케이블이 올바르게 연결되어 있어야 합니다.
+
https://["NetApp 다운로드: Config Advisor"^]

* 다른 4개의 팬을 포함하여 시스템의 다른 모든 구성 요소가 제대로 작동해야 합니다.


.이 작업에 대해
* NSM(NVMe 쉘프 모듈)을 제거하고 설치하는 데 최소 70초가 소요됩니다.
+
그러면 ONTAP에서 NSM 제거 이벤트를 처리할 수 있는 충분한 시간이 허용됩니다.

* * 모범 사례: * FRU 구성 요소를 교체하기 전에 시스템에 최신 버전의 NVMe 쉘프 모듈(NSM) 펌웨어 및 드라이브 펌웨어를 사용하는 것이 가장 좋습니다.
+
https://["NetApp 다운로드: 디스크 쉘프 펌웨어"^]

+
https://["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

+
[NOTE]
====
펌웨어를 쉘프와 해당 구성요소를 지원하지 않는 버전으로 되돌리지 마십시오.

====
* 필요한 경우 셸프의 위치(파란색) LED를 켜서 해당 셸프를 물리적으로 찾을 수 있습니다. 'Storage shelf location-led modify-shelf-name_shelf_name_-led-status on'
+
해당 셸프의 '_shelf_name_'을 모르는 경우 'storage shelf show' 명령어를 실행한다.

+
선반에는 3개의 위치 LED가 있습니다. 하나는 운영자 디스플레이 패널에, 다른 하나는 각 NSM 모듈에 있습니다. 위치 LED가 30분 동안 켜져 있습니다. 같은 명령을 입력해도 끄기는 되지만 '해제' 옵션을 사용하면 끌 수 있습니다.

* 교체용 팬의 포장을 풀 때 고장난 팬을 반환할 때 사용할 수 있도록 포장재를 모두 보관하십시오.
+
교체 절차에 대한 RMA 번호 또는 추가 도움이 필요한 경우, 에서 기술 지원 팀에 문의하십시오 https://["NetApp 지원"^], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양).

* 다음 애니메이션 또는 기록된 단계를 사용하여 팬을 교체할 수 있습니다.
+
.애니메이션 - N224 드라이브 쉘프에 팬을 교체합니다
video::29635ff8-ae86-4a48-ab2a-aa86002f3b66[panopto]


.단계
. 적절하게 접지합니다.
. 교체할 FRU가 포함된 NSM 모듈에서 케이블 연결을 분리합니다.
+
.. AC 전원 공급 장치인 경우 전원 코드 고정 장치를 열어 전원 공급 장치에서 전원 코드를 분리하거나, DC 전원 공급 장치인 경우 두 개의 나비 나사를 푼 다음 전원 공급 장치에서 전원 코드를 뽑습니다.
+
전원 공급 장치에는 전원 스위치가 없습니다.

.. NSM 모듈 포트에서 스토리지 케이블 연결을 분리합니다.
+
각 케이블이 연결된 NSM 모듈 포트를 기록해 둡니다. 이 절차의 뒷부분에서 NSM 모듈을 다시 삽입할 때 동일한 포트에 케이블을 다시 연결합니다.



. 쉘프에서 NSM 모듈을 제거합니다.
+
.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 분리하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍에 대고(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
+
래칭 메커니즘이 올라와 선반에 있는 래치 핀을 지웁니다.

.. NSM 모듈이 선반에서 약 1/3이 될 때까지 부드럽게 당긴 후 양손으로 NSM 모듈 측면을 잡고 무게를 지탱한 다음 평평하고 안정적인 표면에 놓습니다.
+
당기기 시작 시 래칭 메커니즘 암은 NSM 모듈에서 연장되어 완전히 확장된 위치에 고정됩니다.



. NSM 모듈 덮개 나비 나사를 풀고 덮개를 엽니다.
+

NOTE: NSM 모듈 덮개의 FRU 레이블은 NSM 모듈의 후면 벽을 따라 5개의 팬의 위치를 표시합니다.

. 장애가 발생한 팬을 물리적으로 식별합니다.
+
팬에 장애가 발생하면 시스템 콘솔에 어떤 팬이 고장났는지 나타내는 경고 메시지가 기록됩니다.

. 장애가 발생한 팬을 교체합니다.
+
.. 파란색 터치 포인트가 있는 측면을 단단히 잡고 수직으로 들어올려 소켓에서 분리한 후 결함이 있는 팬을 분리합니다.
.. 교체용 팬을 가이드 안에 맞춘 다음 팬 모듈 커넥터가 소켓에 완전히 장착될 때까지 아래로 누릅니다.


. NSM 모듈 덮개를 닫은 다음 나비 나사를 조입니다.
. NSM 모듈을 선반에 다시 삽입합니다.
+
.. 래칭 메커니즘 암이 완전히 확장된 위치에 잠겨 있는지 확인하십시오.
.. NSM 모듈의 무게가 셸프에서 완전히 지지될 때까지 양손으로 NSM 모듈을 선반에 부드럽게 밀어 넣습니다.
.. NSM 모듈을 선반에 밀어 넣어 멈출 때까지 기다립니다(선반 후면에서 약 2.5cm).
+
NSM 모듈을 밀어 넣을 수 있도록 각 핑거 루프(래칭 메커니즘 암)의 전면에 있는 주황색 탭에 엄지 손가락을 올려 놓을 수 있습니다.

.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 삽입하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍을 통해(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
.. 걸쇠가 정지 상태에서 걸리도록 앞으로 부드럽게 밉니다.
.. 래칭 메커니즘의 상단과 엄지 손가락을 분리한 다음 래칭 메커니즘이 제자리에 고정될 때까지 계속 밉니다.
+
NSM 모듈은 셸프에 완전히 삽입되어 셸프의 모서리와 같은 높이가 되어야 합니다.



. NSM 모듈에 케이블을 다시 연결합니다.
+
.. 동일한 NSM 모듈 포트 2개에 스토리지 케이블을 다시 연결합니다.
+
케이블은 커넥터 당김 탭이 위를 향하도록 삽입됩니다. 케이블이 올바르게 삽입되면 딸깍 소리가 나면서 제자리에 고정됩니다.

.. 전원 코드를 전원 공급 장치에 다시 연결한 다음, AC 전원 공급 장치인 경우 전원 코드 고정 장치로 전원 코드를 고정하거나 DC 전원 공급 장치인 경우 두 개의 나비 나사를 조인 다음 전원 공급 장치에서 전원 코드를 뽑습니다.
+
올바르게 작동하면 전원 공급 장치의 이중 LED가 녹색으로 켜집니다.

+
또한 두 NSM 모듈 포트 LNK(녹색) LED가 모두 켜집니다. LNK LED가 켜지지 않으면 케이블을 다시 연결합니다.



. 장애가 발생한 팬과 쉘프 운영자 디스플레이 패널이 포함된 NSM 모듈의 주의(황색) LED가 더 이상 켜지지 않는지 확인합니다.
+
NSM 모듈이 재부팅되고 팬 문제가 더 이상 감지되지 않으면 NSM 모듈 주의 LED가 꺼집니다. 이 작업은 3~5분 정도 걸릴 수 있습니다.

. Active IQ Config Advisor를 실행하여 NSM 모듈의 케이블이 올바르게 연결되었는지 확인합니다.
+
케이블 연결 오류가 발생하면 제공된 수정 조치를 따르십시오.

+
https://["NetApp 다운로드: Config Advisor"^]


