---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 전원이 켜진 NS224 드라이브 쉘프 및 I/O가 진행 중인 동안 장애가 발생한 드라이브를 중단 없이 교체할 수 있습니다. 
---
= 드라이브-NS224 쉘프 핫 스왑
:icons: font
:imagesdir: ../media/


[role="lead"]
전원이 켜진 NS224 드라이브 쉘프 및 I/O가 진행 중인 동안 장애가 발생한 드라이브를 중단 없이 교체할 수 있습니다.

.시작하기 전에
* 설치할 드라이브는 NS224 쉘프에서 지원되어야 합니다.
+
https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

* SED 인증이 활성화된 경우 ONTAP 설명서의 SED 교체 지침을 사용해야 합니다.
+
ONTAP 설명서의 지침은 SED를 교체하기 전과 후에 수행해야 하는 추가 단계를 설명합니다.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["CLI를 통한 NetApp 암호화 개요"^]

* 시스템의 다른 모든 구성 요소가 올바르게 작동해야 합니다. 그렇지 않은 경우 기술 지원 부서에 문의하십시오.
* 분리하려는 드라이브가 실패했는지 확인합니다.
+
'storage disk show-Broken' 명령을 실행하여 드라이브 실패를 확인할 수 있습니다. 오류가 발생한 드라이브가 실패한 드라이브 목록에 나타납니다. 그렇지 않으면 기다린 다음 명령을 다시 실행해야 합니다.

+

NOTE: 드라이브 유형 및 용량에 따라 장애가 발생한 드라이브 목록에 드라이브가 표시되는 데 최대 몇 시간이 걸릴 수 있습니다.



.이 작업에 대해
* * 모범 사례:* 가장 좋은 방법은 드라이브를 핫 스와핑하기 전에 최신 버전의 DQP(Disk Qualification Package)를 설치하는 것입니다.
+
현재 버전의 DQP를 설치하면 시스템이 새로 인증된 드라이브를 인식하고 사용할 수 있습니다. 이렇게 하면 드라이브가 인식되지 않으므로 최신 드라이브 정보가 없는 경우 및 드라이브 파티셔닝 예방에 대한 시스템 이벤트 메시지가 표시되지 않습니다. 또한 DQP는 최신 버전이 아닌 드라이브 펌웨어에 대해서도 알려줍니다.

+
https://mysupport.netapp.com/NOW/download/tools/diskqual/["NetApp 다운로드: 디스크 검증 패키지"^]

* * 모범 사례: * FRU 구성 요소를 교체하기 전에 시스템에 최신 버전의 NVMe 쉘프 모듈(NSM) 펌웨어 및 드라이브 펌웨어를 사용하는 것이 가장 좋습니다.
+
[NOTE]
====
펌웨어를 쉘프와 해당 구성요소를 지원하지 않는 버전으로 되돌리지 마십시오.

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 다운로드: 디스크 쉘프 펌웨어"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 다운로드: 디스크 드라이브 펌웨어"^]

====
* 최신 버전이 아닌 펌웨어 버전이 있는 새 드라이브에서 드라이브 펌웨어가 중단 없이 자동으로 업데이트됩니다.
+

NOTE: 드라이브 펌웨어 검사는 2분마다 수행됩니다.

* 필요한 경우 셸프의 위치(파란색) LED를 켜서 해당 셸프를 물리적으로 찾을 수 있습니다. 'Storage shelf location-led modify-shelf-name_shelf_name_-led-status on'
+
해당 셸프의 '_shelf_name_'을 모르는 경우 'storage shelf show' 명령어를 실행한다.

+
선반에는 3개의 위치 LED가 있습니다. 하나는 운영자 디스플레이 패널에, 다른 하나는 각 NSM 모듈에 있습니다. 위치 LED가 30분 동안 켜져 있습니다. 같은 명령을 입력해도 끄기는 되지만 '해제' 옵션을 사용하면 끌 수 있습니다.

* 교체 드라이브의 포장을 풀 때 오류가 발생한 드라이브를 반품할 때 사용할 포장재를 모두 보관하십시오.
+
교체 절차에 대한 RMA 번호 또는 추가 도움이 필요한 경우, 에서 기술 지원 팀에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양).

* 다음 비디오는 드라이브 핫 스왑 절차의 물리적 분리 및 삽입 부분에 대한 개요를 제공합니다.
+
https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=733011a7-e03a-41b0-8723-aa840133bf25["NS224 드라이브 쉘프의 드라이브 핫 스와핑"^]



.단계
. 교체 드라이브에 대해 드라이브 소유권을 수동으로 할당하려면 자동 드라이브 할당을 비활성화해야 합니다.
+

NOTE: 쉘프의 드라이브가 HA 쌍의 두 컨트롤러 모듈에서 소유하는 경우 드라이브 소유권을 수동으로 할당해야 합니다.

+

NOTE: 드라이브 소유권을 수동으로 할당한 다음 이 절차의 뒷부분에서 자동 드라이브 할당을 다시 활성화합니다.

+
.. 자동 드라이브 할당이 설정되었는지 'Storage disk option show'를 확인합니다
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

+
자동 드라이브 할당이 활성화된 경우 각 컨트롤러 모듈에 대해 Auto Assign(자동 할당) 열에 출력이 On(켜짐)으로 표시됩니다.

.. 자동 드라이브 할당이 설정된 경우 'storage disk option modify -node_name -autostassign off'를 비활성화합니다
+
두 컨트롤러 모듈에서 자동 드라이브 할당을 비활성화해야 합니다.



. 적절하게 접지합니다.
. 장애가 발생한 드라이브를 물리적으로 식별합니다.
+
드라이브에 오류가 발생하면 시스템 콘솔에 오류가 발생한 드라이브를 나타내는 경고 메시지가 기록됩니다. 또한 드라이브 쉘프 운영자 디스플레이 패널의 주의(황색) LED와 고장난 드라이브가 켜집니다.

+

NOTE: 장애가 발생한 드라이브의 작동(녹색) LED는 켜져(계속 켜짐) 있으며, 이는 드라이브에 전원이 들어오지만 깜박이지 않아야 함을 나타냅니다. 이는 I/O 작동을 나타냅니다. 장애가 발생한 드라이브에 입출력 작업이 없습니다.

. 장애가 발생한 드라이브를 분리합니다.
+
.. 드라이브 면의 분리 버튼을 눌러 캠 핸들을 엽니다.
.. 캠 핸들을 사용하여 드라이브를 선반에서 밀어내고 다른 손으로 드라이브를 지지합니다.


. 교체 드라이브를 끼우기 전에 최소 70초 정도 기다리십시오.
+
이렇게 하면 시스템이 드라이브가 제거되었는지 인식할 수 있습니다.

. 교체 드라이브를 삽입합니다.
+
.. 캠 핸들이 열린 위치에 있는 상태에서 두 손을 사용하여 교체용 드라이브를 삽입합니다.
.. 드라이브가 멈출 때까지 누릅니다.
.. 드라이브가 중간 평면에 완전히 장착되고 핸들이 제자리에 고정되도록 캠 핸들을 닫습니다.
+
캠 핸들이 드라이브 면과 올바르게 정렬되도록 캠 핸들을 천천히 닫아야 합니다.



. 드라이브의 작동(녹색) LED가 켜져 있는지 확인합니다.
+
드라이브의 작동 LED가 고정되어 있으면 드라이브에 전원이 공급되고 있는 것입니다. 드라이브 작동 LED가 깜박이면 드라이브에 전원이 공급되고 I/O가 진행 중임을 의미합니다. 드라이브 펌웨어가 자동으로 업데이트되면 LED가 깜박입니다.

. 다른 드라이브를 교체하는 경우 3단계부터 7단계까지 반복합니다.
. 1단계에서 자동 드라이브 할당을 해제한 경우 드라이브 소유권을 수동으로 할당한 다음 필요한 경우 자동 드라이브 할당을 다시 사용하도록 설정합니다.
+
.. 소유되지 않은 모든 드라이브:'스토리지 디스크 표시 - 컨테이너 유형 지정안함'을 표시합니다
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

.. 각 드라이브에 스토리지 디스크 할당 - disk disk_name - owner owner_name'을 할당합니다
+
두 컨트롤러 모듈 중 하나에서 명령을 입력할 수 있습니다.

+
와일드카드 문자를 사용하여 한 번에 두 개 이상의 드라이브를 할당할 수 있습니다.

.. 필요한 경우 자동 드라이브 할당을 다시 활성화합니다. 'storage disk option modify -node_name -autostassign on'
+
두 컨트롤러 모듈 모두에서 자동 드라이브 할당을 다시 활성화해야 합니다.




