---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 'ONTAP 9.7 이상을 실행 중인 HA 쌍의 NS224 드라이브 쉘프에서 부팅 미디어가 실패하거나, 쉘프가 NVMe 쉘프 모듈\(NSM\) 펌웨어 버전 1.1x 이상을 실행 중인 경우 부팅 미디어를 교체할 수 있습니다. 드라이브 쉘프의 전원이 켜져 있고 I/O가 진행 중인 동안 부팅 미디어를 중단 없이 교체할 수 있습니다.' 
---
= 부팅 미디어-NS224 쉘프를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 이상을 실행 중인 HA 쌍의 NS224 드라이브 쉘프에서 부팅 미디어가 실패하거나, 쉘프가 NVMe 쉘프 모듈(NSM) 펌웨어 버전 0111 이상을 실행 중인 경우 부팅 미디어를 교체할 수 있습니다. 드라이브 쉘프의 전원이 켜져 있고 I/O가 진행 중인 동안 부팅 미디어를 중단 없이 교체할 수 있습니다.

.시작하기 전에
* HA 쌍이 NSM 펌웨어의 최소 지원 버전을 포함하는 ONTAP 9.7 이상을 이미 실행 중이거나, HA 쌍이 NSM 펌웨어 버전 0111 이상을 포함하는 ONTAP 9.6 버전을 이미 실행하고 있어야 합니다.
+
컨트롤러의 콘솔에서 'storage shelf show-module' 명령을 입력하여 쉘프에 있는 NSM 펌웨어의 버전을 확인할 수 있습니다.

+
[NOTE]
====
셸프에서 NSM 펌웨어 버전 0111 이상을 실행하고 있지 않으면 부팅 미디어를 교체할 수 없으므로 NSM 모듈을 교체해야 합니다.

link:service-replace-nsm100.html["NSM 모듈-NS224 쉘프를 교체합니다"^]

====
* Phillips #1 드라이버가 필요합니다.
+
부트 미디어를 보드에 고정하는 데 사용되는 나사는 Phillips #1 드라이버가 필요합니다. 다른 유형의 드라이버를 사용하면 나사가 벗겨질 수 있습니다.

* 장애가 발생한 FRU(타겟 NSM 모듈)를 사용하여 NSM 모듈을 제거할 때 셸프가 연결을 유지할 수 있도록 셸프의 파트너 NSM 모듈이 가동 및 실행 중이고 케이블이 올바르게 연결되어 있어야 합니다.
+
https://["NetApp 다운로드: Config Advisor"^]

* 시스템의 다른 모든 구성 요소가 제대로 작동해야 합니다.


.이 작업에 대해
* 부팅 미디어를 교체한 후 셸프의 파트너 NSM 모듈의 부팅 이미지가 교체 부팅 미디어에 자동으로 복사됩니다.
+
이 작업은 최대 5분 정도 걸릴 수 있습니다.

* NSM(NVMe 쉘프 모듈)을 제거하고 설치하는 데 최소 70초가 소요됩니다.
+
그러면 ONTAP에서 NSM 제거 이벤트를 처리할 수 있는 충분한 시간이 허용됩니다.

* 필요한 경우 셸프의 위치(파란색) LED를 켜서 해당 셸프를 물리적으로 찾을 수 있습니다. 'Storage shelf location-led modify-shelf-name_shelf_name_-led-status on'
+
해당 셸프의 '_shelf_name_'을 모르는 경우 'storage shelf show' 명령어를 실행한다.

+
선반에는 3개의 위치 LED가 있습니다. 하나는 운영자 디스플레이 패널에, 다른 하나는 각 NSM 모듈에 있습니다. 위치 LED가 30분 동안 켜져 있습니다. 같은 명령을 입력해도 끄기는 되지만 '해제' 옵션을 사용하면 끌 수 있습니다.

* 부팅 미디어를 교체한 후 키트와 함께 제공된 RMA 지침에 따라 오류가 발생한 부품을 NetApp으로 반환할 수 있습니다.
+
교체 절차에 대한 RMA 번호 또는 추가 도움이 필요한 경우, 에서 기술 지원 팀에 문의하십시오 https://["NetApp 지원"^], 888-463-8277 (북미), 00-800-44-638277 (유럽) 또는 +800-800-80-800 (아시아/태평양).

* 다음 애니메이션 또는 기록된 단계를 사용하여 부팅 미디어를 교체할 수 있습니다.
+
.애니메이션 - NS224 드라이브 쉘프에 부팅 미디어를 교체합니다
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[panopto]


.단계
. 셸프의 두 NSM 모듈이 버전 0200 이상의 동일한 펌웨어 버전을 실행하고 있는지 확인합니다.
. 적절하게 접지합니다.
. 교체할 FRU가 포함된 NSM 모듈에서 케이블 연결을 분리합니다.
+
.. AC 전원 공급 장치인 경우 전원 코드 고정 장치를 열어 전원 공급 장치에서 전원 코드를 분리하거나, DC 전원 공급 장치인 경우 두 개의 나비 나사를 푼 다음 전원 공급 장치에서 전원 코드를 뽑습니다.
+
전원 공급 장치에는 전원 스위치가 없습니다.

.. NSM 모듈 포트에서 스토리지 케이블 연결을 분리합니다.
+
각 케이블이 연결된 NSM 모듈 포트를 기록해 둡니다. 이 절차의 뒷부분에서 NSM 모듈을 다시 삽입할 때 동일한 포트에 케이블을 다시 연결합니다.



. 쉘프에서 NSM 모듈을 제거합니다.
+
.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 분리하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍에 대고(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
+
래칭 메커니즘이 올라와 선반에 있는 래치 핀을 지웁니다.

.. NSM 모듈이 선반에서 약 1/3이 될 때까지 부드럽게 당긴 후 양손으로 NSM 모듈 측면을 잡고 무게를 지탱한 다음 평평하고 안정적인 표면에 놓습니다.
+
당기기 시작 시 래칭 메커니즘 암은 NSM 모듈에서 연장되어 완전히 확장된 위치에 고정됩니다.



. NSM 모듈 덮개 나비 나사를 풀고 덮개를 엽니다.
. 장애가 발생한 부팅 미디어를 물리적으로 찾습니다.
+
부팅 미디어는 전원 공급 장치와 반대되는 선반 섀시 벽을 따라 있습니다.

. 부팅 미디어를 교체합니다.
+
.. 1 십자 드라이버를 사용하여 부트 미디어의 하단(홈이 파인) 끝을 보드에 고정하는 나사를 조심스럽게 분리합니다.
.. 홈이 파인 부분을 약간 위로 돌려 부트 미디어를 분리한 다음 소켓에서 분리될 때까지 앞쪽으로 부드럽게 당겨 분리합니다.
+
엄지 손가락과 검지 손가락을 측면 가장자리, 노치 끝에 올려 부팅 매체를 잡고 있습니다

.. 정전기 방지용 백에서 부팅 미디어의 압축을 풉니다.
.. 교체 부팅 매체를 소켓에 똑바로 완전히 장착될 때까지 소켓에 부드럽게 밀어 넣습니다.
+
엄지 손가락과 검지 손가락을 측면 가장자리, 노치 끝에 올려 부팅 매체를 잡고 있습니다 방열판이 있는 면이 위를 향하도록 합니다.

+
올바르게 장착되고 부트 미디어를 사용할 수 있게 되면, 부트 미디어의 톱니 모양의 끝부분을 보드에서 먼 쪽으로 비스듬하게 하여 나사를 사용하여 아직 고정하지 않았기 때문입니다.

.. 부팅 매체를 삽입할 때 홈이 파인 부분을 조심스럽게 누르고 드라이버로 나사를 조여 부트 매체를 제자리에 고정합니다.
+

NOTE: 부트 미디어를 제자리에 단단히 고정할 수 있을 정도로 나사를 조이지만 너무 조이지 마십시오.



. NSM 모듈 덮개를 닫은 다음 나비 나사를 조입니다.
. NSM 모듈을 선반에 다시 삽입합니다.
+
.. 래칭 메커니즘 암이 완전히 확장된 위치에 잠겨 있는지 확인하십시오.
.. NSM 모듈의 무게가 셸프에서 완전히 지지될 때까지 양손으로 NSM 모듈을 선반에 부드럽게 밀어 넣습니다.
.. NSM 모듈을 선반에 밀어 넣어 멈출 때까지 기다립니다(선반 후면에서 약 2.5cm).
+
NSM 모듈을 밀어 넣을 수 있도록 각 핑거 루프(래칭 메커니즘 암)의 전면에 있는 주황색 탭에 엄지 손가락을 올려 놓을 수 있습니다.

.. NSM 모듈 양쪽에 있는 래치 메커니즘의 손가락 구멍을 통해 검지 손가락을 감습니다.
+

NOTE: 하단 NSM 모듈을 삽입하는 경우 하단 레일이 래치 메커니즘에 접근하는 데 방해가 되는 경우, 검지 손가락을 안쪽의 손가락 구멍을 통해(팔을 교차함) 넣습니다.

.. 엄지 손가락으로 래칭 장치 위에 있는 주황색 탭을 누르고 있습니다.
.. 걸쇠가 정지 상태에서 걸리도록 앞으로 부드럽게 밉니다.
.. 래칭 메커니즘의 상단과 엄지 손가락을 분리한 다음 래칭 메커니즘이 제자리에 고정될 때까지 계속 밉니다.
+
NSM 모듈은 셸프에 완전히 삽입되어 셸프의 모서리와 같은 높이가 되어야 합니다.



. NSM 모듈에 케이블을 다시 연결합니다.
+
.. 동일한 NSM 모듈 포트 2개에 스토리지 케이블을 다시 연결합니다.
+
케이블은 커넥터 당김 탭이 위를 향하도록 삽입됩니다. 케이블이 올바르게 삽입되면 딸깍 소리가 나면서 제자리에 고정됩니다.

.. 전원 코드를 전원 공급 장치에 다시 연결한 다음, AC 전원 공급 장치인 경우 전원 코드 고정 장치로 전원 코드를 고정하거나 DC 전원 공급 장치인 경우 두 개의 나비 나사를 조입니다.
+
올바르게 작동하면 전원 공급 장치의 이중 LED가 녹색으로 켜집니다.

+
또한 두 NSM 모듈 포트 LNK(녹색) LED가 모두 켜집니다. LNK LED가 켜지지 않으면 케이블을 다시 연결합니다.



. 실패한 부팅 미디어가 포함된 NSM 모듈의 주의(황색) LED와 쉘프 운영자 디스플레이 패널에 더 이상 불이 들어오지 않는지 확인합니다.
+
주의 LED가 꺼지려면 5-10분 정도 걸릴 수 있습니다. NSM 모듈이 재부팅되고 부팅 미디어 이미지 복제가 완료되는 데 걸리는 시간입니다.

+
오류 LED가 계속 켜져 있으면 부팅 미디어가 제대로 장착되지 않았거나 다른 문제가 있을 수 있으므로 기술 지원 부서에 지원을 요청해야 합니다.

. Active IQ Config Advisor를 실행하여 NSM 모듈의 케이블이 올바르게 연결되었는지 확인합니다.
+
케이블 연결 오류가 발생하면 제공된 수정 조치를 따르십시오.

+
https://["NetApp 다운로드: Config Advisor"^]


