---
permalink: fas8300/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: fas8300, fas8700, boot, media, store, primary, secondary, set, system, boot, image, file, replace, replace the boot media 
summary: 부팅 미디어에는 시스템이 부팅될 때 사용하는 기본 및 보조 시스템 부팅 이미지 파일 세트가 저장됩니다. 
---
= 부팅 미디어 교체 개요 - FAS8300 및 FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
부팅 매체는 시스템이 부팅될 때 사용하는 1차 및 2차 시스템(부팅 이미지) 파일 세트를 저장합니다. 네트워크 구성에 따라 중단 없는 교체 또는 중단 없는 교체를 수행할 수 있습니다.

[NOTE]
====
NetApp에서는 작업 중인 장치에서 콘솔 로깅을 활성화하고 이 절차를 수행할 때 다음 조치를 취할 것을 강력히 권장합니다.

* 유지 관리 중에도 AutoSupport 기능을 활성화 상태로 유지하십시오. 이렇게 하면 문제가 발생할 경우 NetApp 지원팀에서 진단 정보를 받을 수 있습니다.
* CLI 세션에 대한 세션 로깅을 활성화하십시오. 이렇게 하면 유지보수 윈도우 중에 수행된 모든 명령과 시스템 출력에 대한 완전한 기록이 생성됩니다. 세션 로깅 활성화 방법에 대한 자세한 내용은 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 최적의 연결을 위해 PuTTY를 구성하는 방법"^]을 참조하십시오.


====
"image_xxx.tgz" 파일을 저장할 적절한 저장 공간을 가진 FAT32로 포맷된 USB 플래시 드라이브가 있어야 합니다.

이 절차에서 나중에 사용할 수 있도록 'image_xxx.tgz' 파일을 USB 플래시 드라이브에 복사해야 합니다.

* 부팅 미디어를 중단 없이 교체하는 방법은 모두 'var' 파일 시스템을 복구해야 합니다.
+
** 무중단 교체를 위해서는 'var' 파일 시스템을 복구하기 위해 HA 쌍을 네트워크에 연결해야 합니다.
** 시스템 중단을 교체하기 위해 네트워크 연결을 통해 'var' 파일 시스템을 복원할 필요가 없지만, 이 프로세스를 수행하려면 두 번의 재부팅이 필요합니다.


* 오류가 발생한 구성 요소를 공급업체로부터 받은 교체 FRU 구성 요소로 교체해야 합니다.
* 다음 단계에 따라 올바른 노드에 명령을 적용하는 것이 중요합니다.
+
** impaired_node는 유지 관리를 수행하는 노드입니다.
** healy node_는 손상된 노드의 HA 파트너입니다.



