---
permalink: fas8300/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas8300, fas8700, how to recable the system, how to reassign disks 
summary: 스토리지를 다시 설정하고 디스크 재할당을 확인해야 합니다. 
---
= 시스템 회수 및 디스크 재할당 - FAS8300 및 FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템을 전체 작동 상태로 복원하기 전에 일련의 작업을 완료해야 합니다.



== 1단계: 시스템 회수

컨트롤러 모듈의 스토리지 및 네트워크 연결을 확인합니다.

.단계
. 을 사용하여 케이블이 올바른지 확인합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Config Advisor를 다운로드하고 설치합니다.
.. 대상 시스템에 대한 정보를 입력한 다음 데이터 수집 을 클릭합니다.
.. 케이블 연결 탭을 클릭한 다음 출력을 확인합니다. 모든 디스크 쉘프가 표시되고 모든 디스크가 출력에 표시되는지 확인하여 찾은 케이블 연결 문제를 해결합니다.
.. 해당 탭을 클릭하여 다른 케이블을 확인한 다음 Config Advisor의 출력을 확인합니다.






== 2단계: 디스크를 재할당합니다

스토리지 시스템이 HA 쌍 내에 있는 경우, 절차 종료 시 기브백이 발생하면 새 컨트롤러 모듈의 시스템 ID가 자동으로 디스크에 할당됩니다. 독립 실행형 시스템에서는 ID를 디스크에 수동으로 재할당해야 합니다.

구성에 올바른 절차를 사용해야 합니다.

[cols="1,2"]
|===
| 컨트롤러 이중화 | 다음 절차를 따르십시오. 


 a| 
HA 쌍
 a| 
<<옵션 1: HA 시스템의 시스템 ID 변경을 확인합니다>>]



 a| 
2노드 MetroCluster 구성
 a| 
<<옵션 2: 2노드 MetroCluster 구성의 시스템에서 시스템 ID를 수동으로 재할당합니다>>

|===


=== 옵션 1: HA 시스템의 시스템 ID 변경을 확인합니다

_replacement_controller를 부팅할 때 시스템 ID 변경을 확인한 다음 변경이 구현되었는지 확인해야 합니다.

이 절차는 HA 쌍에서 ONTAP를 실행하는 시스템에만 적용됩니다.

. replacement_controller가 유지보수 모드("*>" 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. system ID mismatch에 의한 시스템 ID 재정의를 묻는 메시지가 나타나면 _replacement_controller의 LOADER 프롬프트에서 컨트롤러를 부팅하고 "y"를 입력합니다.
. replacement_controller 콘솔에 'Waiting for 반환...' 메시지가 표시될 때까지 기다린 후 정상적인 컨트롤러에서 새 파트너 시스템 ID가 자동으로 지정되었는지 확인합니다. 'storage failover show
+
명령 출력에는 손상된 컨트롤러에서 시스템 ID가 변경되었다는 메시지와 함께 올바른 이전 및 새 ID가 표시되어야 합니다. 다음 예제에서 node2는 교체를 거쳤으며 새 시스템 ID가 151759706입니다.

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 정상적인 컨트롤러에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 모든 코어 덤프를 저장합니다. 'system node run-node_local-node-name_partner savecore'
.. 반환 명령을 실행하기 전에 'avecore' 명령이 완료될 때까지 기다리십시오.
+
다음 명령을 입력하여 savecore 명령의 진행 상태를 모니터링할 수 있습니다. 'system node run-node_local-node-name_partner savecore -s'

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. 스토리지 시스템에 스토리지 또는 볼륨 암호화가 구성된 경우 온보드 키 관리를 사용하는지 또는 외부 키 관리를 사용하는지 여부에 따라 다음 절차 중 하나를 사용하여 스토리지 또는 볼륨 암호화 기능을 복원해야 합니다.
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["온보드 키 관리 암호화 키를 복원합니다"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["외부 키 관리 암호화 키를 복원합니다"^]


. 컨트롤러를 다시 제공합니다.
+
.. 정상적인 컨트롤러에서 교체된 컨트롤러의 스토리지를 다시 제공합니다. 'storage failover 반환 - ofnode_replacement_node_name_'
+
replacement_controller가 스토리지를 다시 가져와 부팅을 완료합니다.

+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 y를 입력해야 합니다.

+

NOTE: 기브백이 거부되면 거부권을 재정의할 수 있습니다.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["사용 중인 ONTAP 9 버전에 대한 고가용성 구성 가이드를 찾아보십시오"]

.. 기브백이 완료된 후 HA 쌍이 정상 작동 중인지, 그리고 테이크오버가 가능한지, 즉 '스토리지 페일오버 표시'인지 확인합니다
+
'storage failover show' 명령의 출력에는 파트너 메시지에서 변경된 시스템 ID가 포함되지 않아야 합니다.



. 디스크가 제대로 할당되었는지 확인합니다. '스토리지 디스크 표시-소유권'
+
_replacement_controller에 속하는 디스크는 새 시스템 ID를 표시해야 합니다. 다음 예에서는 노드 1이 소유한 디스크에 새 시스템 ID 1873775277이 표시됩니다.

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----




=== 옵션 2: 2노드 MetroCluster 구성의 시스템에서 시스템 ID를 수동으로 재할당합니다

ONTAP를 실행하는 2노드 MetroCluster 구성에서는 시스템을 정상 운영 상태로 되돌리기 전에 디스크를 새 컨트롤러의 시스템 ID로 수동으로 재할당해야 합니다.

.이 작업에 대해
이 절차는 ONTAP를 실행하는 2노드 MetroCluster 구성의 시스템에만 적용됩니다.

이 절차에서 올바른 노드에 대한 명령을 실행해야 합니다.

* impaired_node는 유지 관리를 수행하는 노드입니다.
* replacement_node는 이 절차의 일부로 손상된 노드를 교체한 새 노드입니다.
* healthy_node는 손상된 노드의 DR 파트너입니다.


.단계
. 아직 재부팅하지 않았다면 _replacement_node를 재부팅하고 "Ctrl-C"를 입력하여 부팅 프로세스를 중단한 다음 표시된 메뉴에서 유지보수 모드로 부팅하는 옵션을 선택하십시오.
+
시스템 ID 불일치로 인해 시스템 ID를 무시하라는 메시지가 나타나면 Y를 입력해야 합니다.

. 정상 노드의 기존 시스템 ID를 보면 MetroCluster node show-fields node-systemid, dr-partner-systemid가 보입니다
+
이 예에서 Node_B_1은 이전 시스템 ID가 11807329인 이전 노드입니다.

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. 손상된 노드의 유지보수 모드 프롬프트에서 새 시스템 ID를 확인합니다. "디스크 쇼"
+
이 예에서 새 시스템 ID는 118065481입니다.

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. disk show 명령에서 얻은 시스템 ID 정보를 사용하여(FAS 시스템의 경우) 디스크 소유권을 재할당합니다. `disk reassign -s old system ID`
+
위의 예시에서 명령어의 내용은 '디스크 재할당-s 118073209'이다

+
계속하라는 메시지가 나타나면 Y로 응답할 수 있습니다.

. 디스크가 올바르게 할당되었는지 확인합니다
+
replacement_node에 속한 디스크에 _replacement_node의 새 시스템 ID가 표시되는지 확인합니다. 다음 예에서는 system-1에서 소유한 디스크에 새 시스템 ID 118065481이 표시됩니다.

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. 정상 노드에서 코어 덤프가 저장되었는지 확인합니다.
+
.. 고급 권한 수준 'Set-Privilege advanced'로 변경합니다
+
고급 모드로 계속 진행하라는 메시지가 나타나면 Y로 응답할 수 있습니다. 고급 모드 프롬프트가 나타납니다(*>).

.. 코어 덤프가 저장되었는지 확인합니다. 'system node run-node_local-node-name_partner savecore'
+
명령 출력에 savecore가 진행 중임을 나타내는 경우 savecore가 완료될 때까지 기다린 다음 반환 명령을 실행합니다. 'system node run-node_local-node-name_partner savecore -s command'를 사용하여 savecore의 진행률을 모니터링할 수 있습니다.</info>

.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. replacement_node가 유지보수 모드(*> 프롬프트 표시)인 경우 유지보수 모드를 종료하고 로더 프롬프트인 "halt"로 이동합니다
. replacement_node: boot_ontap를 부팅합니다
. replacement_node가 완전히 부팅된 후 스위치백(MetroCluster 스위치백)을 수행합니다
. MetroCluster 설정 'MetroCluster node show-fields configuration-state'를 확인한다
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Data ONTAP에서 MetroCluster 구성 작동을 확인합니다.
+
.. 두 클러스터에 대한 상태 경고 '시스템 상태 알림 표시'를 확인합니다
.. MetroCluster가 구성되어 있고 'MetroCluster show'(정상 모드)로 설정되어 있는지 확인합니다
.. 'MetroCluster check run'이라는 MetroCluster check을 수행한다
.. MetroCluster 체크 표시 결과를 MetroCluster check show로 출력한다
.. Config Advisor를 실행합니다. NetApp Support 사이트 의 Config Advisor 페이지로 이동합니다 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor/["support.netapp.com/NOW/download/tools/config_advisor/"].
+
Config Advisor를 실행한 후 도구의 출력을 검토하고 출력에서 권장 사항을 따라 발견된 문제를 해결하십시오.



. 스위치오버 작업 시뮬레이션:
+
.. 노드 프롬프트에서 고급 권한 레벨 'Set-Privilege Advanced'로 변경합니다
+
고급 모드로 계속 진행하고 고급 모드 프롬프트(*>)를 보려면 "y"로 응답해야 합니다.

.. simulate parameter: MetroCluster switchover-simulate로 스위치백 동작을 수행한다
.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다



